### ISSUE TITLE
HTS Arabic voice

### ISSUE THREAD

**Issue by linuxscout** [marytts/marytts#1008]
Salam,
We have developed an [HTS voice for Arabic](https://github.com/linuxscout/festival-tts-arabic-voices), It works on festival,
How can convert it to be used on MayTTS?
Thanks

**Comment by seblemaguer** [comment]
Hello,

Training a new HTS voice for a new language is currently in a broken state as some part of the code has been lost a couple of years ago. I may work on fixing this part at one point. I will keep you updated if there is some progress.
