### ISSUE TITLE
How to disable log4j logging for the library?

### ISSUE THREAD

**Issue by duc0** [marytts/marytts#1009]
We have added the following to log4j.xml

<category name="marytts">
    <priority value="OFF"/>
</category>
However, the library still prints log messages such as

[DEBUG] 18:12:34.363 [MesssageProcessor] marytts.HTSCARTReader - loadStateTree: loaded CART contains 254 Decision nodes and 255 Leaf nodes.

How do we disable the logging?

**Comment by seblemaguer** [comment]
Hello,

are you using the master branch or the dependencies from jcenter/bintray/...? If it is the first one, we move to log4j2. The readme indicates how to define the log level threshold.

**Comment by duc0** [comment]
That works, thanks!
