### ISSUE TITLE
Website demo broken in Safari Version 13.1.1 

### ISSUE THREAD

**Issue by JimKillock** [marytts/marytts#1010]
The website demo at http://mary.dfki.de:59125 does not function in Safari 13.1.1 Mac OS, although it works fine in FF and Chrome on Mac OS.

**Comment by seblemaguer** [comment]
Hello,

that is too vague. Could you be more precise?

**Comment by JimKillock** [comment]
On pressing "speak", on Safari 13.1.1 Mac OS, the player reports "ERROR".

**Comment by psibre** [comment]
Thanks for the the report!

Confirmed, reproducible. Will investigate.

**Comment by psibre** [comment]
Turns out this is actually a duplicate of #839. Closing in favor of that one.

**Comment by psibre** [comment]
As a workaround, please use Firefox or Chrome, which works without problems even on macOS Catalina.
