### ISSUE TITLE
MaryTTS for windows or android TTS engine

### ISSUE THREAD

**Issue by elnursamedzade** [marytts/marytts#1017]
Hello there.
Please enlighten me.
How can I make the Marytts unit selection voices as a sapi5 dll in windows?
Or how can I use it as android text to speech engine?
Anyone know about this?
Any tip will be highly appreciated!

**Comment by seblemaguer** [comment]
for the first part of the question, no idea as I don't use Windows.

For the android, there are a couple of issues but it seems for now it is not supported. see #943
