### ISSUE TITLE
Newly created voice not visible in Component Installer

### ISSUE THREAD

**Issue by AntonioCaroppos** [marytts/marytts#1018]
Hello!
I have built a unit selection voice, and it worked fine.
Now I want to install and test it.
I wanted to install it using an offline method. I don't want to upload it anywhere even thought the docs seem to suggest it (see "Step 4" on this page: https://github.com/marytts/marytts/wiki/Publishing-a-MARY-TTS-Voice)

To install the voice offline on my system, I have followed the instructions of "Step 3" on this URL:

> Test the installation as follows. After building the runtime MARY TTS system (using mvn install as described in the README), 
> copy your voice-...zip and voice-...-component.xml into the runtime system's download folder, e.g. target/marytts-5.0-
> SNAPSHOT/download/, and run the marytts component installer (in the example, target/marytts-5.0-SNAPSHOT/bin/marytts-
> component-installer.sh. Verify that the voice shows when selecting the respective language, and that it can be installed as 
> expected.

However, the voice isn't visible in the ComponentInstaller.

What could I check? What might have gone wrong here? 

Thank you!

**Comment by AntonioCaroppos** [comment]
I have also installed many voices. They show the status "INSTALLED", but in the client, only 1 voice is listed:

![1](https://user-images.githubusercontent.com/29504639/90988969-3c237300-e597-11ea-96cb-7008d6212968.jpg)
![2](https://user-images.githubusercontent.com/29504639/90988973-3ded3680-e597-11ea-9f5d-b1d9393ce163.jpg)

**Comment by seblemaguer** [comment]
Hello,

sorry for the delay. I don't really know what to do with the wikipage. It is so outdated that my opinion would be to simply remove everything from it but a lot of information would disappear.

For your specific issue, I suggest you use this repository: https://github.com/marytts/marytts-installer

**Comment by AntonioCaroppos** [comment]
1) This does not solve the problem that I have installed voices from the cloud as seen in my screenshot, and they're still not available in the client.
2) Ok, so there is actually no way to install the newly created voice offline? Just wanted to ask again...

**Comment by seblemaguer** [comment]
For 1., this client is not maintained and will disappear in the next update, so if you want to install a voice from the cloud, I suggest to use the previous repository and to ignore the client you used.

For 2., there is you have to add the of the unit selection voice in the classpath and configure the MARY_BASE environment variable to point to where the voice is available. For example, the following line is extracted from the bits1 configuration file:

```java
voice.bits1.databaseClass = marytts.unitselection.data.DiphoneUnitDatabase                                                                                                                                                                
voice.bits1.selectorClass = marytts.unitselection.select.DiphoneUnitSelector                                                                                                                                                              
voice.bits1.concatenatorClass = marytts.unitselection.concat.OverlapUnitConcatenator                                                                                                                                                      
voice.bits1.targetCostClass = marytts.unitselection.select.DiphoneFFRTargetCostFunction                                                                                                                                                   
voice.bits1.joinCostClass = marytts.unitselection.select.JoinCostFeatures                                                                                                                                                                 
voice.bits1.unitReaderClass = marytts.unitselection.data.UnitFileReader                                                                                                                                                                   
voice.bits1.cartReaderClass = marytts.cart.io.MARYCartReader                                                                                                                                                                              
voice.bits1.audioTimelineReaderClass = marytts.unitselection.data.TimelineReader                                                                                                                                           
voice.bits1.featureFile = MARY_BASE/lib/voices/bits1/halfphoneFeatures_ac.mry                                                                                                                                                             
voice.bits1.targetCostWeights = jar:/marytts/voice/Bits1/halfphoneUnitFeatureDefinition_ac.txt                                                                                                                                            
voice.bits1.joinCostFile = MARY_BASE/lib/voices/bits1/joinCostFeatures.mry                                                                                                                                                                
voice.bits1.joinCostWeights = jar:/marytts/voice/Bits1/joinCostWeights.txt                                                                                                                                                                
voice.bits1.unitsFile = MARY_BASE/lib/voices/bits1/halfphoneUnits.mry                                                                                                                                                                     
voice.bits1.cartFile = jar:/marytts/voice/Bits1/cart.mry                                                                                                                                                                                  
voice.bits1.audioTimelineFile = MARY_BASE/lib/voices/bits1/timeline_waveforms.mry                                                                                                                                                         
voice.bits1.basenameTimeline = MARY_BASE/lib/voices/bits1/timeline_basenames.mry   
```

**Comment by AntonioCaroppos** [comment]
What is the client that is currently maintained?

**Comment by seblemaguer** [comment]
The webpage is generated by the mary server. So if your jar are not in the classpath when you start mary, you won't see them in the webpage.

**Comment by AntonioCaroppos** [comment]
Thank you, this worked.
