### ISSUE TITLE
New dictionary is not being used

### ISSUE THREAD

**Issue by AntonioCaroppos** [marytts/marytts#1019]
Hello!

I have written a dictionary ("de.txt") from scratch.

I have removed the old one and put my new dictionary here:

/marytts/martytts-languages/martytts-lang-de/lib/modules/de/lexicon

However, AllophonesExtractor tells me that some words are being translated by g2p_method="rules", indicating that the word is not found in the dictionary. 
However, the word is present in the dictionary.

This leads me to thinking that the dictionary is not used at all.

Do I have to do anything special to use the new dictionary? 
Is putting it into the directory mentioned above not sufficient?

Thank you.

**Comment by seblemaguer** [comment]
`de.txt` contains the dictionnary used to build the G2P model. g2p_method is 'rules' which means the G2P module uses the trained model which is normal.

From your issue, I see two possibilities:
  - either you want to replace the G2P model which means that you have to build it but the method would be g2p_method="rules"
  - either you want to use your own dictionary in priority to the G2P model. In this case, you want to use the user dictionnary. To do so, you simply fill a side file and when you start mary, you simply define the java property `de.userdict` to the path of this file

**Comment by AntonioCaroppos** [comment]
I want to use my userdict-de.txt directly without using G2P.
I want to use direct look-up.
I don't understand if this is possible, or if I have to build a new g2p tree in any case.

If it's possible to use my userdict directly, could you please tell me how to do it exactely? I didn't understand what you meant by side file and where to define it.

**Comment by seblemaguer** [comment]
you define the java property `de.userdict=<PATH>/userdict-de.txt`

**Comment by AntonioCaroppos** [comment]
Do you really mean "de.userdict" or "db.userdict"?

**Comment by seblemaguer** [comment]
I really mean "de.userdict", see https://github.com/marytts/marytts/blob/bdca421b19d79bd7210c33221223a3b6a0a54a7a/marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/JPhonemiser.java#L67

**Comment by AntonioCaroppos** [comment]
So the database.config file might look like this, right?

```
db.wavDir /home/defaultuser/marytts/myvoice/wav/
de.userdict /home/defaultuser/marytts/userdict-de.txt
```

(I'm asking because it doesn't work for me)

**Comment by AntonioCaroppos** [comment]
I had placed it in the wrong path, and the userdict has to be in a different format (with | and space between phones). Once I did that, it worked fine.
