### ISSUE TITLE
Retire wiki

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#1022]
https://github.com/marytts/marytts/wiki should be retired, since it's totally outdated.

But to preserve the information, we can move the content to a new repo and archive it.

**Comment by psibre** [comment]
Done: https://github.com/marytts/marytts-wiki

**Comment by psibre** [comment]
Archived that repo.

**Comment by psibre** [comment]
Disabled the wiki here.

**Comment by AAverin** [comment]
@psibre Is there a new place for documentation?
