### ISSUE TITLE
whats going on with new language surpport?

### ISSUE THREAD

**Issue by alphamwamanda** [marytts/marytts#1023]
I have been working on Swahili language recently with Marytts version 5.x using maven, i cant find a new language surpport tutorial any more, what happened?

**Comment by seblemaguer** [comment]
Hello,

do you mean the wiki? if yes we archived it in this repository: https://github.com/marytts/marytts-wiki as a lot of it is not valid for a while.

**Comment by alphamwamanda** [comment]
Thank you @seblemaguer found it
