### ISSUE TITLE
Where are the weights for the phone decision tree?

### ISSUE THREAD

**Issue by AntonioCaroppos** [marytts/marytts#1025]
Hello!

In the voice/temp folder I can see the input for the duration cart/ tree and for the f0 cart / tree.
For example, in dur.tree, I see the following:

```
((word_numsegs < 1.9)
 ((phrase_numsyls < 1.9)
  ((prev_prev_phone is _)
   ((next_next_vlng is l)
    ((next_next_vheight is 1)
     ((0.022764 0.279703))
     ((next_next_phone is e:)
      ((0.0438966 0.282029))
      ((0.0693542 0.341281))))
```

I would now like to investigate how Mary turns the phone units and their features into a cart/ tree. I would therefore like to take a look at the phoneunit.tree (not sure about the name because I haven't found such a file).

Where do I find this file, please? 

Thank you!

**Comment by AntonioCaroppos** [comment]
Is my question stupid?

**Comment by seblemaguer** [comment]
phoneunit.tree doesn't make sense. The only CART used is for the F0. You can search for f0.left.tree, f0.mid.tree, f0.right.tree
