### ISSUE TITLE
NewLanguageSupport

### ISSUE THREAD

**Issue by leyvatheam** [marytts/marytts#1026]
hi, until recently I was able to access the section for NewLanguageSupport here on github, but it suddenly disappeared, someone could provide it to me, I am in an investigation of my school and the one here is the clearest (and current).
I have tried with this https://mary.opendfki.de/trac/wiki/NewLanguageSupport
but it doesn't seem to be correct.
Thanks in advance

**Comment by seblemaguer** [comment]
We moved the wiki to its own repository: https://github.com/marytts/marytts-wiki  as we are moving toward a new voice building strategy
