### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by leyvatheam** [marytts/marytts#1027]
sh wkdb_database_selector.sh /home/anas/NewDevelopBranch/wkdb/wkdb.conf 
...
....
....
....
Checking if es_test_selectedSentences already exist.
  TABLE = es_test_selectedSentences already exist. New selected sentences will be added to this table.
  A description for the table es_test_selectedSentences already exist in TABLE = tablesDescription.

Analysing feature vectors of 13129 sentences:
Exception in thread "main" java.lang.NullPointerException
	at marytts.tools.dbselection.CoverageDefinition.initialiseCoverage(CoverageDefinition.java:427)
	at marytts.tools.dbselection.DatabaseSelector.main2(DatabaseSelector.java:237)
	at marytts.tools.dbselection.DatabaseSelector.main(DatabaseSelector.java:116)

i cannot pass from this step, in the wkdb_cleaning_up.sh also i encounteres problem in the rev-comment data truncation, i change the bytecode a bit and configure that table to longblob and utf8mb4, i dont know if that afects, im adding support for spanish, i need help i plan to after some time upload here the new lang.
thanks for the help.

**Comment by seblemaguer** [comment]
Hello,

I never used this tool. Could you tell me at which step it is failing? is it when you try to build the g2p module?
