### ISSUE TITLE
Important Jcenter is deprecated 

### ISSUE THREAD

**Issue by ahmedsaheed** [marytts/marytts#1071]
I recently tried to use marytts on a java project with gradle, but i found out that this can no longer work because JCenter is now deprecated and marytts would have to find an alternative repository or migrate to maven as said [here](https://blog.gradle.org/jcenter-shutdown#:~:text=The%20jcenter()%20method%20will,may%20only%20publish%20new%20versions.)

**Comment by psibre** [comment]
Thanks for your patience, this has been mostly resolved by publishing the [v5.2.1 maintenance release](https://github.com/marytts/marytts/releases/tag/v5.2.1) to Maven Central.

See also  #1073.
