### ISSUE TITLE
PraatPitchmarker fails when no pitchmarks are detected

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#110]
This can easily occur if the pitch data falls outside the configure pitch range, or if non-speech files are processed. The error occurs at [this line in the praat script](https://github.com/marytts/marytts/blob/a17207b68a03d2d09a2561f2e1215d4822db14de/marytts-builder/src/main/resources/marytts/tools/voiceimport/script.praat#L95) and causes the PraatPitchmarker to throw an Exception.

**Comment by seblemaguer** [comment]
is it still open or is it deprecated ?
