### ISSUE TITLE
Mary 5.0 mangles simple sentence

### ISSUE THREAD

**Issue by fsteinhardt** [marytts/marytts#116]
To reproduce go to the online demo and enter:

Voice: dfki-pavoque-styles de
Input Text: Das ist ein Test.

This sentence is completely mangled, the output is incomprehensible and way to short.

**Comment by Munzey** [comment]
@psibre seems the voice was never rebuilt, perhaps this should be looked at after we have voice resources building correctly, a 5.2.1 perhaps? :laughing:

**Comment by psibre** [comment]
Yes, the rebuilt voices will be deployed concurrently with the 5.2 release.
Of course we'll test all of them internally first. =)

**Comment by seblemaguer** [comment]
Apparently it is still going on with the current version of the voices
