### ISSUE TITLE
jar for french voice

### ISSUE THREAD

**Issue by ralfhauser** [marytts/marytts#126]
https://mary.opendfki.de/repos/branches/fr-branch/download/ there is mary-catherine_fr_hmm-4.3.0.zip and mary-florent_fr_hmm-4.3.0.zip 
but for non-experts, it is not obvious, how to use that in the new version 5.

Wouldn't there have to be a marytts-lang-fr-5.0.jar ?

**Comment by C0NPAQ** [comment]
Hey, excuse me but I have a random question: Why is it so hard to find voice jar files for marytts? 

They are scattered all over the place ... in some download folder on some fr-branch on some password protected site, some other site had bits1-hsmm and bits2-hsmm but the link was only accessible in some tutorial. Why? Is there some reason to keep them hidden?
