### ISSUE TITLE
New voice failing with HMMVoiceMakeVoice

### ISSUE THREAD

**Issue by karthikkrishnanv** [marytts/marytts#134]
Hello all

I am trying to get a new voice imported with marytts. I got to a stage where it is failing with "HMMVoiceMakeVoice". All the previous steps in the documentation until this have succeeded. The final extracted error is as below
- system is PLAIN
  ERROR [+2121]  HInit: Too Few Observation Sequences [0] 
  FATAL ERROR - Terminating program /usr/local/HTS-2.2beta/bin/HInit 
  Error in  

/usr/local/HTS-2.2beta/bin/HInit     -A    -C /myvoice/hts/configs/trn.cnf -D -T 1 -S /myvoice/hts/data/scp/train.scp                -m 1 -u tmvw    -w 5000  -H /myvoice/hts/models/qst001/ver1/cmp/init.mmf -M /myvoice/hts/models/qst001/ver1/cmp/HInit -I /myvoice/hts/data/labels/mono.mlf -l dZ -o dZ /myvoice/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt

It sounds like I have too few training wav files ? Can anyone help me if there are other ways to overcome this ? Also is there a way to check if the wav files I have are sufficient or if there are any guidelines on how to build the training wav files with enough coverage ?  

Thanks
Karthik

**Comment by yash90** [comment]
I had the same error. Can you please tell me how you resolved it ? I am a beginner for this, I reffered the given link also but could not go for a solution.

**Comment by seblemaguer** [comment]
is it an error in hinit or in herest like you indicated in #422 ?

**Comment by yash90** [comment]
No after that error, I installed MARY again. Then I got a new error in HMMVoiceMakeVoice step. 

ERROR [+2121]  HInit: Too Few Observation Sequences [0]
 FATAL ERROR - Terminating program /home/yashj/MaryBase/marytts/lib/external/bin/HInit
Error in /home/yashj/MaryBase/marytts/lib/external/bin/HInit     -A    -C /home/yashj/MaryBase/HMM_Voice_Si/hts/configs/trn.cnf -D -T 1 -S /home/yashj/MaryBase/HMM_Voice_Si/hts/data/scp/train.scp                -m 1 -u tmvw    -w 5000  -H /home/yashj/MaryBase/HMM_Voice_Si/hts/models/qst001/ver1/cmp/init.mmf -M /home/yashj/MaryBase/HMM_Voice_Si/hts/models/qst001/ver1/cmp/HInit -I /home/yashj/MaryBase/HMM_Voice_Si/hts/data/labels/mono.mlf -l f -o f /home/yashj/MaryBase/HMM_Voice_Si/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt
yashj@yashj-HP-ProBook-4430s:~/MaryBase/HMM_Voice_Si/hts$

**Comment by seblemaguer** [comment]
Therefore it means you have no "f" instance. Check you label files. I close the other issue as it's not related anymore with your problem

**Comment by yash90** [comment]
Can you give me more details on how to do that. I checked inside /hts/data/labels/mono/  folder. There are 987 label files for sentences. And two files has values for "f".

**Comment by seblemaguer** [comment]
You need to have instances of "f" whose lengths are superior or equal to : number of states * frameshift. If you are using the default parameters it should be >= 5*5 >= 25ms

**Comment by yash90** [comment]
Yes. I got to know about that condition from an above given link, but I am confused on how to check number of instances and values for "f".

**Comment by nikigre** [comment]
Hi!
Sorry for opening this issue again, but I got the same error. Is there a way to skip training for this instance? Like deleting it from some file?
I tried deleting it from `mono.list`, but then it fails on some other task.

Thank you!
