### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#144]
Various improvements to the current documentation.

**Problems**
* [x] [official website](http://mary.dfki.de/) is hideously out of date (also hideous).
* [x] [legacy dev site](http://mary.opendfki.de/) needs to be frozen.
* [x] we should embed the stable documentation in this very repo (using the [maven-site-plugin](http://maven.apache.org/plugins/maven-site-plugin/)); this also gives us a shiny developer website for free; it could be deployed to the official URL or http://marytts.github.io/, depending on what we prefer.
* [x] [the wiki](https://github.com/marytts/marytts/wiki) should be reserved for experimental, volatile documentation; pages that are mature and describe useful things well should graduate to the documentation under `src/site`.
* [x] update README

P.S. http://stevelosh.com/blog/2013/09/teach-dont-tell/

**Comment by Munzey** [comment]
changes to wiki pushed to mirror

**Comment by aitorme** [comment]
@Munzey which changes are pushed to mirror? Is the fourth problem (documentation) solved, then?

**Comment by Munzey** [comment]
@aitorme  @psibre would need to clarify this, but I think when the TTS voicebuilding seminar was on earlier this year(2015), the participants updated parts of the wiki and were asked to make pull requests of their changes to [this marytts wiki repo](https://github.com/psibre/marytts-wiki), which as it states in the description, is a mirror of https://github.com/marytts/marytts.wiki.git
I was charged with reviewing the changes and merging the pull requests.

**Comment by psibre** [comment]
The updates @Munzey mentions are restricted to the voicebuilding pages in the wiki. Incidentally, there was a [detailed post on this](http://www.dfki.de/pipermail/mary-users/2015-November/001779.html) on mary-users recently.
Note that the [gradle voicebuilding plugin](/marytts/gradle-marytts-voicebuilding-plugin) will be used to rebuild voices for 5.2, and it will have its own documentation.

**Comment by psibre** [comment]
Thanks for updating the README, @seblemaguer!
