### ISSUE TITLE
Places of Articulation in allophones.de.xml

### ISSUE THREAD

**Issue by bnjmnwe** [marytts/marytts#147]
There are some inconsistencies in allophones.de.xml concerning the cplace-Attribute.
- It seems as if cplace="p" is used for both postalveolar and palatal consonants (see for example S and j)
- C has got cplace="v", shouldn't it be palatal?

**Comment by Munzey** [comment]
should be investigated when the language resources are rebuilt for 5.2

**Comment by psibre** [comment]
Yes, but this is actually an issue with the feature set, not the lexicon...
