### ISSUE TITLE
Phoneme vs input audio map via log and smoothing

### ISSUE THREAD

**Issue by karthikkrishnanv** [marytts/marytts#148]
Hello all

This isn't an issue per se, but I am hoping someone could guide me. I would like to be able to match the synthesized phenome vs input source audio. Is there a way to get such a log or can anyone point me which source files to hack this ? Also I am interested in experimenting with different smoothing operations during concat operation and if anyone could point to relevant source files, that would be awesome as well.

Thanks
Karthik

**Comment by Munzey** [comment]
you could start by taking a look at `marytts.unitselection.concat.BaseUnitConcatenator` in `marytts-runtime` as a start. Another thread which may interest you is issue #291.
We are considering adding a mechanism to get a dump of the sequence of unique unit indices selected by the viterbi algorithm. Following this, we also want to be able to start up a UnitConcatenator that simply takes such a unit index list and stupidly concatenates them.
Hope this helps :+1:
