### ISSUE TITLE
How to control too many diphone concatenation ?

### ISSUE THREAD

**Issue by karthikkrishnanv** [marytts/marytts#152]
Hello all

I find that during synthesis there are too many concatenation points and am interested in tuning various parameters to see if they could be tuned. I suspect I may be able to get better synthesis by tuning those.

Simply changing target cost weight and join cost weight don't seem to make much of a difference. How can I modify the weights of various other features during target cost evaluation in a clean way ? Can anyone point me to the relevant file ?

Thanks
Karthik

**Comment by Munzey** [comment]
issue #254 could help
