### ISSUE TITLE
Fail to load Timeline file

### ISSUE THREAD

**Issue by mukundroy** [marytts/marytts#159]
Hi 

I'm running the voice creation tool and got stuck DurationCarTTrainer module with exception: marytts.exceptions.MaryConfigurationException: Cannot load timeline file from .....//mary/timeline_waveforms.mry.
I am training MARY with around 11 thousand .wav files and when I tried to see "timeIdxBytePos" , it is coming to -timeIdxBytePos: :-1999965209 (negative value). Can somebody throw light on what could be the possible cause for this error.

Thanks in Advance

**Comment by Munzey** [comment]
see #117

**Comment by psibre** [comment]
Closing this in favor of #117.
