### ISSUE TITLE
Show voice details in web interface

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#161]
A remote MaryTTS server instance does not provide much information about the installed voices. For example, the demo running at http://mary.dfki.de:59125/ provides only some information in the _Voice_ drop-down menu (or through the [`voices` info request](http://mary.dfki.de:59125/voices))

```
voxforge-ru-nsh ru male unitselection general
dfki-spike en_GB male unitselection general
dfki-prudence en_GB female unitselection general
dfki-poppy en_GB female unitselection general
dfki-pavoque-styles de male unitselection general
dfki-obadiah en_GB male unitselection general
bits3 de male unitselection general
istc-lucia-hsmm it female hmm
dfki-spike-hsmm en_GB male hmm
dfki-prudence-hsmm en_GB female hmm
dfki-poppy-hsmm en_GB female hmm
dfki-pavoque-neutral-hsmm de male hmm
dfki-ot-hsmm tr male hmm
dfki-obadiah-hsmm en_GB male hmm
cmu-slt-hsmm en_US female hmm
cmu-rms-hsmm en_US male hmm
cmu-nk-hsmm te female hmm
cmu-bdl-hsmm en_US male hmm
bits3-hsmm de male hmm
bits1-hsmm de female hmm
```

but this conspicuously omits important other information from the corresponding voice components, such as the _description_ and _license_.

(Thanks to Andrej Prilipp for pointing this out.)

**Comment by seblemaguer** [comment]
I will add that part in the html front-end

**Comment by scottlawton** [comment]
Is the license info for voices posted anywhere (including github)? I'm interested in the last 2: bits3-hsmm de male hmm, bits1-hsmm de female hmm. Perhaps it could be added to https://github.com/marytts/marytts/blob/master/LICENSE.md even before the 6.0 milestone?
