### ISSUE TITLE
New language: hard-coded locale in SelectionFunction

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#173]
In [SelectionFunction](https://github.com/marytts/marytts/blob/0faed4440fb087866904f68c1272844f0ceca88e/marytts-builder/src/main/java/marytts/tools/dbselection/SelectionFunction.java#L260), the locale string is hard-coded as `"it"`. This seems to be a bug... but we need to double-check.

Thanks to Samir Abbasov for [reporting this](http://www.dfki.de/pipermail/mary-users/2014-March/001499.html)!

**Comment by seblemaguer** [comment]
Is it still going on on is it solved for this part ?

**Comment by psibre** [comment]
I haven't touched the dbselection code, and it can be considered deprecated.
