### ISSUE TITLE
Better sorting of available voices in web interface

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#174]
The list of installed voices in the web interface of a running MaryTTS server is a bit difficult to digest. Upon closer inspection, it seems that they're sorted by voice type (`hmm`, `unitselection`), then by voice name, *in reverse*.

It would be better to sort them by locale, then by voice name (regardless of type) and perhaps by gender even before that.

A side-effect of the current behavior is that the first voice in the list happens to be `voxforge-ru-nsh`, and for a demo server where people will tend to click the big shiny SPEAK button before looking at anything else, it might be better to have an English voice as the default anyway. (Bonus points for defaulting to the browser's `HTTP_ACCEPT_LANGUAGE` or some comparable heuristic...)

**Comment by seblemaguer** [comment]
Done in the html web interface
