### ISSUE TITLE
Windows compatability for HTK labeler

### ISSUE THREAD

**Issue by SimonOst** [marytts/marytts#176]
The class marytts.tools.voiceimport.HTKLabeler is not working properly under Windows, since there are several UNIX-dependent shell commands.

**Comment by psibre** [comment]
`marytts-builder` will be dropped from the next major release; force-aligning is something that should be done in a process that is decoupled from the main voicebuilding workflow.
Our favored framework for this is to use a dedicated gradle plugin, which could be adapted for HTK.
