### ISSUE TITLE
voiceimport EHMMLabeler baumWelchEHMM exception

### ISSUE THREAD

**Issue by johnaoga** [marytts/marytts#178]
Following this tutorial http://mary.opendfki.de/wiki/NewLanguageSupport i have built new language support! Find my new language module here:
https://www.dropbox.com/s/p7z2unoum2ro1zw/marytts-lang-yo.tar.gz. Notice that yoruba is a tonal language so in my allophone.yo.xml I added "vtone", I don't know if It is correct!

After, I read this tutorial: https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial. The requirements specified at section 1 is available here https://www.dropbox.com/s/8gjzt65y16co1qx/std_yoruba.tar.gz.

In the step of EHMMLabeler i have got this exception:
Preparing voice database for labelling using EHMM :
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Setting up EHMM directory ...
 ... done.
Getting Phone Sequence from Phone Features...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Dumping required files ....
( cd /home/johnaoga/std_yoruba/std_yoruba/ehmm; perl /home/johnaoga/ttsapps/marytts-psibre/lib/external//bin/phfromutt.pl /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.align /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.phoneList 5; perl /home/johnaoga/ttsapps/marytts-psibre/lib/external//bin/getwavlist.pl /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.align /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.waveList; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Computing MFCCs ...
( cd /home/johnaoga/std_yoruba/std_yoruba/ehmm; /home/johnaoga/ttsapps/marytts-psibre/lib/external//bin/FeatureExtraction /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.featSettings /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.waveList >> log.txt; perl /home/johnaoga/ttsapps/marytts-psibre/lib/external//bin/comp_dcep.pl /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.waveList /home/johnaoga/std_yoruba/std_yoruba/ehmm/feat mfcc ft 0 0 >> log.txt ; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Scaling Feature Vectors ...
( cd /home/johnaoga/std_yoruba/std_yoruba/ehmm; perl /home/johnaoga/ttsapps/marytts-psibre/lib/external//bin/scale_feat.pl /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.waveList /home/johnaoga/std_yoruba/std_yoruba/ehmm/feat /home/johnaoga/std_yoruba/std_yoruba/ehmm/mod ft 4 >> log.txt; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Intializing EHMM Model ...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
EHMM baum-welch re-estimation ...
It may take more time (may be 1 or 2 days) depending on voice database ...
( cd /home/johnaoga/std_yoruba/std_yoruba/ehmm; /home/johnaoga/ttsapps/marytts-psibre/lib/external//bin/ehmm /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.phoneList.int /home/johnaoga/std_yoruba/std_yoruba/ehmm/etc/ehmm.align.int 1 0 /home/johnaoga/std_yoruba/std_yoruba/ehmm/feat ft /home/johnaoga/std_yoruba/std_yoruba/ehmm/mod 0 0 0 >> log.txt; exit )

java.lang.Exception: The component EHMMLabeler produced the following exception: 
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: marytts.exceptions.MaryConfigurationException: baumWelchEHMM computation failed.
Error: null
    at marytts.tools.voiceimport.EHMMLabeler.baumWelchEHMM(EHMMLabeler.java:513)
    at marytts.tools.voiceimport.EHMMLabeler.compute(EHMMLabeler.java:183)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)

I have built test en_US voice with any problem but when i have used db.locale=yo in my general setting i have got the exception.

Someone can help me?

**Comment by doaaobiedat** [comment]
hi all
i have the same error, i run the commend
and this is my log.txt file https://www.dropbox.com/s/5khf6keb3pjg6sx/log.txt?dl=0

**Comment by neouyghur** [comment]
@ahsaynbeatmaker  I am trailing behind you. :) did you solved the problem?
