### ISSUE TITLE
Locale null breaks MaryServer

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#204]
Despite thorough efforts back in 40bc5dccf50c0002e26df5167625aa52e9a17a57, there are several cases where the Locale for a given input is `null`. This causes an IllegalStateException in the Mary shutdown hook.

**Comment by Mullahz** [comment]
I am also facing the same error of above BUILD FAILURE
Failed tests: 
  canProcessToTokens(marytts.MaryInterfaceIT)

Tests in error: 
  unknownOutputType(marytts.MaryInterfaceIT): Module TextToMaryXML: Power-on self test failed.

Tests run: 20, Failures: 1, Errors: 1, Skipped: 0

Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
    at marytts.server.Mary.shutdown(Mary.java:384)
    at marytts.server.Mary$3.run(Mary.java:290)


Sir, what shall I do to resolve the error. plz help me out.

**Comment by psibre** [comment]
@Mullahz How do you know it's the same error? Could you please open a new issue for this and describe in detail the conditions under which the test fails?

**Comment by Mullahz** [comment]
Sir, i am trying to build the synthesis sysytem for Assamese language using Mary TTS.
I have performed all the steps of new language support upto step 4 i.e; Minimal NLP components for the new language. The steps for building assamese language file i.e;
                           $ cd marytts-lang-xy
                           $ mvn test
were successful. After this when i tried to build the system with the new language support and run the below commands it shows the error as given.
                            $ cd marytts
                            $ mvn install.
After running them it shows as below....

helal@helal-HP-Compaq-6200-Pro-MT-PC:~/marytts-master$ mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] MaryTTS
[INFO] marytts-common
[INFO] marytts-signalproc
[INFO] marytts-runtime
[INFO] marytts-lang-de
[INFO] marytts-lang-en
[INFO] marytts-lang-te
[INFO] marytts-lang-as
[INFO] marytts-lang-bn
[INFO] marytts-lang-hi
[INFO] marytts-lang-tr
[INFO] marytts-lang-ru
[INFO] marytts-lang-it
[INFO] marytts-lang-fr
[INFO] marytts-lang-sv
[INFO] marytts-languages
[INFO] voice-cmu-slt-hsmm
[INFO] marytts-client
[INFO] marytts-builder
[INFO] marytts-redstart
[INFO] marytts-transcription
[INFO] marytts-assembly-builder
[INFO] marytts-assembly-runtime
[INFO] marytts-assembly
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MaryTTS 5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-7-or-higher) @ marytts ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ marytts ---
[INFO] Executing: /bin/sh -c cd /home/helal/marytts-master && git rev-parse --verify HEAD
[INFO] Working directory: /home/helal/marytts-master
[INFO] Storing buildNumber: null at timestamp: 1423738954062
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: /bin/sh: 1: git: not found

[INFO] Executing: /bin/sh -c cd /home/helal/marytts-master && git rev-parse --verify HEAD
[INFO] Working directory: /home/helal/marytts-master
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:integration-test (integration-test) @ marytts ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:verify (verify) @ marytts ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-source-plugin:2.3:jar-no-fork (attach-sources) @ marytts ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ marytts ---
[INFO] Installing /home/helal/marytts-master/pom.xml to /home/helal/.m2/repository/de/dfki/mary/marytts/5.2-SNAPSHOT/marytts-5.2-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-common 5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-7-or-higher) @ marytts-common ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ marytts-common ---
[INFO] Executing: /bin/sh -c cd /home/helal/marytts-master/marytts-common && git rev-parse --verify HEAD
[INFO] Working directory: /home/helal/marytts-master/marytts-common
[INFO] Storing buildNumber: null at timestamp: 1423738954468
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: /bin/sh: 1: git: not found

[INFO] Executing: /bin/sh -c cd /home/helal/marytts-master/marytts-common && git rev-parse --verify HEAD
[INFO] Working directory: /home/helal/marytts-master/marytts-common
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ marytts-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 13 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ marytts-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ marytts-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ marytts-common ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ marytts-common ---
[INFO] Surefire report directory: /home/helal/marytts-master/marytts-common/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
Running marytts.util.string.ByteStringTranslatorTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.04 sec - in marytts.util.string.ByteStringTranslatorTest
Running marytts.util.dom.DomUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec - in marytts.util.dom.DomUtilsTest
Running marytts.modules.phonemiser.AllophoneSetTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in marytts.modules.phonemiser.AllophoneSetTest

Results :

Tests run: 19, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ marytts-common ---
[INFO] Building jar: /home/helal/marytts-master/marytts-common/target/marytts-common-5.2-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:integration-test (integration-test) @ marytts-common ---
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:verify (verify) @ marytts-common ---
[INFO] Failsafe report directory: /home/helal/marytts-master/marytts-common/target/failsafe-reports
[INFO] 
[INFO] --- maven-source-plugin:2.3:jar-no-fork (attach-sources) @ marytts-common ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ marytts-common ---
[INFO] Installing /home/helal/marytts-master/marytts-common/target/marytts-common-5.2-SNAPSHOT.jar to /home/helal/.m2/repository/de/dfki/mary/marytts-common/5.2-SNAPSHOT/marytts-common-5.2-SNAPSHOT.jar
[INFO] Installing /home/helal/marytts-master/marytts-common/pom.xml to /home/helal/.m2/repository/de/dfki/mary/marytts-common/5.2-SNAPSHOT/marytts-common-5.2-SNAPSHOT.pom
[INFO] Installing /home/helal/marytts-master/marytts-common/target/marytts-common-5.2-SNAPSHOT-sources.jar to /home/helal/.m2/repository/de/dfki/mary/marytts-common/5.2-SNAPSHOT/marytts-common-5.2-SNAPSHOT-sources.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-signalproc 5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-7-or-higher) @ marytts-signalproc ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ marytts-signalproc ---
[INFO] Executing: /bin/sh -c cd /home/helal/marytts-master/marytts-signalproc && git rev-parse --verify HEAD
[INFO] Working directory: /home/helal/marytts-master/marytts-signalproc
[INFO] Storing buildNumber: null at timestamp: 1423738955451
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: /bin/sh: 1: git: not found

[INFO] Executing: /bin/sh -c cd /home/helal/marytts-master/marytts-signalproc && git rev-parse --verify HEAD
[INFO] Working directory: /home/helal/marytts-master/marytts-signalproc
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ marytts-signalproc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 95 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ marytts-signalproc ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ marytts-signalproc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ marytts-signalproc ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ marytts-signalproc ---
[INFO] Surefire report directory: /home/helal/marytts-master/marytts-signalproc/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
Running marytts.signalproc.analysis.LabelsTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.061 sec - in marytts.signalproc.analysis.LabelsTest
Running marytts.signalproc.process.PhaseVocoderTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 sec - in marytts.signalproc.process.PhaseVocoderTest
Running marytts.signalproc.process.FrameProviderTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in marytts.signalproc.process.FrameProviderTest
Running marytts.signalproc.process.FrameOverlapAddTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in marytts.signalproc.process.FrameOverlapAddTest
Running marytts.signalproc.process.PitchFrameProviderTest
correcting last pitchmark to total audio duration: 2.355
correcting last pitchmark to total audio duration: 2.355
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec - in marytts.signalproc.process.PitchFrameProviderTest
Running marytts.signalproc.filter.FilterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.053 sec - in marytts.signalproc.filter.FilterTest
Running marytts.util.data.text.PraatPitchTierTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.16 sec - in marytts.util.data.text.PraatPitchTierTest
Running marytts.util.data.audio.AudioDoubleDataSourceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in marytts.util.data.audio.AudioDoubleDataSourceTest
Running marytts.util.data.ProducingDoubleDataSourceTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec - in marytts.util.data.ProducingDoubleDataSourceTest
Running marytts.util.data.BufferedDoubleDataSourceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in marytts.util.data.BufferedDoubleDataSourceTest
Running marytts.util.math.ComplexNumberTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in marytts.util.math.ComplexNumberTest
Running marytts.util.math.FFTTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in marytts.util.math.FFTTest

Results :

Tests run: 47, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ marytts-signalproc ---
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:integration-test (integration-test) @ marytts-signalproc ---
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:verify (verify) @ marytts-signalproc ---
[INFO] Failsafe report directory: /home/helal/marytts-master/marytts-signalproc/target/failsafe-reports
[INFO] 
[INFO] --- maven-source-plugin:2.3:jar-no-fork (attach-sources) @ marytts-signalproc ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ marytts-signalproc ---
[INFO] Installing /home/helal/marytts-master/marytts-signalproc/target/marytts-signalproc-5.2-SNAPSHOT.jar to /home/helal/.m2/repository/de/dfki/mary/marytts-signalproc/5.2-SNAPSHOT/marytts-signalproc-5.2-SNAPSHOT.jar
[INFO] Installing /home/helal/marytts-master/marytts-signalproc/pom.xml to /home/helal/.m2/repository/de/dfki/mary/marytts-signalproc/5.2-SNAPSHOT/marytts-signalproc-5.2-SNAPSHOT.pom
[INFO] Installing /home/helal/marytts-master/marytts-signalproc/target/marytts-signalproc-5.2-SNAPSHOT-sources.jar to /home/helal/.m2/repository/de/dfki/mary/marytts-signalproc/5.2-SNAPSHOT/marytts-signalproc-5.2-SNAPSHOT-sources.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-runtime 5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-7-or-higher) @ marytts-runtime ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ marytts-runtime ---
[INFO] Executing: /bin/sh -c cd /home/helal/marytts-master/marytts-runtime && git rev-parse --verify HEAD
[INFO] Working directory: /home/helal/marytts-master/marytts-runtime
[INFO] Storing buildNumber: null at timestamp: 1423738956254
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: /bin/sh: 1: git: not found

[INFO] Executing: /bin/sh -c cd /home/helal/marytts-master/marytts-runtime && git rev-parse --verify HEAD
[INFO] Working directory: /home/helal/marytts-master/marytts-runtime
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ marytts-runtime ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 19 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ marytts-runtime ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ marytts-runtime ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ marytts-runtime ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ marytts-runtime ---
[INFO] Surefire report directory: /home/helal/marytts-master/marytts-runtime/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
Running marytts.config.MainConfigTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.08 sec - in marytts.config.MainConfigTest
Running marytts.config.MaryConfigTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec - in marytts.config.MaryConfigTest
Running marytts.datatypes.MaryDataTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.156 sec - in marytts.datatypes.MaryDataTest
Running marytts.tests.junit4.EnvironmentTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec - in marytts.tests.junit4.EnvironmentTest
Running marytts.signalproc.effects.AudioEffectsTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in marytts.signalproc.effects.AudioEffectsTest
Running marytts.util.MaryCacheTest
INFO  Logger: Checkpoint start
0 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - Checkpoint start
INFO  Logger: Checkpoint end
128 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - Checkpoint end
INFO  Logger: open start
136 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - open start
INFO  Logger: open end
272 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - open end
INFO  Logger: DataFileCache.close(true) : start
335 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close(true) : start
INFO  Logger: DataFileCache.close() : save data
360 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close() : save data
INFO  Logger: DataFileCache.close() : flags
360 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close() : flags
INFO  Logger: DataFileCache.close() : seek end
360 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close() : seek end
INFO  Logger: DataFileCache.close() : close
385 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close() : close
INFO  Logger: Database closed
435 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - Database closed
INFO  Logger: open start
557 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - open start
INFO  Logger: open end
586 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - open end
INFO  Logger: DataFileCache.close(true) : start
683 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close(true) : start
INFO  Logger: DataFileCache.close() : save data
684 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close() : save data
INFO  Logger: DataFileCache.close() : close
684 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close() : close
INFO  Logger: Database closed
735 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - Database closed
INFO  Logger: open start
853 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - open start
INFO  Logger: open end
853 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - open end
INFO  Logger: DataFileCache.close(true) : start
932 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close(true) : start
INFO  Logger: DataFileCache.close() : save data
932 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close() : save data
INFO  Logger: DataFileCache.close() : close
933 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - DataFileCache.close() : close
INFO  Logger: Database closed
982 [main] INFO HSQLDB4B7D746C8C.org.hsqldb.persist.Logger  - Database closed
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.402 sec - in marytts.util.MaryCacheTest
Running marytts.util.dom.MaryDomUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 sec - in marytts.util.dom.MaryDomUtilsTest
Running marytts.util.FeatureUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in marytts.util.FeatureUtilsTest
Running marytts.tools.install.ComponentDescriptionTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in marytts.tools.install.ComponentDescriptionTest

Results :

Tests run: 48, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ marytts-runtime ---
[INFO] 
[INFO] --- maven-assembly-plugin:2.4.1:single (make-assembly) @ marytts-runtime ---
[INFO] Building jar: /home/helal/marytts-master/marytts-runtime/target/marytts-runtime-5.2-SNAPSHOT-jar-with-dependencies.jar
[INFO] 
[INFO] --- maven-jar-plugin:2.5:test-jar (default) @ marytts-runtime ---
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:integration-test (integration-test) @ marytts-runtime ---
[INFO] Failsafe report directory: /home/helal/marytts-master/marytts-runtime/target/failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running marytts.server.MaryPropertiesIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.048 sec - in marytts.server.MaryPropertiesIT
Running marytts.MaryInterfaceIT
Tests run: 17, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.387 sec <<< FAILURE! - in marytts.MaryInterfaceIT
unknownOutputType(marytts.MaryInterfaceIT)  Time elapsed: 0.375 sec  <<< ERROR!
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at de.dfki.lt.tools.tokenizer.JTok.<clinit>(JTok.java:60)
	at marytts.modules.JTokeniser.startup(JTokeniser.java:92)
	at marytts.server.Mary.startModules(Mary.java:148)
	at marytts.server.Mary.startup(Mary.java:298)
	at marytts.server.Mary.startup(Mary.java:205)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:71)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:63)
	at marytts.MaryInterfaceIT.setUp(MaryInterfaceIT.java:47)

canProcessToTokens(marytts.MaryInterfaceIT)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: null
	at marytts.server.Request.process(Request.java:271)
	at marytts.LocalMaryInterface.process(LocalMaryInterface.java:395)
	at marytts.LocalMaryInterface.generateXML(LocalMaryInterface.java:281)
	at marytts.MaryInterfaceIT.canProcessToTokens(MaryInterfaceIT.java:123)

Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:384)
	at marytts.server.Mary$3.run(Mary.java:290)

Results :

Failed tests: 
  MaryInterfaceIT.canProcessToTokens:123 null

Tests in error: 
  MaryInterfaceIT.setUp:47 » MaryConfiguration Cannot start MARY server

Tests run: 20, Failures: 1, Errors: 1, Skipped: 0

[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:verify (verify) @ marytts-runtime ---
[INFO] Failsafe report directory: /home/helal/marytts-master/marytts-runtime/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MaryTTS ........................................... SUCCESS [0.803s]
[INFO] marytts-common .................................... SUCCESS [1.010s]
[INFO] marytts-signalproc ................................ SUCCESS [0.768s]
[INFO] marytts-runtime ................................... FAILURE [4.458s]
[INFO] marytts-lang-de ................................... SKIPPED
[INFO] marytts-lang-en ................................... SKIPPED
[INFO] marytts-lang-te ................................... SKIPPED
[INFO] marytts-lang-as ................................... SKIPPED
[INFO] marytts-lang-bn ................................... SKIPPED
[INFO] marytts-lang-hi ................................... SKIPPED
[INFO] marytts-lang-tr ................................... SKIPPED
[INFO] marytts-lang-ru ................................... SKIPPED
[INFO] marytts-lang-it ................................... SKIPPED
[INFO] marytts-lang-fr ................................... SKIPPED
[INFO] marytts-lang-sv ................................... SKIPPED
[INFO] marytts-languages ................................. SKIPPED
[INFO] voice-cmu-slt-hsmm ................................ SKIPPED
[INFO] marytts-client .................................... SKIPPED
[INFO] marytts-builder ................................... SKIPPED
[INFO] marytts-redstart .................................. SKIPPED
[INFO] marytts-transcription ............................. SKIPPED
[INFO] marytts-assembly-builder .......................... SKIPPED
[INFO] marytts-assembly-runtime .......................... SKIPPED
[INFO] marytts-assembly .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.254s
[INFO] Finished at: Thu Feb 12 16:32:40 IST 2015
[INFO] Final Memory: 26M/295M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.17:verify (verify) on project marytts-runtime: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/helal/marytts-master/marytts-runtime/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :marytts-runtime
helal@helal-HP-Compaq-6200-Pro-MT-PC:~/marytts-master$

**Comment by psibre** [comment]
@Mullahz Like I said, could you please open a new issue?
