### ISSUE TITLE
energy issue with mary builder

### ISSUE THREAD

**Issue by nlphacker** [marytts/marytts#214]
I rebuilt the cmu slt voice with mary 5.2 builder snapshot built from trunk

when trying it in the client,  the default sentence "Welcome to the world of speech synthesis!"  has suddenly volume drop after the word "welcome"  

Any idea what could be the possible reason?  

Or how can I repro the cmu slt font that has been checked in?

**Comment by jesinj** [comment]
Hi,

These comments are very useful. I did  change the values of the HMM Voice Configure parameters, and did get some different (some better) results. 

I would like to know how we can change the values of GV iterations from the default 100? 

Any suggestions would be very useful to give me a good direction.
