### ISSUE TITLE
Drop FreeTTS dependencies

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#228]
The three dependencies `freetts`, `freetts-de`, and `freetts-en_us` do not have sources available, and don't seem to correspond to any known version of [upstream FreeTTS](http://freetts.sourceforge.net/). This is a problem, since there a few issues that cannot be properly debugged.

Also [jCenter](https://bintray.com/bintray/jcenter) does not allow us to publish the artifacts without sources, so we have to add [OJO](https://oss.jfrog.org/) as an additional repository.

**Comment by Munzey** [comment]
nice :+1:

**Comment by psibre** [comment]
There are a couple of minor bugs with the new Preprocess class, but those can be separate issues.
