### ISSUE TITLE
Mary phoneme-grapheme correspondence 

### ISSUE THREAD

**Issue by LTVDev** [marytts/marytts#233]
Hello everyone,

does anyone know how the phoneme-grapheme correspondence works with Mary? When the en_GB text-files include minimal pairs like "cot" and "caught" and they are both transcribed as [kot]  (SAMPA), does Mary differentiate between those two? If we annotate the pronunciation of one vowel as wrong, can Mary use the graphemes around the vowel to differentiate between those two? Would an annotation for the word "too" also apply to the words "to" and "two", which would be counterproductive for us?
We would appreciate any help. Thank you in advance.

**Comment by Munzey** [comment]
mary looks for the word first by fst lookup, and if it not found, it applies g2p rule using the .lts file
