### ISSUE TITLE
Create a new voice

### ISSUE THREAD

**Issue by furkancelik** [marytts/marytts#239]
Hi everyone,
I want to create a new voice for it but what should I do?
step-by-step what I can do, I'd appreciate it if you write.

voiceimport tool errors when using the sounds cannot compile (I think some of the programs are not installed), and audio recordings I don't know how to create one.

Turkish sound I'm trying to create for it /marytts-lang-tr/lib/modules/tr/lexicon/tr.txt
directory tr.txt the text file in my writing, I'll perform?

**Comment by winman3000** [comment]
I would also like to build and import a voice for an existing language (German). Unfortunately, the site https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial seems to no longer exist in this form. Anyway, I can't find any instructions at this link.

I am mainly interested in the following:
1. Which text do I have to record in German? Is the text arbitrary or is it given somewhere? If so, where can I find this text.
1. If the text may be arbitrary, how long must the recording be?
1. Must the file name of the audio file be the same as the TXT file?

Thanks in advance for the help!
