### ISSUE TITLE
Odd pause in generated audio (Italian, istc-lucia-hsmm)

### ISSUE THREAD

**Issue by ugilio** [marytts/marytts#242]
With certain pieces of text (i.e. the word "cento" at the end of a sentence) the generated audio contains some unnatural pauses with istc-lucia-hsmm voice.

How to reproduce:
- Start MaryTTS server and Mary GUI Client
- In the client, set Input Type = TEXT, Output Type = AUDIO, voice = istc-lucia-hsmm
- Try to synthesize the text "cento"

The output sounds odd, with a pause between "cen" and "to", as if it was "cen.to".
This does NOT happen if "cento" is followed by another word: that is, "cento cani" is correctly pronounced (listen to both to hear the problem)

For me, this bug is always reproducibile with MaryTTS 5.0 and 5.1, both with server & client configuration and using LocalMaryInterface to generate an audio stream in java code.
I don't know if it is a voice or language problem, as there is only one voice for italian.

**Comment by lisitso** [comment]
Hi, there are other words badly pronounced, for example:
- "L'alimentazione" is wrong, while "alimentazione" is right  (the wrong is a pause like: "L'alimen.tazione")
- the same for "l'appetito" is wrong, "appetito" is right.
- Antropologica
- Ippocrate
- Duodenale
- Pressorio

and others. How's possible to contribute fixing this words?

**Comment by aitorme** [comment]
hi @lisitso, could you please tell where the pause happens in words like "Duodenale" or "Pressorio"?

**Comment by lisitso** [comment]
Hi @aitorme,
the pause should happen as follow:
Duodena.le
presso.rio

if I found other words, should I report them to you?
Is then possible to have the voice fixed?
Thank you

**Comment by lisitso** [comment]
Please could you consider to fix also the issue reported by @ugilio 
because the word "cento" (or the number 100) are still badly pronunced in Mary TTS server 5.1.2
For example, this sounds wrong:
"noi siamo in cento"

but note this:
"noi siamo in cento. voi siete in cento"
the first cento is good pronunced but the last cento in add a pause (cen.to) like ugilio reported.

Thanks

**Comment by ftesser** [comment]
Hello, if I remember well, some of the problems you listed could be fixed by adding a final punctuation mark at the end of the sentence.

E.g.: Noi siamo cento. Voi siete in cento.

**Comment by lisitso** [comment]
Hi @ftesser 
unfortunately even if adding "." it doesn't work. It works only if the word is NOT the last word of the sentence. If it's the last, an expected pause is added.

**Comment by giox79** [comment]
Good morning @lisitso , did you find any fix about this issue?
I'm facing the same problem, I'd like to know if you found any "special" mark fixing the problem.
Thank you for any help

**Comment by lisitso** [comment]
Hi @giox79 , unfortunately no. If you'd found any solution feel free to share it :-) Ciao!
