### ISSUE TITLE
HMM Voice Building

### ISSUE THREAD

**Issue by ahoenemann** [marytts/marytts#244]
Hi everyone,

I try to build a new voice with the VoiceImport tool. I could extract all features but now I have a problem with the Data Preparation for the training process (HMMVoiceMakeData). I don't know if it is a problem with the path or something. 

console output: 

---

Opening GUI....... 
Loading database layout:
Reading config file /home/voice/database.config
Reading external binaries config file /home/marytts/lib/external/externalBinaries.config
Loading basename list from file /home/voice/basenames.lst
Found 366 files in basename list
Loading features from file /home/voice/mary/features.txt
Running: cd /home/voice/hts/data
make mgc

make: **\* No rule to make target `mgc'.  Stop.
java.lang.Exception: The component HMMVoiceMakeData produced the following exception: 
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.lang.RuntimeException:  computation failed on file [/home/voice/]!
Command line was: [cd /home/voice/hts/data
make mgc
].
    at marytts.util.io.General.launchBatchProc(General.java:609)
    at marytts.tools.voiceimport.HMMVoiceMakeData.compute(HMMVoiceMakeData.java:184)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)

---

There is no mgc in the data folder...

**Comment by ahoenemann** [comment]
Sorry, but I have one question. I've started the HMMVoiceMakeDate from the VoiceImpoirtTool and now after 7 hour I have an error and the process was stopped. How can I start it at a particular point of the process or have I start it again and have to wait 7 hours? I have almost 1700 file. I couldn't find a script for that.

**Comment by seblemaguer** [comment]
Hello,

have you got the error message ?

Kind regards,
Sébastien

ahoenemann writes:

> Sorry, but I have one question. I've started the HMMVoiceMakeDate from the
> VoiceImpoirtTool and now after 7 hour I have an error and the process was
> stopped. How can I start it at a particular point of the process or have I
> start it again and have to wait 7 hours? I have almost 1700 file. I couldn't
> find a script for that.
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by ahoenemann** [comment]
Yes, the question folder or files could not be found. Of course because there wasn't a folder. I don't no why. Unfortunately I had no log file, so I can't give you the exact error message.  I've started the whole process again with a log file. I use now the makefile instead the GUI. 
I've built a HMM voice but with a smaller set of files (400), so the voice sounds like micky mouse.

**Comment by seblemaguer** [comment]
Hello,

sorry for the delay. You need to go to the specific hts directory (<voicedir>/hts/) and run manually the following command:

```
perl scripts/Training.pl scripts/Config.pm
```

**Comment by ahoenemann** [comment]
Hello,
no problem. I've already found it. After two days and nights training I hope it will be finished today and  it will be sounds good ;-)

**Comment by ahoenemann** [comment]
Ok, it doesn't work. I've built a voice now but it sounds like micky mouse. What could be the problem? It seems that are only 9 files were taken because it is written at the end the following only for 9 files. Can it be?  
---------------------------------------------------------------------------------------------
Synthesizing a speech waveform from /home/ahoenemann/pv_full/hts/data/labels/gen/gen_s0084.lab using hts_engine...done.
----------------------------------------------------------------------------------------------
I had also many warnigs at the step HAlign (I think) that the input data does not in the 'short' (or something like this). It has something to do with the f0? Otherwise there were  no errors.

Can I do something afterwards to improve the voice? I tried it with the client but it doesn't work neither.

Or mybe the recording, the human voice, is not useful?

**Comment by seblemaguer** [comment]
Hello,

what is the samplerate of your signal ?


ahoenemann writes:

> Ok, it doesn't work. I've built a voice now but it sounds like micky mouse.
> What could be the problem? It seems that are only 9 files were taken because it
> is written at the end the following only for 9 files. Can it be?
>
> Synthesizing a speech waveform from /home/ahoenemann/pv_full/hts/data/labels/
> gen/gen_s0084.lab using hts_engine...done.
>
> I had also many warnigs at the step HAlign (I think) that the input data does
> not in the 'short' (or something like this). It has something to do with the
> f0? Otherwise there were no errors.
>
> Can I do something afterwards to improve the voice? I tried it with the client
> but it doesn't work neither.
>
> Or mybe the recording, the human voice, is not useful?
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by ahoenemann** [comment]
they were 48khz but i downsampled them on 44khz

**Comment by ahoenemann** [comment]
if i started the compile process there was the message that it couldn't find the file mix_excitation_5filters_99taps_44Kz.txt. And this file was not there only mix_excitation_7filters_99taps_44Kz.txt

**Comment by ahoenemann** [comment]
i renamed it and then the compile process worked

**Comment by seblemaguer** [comment]
why have you downsampled ? Apparently, Mary support 48kHz 
ahoenemann writes:

> i renamed it and then the compile process worked
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by ahoenemann** [comment]
yes, now i know it. Because there were erros and then I downsampled it. I'ven't seen it before. Do you think this is the problem?

**Comment by ahoenemann** [comment]
But it have to work with 44hkz. I changed it in the settings on 44khz.

**Comment by seblemaguer** [comment]
I think your solution (renaming the file) was too naïve as you are using only a part of the mix_excitation part. Therefore, your coeffients doesn't represent any consistent data which could lead to the warning in the hsmmalign stage.

Can you run everything in default configuration and give me the error ?


ahoenemann writes:

> yes, now i know it. Because there were erros and then I downsampled it. I'ven't
> seen it before. Do you think this is the problem?
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by ahoenemann** [comment]
But I need three days. Whar do you with default configuaration. I did it. I changed only the paths in the seetings. Or should I try it with the 48khz files?

**Comment by seblemaguer** [comment]
Can't you use a subset (modify the train.scp to take 1/3 of the files). I'm pretty sure that most of the time was due to the alignment.

ahoenemann writes:

> But I need three days. Whar do you with default configuaration. I did it. I
> changed only the paths in the seetings. Or should I try it with the 48khz
> files?
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by ahoenemann** [comment]
No, the most time was the building of the trees. I can try it with 400 file. With 48khz?

**Comment by ahoenemann** [comment]
So, not the whole process. Which error do you mean? It was no error only warnings. This is waht you mean?

**Comment by ahoenemann** [comment]
When should I start with the script?

**Comment by psibre** [comment]
Just for the record, downsampling from 48 to 44.1 is a [bad idea](http://en.wikipedia.org/wiki/Quantization_error), unless you want to burn CDDA.

**Comment by ahoenemann** [comment]
Yes, I have understood. I can take 400 files with 48khz but you said that I can only modiefied the train.scp. So, I do not have to do the whole process? So, When can I start with the script?

**Comment by ahoenemann** [comment]
I have also to modiefied the training.pl script

**Comment by seblemaguer** [comment]
Warnings indicate that something may me wrong in the models. Based on the fact you told me you downsampled and rename the file, I assume that it might be a too violent a lead to inconsistent mixed excitation coefficients which could lead to the bad voice.

So only modifying the train.scp and run the training.pl should be ok to test

ahoenemann writes:

> So, not the whole process. Which error do you mean? It was no error only
> warnings. This is waht you mean?
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by seblemaguer** [comment]
no don't modify this script, you should never modify this script except if you know how it works
ahoenemann writes:

> I have also to modiefied the training.pl script
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by ahoenemann** [comment]
yes, but then it starts from the beginning

**Comment by ahoenemann** [comment]
yes but if the process was stopped because of an error I modiefied it. I started from the place where it stopped. This was ok. I can see it because of the comments

**Comment by seblemaguer** [comment]
It has to. Nothing guarantees that even the initial models are good.
ahoenemann writes:

> yes, but then it starts from the beginning
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by ahoenemann** [comment]
I think I have to start with the tool because I have to change the setting?

**Comment by ahoenemann** [comment]
ok, I started but now I habe the error:

...
 - system is PLAIN
  ERROR [+2121]  HInit: Too Few Observation Sequences [0]
 FATAL ERROR - Terminating program /usr/local/bin/HInit
Error in /usr/local/bin/HInit     -A    -C /home/ahoenemann/pv_full/hts/configs/trn.cnf -D -T 1 -S /home/ahoenemann/pv_full/hts/data/scp/train.scp                -m 1 -u tmvw    -w 5000  -H /home/ahoenemann/pv_full/hts/models/qst001/ver1/cmp/init.mmf -M /home/ahoenemann/pv_full/hts/models/qst001/ver1/cmp/HInit -I /home/ahoenemann/pv_full/hts/data/labels/mono.mlf -l de15 -o de15 /home/ahoenemann/pv_full/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt
...

**Comment by ahoenemann** [comment]
I only modiefied the train.scp so that ther are only 400 files for the process and start 

perl script/Training.pl script/Config.pm from the console

**Comment by seblemaguer** [comment]
Yes my mistake, you have to restart everything from the beginning as you are using not the same samplerate
ahoenemann writes:

> I only modiefied the train.scp so that ther are only 400 files for the process
> and start
>
> perl script/Training.pl script/Config.pm from the console
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website : http://sites.google.com/site/seblemaguer

**Comment by ahoenemann** [comment]
yes. From the beginning means up to HMMVoiveTrainer or earlier?

**Comment by ahoenemann** [comment]
For me its important that I will habe a good voice. So, do you mean 400 files are enough?

**Comment by ahoenemann** [comment]
I've got this message:
...
Extracting strengths from raw/s0323.raw
Unable to open mixer /dev/mixer
---

Is it a problem? For what is the mixer?

**Comment by ftesser** [comment]
Hi, this is only a warning that refers to snack/tcl, it does not affect the computation of the strengths coefficients. So you can ignore them.

**Comment by ahoenemann** [comment]
I'm not sure because of the much numUsing 0. Looks this ok?
..
Reestimating HMM /home/ahoenemann/pv_full/hts/models/qst001/ver1/cmp/HInit/aU . . . 
 States   :   2  3  4  5  6 (width)
 Mixes  s1:   1  1  1  1  1 ( 105  )
 ( 105  )
 Num Using:   0  0  0  0  0
 Mixes  s2:   2  2  2  2  2 (  1  )
 ( MSD  <=  1 )
 Num Using:   0  0  0  0  0
 Mixes  s3:   2  2  2  2  2 (  1  )
 ( MSD  <=  1 )
 Num Using:   0  0  0  0  0
 Mixes  s4:   2  2  2  2  2 (  1  )
 ( MSD  <=  1 )
 Num Using:   0  0  0  0  0
 Mixes  s5:   1  1  1  1  1 ( 15  )
 ( 15  )
 Num Using:   0  0  0  0  0

Initialising  HMM /home/ahoenemann/pv_full/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt . . . 
 States   :   2  3  4  5  6 (width)
 Mixes  s1:   1  1  1  1  1 ( 105  )
 ( 105  )
 Num Using:   0  0  0  0  0
 Mixes  s2:   2  2  2  2  2 (  1  )
 ( MSD  <=  1 )
 Num Using:   0  0  0  0  0
 Mixes  s3:   2  2  2  2  2 (  1  )
 ( MSD  <=  1 )
 Num Using:   0  0  0  0  0
 Mixes  s4:   2  2  2  2  2 (  1  )
 ( MSD  <=  1 )
 Num Using:   0  0  0  0  0
 Mixes  s5:   1  1  1  1  1 ( 15  )
 ( 15  )
...

**Comment by ahoenemann** [comment]
Is this ok? UT seems to be empty. All parameter looks like this one.

...
UT {}
 Untie previously tied structures
 UT: Untied 18399 ~p structures
...

**Comment by ahoenemann** [comment]
The downsamplen was not the problem. Its the same with 48khz. Micky Mouse.

**Comment by ahoenemann** [comment]
The problem is the pitch and the duration together. I modified the Mickey Mouse voice im Audacity and it sound s good. Is there a parameter which I can set for the control of there features. The pitch I know but the duration?
