### ISSUE TITLE
add new language to MARY TTS

### ISSUE THREAD

**Issue by ghost** [marytts/marytts#249]
Hello, I want to add my language to MARY TTS. I have passed without problem all steps of 
github.com/marytts/marytts/wiki/New-Language-Support and made only 1000 transcribe most frequent
 words using "./transcription.sh" and selected sentences using wkdb_synthesis_script_GUI.sh and create
 120 wavs using redstart tool. In final I can't get any result. Using marytts-server.sh i am checking NLP
 part is normal but I can't get "AUDIO" of text. I don't know voice build i have done bad or transcribe of
 words, selecting sentence, wavs aren't enough or little? Please give advice .

**Comment by Yamin372** [comment]
![desktop](https://cloud.githubusercontent.com/assets/15828708/11621401/9d9a842e-9ce1-11e5-99bb-78ecae5b6081.jpeg)
why is it starting from 20...have been trying tis for soo long...can u help??

**Comment by BibekBazaz** [comment]
i have posted an issue #502 where I am finding the problem with the number of words to be trained. i do not understand if the written format of the words is wrong or there is some other problem but the training does not take all the words into account. out of 300 words only 20 words are taken and for the rest all the allophone entries are deleted by the system.  i do not understand how to move forward. i need urgent help. please help me
