### ISSUE TITLE
Accent feature for new locale/language

### ISSUE THREAD

**Issue by sjai013** [marytts/marytts#250]
Hi,

I'm having difficulty using _accent_ as a feature for a new locale for english.  I've attached the outputs I get for enNZ (new locale) and enUS for the word _welcome_, and feature _accented_.  

enNZ
-----------
w 0
{ 0
l 0
k 0
@ 0
m 0

enUS
----------
w 1
E 1
l 1
k 0
@ 0
m 0

I've defined functional words in the enNZ dictionary, and used dashes ("-") to denote syllables in the dictionary.

Is anyone able to shed some light on how the _accent_ feature is determined?

**Comment by sjai013** [comment]
The issue was caused by the transcription of words in my en_NZ dictionary.  [The OpenMARY system expects a _'_ (apostrophe) character to process whether a syllable has a stress or accent](https://github.com/marytts/marytts/blob/7b8ec6a686bca840b16546935efd9ec2e8d290b8/marytts-runtime/src/main/java/marytts/modules/PronunciationModel.java#L333-L340) (the absence of the apostrophe character meant that OpenMARY was setting the accent to _0_ by default.

In the provided en_US dictionary, the word _welcome_ is transcribed as _' w E l - k @ m_.  However, in my en_NZ dictionary, the apostrophe is not present (i.e. the word _welcome_ is transcribed as _w { l - k @ m_).  Modifying the transcription of the word _welcome_ to include the apostrophe character resolved the issue for that particular word, and accent is now properly applied for that word.

**Comment by psibre** [comment]
Incidentally, there is a related issue (#266) with syllabification of words that are *not* in the dictionary...
