### ISSUE TITLE
Transcription tool (Problem occured)

### ISSUE THREAD

**Issue by dayoreke** [marytts/marytts#252]
My name is Oluokun Adedayo. I am currently trying to develop mary for Yoruba language. I am stuck with the transcription tool.

I have been able  to create a db of Yoruba words extracted from wikipedia, and the transcription tool loads them correct and i also have a list of transcribed words which i also loaded for the training.

However my problem is this:

After loading the files, when i click on 'train and predict', it displays a message box with the content "problem occurred, null--see console for details"

I checked the console and couldn't get any useful information.
I use ubuntu 13.10 and java version "1.7.0_25".

I will appreciate your responses. Thanks.

**Comment by vishalranapatgiri** [comment]
how did you correct the duplicates
