### ISSUE TITLE
featureDefinition.txt not formed/found

### ISSUE THREAD

**Issue by Nrdp** [marytts/marytts#259]
the wkdb_featuremaker.sh wkdb.conf runs sucessfuly once i changed the FeatureMaker to FeatureMakerMaryServer in marytts.tools.dbselection but when i try for the next step ie wkdb_database_selector.sh wkdb.conf
i get the following error
locale : as_IN
mysqlHost : localhost
mysqlUser : ***********
mysqlPasswd : **********
mysqlDB : wiki
selectedSentencesTable name: test
tableDescription: Testing table for selected sentences. Wikipedia locale:

stop criterion : numSentences 90 simpleDiphones simpleProsody
logCoverageDevelopment
verbose

Checking if there is [locale]_featureDefinition.txt in the current directory
Please provide a [locale]_featureDefinition.txt, it should have been generated by the FeatureMaker.
See: http://mary.opendfki.de/wiki/NewLanguageSupport step 5.

Checking if there is already a covDef.config in the current directory
Using covDef.config in current directory.
covDefConfigFileName = /home/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wiki_directory/covDef.config

Checking stop criterion:
Stop: num sentences 90
Stop: simpleDiphones
Stop: simpleProsody

Mysql driver loaded, set locale=as_IN
Current selected sentences table name = as_IN_test_selectedSentences
Mysql connection created successfully.

Loading feature definition...
java.lang.NullPointerException
at java.io.File.(File.java:277)
at marytts.tools.dbselection.DatabaseSelector.main2(DatabaseSelector.java:189)
at marytts.tools.dbselection.DatabaseSelector.main(DatabaseSelector.java:113)
Exception in thread "main" java.lang.Exception: Error opening featureDefinition file
at marytts.tools.dbselection.DatabaseSelector.main2(DatabaseSelector.java:196)
at marytts.tools.dbselection.DatabaseSelector.main(DatabaseSelector.java:113)

**Comment by Shandigutt** [comment]
Could you manage to solve this issue? I also get the same error. I'm trying to add Sinhala language support to MaryTTS

**Comment by Shandigutt** [comment]
I solved this problem. Add your language module to marytts-assembly/assembly-builder/pom.xml. Then you can run FeatureMarker without assertion error. No need to use FeatureMarkerMaryServer. FeatureMarker creates the <locale>_featureDefinition.txt

**Comment by Munzey** [comment]
@Nrdp did that solve the issue? if not please comment and we can reopen the issue, or you can open a new issue
