### ISSUE TITLE
VoiceCompiler-Build failure

### ISSUE THREAD

**Issue by Georgakopoulos** [marytts/marytts#261]
I have successfully created a few voices with the MaryTTS-voice-import-tools, while using parts of my Database. I was successful using up to 75% of the Recordings(1.1GB, 6100 sentences), but when I tried to create the voice using all of the sentences in my database it failed at the very end in the voice_compiler!

He is a part of the error message I get:
...
maven out>[INFO] --- build-helper-maven-plugin:1.7:attach-artifact (attach-artifacts) @ voice-tlabs6000 ---
maven out>[INFO] 
maven out>[INFO] --- maven-failsafe-plugin:2.8:integration-test (integration-test) @ voice-tlabs6000 ---
maven out>[INFO] Failsafe report directory: /home/demo/Desktop/Mary/tlabsvoice/mary/voice-tlabsvoice/target/failsafe-reports
maven out>
maven out>-------------------------------------------------------
maven out> T E S T S
maven out>-------------------------------------------------------
maven out>Running marytts.voice.Tlabs6000.LoadVoiceIT
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 43.8 sec <<< FAILURE!
maven out>
maven out>Results :
maven out>
maven out>Tests in error: 
maven out>  canLoadVoice(marytts.voice.Tlabs6000.LoadVoiceIT): Java heap space
maven out>
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
...

I can not find a good reason why this is happening, does anybody have an idea?
Best regards, Iason

**Comment by aWelker** [comment]
I'm facing the same problem right now; my basename.lst only contains 5069 items
Does anybody know how to solve this? If not, what amount of data did still work for you?
I get this output:

maven out>-------------------------------------------------------
maven out> T E S T S
maven out>-------------------------------------------------------
maven out>Running marytts.voice.My_voice.LoadVoiceIT
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 39.158 sec <<< FAILURE! - in marytts.voice.My_voice.LoadVoiceIT
maven out>canLoadVoice(marytts.voice.My_voice.LoadVoiceIT)  Time elapsed: 37.049 sec  <<< ERROR!
maven out>java.lang.OutOfMemoryError: Java heap space
maven out>	at marytts.features.FeatureDefinition.readFeatureVector(FeatureDefinition.java:1408)
maven out>	at marytts.unitselection.data.FeatureFileReader.loadFromByteBuffer(FeatureFileReader.java:110)
maven out>	at marytts.unitselection.data.FeatureFileReader.load(FeatureFileReader.java:72)
maven out>	at marytts.unitselection.data.FeatureFileReader.<init>(FeatureFileReader.java:68)
maven out>	at marytts.unitselection.data.FeatureFileReader.getFeatureFileReader(FeatureFileReader.java:53)
maven out>	at marytts.unitselection.select.DiphoneFFRTargetCostFunction.load(DiphoneFFRTargetCostFunction.java:56)
maven out>	at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:111)
maven out>	at marytts.voice.My_voice.LoadVoiceIT.canLoadVoice(LoadVoiceIT.java:20)
maven out>
maven out>
maven out>Results :
maven out>
maven out>Tests in error: 
maven out>  LoadVoiceIT.canLoadVoice:20 » OutOfMemory Java heap space
maven out>
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
maven out>   ...

I'm running maven 3 and java 1.8, .wav files evaluate to 833,3 MB

**Comment by aWelker** [comment]
If anyone should have the same problem, here is the solution that finally worked for me:

a) increase java heap space from 4G to 8G
b) decrease java heap space from 8G to 4G
c) run the VoiceCompiler

**Comment by aitorme** [comment]
@Georgakopoulos did you try the workaround that @aWelker suggested? Does it work now?

**Comment by Georgakopoulos** [comment]
Not yet, but as soon as I find the time I will.

**Comment by Georgakopoulos** [comment]
I does not seem to work for me! I tried that using: 
```java
demo@demo-LIFEBOOK-S710:~$ export _JAVA_OPTIONS=-Xmx4096m
demo@demo-LIFEBOOK-S710:~$ java -XshowSettings:vm
Picked up _JAVA_OPTIONS: -Xmx4096m
VM settings:
    Max. Heap Size (Estimated): 3.56G
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM
```
+ I dont understand the point of first increasing and then decreasing the heap space from 4G to8G and back again!?

**Comment by Georgakopoulos** [comment]
I even tried changing the heap size in the pom.xml file, but it did not work.
```java
<configuration>
					<argLine>-Xms256m -Xmx512m</argLine>
					<systemPropertyVariables>
						<!-- The MARY installation directory, setting to the project dir for the purposes of our integration test: -->
						<mary.base>${basedir}</mary.base>
					</systemPropertyVariables>
				</configuration>
```
Mary sets it back to the initial levels **-Xms256m -Xmx512m** automatically, after running the voice compiler. I also tried changing the same *argLine* of the MaryBase **pom.xml**, but still nothing.
Any ideas?

**Comment by aWelker** [comment]
Hi,
It seems that it was rather a coincidence that the method worked for me; I tried again with slightly more data and haven't gotten it to work since then. Changing the pom.xml didn't work for me, either

**Comment by seblemaguer** [comment]
@Georgakopoulos I start to get a little bit confuse, did you try to change the heap size and this size didn't change ? Or did it change but you still facing the overused memory ?

**Comment by Georgakopoulos** [comment]
The second: I did change the heap-size, as far as I am aware, but the overused memory problem still persists.

**Comment by seblemaguer** [comment]
ok thanks. Have you had a look at the memory usage while you were trying to build ?

**Comment by Georgakopoulos** [comment]
Yes. The whole system reaches about 45% of it's capacity. Which is 3.1 GiB of 7.6GiB available in my case. It does not seem to be influenced by other programs being run in parallel. I have tried the building process only by itself and during normal usage (web-browser etc.). Both fail, whereas a smaller database 90% of my Data does not have any problem.
