### ISSUE TITLE
Default language TTS

### ISSUE THREAD

**Issue by omidp** [marytts/marytts#262]
regardless of adding a new language, I want to use marytts built-in languages which AFAIK contains it, de and etc. after building the source, I run http://localhost:59125/documentation.html non of the languages work except English I also couldn't find where marytts is loading audio files.
for non English languages I get following exception :  

http://localhost:59125/process?INPUT_TEXT=salam&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&LOCALE=de_DE&AUDIO=WAVE_FILE

No such property: de_DE.allophoneset

OR 
http://localhost:59125/process?INPUT_TEXT=salam&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&LOCALE=de&AUDIO=WAVE_FILE

No voice available for locale 'de'

What am I missing ?

**Comment by mcicolella** [comment]
Hi,
I copied voice-bits3.5.1.jar into "bin" folder where there is already voice-cmu-slt-hsmm-5.1.jar but calling getAvailableVoices() it returns only [cmu-slt-hsmm]. How to solve?
Thanks

**Comment by psibre** [comment]
> I copied voice-bits3.5.1.jar into "bin" folder where there is already voice-cmu-slt-hsmm-5.1.jar

You mean `voice-bits3-5.1.jar`? That should be under `lib`, not `bin`. Not sure how it ended up there.
Voice jars need to be on the classpath at MaryTTS startup to become available, and the classpath is set to `lib/*` by the startup script.

**Comment by mcicolella** [comment]
Hi, sorry my fault.
I meant "lib" folder, but it is not recognized. I'm integrating MaryTTS into our framework.
My code is available at https://github.com/mcicolella/freedomotic/tree/marytts/plugins/devices/marytts
Thanks

**Comment by psibre** [comment]
To use a unit-selection voice, it's not enough to put the jar file on the classpath; you also need to have the data files on your file system, and set the `MARYBASE` property so that the corresponding paths in the voice config resource are resolved correctly.
For the HSMM voices, putting the voice jar on the classpath is already sufficient.

**Comment by mcicolella** [comment]
Please,can you give me a complete example?
Thanks

**Comment by psibre** [comment]
The `marytts/voice/Bits3/voice.config` resource contains lines like
```aconf
# Voice-specific files
voice.bits3.featureFile       = MARY_BASE/lib/voices/bits3/halfphoneFeatures_ac.mry
voice.bits3.targetCostWeights = jar:/marytts/voice/Bits3/halfphoneUnitFeatureDefinition_ac.txt
voice.bits3.joinCostFile      = MARY_BASE/lib/voices/bits3/joinCostFeatures.mry
voice.bits3.joinCostWeights   = jar:/marytts/voice/Bits3/joinCostWeights.txt
voice.bits3.unitsFile         = MARY_BASE/lib/voices/bits3/halfphoneUnits.mry
voice.bits3.cartFile          = jar:/marytts/voice/Bits3/cart.mry
voice.bits3.audioTimelineFile = MARY_BASE/lib/voices/bits3/timeline_waveforms.mry
voice.bits3.basenameTimeline  = MARY_BASE/lib/voices/bits3/timeline_basenames.mry
```
So you could either set all properties containing the `MARY_BASE` string to point to where you unpacked the data files, like `-Dvoice.bits3.featureFile=/path/to/bits3/halfphoneFeatures_ac.mry` etc. or just set the special `MARY_BASE` property, i.e., `-Dmary.base=/path/to/mary/installation`, which will then make all those config properties expand to the correct paths.

**Comment by mcicolella** [comment]
I tried but it doesn't work. Thanks

**Comment by psibre** [comment]
Could you be more specific? How exactly did you try?

**Comment by mcicolella** [comment]
I extracted voicebit zip under my "lib" folder where HMSS default voice is placed. In that folder there are all .jar files and another folder voices
So I set mary.base property as       
System.setProperty("mary.base",Info.PATHS.PATH_DEVICES_FOLDER+System.getProperty("file.separator")+"marytts");

**Comment by psibre** [comment]
So to which path string does `Info.PATHS.PATH_DEVICES_FOLDER+System.getProperty("file.separator")+"marytts"` evaluate?

**Comment by mcicolella** [comment]
It points to
C:\Users\maurocic\Desktop\commander\plugins\devices\marytts
In marytts there is a "lib" folder including all .jar files (and voices) and in "lib" a subfolder "voices".
By code I read all available voices and languages
INFO  <AWT-EventQueue-0> [MaryTTS] Available voices: '[cmu-slt-hsmm]'
INFO  <AWT-EventQueue-0> [MaryTTS] Available languages: '[en_US, fr, ru, tr, sv,
 de, it, te, en_GB]'

**Comment by psibre** [comment]
Just to be sure: ` C:\Users\maurocic\Desktop\commander\plugins\devices\marytts\lib\voice-bits3-5.1.jar` exists? Can you double-check that it's on your classpath?

**Comment by mcicolella** [comment]
Hi, 
thanks for your suggestions. Now it works! I found a solution to specify as parameter which voice to use. I uploaded the plugin on our marketplace. The link is http://www.freedomotic.com/content/plugins/marytts-text-speech

**Comment by psibre** [comment]
Glad you got it working. Nice!
