### ISSUE TITLE
a letter has different phone

### ISSUE THREAD

**Issue by ghost** [marytts/marytts#263]
Hello, in my lang there is  letter (k) which has two phone and I describe in allophones.xy.xml like this : 
	<consonant ph="c" ctype="s" cplace="p" cvox="-" /> 
	<consonant ph="k" ctype="s" cplace="v" cvox="-" /> 
In final I am always getting first phone of letter and in  How can I get second phone of letter (k)? with adding a lot recording which contain the second phone of letter?

**Comment by seblemaguer** [comment]
Hello,

you are mistaking between grapheme and phoneme. In the allophones.xy.xml file, you need to have unique id. However, in the lexicon file or if you have another mean you will describe the rule to transform the grapheme k in the appropriate phoneme

**Comment by NeptunSun** [comment]
Hello, thanks for your answer. In my language one grapheme has different pronunciation or one grapheme describes 2 phonemes. I am trying to solve this task like this: 

1. In allophones I describe two phone with unique id 
{
	<consonant ph="c" ctype="s" cplace="p" cvox="-" /> 
	<consonant ph="k" ctype="s" cplace="v" cvox="-" /> 
}
2.  When I create pronunciation dictionary In Transcription step I take a lot of word which contain k grapheme and transform  the grapheme k in the appropriate phoneme.  

But. in result I am always getting  first phoneme. 
Is this good solution? or what I must do to solve this task?

**Comment by NeptunSun** [comment]
When I run this command : 

http://localhost:59125/process?INPUT_TEXT=medikal&INPUT_TYPE=TEXT&OUTPUT_TYPE=PHONEMES&...   

I am getting 
<t g2p_method="rules" ph="' m e - d I - c A l" pos="content">  

but I must  get 

<t g2p_method="rules" ph="' m e - d I - k A l" pos="content">  

Maybe problem is g2p_method?

**Comment by psibre** [comment]
So you're saying that you have two different words, both spelled *medikal*, and one is pronounced [me-dI-cAI] and other, [me-dI-kaI]?

**Comment by psibre** [comment]
Or that there is a word *medikal* that is not in the lexicon, which should be pronounced [me-dI-kAl], but the g2p rules predict the pronunciation [me-dI-cAl]?
In this case, why not add it to the lexicon?

**Comment by NeptunSun** [comment]
Hello, There is a word 'medikal' that is in the lexicon and which should be pronounced [me-dI-kAl], but I don't know why I am always getting the pronunciation [me-dI-cAl]. 

My problem is 'k' grapheme which describes two phone [k] and [c]. 
Exp. In the word medi[k]al I must take [k] but in the word [k]itab i must take [c]. 
finally,  I am always getting [c] phoneme.

how can I solve this problem?

**Comment by psibre** [comment]
If you have a line like
```
medikal    m e - d I - k A l
```
in your lexicon file, but your Phonemiser module is setting `g2p_method="rules"`, then something is wrong. Did you retrain your LTS model after adding the entry to the lexicon?

**Comment by NeptunSun** [comment]
Sorry but, I don't understand last question especially "retrain your LTS model". Can you write clear for me. Thank you in advance

**Comment by psibre** [comment]
The LTS model is generated by running the TranscriptionTool on your lexicon. The runtime files in [Section 4](https://github.com/marytts/marytts/wiki/New-Language-Support#4-minimal-nlp-components-for-the-new-language) are up-to-date and in the right place?

**Comment by NeptunSun** [comment]
Thank you very much. I solved this problem with your help.
