### ISSUE TITLE
MaryTTS server embedded

### ISSUE THREAD

**Issue by mcicolella** [marytts/marytts#265]
Hi all,
I'd like to create a plugin for our framework freedomotic.com but I'd to embed the server to make the installation simpler for common users (no compilation, no os configuration etc).
My idea is to copy the jar server into a folder of the plugin and start it by code when the sw loads.
I'd use ProcessBuilder. What do you think? any suggestions?
Thanks

**Comment by psibre** [comment]
If your framework is written in Java, I would suggest you simply add a MaryTTS voice as a dependency of your project; in Gradle you can do
```groovy
repositories {
  jcenter()
}
dependencies {
  compile "mary.dfki.de:voice-cmu-slt-hsmm:5.1.1"
}
```
Then there is no need to manually download or compile anything.
