### ISSUE TITLE
Syllabifier always assigns initial stress

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#266]
The [Syllabifier](https://github.com/marytts/marytts/blob/71e80fe5a8fb4e3cfc9a590d39f4c898524cb8d5/marytts-runtime/src/main/java/marytts/modules/phonemiser/Syllabifier.java) always assigns initial stress to phone strings, even when the input already contains non-initial stress.

**Comment by psibre** [comment]
Code smell and several problems in that class, including,
* *contrary to its Javadoc*, the `syllabify(LinkedList)` method returns `void`, while the `syllabify(String)` method returns the syllabified string;
* the `splitIntoAllophones` method *silently ignores* any symbols that are not in the AllophoneSet;
* the `splitIntoAllophones` method *silently drops* any stress marks already present!

**Comment by psibre** [comment]
It's becoming increasingly obvious that the Syllabifier class was designed to fundamentally different specifications than what is required now. The `syllabify` method does not perform as documented, is implemented in an overly convoluted way (inserting strings as markers, then removing them again, etc.).

I believe the entire Syllabifier class is a lost cause and should be deprecated, and a new `syllabify` method added to the AllophoneSet instead. (Incidentally, why is it in a different Maven module?)

**Comment by Munzey** [comment]
indeed it would seem to make a lot more sense to implement a syllabify() method in the AllophoneSet class. If a main method was then also added allowing for parameters (an allophone file and words_to_be_syllabified) to be passed to it , it would be a lot easier to implement in a gradle script :dancer:
