### ISSUE TITLE
TEXT->REALISED_DURATIONS works, REALISED_DURATIONS->AUDIO doesn't

### ISSUE THREAD

**Issue by kjyv** [marytts/marytts#267]
As with other combinations, some of the generated data seem to not be parsed properly.
While it is possible to synthesize REALISED_DURATIONS from TEXT or EMOTIONML, 
generating audio from these is not possible (server gets stuck with 100% cpu).
An example input is 
#
0.080000006 125 h
0.14000002 125 a
0.19500002 125 l
0.30500004 125 o:
0.64500004 125 _

It would be very helpful to have this fine grained control over the output.

**Comment by alishah-ahmed** [comment]
Could you please provide us with the following details if possible:
- Stacktrace
- Java Version
- Machine details that you are using along with OS details.
Thanks.

**Comment by kjyv** [comment]
As it "gets stuck", there is no stacktrace, as no error is thrown. At least I couldn't see any on both terminal windows (server or client).

$ java -version
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)

Running on OSX 10.10.1.

**Comment by psibre** [comment]
Could you please provide the details of your request? Which locale/voice are you using?

**Comment by kjyv** [comment]
Language de or en, and it seems the voice doesn't matter, bits1-hsmm, bits3, bits3-hsmm, dfki-pavoque-neutral-hsmm all produce this behavior.

**Comment by psibre** [comment]
I believe that the source of this issue is that `REALISED_DURATIONS` and `REALISED_ACOUSTPARAMS` were *intended only as output types*, but when they were originally introduced (in bd582c8d8b7f0e3da42b067b72c142e6d8758a80 and eb8807b7eeeeb430ccf098127e2bd9624b47f7a9, respectively), their `isInputType` parameter was set to `true`.
