### ISSUE TITLE
Unhandled text preprocessing of numeric tokens

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#269]
Rather a major issue, but something that cannot simply be implemented from scratch on a shoestring budget, which is why we had to live with it up to now.

For the "lite" language components, no text preprocessing is implemented, which causes numeric tokens to be ignored further down the pipeline. For example, converting the input text "a 15 b" from `TEXT` to `WORDS` for **German** produces
```xml
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
  <p>
    <s>
      <t>a</t>
      <mtu accent="last" orig="15">
        <t>fünfzehn</t>
      </mtu>
      <t>b</t>
    </s>
  </p>
</maryxml>
```
This is courtesy of the `marytts.language.de.Preprocess` module.

On the other hand, for **French** (and most other languages), we get
```xml
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="fr">
  <p>
    <s>
      <t>a</t>
      <t>15</t>
      <t>b</t>
    </s>
  </p>
</maryxml>
```
This is because those languages don't have their own text preprocessing module and fall back on `marytts.modules.DummyTokens2Words`, which does exactly *nothing*.

The fallout is that at the stage of pronunciation prediction, those numeric tokens receive no `ph` attributes, so they are completely ignored in the TTS synthesis!

**Comment by psibre** [comment]
I think we can get a certain amount of mileage from [ICU4J](http://icu-project.org/apiref/icu4j/) by utilizing a *spellout formatter* (cf. [`RuleBasedNumberFormat`](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/RuleBasedNumberFormat.html#SPELLOUT). This should work for the major languages (such as French) out of the box; others may need a custom ULocale and rules to be written...

**Comment by psibre** [comment]
As a bonus, using this for English might help wean us off the problematic FreeTTS dependencies (see #228 ), which seem to be required exclusively for text preprocessing.

**Comment by psibre** [comment]
For French, @seblemaguer could also help. =)

**Comment by Munzey** [comment]
My fix269 branch now contains a preprocessing module for French which handles cardinal and ordinal numbers
