### ISSUE TITLE
test failure for arabic language support

### ISSUE THREAD

**Issue by doaaobiedat** [marytts/marytts#271]
https://github.com/bellegdi/marytts/tree/master/marytts-lang-ar
hello
i found this initial support for arabic language but when i try to test it, the build failure

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running marytts.language.ar.ArabicConfigTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.137 sec <<< FAILURE!

Results :

Failed tests:
  canGet(marytts.language.ar.ArabicConfigTest)
  hasRussianLocale(marytts.language.ar.ArabicConfigTest)

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.011s
[INFO] Finished at: Thu Jan 22 09:02:30 EET 2015
[INFO] Final Memory: 12M/126M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.8:test (default-test) on project marytts-lang-ar: There are test failures.
[ERROR]
[ERROR] Please refer to /home/engdoaa/marytts/adding_ar_lang/marytts-master/marytts-lang-ar/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by psibre** [comment]
Without the actual full stacktrace, it's not entirely clear. But at first glance, there are a few things you'll want to fix:
* `hasRussianLocale` should be renamed;
* your `ar.config` is simply an unmodified copy of the German `de.config`, it should be heavily modified -- in fact, I would recommend using `ru.config` as a template instead and modifying that.

**Comment by bellegdi** [comment]
@doaaobiedat Can you please rebuild the project with the updated Arabic version of marytts as there are some modified files that work for me all steps until feature maker.

**Comment by doaaobiedat** [comment]
thank you, it work. 
now I would like to go to step 5
```
$ Wkdb_featuremaker.sh wkdb.conf
```
But it depends on the Step 2
Do I have to implement all the previous steps?

**Comment by psibre** [comment]
@doaaobiedat Step 5 relies on the NLP resources you created in steps 3-4. So yes, you'll want to make sure they were successful before proceeding.
Please open a new ticket if you run into new issues.
