### ISSUE TITLE
Selecting a speaker and Recording voice in studio

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#283]
I have already made tts using maryTTS with little my own voice content. But now I want to make tts with professinal, big voice content in studio using maryTTS. I read some advices in these sources : 
http://festvox.org/bsv/x782.html
http://festvox.org/bsv/x818.html

and decide that speaker don't mumble and don't have any speech impediments and for sound record mono, 16000Hz, 16bit PCM.  

am I right? or can anybody give advice for recording voice proccess?

or can i make quality voice at home with using laptop?

**Comment by nshmyrev** [comment]
It is better to take audiobook or several audiobooks by same speaker and segment them with automatic aligner like sphinx4. If you find speaker with many audiobooks (50 hours of speech or so) you can create a very good voice.

**Comment by NeptunSun** [comment]
ok. but it is difficult for me to find audiobooks than to find speaker. I have already find speaker who don't mumble and don't have any speech impediments. But it is very important for me recording audio file format . Can I convert mp3 file to wav in this case what I will lose?  or sample format will be how? 16 bit PCM, or 32 bit float?

**Comment by nshmyrev** [comment]
What language are you looking on? For English there are many high-quality audiobooks on http://librivox.org

It is better to avoid mp3, but high-quality 256kb/s mp3 should be ok. 16bit PCM is a good format, 32-bit is not really required.

**Comment by psibre** [comment]
This is for Yoruba, right?
I would recommend using a lossless compression format such as [FLAC](https://xiph.org/flac/). For the sample rate, consider using something higher than 16 kHz; 48 kHz should give perfect quality. Remember that the recordings don't need to have the same (low) specification as the voicebuilding data.

**Comment by NeptunSun** [comment]
@nshmyrev  Thanks for links but I am not looking for audiobooks.  

@psibre  no this not Yoruba :) But thanks for advice.

If I understand right I can record speaker sound rate higher than 16 kHz MONO and file format flac ? 

But before voicebuilding i must convert sound rate 16000 and format wav MONO?   

am i right?  can i use sound rate 48000 in voicebuilding step?

**Comment by psibre** [comment]
FLAC supports much higher rates and channel numbers. But for voicebuilding, mono is fine. There is an open issue or two about building voices from data that is not 16 kHz. So for now you may get problems if you don't downsample first.

Having said that, we actually record using several channels, one for the speech, another one for beeps that mark the start of a new sentence (these are played automatically by the prompt presentation on each new slide), and a third channel for manual markers that we insert using a MIDI keyboard. The two extra channels speed up the post-processing by allowing us to split into sentences automatically and identify mis-takes etc.

**Comment by NeptunSun** [comment]
ok. @psibre  and @nshmyrev  thanks for all informations. 
But my last question is about aligner. I am using maryTTS's voicebuilder tool for listening letters in [LABELLEDFILESINSPECTOR].  I select a sentence and listen every letters in [LABELLEDFILESINSPECTOR] step. if i get all letters sound  i detect that wav file good aligner.  is there other solution to detect sound file is recording fine?
