### ISSUE TITLE
HMMVoiceConfigure

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#288]
Hello, I changed my voice configure like this. But in final I am getting speech like robot. Do anybody know which parameter I must change to have like human speech. Thanks in advance

```
# Properties for module HMMVoiceConfigure:
HMMVoiceConfigure.adaptF0Ranges 'awb 40 280 bdl 40 280 clb 80 350 jmk 40 280 rms 40 280 slt 80 35'
HMMVoiceConfigure.adaptHead b05
HMMVoiceConfigure.adaptScripts false
HMMVoiceConfigure.adaptSpkr slt
HMMVoiceConfigure.adaptSpkrMask */cmu_us_arctic_%%%_*
HMMVoiceConfigure.adaptTrainSpkr 'awb bdl clb jmk rms'
HMMVoiceConfigure.adaptTransKind feat
HMMVoiceConfigure.adaptTreeKind dec
HMMVoiceConfigure.configureFile /home/mary/Desktop/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/hts/configure
HMMVoiceConfigure.dataSet cmu_us_arctic
HMMVoiceConfigure.fftLen 512
HMMVoiceConfigure.frameLen 400
HMMVoiceConfigure.frameShift 80
HMMVoiceConfigure.freqWarp 0.42
HMMVoiceConfigure.gamma 0
HMMVoiceConfigure.lf0BandWidth 1
HMMVoiceConfigure.lnGain 1
HMMVoiceConfigure.lowerF0 110
HMMVoiceConfigure.mgcBandWidth 24
HMMVoiceConfigure.mgcOrder 24
HMMVoiceConfigure.normalize 1
HMMVoiceConfigure.numIterations 5
HMMVoiceConfigure.numState 5
HMMVoiceConfigure.numTestFiles 5
HMMVoiceConfigure.questionsNum 1
HMMVoiceConfigure.sampfreq 16000
HMMVoiceConfigure.speaker julie
HMMVoiceConfigure.strBandWidth 5
HMMVoiceConfigure.strFilterFileName filters/mix_excitation_5filters_99taps_16Kz.txt
HMMVoiceConfigure.strOrder 5
HMMVoiceConfigure.upperF0 250
HMMVoiceConfigure.version 1
HMMVoiceConfigure.windowType 1
```

**Comment by seblemaguer** [comment]
Hi,

can you provide a link to a sample ?

**Comment by NeptunSun** [comment]
Hi, 
    I can provide the link but you can connect with using our Cisco VPN client parameters : 

login: remotevpn1
parol: R3mp@183
link : http://172.16.6.73:59125/

I sent VPN pcf file to your email address [*** slemaguer [at] coli [dot] uni-saarland [dot] de ***]  with Object [VPN - MARY Web Client]. 

Thanks a lot.

**Comment by NeptunSun** [comment]
Hi,
I can provide the link but you can connect with using our mmy VPN  parameters.

I sent VPN pcf file and VPN client parameters to your email address [*** slemaguer [at] coli [dot] uni-saarland [dot] de ***] with Object [VPN - MARY Web Client].

Thanks a lot.

**Comment by seblemaguer** [comment]
Hi,

after listening to the samples, I can say that I think the achieved quality is normal. For the moment, the used HTS version is quite old and no high vocoding techniques into MARYTTS. Update of the used HTS version is planned for a near future but for the high vocoding techniques I really can't tell when it's going to be included.

**Comment by NeptunSun** [comment]
Hi, thank for help. I will change HTS version and will try again.

**Comment by NeptunSun** [comment]
Hi, thank for help. I am using these tools versions for generation new voice : 

    HTK-3.4.1
    HTS-2.2_for_HTK-3.4.1
    HDecode-3.4.1
    hts_engine_API-1.05
    SPTK-3.4.1
    OS version is  Ubuntu 32 bit

as written in script check_install_external_programs.sh. 

But during "start synthesizing waveforms (1mix)" step I am getting below warning for a lot of files (.mgc and .lf0): 

"x2x : warning: input data is over the range of type 'short'!"


PS:  HMMVoiceMakeData step I am not getting "unable to open mixer /dev/mixer hts ". 
I dont know where is my problem? 
and what will be negative effect of this warning during new voice generation ?

**Comment by seblemaguer** [comment]
If I remember correctly the use of global variance sometimes introduce an "overflow" during the parameter generation stage. Basically it implies a saturation on few frames. However, from what I listened, it's not really perceptible on your system. I conclude that too few frames are impacted by this error.

**Comment by NeptunSun** [comment]
ok. good, but how can I define these values : lowerF0 and upperF0. Is there any definition or rules to determine these values?  for female voice I wrote like below, but when I change these values I am getting always different voice.  

HMMVoiceConfigure.lowerF0 80
HMMVoiceConfigure.upperF0 350
