### ISSUE TITLE
parallelize voice training

### ISSUE THREAD

**Issue by timobaumann** [marytts/marytts#296]
Even though you guys want to replace the legacy voice building scripts (which I strongly support), it would be nice to use multi-processing where it's already easy. Below patches fix EHMM labelling to use ehmm2.7 which supports multi-processing, as well as a patch to HTS (adapted for 2.2 from the HTS mailling list) to use at least 5 of the available processors.
EHMM parallelization: https://gist.github.com/timobaumann/00dd14ce3015fdc3596c
HTS parallelization (maximum of 5 HERest in parallel): https://gist.github.com/timobaumann/4f1d7a300b0825bed8be

**Comment by psibre** [comment]
HTS parallelization I'll leave to @seblemaguer

**Comment by psibre** [comment]
@timobaumann ehmm works like a charm -- thanks very much! :grinning:

**Comment by pineking** [comment]
@timobaumann The HTS parallelization seem not for HERest, perhaps is for HHEd  with "JM" functions (that is the reason why the limit of maximum parallel  is 5). For HERest parallelization, the simplest way is to split the scp file to multiple one and use "-p 0" to merge the accumulate statistics.

**Comment by timobaumann** [comment]
thanks. I discovered though, that the ehmm-implementation suffers very
much from lock contention -- essentially all that is decoupled is
input-loading and some preparations from the actual baumWelch
reestimation (as accumulation messes up when multiple files are being
processed simultaneously). Thus, more than three of four threads don't
give any additional benefit. Also, none of the perl-scripts are
parallelized in any way, so the majority of things is still very slow. I
have changed this accordingly (max 4 threads for training,
availableProcessors() threads for alignment).
I have also now added three flags to perform/skip setup, training, and
alignment, respectively, to make the tool more useful. (This way, you
can perform training without needing an ongoing X connection, e.g. using
tmux or screen.)
Please see the updated patch in
https://gist.github.com/timobaumann/2993f57873d440de2c3b .


Am 30.03.2015 um 22:56 schrieb psibre:
>
> @timobaumann <https://github.com/timobaumann> ehmm works like a charm
> -- thanks very much! :grinning:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marytts/marytts/issues/296#issuecomment-87829278>.
>


-- 
Timo Baumann, Wissenschaftlicher Mitarbeiter

Fachbereich Informatik, Universität Hamburg
AB Natürlichsprachliche Systeme

http://nats-www.informatik.uni-hamburg.de/User/TimoBauman

**Comment by timobaumann** [comment]
yes, you're right, I mixed HERest and HHEd. However, HHEd is what takes
most of the time (at least on my machine with just a few processors).
I guess splitting the scp file would be the right thing (as then, we'd
be able to run as many HERests concurrently as we want), but I think
some people are working on making this much more flexible anyway.

Am 31.03.2015 um 07:35 schrieb Qingsong Liu:
>
> @timobaumann <https://github.com/timobaumann> The HTS parallelization
> seem not for HERest, perhaps is for HHEd with "JM" functions (that is
> the reason why the limit of maximum parallel is 5). For HERest
> parallelization, the simplest way is to split the scp file to multiple
> one and use "-p 0" to merge the accumulate statistics.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marytts/marytts/issues/296#issuecomment-87943684>.
>


-- 
Timo Baumann, Wissenschaftlicher Mitarbeiter

Fachbereich Informatik, Universität Hamburg
AB Natürlichsprachliche Systeme

http://nats-www.informatik.uni-hamburg.de/User/TimoBaumann

**Comment by psibre** [comment]
@timobaumann thanks very much!

Internally, we delegate the parallelization to gradle, but we haven't gotten around to rewrapping ehmm to this end. So ultimately I personally would favor that solution.

Meanwhile, could you please resubmit your patch as a pull request on https://github.com/psibre/marytts/tree/upgrade-ehmm ? This makes the changes easy to understand and avoids accidentally committing compiled binaries etc. Note that the tarball has been replaced by a source tree under `lib/external/ehmm` to keep things transparent.

**Comment by pineking** [comment]
@timobaumann ,yes, HHEd is still the slowest one, although it was parallelized.

**Comment by Munzey** [comment]
@psibre has this been merged? should it be closed?

**Comment by psibre** [comment]
I think the title is a bit misleading. This is about parallel forced alignment with EHMM, and also about the old HSMM training scripts...

**Comment by psibre** [comment]
In any case, I think we should close this, and open new specific issues as needed.
