### ISSUE TITLE
OpenNLPPosTagger mistakenly tags some tokens as `.` (punctuation)

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#298]
With output type `PARTSOFSPEECH`, compare

**Fnord**:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<voice name="cmu-slt-hsmm">
<s>
<t pos="NN">
Fnord
</t>
</s>
</voice>
</p>
</maryxml>
```
vs.
**Fnordalicious**:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<voice name="cmu-slt-hsmm">
<s>
<t pos=".">
Fnordalicious
</t>
</s>
</voice>
</p>
</maryxml>
```
This is not only wrong, but actually causes havoc downstream, when the JPhonemiser *ignores* tokens with `pos="."`!

**Comment by timobaumann** [comment]
going into the opposite direction, using bits3-hsmm-5.1 (is there a 5.2 voice that differs?), for "eins, zwei, drei, vier", I get the wrong tokenization as posted below. However, the comma is not an NN and should/cannot be phonemized later on. 

<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t pos="PIS">
eins
</t>
<t pos="$,">
,
</t>
<t pos="CARD">
zwei
</t>
<t pos="$,">
,
</t>
<t pos="CARD">
drei
</t>
<t pos="NN">
,
</t>
<t pos="CARD">
vier
</t>
</s>
</p>
</maryxml>

**Comment by psibre** [comment]
Interesting. My impression is that it could be an upstream issue with `opennlp-maxent`.
@timobaumann If you have time, perhaps it might make sense to [open an issue](https://issues.apache.org/jira/browse/OPENNLP?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel)...?

**Comment by timobaumann** [comment]
they might (rightfully) claim that stochastic models will always commit all sorts of errors and that both kinds of errors should be handled by downstream.  The original case (proper word tagged as punctuation) in this issue is being handled (somewhat) gracefully, whereas the reverse results in an error. That error could be avoided if handling for empty words (even the LTSrules work fine for the comma) were improved.

**Comment by timobaumann** [comment]
I guess this bug originally revolved about needed improvements in opennlp-maxent (or the models they provide?) 
Should I open a new issue for more graceful LTS handling (i.e., allow LTS to output nothing) in Mary?
