### ISSUE TITLE
MaryTTS Maven artifacts not are installed in my local Maven repository.  

### ISSUE THREAD

**Issue by jetremote** [marytts/marytts#302]
I use this tutorial and everything works fine except it does not install MaryTTS Maven artifacts in my local Maven repository.  

https://github.com/marytts/marytts/wiki/Eclipse

How I can fix this?

Regards

**Comment by psibre** [comment]
Try running the `pom.xml` as a "Maven install":
![m2e_install](https://cloud.githubusercontent.com/assets/1278639/7047442/d5736ecc-de0c-11e4-940e-74d933764a3d.jpg)
