### ISSUE TITLE
Quality control MaryTTS

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#304]
Hi, I enable "marytts.tools.voiceimport.QualityControl labels_features" component in Voice Import Tools.

I am getting such information in "QualityControl_Problems.txt" text file : 

1084	v	1.0	1.045	Fricative High-Frequency Energy is very low
1084	s	1.675	1.76	Fricative High-Frequency Energy is very low
1084	h	3.285	3.3	Fricative High-Frequency Energy is very low
1084	h	3.92	3.935	Fricative High-Frequency Energy is very low
1084	v	4.21	4.3	Fricative High-Frequency Energy is very low
1085	s	0.455	0.57	Fricative High-Frequency Energy is very low
1085	f	1.01	1.17	Fricative High-Frequency Energy is very low
1085	z	1.745	1.82	Fricative High-Frequency Energy is very low
1085	Z	2.04	2.17	Fricative High-Frequency Energy is very low
1085	S	3.15	3.3	Fricative High-Frequency Energy is very low
1085	h	3.3	3.315	Fricative High-Frequency Energy is very low
1086	S	0.425	0.49	Fricative High-Frequency Energy is very low
1086	G	0.755	0.845	Fricative High-Frequency Energy is very low
1086	Z	1.08	1.33	Fricative High-Frequency Energy is very low
1086	A	1.69	1.775	Un-Voiced Vowel
1087	z	0.515	0.59	Fricative High-Frequency Energy is very low
1087	h	1.28	1.57	Fricative High-Frequency Energy is very low
1087	s	2.585	2.63	Fricative High-Frequency Energy is very low
1087	s	2.63	2.655	Fricative High-Frequency Energy is very low
1087	s	2.985	3.105	Fricative High-Frequency Energy is very low
1087	S	3.32	3.435	Fricative High-Frequency Energy is very low
1088	x	1.5	1.565	Fricative High-Frequency Energy is very low
1088	v	1.69	1.725	Fricative High-Frequency Energy is very low
1088	x	2.56	2.615	Fricative High-Frequency Energy is very low
1088	f	2.85	2.885	Fricative High-Frequency Energy is very low
1088	Z	3.4	3.55	Fricative High-Frequency Energy is very low
1088	z	3.875	3.925	Fricative High-Frequency Energy is very low
1088	v	4.36	4.39	Fricative High-Frequency Energy is very low
1089	h	1.51	1.84	Fricative High-Frequency Energy is very low
1089	s	2.17	2.27	Fricative High-Frequency Energy is very low
1089	G	2.945	2.97	Fricative High-Frequency Energy is very low
109	G	0.265	0.315	Fricative High-Frequency Energy is very low
109	f	0.555	0.605	Fricative High-Frequency Energy is very low
109	S	1.74	1.845	Fricative High-Frequency Energy is very low
109	h	3.94	3.955	Fricative High-Frequency Energy is very low
109	G	5.515	5.645	Fricative High-Frequency Energy is very low
109	s	5.98	6.1	Fricative High-Frequency Energy is very low
109	f	6.13	6.175	Fricative High-Frequency Energy is very low
1090	h	0.665	0.74	Fricative High-Frequency Energy is very low
1090	s	1.395	1.5	Fricative High-Frequency Energy is very low
1090	Z	1.665	1.915	Fricative High-Frequency Energy is very low
1090	s	2.41	2.5	Fricative High-Frequency Energy is very low
1091	f	0.17	0.23	Fricative High-Frequency Energy is very low
1091	Z	0.425	0.53	Fricative High-Frequency Energy is very low
1091	s	1.27	1.365	Fricative High-Frequency Energy is very low
1091	x	2.15	2.195	Fricative High-Frequency Energy is very low
1091	S	2.195	2.27	Fricative High-Frequency Energy is very low
1091	f	2.715	2.82	Fricative High-Frequency Energy is very low

How can I fix this and what doesn't mean of these messages ? 
Thanks

**Comment by psibre** [comment]
Your guess is as good as mine. That code was written in 2007-2008, and hasn't been used since as far as I'm aware.

**Comment by NeptunSun** [comment]
ok. I have 2000+ records to create HMM based voice.  But in final I have result but not very good. In short sentence which have 5-10 words I am getting normal result, but when test with long sentences I am getting not good result. It may bee when i record sentences i have taken not long sentences?  Especially  when sentence start I hear loud voice but after low voice as i have mark in question  :https://github.com/marytts/marytts/issues/300

@psibre  thanks for your answers
