### ISSUE TITLE
MaryTTS text Corpus

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#305]
Hi, 
        I have already created first version of TTS my language with using 2200 sentences and HMM based voices (16000Hz, 16 bit, mono). Text corpus are chosen from wiki. But with sentences (contain 5-10 words) I am getting good result but speaker intonation lose for long sentences (+15 words). Maybe in text corpus there is not a lot long sentences than normal or small ???

**Comment by seblemaguer** [comment]
Hello,

yes it could be the problem. Can you check the number of words before having a punctuation mark ?

**Comment by NeptunSun** [comment]
I think, It was problem of normalize. I solve the problem with changing  freqWarp parameter as this :  HMMVoiceConfigure.freqWarp=0.2  or HMMVoiceConfigure.freqWarp=0.3 not 0.42 for female voice.   At same time I am making TTS text corpus with long sentences. this time corpus is big and there are many long sentences + with  freqWarp parameter as 0.2. When I will result i will publish

**Comment by seblemaguer** [comment]
Ok perfect
