### ISSUE TITLE
Migrate build to gradle

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#310]
For a number of reasons, we should replace [maven](http://maven.apache.org/) with [gradle](http://gradle.org/) as the build system for MaryTTS. These reasons include,
- **stability:** maven build behavior varies significantly from version to version
- **portability:** gradle's cross-platform support is better
- **flexibility:** numerous customizations, including resource generation and custom 3rd-party dependencies, are straightforward with gradle
- **performance:** caching and incremental build support are better in gradle

etc.

**Comment by psibre** [comment]
This depends on
* [ ] #324
* [ ] #325

**Comment by psibre** [comment]
[Two](274#issuecomment-71478213) [more](337#issuecomment-114602114) nails in maven's coffin.

**Comment by seblemaguer** [comment]
why the javadoc is related with gradle part ?

**Comment by psibre** [comment]
@seblemaguer because the workaround is a hack in the POM, which gradle doesn't use. But I haven't verified whether the javadoc lint strictness also affects the gradle build...

**Comment by seblemaguer** [comment]
We only have to merge the gradle part to the main branch. Do we do that for the 5.2 ?

**Comment by psibre** [comment]
@seblemaguer no, we merge `gradle` into `6.x`, then shift `master` over after tagging `v5.2`.
