### ISSUE TITLE
Downloading Existing Voices

### ISSUE THREAD

**Issue by quakig** [marytts/marytts#311]
I am trying to download existing voices. The file `download/marytts-components.xml` lists the following locations for downloading existing voices:

  `<location folder="true" href="http://mary.dfki.de/download/5.1/"/> `

But the link http://mary.dfki.de/download/5.1/ gives a `403 Forbidden error`.
The same cannot be installed even via  `mary-tts component installer `. The following error message is displayed:
```java
Starting installation
Now installing cmu-slt...
Trying location http://mary.dfki.de/download/5.1/voice-cmu-slt-5.1.zip...
...connected
...downloading
java.io.FileNotFoundException: /home/gublu/Desktop/Text2SpeechStuff/marytts/marytts/target/marytts-5.2-SNAPSHOT/download/voice-cmu-slt-5.1.zip (Permission denied)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
	at marytts.tools.install.ComponentDescription$Downloader.tryToDownloadFromLocation(ComponentDescription.java:737)
	at marytts.tools.install.ComponentDescription$Downloader.run(ComponentDescription.java:722)
	at marytts.tools.install.ComponentDescription.download(ComponentDescription.java:361)
```
How do I access these existing voices ?

**Comment by quakig** [comment]
Can I expect some answer on this ?

**Comment by psibre** [comment]
http://mary.dfki.de/download/5.1/voice-cmu-slt-5.1.zip works fine for me.
Incidentally, you can also use the [marytts-installer](https://github.com/marytts/marytts/releases/download/v5.1.2/marytts-installer-5.1.2.zip) and run `./marytts install:cmu-slt` as an alternative to the legacy voice installer GUI.
