### ISSUE TITLE
 HMMVoiceMakeVoice [making global variance]

### ISSUE THREAD

**Issue by A-Abdelkader** [marytts/marytts#312]
Hello,
When I run the HMMVoiceMakeVoice component of the HMM Voice trainer group I am always getting such error : 
Making data, labels, and scp from AcceptedError_RGB_010601_RGB_010601_0180_0.lab for GV...done
Making data, labels, and scp from AcceptedError_RGB_010601_RGB_010601_0181_0.lab for GV...done
Making data, labels, and scp from AcceptedError_RGB_010601_RGB_010601_0182_0.lab for GV...done
Making data, labels, and scp from AcceptedError_RGB_010601_RGB_010601_0183_0.lab for GV...Cannot open No such file or directory at /Path-to/Model_Name/hts/scripts/Training.pl line 1214, <SCP> line 43
__________________________
But when I run HMMVoiceMakeVoice component on 4 hours of wav files it works very well, the above error occurred when I increased number of wav files to become 6 hours. I'm using marytts-5.2

Thanks in advance

**Comment by A-Abdelkader** [comment]
I need any help please.

**Comment by fuzeller** [comment]
Hello A-Abdelkader, Have a look in the log file in your "/(voice)/hts" directory and review any errors, such as "WARNING [-9999]  HSMMAlign: No tokens survived to final node of network at beam 1500". This can point you to the trouble audio/text files. Review any audio and the associated txt.done.data for files that don't build a .lab file in your "/(voice)/hts/gv/qst001/ver1/lab" directory. This is an indication the HSMMAlign process can't align the text input phones with the audio. My most common observation here is that the audio and text don't match in some way; often just a few missing words in the audio. If that's the case, correct the error or remove that sample from the collection.

That's where I'd start - I'm just a linguist, though!

Good luck!

Fuz

**Comment by seblemaguer** [comment]
Hello,

as suggested, fuzeller, it's an HTS problem. I suggest to just discard the problematic files.

Kind regards,
Sébastien

**Comment by A-Abdelkader** [comment]
Thank you @fuzeller and @seblemaguer  I'll try this out.

**Comment by seblemaguer** [comment]
As no answer came, I suppose it worked :D Therefore, I close this issue

**Comment by Nandutu** [comment]
@seblemaguer @fuzeller @A-Abdelkader 
I equally have the same above issue, i have identified the name of the text and audio file that donot match. 
I removed the file  from the training data ie my text and wav files in the voice building directory but still experienced the same issue.

My only Question is what files do i have to delete that correspond to the un identified text and audio file above??
