### ISSUE TITLE
Debugging marytts on eclipse with a different voice

### ISSUE THREAD

**Issue by Peppemao** [marytts/marytts#315]
Hi,
I have imported marytts maven project on eclipse and I have set build configuration to run marytts server. I also installed istc-lucia-hsmm voice and I would like to debug the software using this voice, but when I go to the  web interface it is avaible just default voice.
What am I doing wrong? How can i fix it?

**Comment by psibre** [comment]
You add the `voice-istc-lucia-hsmm-5.1.2.jar` file and the `marytts-lang-it` project to the classpath.
I've added a note to the [Eclipse](../wiki/Eclipse) wiki page.
