### ISSUE TITLE
OpenNLPPosTagger will override a token which already has a pos attribute set

### ISSUE THREAD

**Issue by Munzey** [marytts/marytts#316]
this is actually the desired behaviour with the english languages current token to words implementation, but with my new implementation it is problematic

**Comment by Rootex** [comment]
Hello, 
Please can you elaborate more on what is problematic? because i need to have something to go with. On assumption basis, is this also a desired behavior for the rest of the languages or just english?
Thanks.

**Comment by Munzey** [comment]
long time since I looked at it, but this is something that may have been transitively fixed when we stripped out all the FreeTTS stuff. See [this commit](https://github.com/marytts/marytts/commit/385933bb899fdb984375904ff593c6d88cb96d12). Why I specified English here was because English was (I think) the only language still depending on FreeTTS packages in its list of processing modules. It was problematic because the old FreeTTS way of preprocessing would fill in dummy pos tags which we wanted overriden in the OpenNLPPosTagger(they may have been strings which the tagger could interpret, not sure). If you take a look at the new Preprocess class for English, it adds in useful POS data. Thus in that commit youll find somewhere a small block added to OpenNLPPosTagger.java which stops it overriding tokens which have pos data.

I think you can go ahead and mark this closed :)

**Comment by Rootex** [comment]
Ohh yea :D i came across the block you are talking about just now, well cheers!
