### ISSUE TITLE
Mary TTS with HTML/JavaScript and PHP

### ISSUE THREAD

**Issue by blsn** [marytts/marytts#317]
I installed Mary TTS (version 5.1.2) on my Windows (and Linux computers). I started the Mary TTS server and the Mary TTS client, and I did some trials with text to audio conversion in the GUI window (its great).
I would like to use Mary TTS on my website to read text aloud, where a user can add a text into the input field and generate the output like in the GUI window, without using the java client.
For example: button onclick="play('audio')"

Just to get started.. I can't realize how to do that in HTML/JavaScript and PHP?

**Comment by seblemaguer** [comment]
Hi,

you can realize it using HTML/Javascript. If you run the server on your machine you can access to API documentation through http://localhost:59125/documentation.html. You will also have an example of html/javascript implementation GUI at http://localhost:59125. The code of this gui is embedded, for now, into the java code. It is something we plan to change but, therefore, for the moment I suggest to use the "view source code" of your browser.
