### ISSUE TITLE
Can I use Marytts engine on android application?

### ISSUE THREAD

**Issue by wktest99** [marytts/marytts#318]
is it possible to use marytts engine on android application, if it is can you guys point some link to me how I will be able to do this.

First I want to add my language on marytts and then I want to develop a android application using marytts engine so I can convert text to speech of my languages text in an android application.

**Comment by psibre** [comment]
If you declare a dependency on the voice you want to use, it should work (in theory). It has been done before, but I believe the developers had to make some modifications to the main MaryTTS code.

**Comment by psibre** [comment]
Assuming resolved due to lack of further feedback.

**Comment by AstonBraham** [comment]
Hi everyone !

Please @wktest99 have you been able to achieve this ? I also need to implement MaryTTS in my app.

**Comment by wktest99** [comment]
No i didn't tried it.

**Comment by Munzey** [comment]
@AstonBraham please refer to #450 for tips on how one would go about implementing an android friendly version of marytts

**Comment by farizaghayev** [comment]
He have already start to integrate MaryTTS code to android and have already first version.  we tested this with android lollipop 5.1 version without any problem.  But the audio is lagging with the version marshmallow. Can test this from here : https://github.com/AndroidMaryTTS

**Comment by Israel7777** [comment]
Hello, I was trying to try out MaryTTS Android in Android Studio, anybody tried that?

**Comment by Swathi2610** [comment]
Hi, I want to give voice to my android app. Will I be able to do this with MaryTTS. I don't want to create anything complicated just a few conversations. How can i do that. How can I implement Android MaryTTS as a library in android studio.

**Comment by psibre** [comment]
@Swathi2610 Please open a new issue if you have a specific question. Until then, please see the previous discussion in this issue.

**Comment by toblinkz** [comment]
First I want to add my language on marytts and then I want to develop a android application using marytts engine so I can convert text to speech of my languages text in an android application

**Comment by toblinkz** [comment]
First I want to add my language on marytts and then I want to develop a android application using marytts engine so I can convert text to speech of my languages text in an android application
