### ISSUE TITLE
MaryClientUser.java example file

### ISSUE THREAD

**Issue by blsn** [marytts/marytts#319]
I'm trying to run the MaryClientUser.java example file:
(https://github.com/marytts/marytts/blob/master/marytts-assembly/assembly-runtime/src/runtime/doc/examples/client/MaryClientUser.java).

I added to classpath all jar files under ‘lib’ folder (jars under lib – see picture attached).

![lib](https://cloud.githubusercontent.com/assets/2880423/7800645/8097b74c-02e6-11e5-9053-851ba948793c.jpg)

Compiled successfully this as follows:
```
C:\Users\Mike\Documents\DreamwaveDocs\edchant>javac -classpath .;C:\Users\Mike\Downloads\marytts-5.1.2\lib\* MaryClientUser.java

C:\Users\Mike\Documents\DreamwaveDocs\edchant>
```
Then (after .class created), I run as follows:
```
C:\Users\Mike\Documents\DreamwaveDocs\edchant>java -classpath . MaryClientUser
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: marytts/util/http/Address
        at MaryClientUser.main(MaryClientUser.java:71)
        Caused by: java.lang.ClassNotFoundException: marytts.util.http.Address
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
```
Please see the above error message received.
How to fix it?

Thank you for the support,
Mike

**Comment by psibre** [comment]
```
C:\Users\Mike\Documents\DreamwaveDocs\edchant>java -classpath . MaryClientUser
```
If you're running with the classpath set to your `edchant` directory, where do you expect to find the `marytts-common` dependency (which contains the missing class)?
I *strongly* recommend you use a modern build tool that takes care of things like this for you.

**Comment by blsn** [comment]
Thank you for your reply.

Please advise if the first stage that I did as follows, was okay?:

C:\Users\Mike\Documents\DreamwaveDocs\edchant>javac -classpath .;C:\Users\Mike\Downloads\marytts-5.1.2\lib* MaryClientUser.java

I’m asking this question because compiled was successfully (no errors) and .class file was created.
Also, please note that ‘marytts-common’ wasn't added above to classpath (see jar files under ‘lib’).

If you think that the above is okay, please advise how correctly to run the java line code.

Thanks for your help,
Mike

**Comment by blsn** [comment]
I'm running a local Mary 5.1.2 server, I tested several voices and can access to API documentation through http://localhost:59125/documentation.html. This works fine.

My problem is still no success in running the ‘MaryClientUser.java’ example file. 

What I did:
•	Download and unpack MaryTTS Installer
•	Windows command line > marytts install:cmu-slt
•	Use Eclipse to add the following jar files to my classpath:
-	marytts-runtime
-	marytts-common
-	marytts-signalproc

Note: to compile the exported jar’s, I created a folder called ‘lib’ in my project folder and add to build path.

Please see the screenshot containing the error messages.

![screen1](https://cloud.githubusercontent.com/assets/2880423/7817760/2c6468c2-03a5-11e5-93a1-a0869d51b657.jpg)


Results:
Error exists in required project: “The import marytts.client cannot be resolved”
I couldn’t find the related above anywhere in the directory ‘marytts-installer-5.1.2’.

I tried from the downloadable package ready for use (the releases page), the following file instead:
marytts-client-5.1.2-jar-with-dependencies.jar
but I receive too many error messages (see the screenshot). 

![screen2](https://cloud.githubusercontent.com/assets/2880423/7817768/34229b6a-03a5-11e5-8ef7-1f34c13467a9.jpg)


How to solve it and to make ‘MaryClientUser.java’ example file to work?

Thank you,
Mike

**Comment by psibre** [comment]
If you really want to use the `marytts-client` dependency, you can resolve it from [jCenter](https://bintray.com/bintray/jcenter?filterByPkgName=marytts).

**Comment by blsn** [comment]
Thank you very much for advising me to resolve it from jCenter.

I really cannot understand how can it help me, or where can I get this file from, why can’t I get marytts-client from the installer directory (GitHub)? Please can you give more details about your advise.  

I would appreciate your help on how to make the ‘MaryClientUser.java’ example file to work, as explained before?

Thanks for your help,
Mike

**Comment by seblemaguer** [comment]
Hello,

the error you've got when you try to run marytts-client only indicates that the marytts server is not running therefore the timeout expires and it could not connect. Your dependencies are correct.

To have easily a running marytts instance, you should use this installer : https://github.com/marytts/marytts-installer

**Comment by psibre** [comment]
For what it's worth, I've put up [a separate repository](https://github.com/marytts/marytts-txt2wav) containing an example project that uses MaryTTS as a dependency. This is more complete and self-explanatory than the various [wiki entries](https://github.com/marytts/marytts/wiki/MaryInterface).
@blsn Please refer to the linked example code.

**Comment by blsn** [comment]
Hi,

@seblemaguer,
Thank you for indicating that dependencies are corrects.

marytts server is running, and I use your web-link for marytts installer (screenshot attached).

![screenshot](https://cloud.githubusercontent.com/assets/2880423/7867106/fb61a214-0541-11e5-9b4f-43e40851f7c2.jpg)


Note:
The following jar wasn’t taken from marytts installer's folder but was added as external archive from the downloadable package ready folder (since I couldn’t find it anywhere in the marytts installer's folder): 
marytts-client-5.1.2-jar-with-dependencies.jar

Could you advise why I’m getting this error (first & 2nd line):
Mary TTS client 5.1.2 (impl. unknown)

Also, why I’m getting the error of server cannot connect?

Thank you for your support,

**Comment by psibre** [comment]
Your problem is that you're trying to connect to `cling.dfki.uni-sb.de:59125`. Why would you want to do that? Where did you get that address?
Btw, you can also copy and paste the error from your Eclipse console into these text boxes, preferably enclosed by triple backticks, which renders like this:
```
MARY client cannot connect to MARY server at
cling.dfki.uni-sb.de:59125
```
That way, we can read your error without squinting at a screenshot (and retyping when we need to refer to it).

**Comment by blsn** [comment]
Thank you for your reply.

I didn’t notice that the following line in ‘MaryClientUser.java’ is a link to the server address:
String serverHost = System.getProperty("server.host", "cling.dfki.uni-sb.de");

As I’m not good in Java.., please can you advise how to change the address above for Mary TTS server installed on my Windows, as follows (batch file: ‘marytts-server’):
C:\Users\Mike\Downloads\marytts-5.1.2\bin

..and for Linux, as follows:
https://mydomain.com/marytts-5.1.2/bin

Thank you,
Mike

**Comment by psibre** [comment]
Holy cow! That default value for `server.host` in that example is from before the subversion era (i.e., pre-2006)! It certainly explains a lot. I `git blame` @marc1s ... =)
Thanks for pointing out the source of the confusion, I'll open a new issue to strip out that outdated example code once and for all!

To connect to a locally running MaryTTS server (with the default port of 59125), use either http://localhost:59125 or http://127.0.0.1:59125 and if you have MaryTTS running on your web-facing server, it would be http://example.com:59125 or something, but getting that to work might require some additional hackery at the web server level. See [this wiki page](../wiki/Local-MaryTTS-Server-Installation) for more details.

**Comment by blsn** [comment]
Hi,

I tried to connect to a locally running MaryTTS server as you mentioned, as follows:
String serverHost = System.getProperty("server.host", " http://127.0.0.1:59125:59125");

But I get the following error:
Exception in thread "main" java.io.IOException: Cannot connect either to a HTTP nor to a Socket MARY server at http://127.0.0.1:59125:59125

Please advise how to correct the above code that the program can start the MaryTTS server which installed on my Windows, as follows (batch file ‘marytts-server’):

C:\Users\Mike\Downloads\marytts-5.1.2\bin

Thank you,
Mike

**Comment by psibre** [comment]
You have a space in your string (i.e., before the **h** in **http**).

**Comment by blsn** [comment]
Thanks, but after removing the space, or using instead http://localhost,
I'm still getting the same error message (screenshot attached).


![screenshot](https://cloud.githubusercontent.com/assets/2880423/7892824/b6bbdfd2-0625-11e5-8efc-7f102ebcc36b.jpg)


Any idea?

Thank you,
Mike

**Comment by blsn** [comment]
Thanks for the help from a member at MaryTTS mailing list, I would like to give my current status as follows:

The solution:
•	Removed "http://" from the link.
•	Using the same version of Mary for server and client.

The result:
•	I could hear the voice now.
•	I still get an error line (twice):.
Mary TTS client 5.1.2 (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.1.2 (impl. unknown)

Please see the screenshot below:

![screenshot1](https://cloud.githubusercontent.com/assets/2880423/7895260/72d5d50e-0650-11e5-8517-a9bbd8a8d754.jpg)


Note:
I’m using the downloadable package ready folder ‘marytts-5.1.2.zip’.
I cannot use the installer because I can’t find the marytts-client jar file in there..!? : 
https://github.com/marytts/marytts/releases

Any help on the error line above would be appreciated,

Thank you,
Mike

**Comment by psibre** [comment]
> Mary TTS client 5.1.2 (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.1.2 (impl. unknown)

Just because those messages are printed to STDERR doesn't mean they're errors.
If all you wanted was to connect your custom java app to a separate MaryTTS server, then you're done and can close this issue.

The `marytts-client.jar` is not needed for the [marytts-installer](/marytts/marytts-installer), or, indeed, anywhere at all, which is why it's not retrieved. You *can* still download it from JCenter or OJO, but it hasn't been maintained for many years, so using it is really not recommended.
If you want to actually *embed* MaryTTS inside your java app, please refer to the example code in the [marytts-txt2wav](/marytts/marytts-txt2wav) repo (`maven` branch).
