### ISSUE TITLE
Incorrect stress in French lexicon source

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#323]
The [French lexicon source file](https://github.com/marytts/marytts/blob/bb2c683a4cd3ed2c4caab405801b48032e214364/marytts-languages/marytts-lang-fr/lib/modules/fr/lexicon/fr.txt) consistently marks stress on the initial syllable. In French, the stress should be on the final syllable instead.

**Comment by psibre** [comment]
@seblemaguer I've pushed some tests to [the `test-lts` branch in my fork](/psibre/marytts/tree/test-lts).

**Comment by seblemaguer** [comment]
Ok, I'll do with your branch ^^

psibre writes:

> @seblemaguer I've pushed some tests to the test-lts branch in my fork.
>
> —
> Reply to this email directly or view it on GitHub.*

-- 
Dr. Sébastien Le Maguer
Postdoctorate researcher

Saarland University
Campus C7.4 - room 2.03
D-66123 Saarbrücken
Germany

phone : +49-681-302-70030
Mail: slemaguer@coli.uni-saarland.de
website :  http://www.coli.uni-saarland.de/~slemaguer/

**Comment by psibre** [comment]
@seblemaguer mind you, the resource still needs to be retrained on the (corrected) source file before it makes a difference to those tests.

**Comment by psibre** [comment]
This is a dependency of #326.

**Comment by seblemaguer** [comment]
ok but what is order of processing, this one ?
 1. Correct *all* sources
 2. trained  the resources

or can it be done separately ?

**Comment by psibre** [comment]
> 1. Correct *all* sources

This.

If you commit that on the `test-lts` branch, the second step will be automatic as part of #326 .

Having said that, I believe in practically all cases, stress will be on the final syllable, so it's something you could do with a perl one-liner or similar.

**Comment by seblemaguer** [comment]
yes it's done (with an awk script) but I didn't push it due to my previous question ^^

**Comment by psibre** [comment]
@seblemaguer brilliant, thanks! If you rebase it onto my `test-lts` branch, I can fetch it from your fork.

**Comment by psibre** [comment]
@seblemaguer I see you fixed this in b20c4de1ec5b77b53b919541ed169687ccb38d72 and merged it into `master` in #424, so can we close this?

**Comment by seblemaguer** [comment]
yup :D
