### ISSUE TITLE
Run integration tests with Gradle

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#324]

**Comment by psibre** [comment]
This is a dependency of #310.

**Comment by psibre** [comment]
This issue is essentially solved, but it would be cleaner if we could split the source directories (`java`/`groovy` and `resources`) for the `test` and `integrationTest` sourceSets. Especially because the `integrationTest` reports include some unit tests (which *should* have been in `test`), and I think it would be a waste of time to try and debug that vs. just moving to the conventional sourceSet directory layout.

**Comment by seblemaguer** [comment]
Almost achieved. Just one small question, when were developed the integration test? I just realized that in the older version they were not executed and now that they are they are failing with weird reasons (project version not set, ....)

**Comment by seblemaguer** [comment]
I think it's good now
