### ISSUE TITLE
Purge outdated modules

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#327]
Some of the modules with unmaintained (and buggy) code that haven't been used in a long time should be decoupled from the build and shifted into purgatory.
These include
- marytts-assembly
- marytts-builder
- marytts-client (see also #98)
- marytts-redstart
- marytts-transcription
- user-examples (see also #320)

**Comment by psibre** [comment]
Also
* marytts-builder

**Comment by seblemaguer** [comment]
I basically finished to remove that in the current sstate of 6.x, should we close this issue ?

**Comment by psibre** [comment]
I think we should keep it open until it's merged into master...
