### ISSUE TITLE
Unit selection voice sCost

### ISSUE THREAD

**Issue by Georgakopoulos** [marytts/marytts#329]
I work with MaryTTS 5.2 Snapshot Version on an Ubuntu Computer:

I have created an own German voice, with the Voice Import tools and I have noticed that my sCost are at all times 0 when I synthesize a sentence. I recognized that from the first dummy unit to the first actual unit the joinCosts are 0 aswell, which makes perfect sense.

But as I read a Paper _"HMM-based sCost quality control for unit selection speech synthesis" (by Satish Pammi, Marcela Charfuelan)_,  I stumbled upon these sCost (statistical costs) and it suggests they improve both the HMM- & UnitselectionVoice and should be used at all times. 

 **My mary voice does not seem to use these sCosts. Does anybody know why??**

**Comment by NeptunSun** [comment]
When you uncomment  "marytts.tools.voiceimport.QualityControl labels_features" option from 'importMain.config' file you will obtain but this option was written in 2007-2008 and I think not used today

**Comment by Georgakopoulos** [comment]
Thank you for you answer. 
**Is anybody aware why the sCosts are left out/not used today?**

**Comment by psibre** [comment]
The last time sCost was used was for the Blizzard Challenge 2013. But that was with experimental code which was not merged into the `master` branch.

**Comment by gnatenkoav** [comment]
Could you create branch in repository for the Blizzard Challenge 2013? It would be interesting to try sCost feature.
