### ISSUE TITLE
small and big Input Text , rate

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#331]
Hello, I have created new synthetic voice with using [MaryTTS]. 

I am putting big input text (3-5 sentences and which contains 5-10 words) using 'Mary Web Cilent' and for result getting not normal. But RESULT well be NORMAL when i write 'Enter' between two sentences and also 'Escape' after 'comma' or maybe 'Escape' between two words also.  How can I solve this problem I don't know?

Second problem is how can I change rate of voice?  I know there is solution with (http://mary.opendfki.de/wiki/ProsodySpecificationSupport) but without this can i solve this problem?

**Comment by Munzey** [comment]
see issues #97 and #213

**Comment by NeptunSun** [comment]
@Munzey  Thanks for references and I have read all links but can't fixed my problems.  What do you think "Drop FreeTTS dependencies "  will solve my problems?  

My problem is when I put "escape" or "enter" between words and sentences  MaryTTS syntheses normal voice but when I put all sentences together syntheses voices are not normal speed.
