### ISSUE TITLE
Incorrect POS tags and missing transcriptions in Turkish lexicon source

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#332]
Further to #323 and #328, the [Turkish lexicon source file](https://github.com/marytts/marytts/blob/bc1b2bcbad1c7348e96de358f1c5edc9a86d3113/marytts-languages/marytts-lang-tr/lib/modules/tr/lexicon/tr.txt) tags nearly every entry with the `functional` POS.
Moreover, thousands of entries are missing their transcription.

This is another dependency of #326.

**Comment by geekdinazor** [comment]
Dear @psibre, 
I generated new wordlist for Turkish lexicon that solved this problem. I don't make pull request yet, but you can examine it from my [fork](https://github.com/geekdinazor/marytts/commit/3655550f6356521777d91cdbd2cb4c4d7bd1f0c9).
Have a nice day :smile:

**Comment by psibre** [comment]
@geekdinazor Thanks very much, that's brilliant!

From what I can tell, the (Zemberek)[https://code.google.com/p/zemberek/) code, and hence, this wordlist, seem to be covered by the [MPL 1.1](https://www.mozilla.org/MPL/1.1/), which from what I understand permits commercial use.

We're actually planning to reorganize the marytts language components a little, so that the raw lexicon resources can be a separate artifact with its own license. That would make it even more straightforward to clarify the licenses of the lexica, which are typically released under different licenses than software.

I'll run some tests as soon as I have the time, then we can merge your contribution.

**Comment by geekdinazor** [comment]
Is there any progress ?
