### ISSUE TITLE
Maven deploy to Tomcat based war file

### ISSUE THREAD

**Issue by blsn** [marytts/marytts#334]
I have a Dynamic Web project of a simple HTML form, which Converted to Maven with Eclipse.
This is a web application, where a user can add a text into the input field and generate the output to read the text aloud by pressing the submit button. 

The above runs on Tomcat server v8.0 and works fine on the web browser.
I use in my script the ‘RemoteMaryInterface’ with ‘MaryTTS 5.1.2’ server.

I would like to deploy my Maven project to Tomcat based war file but I’m getting the following error when Run As ‘Maven install’:

p.s. 
I’m getting: ‘BUILD SUCCESS’ for Run As ‘Maven clean’ & ‘Maven generate-source’.

[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MyMavenProject 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SimpleServletTest02_5 ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Mike\workspace\SimpleServletTest02_5\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ SimpleServletTest02_5 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to C:\Users\Mike\workspace\SimpleServletTest02_5\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[14,15] package marytts does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[15,22] package marytts.client does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[16,26] package marytts.exceptions does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[17,31] package marytts.util.data.audio does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[34,17] cannot find symbol
  symbol:   class MaryInterface
  location: class org.ed.chant.ServletTest02_05
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[34,45] cannot find symbol
  symbol:   class RemoteMaryInterface
  location: class org.ed.chant.ServletTest02_05
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[44,25] cannot find symbol
  symbol:   class AudioPlayer
  location: class org.ed.chant.ServletTest02_05
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[44,50] cannot find symbol
  symbol:   class AudioPlayer
  location: class org.ed.chant.ServletTest02_05
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[47,26] cannot find symbol
  symbol:   class SynthesisException
  location: class org.ed.chant.ServletTest02_05
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.689 s
[INFO] Finished at: 2015-06-18T20:51:42-05:00
[INFO] Final Memory: 14M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project SimpleServletTest02_5: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[14,15] package marytts does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[15,22] package marytts.client does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[16,26] package marytts.exceptions does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[17,31] package marytts.util.data.audio does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[34,17] cannot find symbol
[ERROR] symbol:   class MaryInterface
[ERROR] location: class org.ed.chant.ServletTest02_05
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[34,45] cannot find symbol
[ERROR] symbol:   class RemoteMaryInterface
[ERROR] location: class org.ed.chant.ServletTest02_05
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[44,25] cannot find symbol
[ERROR] symbol:   class AudioPlayer
[ERROR] location: class org.ed.chant.ServletTest02_05
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[44,50] cannot find symbol
[ERROR] symbol:   class AudioPlayer
[ERROR] location: class org.ed.chant.ServletTest02_05
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_5/src/org/ed/chant/ServletTest02_05.java:[47,26] cannot find symbol
[ERROR] symbol:   class SynthesisException
[ERROR] location: class org.ed.chant.ServletTest02_05
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Is there anything needed to add as dependencies to pom.xml?

![untitled](https://cloud.githubusercontent.com/assets/2880423/8245628/e5896724-15fe-11e5-8cee-2fe31002e0f1.jpg)

Any help would be appreciated,

**Comment by psibre** [comment]
I don't understand how you expect to use MaryTTS if you don't declare it as a dependeny.
Please refer to the `pom.xml` in [this example project](/marytts/marytts-txt2wav/blob/maven/pom.xml) on how that might be accomplished.

**Comment by blsn** [comment]
Thank you for confirming that I need to add dependency to pom.xml.
I tried the following two, but none of them works:

![untitled1](https://cloud.githubusercontent.com/assets/2880423/8258798/f21bce8c-1685-11e5-9ede-d5c05752231d.jpg)

I referred to the example ‘marytts-txt2wav’, but still couldn’t figure it up. 

Please can you give some more help on this issue.
Thank you,

**Comment by psibre** [comment]
It's not straightforward to figure out what's going on if you only paste screenshots from Eclipse.
Could you please paste your actual `pom.xml` (between [triple backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks))?

**Comment by blsn** [comment]
The project works fine when ‘Run As’: ‘Run on server’ (on web browser).

I attached a screenshot of the project structure and also the actual pom.xml file as requested.

![untitled](https://cloud.githubusercontent.com/assets/2880423/8267813/03adbb22-173c-11e5-881f-5c8d7462f7b7.jpg)


I cannot declare successfully dependency for MaryTTS in pom.xml file.

pom.xml file:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>SimpleServletTest02_01</groupId>
  <artifactId>SimpleServletTest02_01</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>war</packaging>
  <name>MavenPomName02_01</name>
  <description>Converted to maven.</description>
  
  <dependencies>
    <dependency>
  	  <groupId>javax.servlet</groupId>
	  <artifactId>javax.servlet-api</artifactId>
	  <version>3.1.0</version>
  	</dependency>
  </dependencies>
  
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.4</version>
        <configuration>
          <warSourceDirectory>WebContent</warSourceDirectory>
          <failOnMissingWebXml>false</failOnMissingWebXml>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

‘Maven install’ gives the following error message:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MavenPomName02_01 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SimpleServletTest02_01 ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\Mike\workspace\SimpleServletTest02_01\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ SimpleServletTest02_01 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to C:\Users\Mike\workspace\SimpleServletTest02_01\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[14,15] package marytts does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[15,22] package marytts.client does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[16,26] package marytts.exceptions does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[17,31] package marytts.util.data.audio does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[34,17] cannot find symbol
  symbol:   class MaryInterface
  location: class org.ed.chant.Servlet02_01
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[34,45] cannot find symbol
  symbol:   class RemoteMaryInterface
  location: class org.ed.chant.Servlet02_01
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[44,25] cannot find symbol
  symbol:   class AudioPlayer
  location: class org.ed.chant.Servlet02_01
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[44,50] cannot find symbol
  symbol:   class AudioPlayer
  location: class org.ed.chant.Servlet02_01
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[47,26] cannot find symbol
  symbol:   class SynthesisException
  location: class org.ed.chant.Servlet02_01
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.899 s
[INFO] Finished at: 2015-06-20T11:05:34-05:00
[INFO] Final Memory: 14M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project SimpleServletTest02_01: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[14,15] package marytts does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[15,22] package marytts.client does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[16,26] package marytts.exceptions does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[17,31] package marytts.util.data.audio does not exist
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[34,17] cannot find symbol
[ERROR] symbol:   class MaryInterface
[ERROR] location: class org.ed.chant.Servlet02_01
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[34,45] cannot find symbol
[ERROR] symbol:   class RemoteMaryInterface
[ERROR] location: class org.ed.chant.Servlet02_01
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[44,25] cannot find symbol
[ERROR] symbol:   class AudioPlayer
[ERROR] location: class org.ed.chant.Servlet02_01
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[44,50] cannot find symbol
[ERROR] symbol:   class AudioPlayer
[ERROR] location: class org.ed.chant.Servlet02_01
[ERROR] /C:/Users/Mike/workspace/SimpleServletTest02_01/src/org/ed/chant/Servlet02_01.java:[47,26] cannot find symbol
[ERROR] symbol:   class SynthesisException
[ERROR] location: class org.ed.chant.Servlet02_01
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
Thank you for your support,
Mike

**Comment by psibre** [comment]
Thanks for posting your `pom.xml` and maven output!
Your POM makes no reference at all to MaryTTS. You need to declare a dependency on the MaryTTS artifacts relevant to your code.
In the [example project](/marytts/marytts-txt2wav), you will find [this in the `pom.xml`](/marytts/marytts-txt2wav/blob/97129b1eda8c797a550b6935fb0709375218c1c7/pom.xml#L38-L42):
```xml
<dependency>
	<groupId>de.dfki.mary</groupId>
	<artifactId>voice-cmu-slt-hsmm</artifactId>
	<version>5.1.1</version>
</dependency>
```
You need to do something similar. Please refer to the [Maven documentation](http://maven.apache.org/guides/getting-started/index.html#How_do_I_use_external_dependencies) for details.
