### ISSUE TITLE
Error occured when MCEPMaker started to run in Voice Import Tool

### ISSUE THREAD

**Issue by Shandigutt** [marytts/marytts#335]
I'm trying to add Sinhala language support to MaryTTS. I got the following error once the MCEPMaker started running (after PraatPitchMarker finishied running) in the MaryTTS Voice Import Tool.

```
---- Calculating the Mel-Cepstrum coefficents...
Creating the directory [/home/tharaka/LTRL/MaryTTS/voice_recording/mcep/].
s20001
WALLOC: failed to malloc -2 bytes
java.lang.Exception: The component MCEPMaker produced the following exception: 
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
Caused by: java.lang.RuntimeException: Mel-Cepstrum  computation failed on file [s20001]!
Command line was: [/usr//bin/sig2fv -window_type hamming -factor 2.5 -otype est_binary -coefs melcep -melcep_order 12 -fbank_order 24 -shift 0.01 -preemph 0.97 -pm /home/tharaka/LTRL/MaryTTS/voice_recording/pm/s20001.pm -o /home/tharaka/LTRL/MaryTTS/voice_recording/mcep/s20001.mcep /home/tharaka/LTRL/MaryTTS/voice_recording/wav/s20001.wav].
    at marytts.util.io.General.launchProc(General.java:543)
    at marytts.tools.voiceimport.ESTCaller.make_mcep(ESTCaller.java:239)
    at marytts.tools.voiceimport.MCEPMaker.compute(MCEPMaker.java:249)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
```

To view the full console log from the start of the VoiceImportTool to the point where this error occurred go to following link,
https://drive.google.com/file/d/0B7Ub8Dlvw7zZX2pSeHM5VmdoOTA/view?usp=sharing

To view all the language data I have used please go to the following link,
https://drive.google.com/file/d/0Byfhm5oQd7gMNzFoeTVSeHo1bjg/view?usp=sharing
(If you download everything inside this file it will be 866MB) 

Note: The "voice_recording" directory mentioned in the error is named as "recorded_voice" in the uploaded data.

**Comment by psibre** [comment]
> `Command line was: [/usr//bin/sig2fv -window_type hamming -factor 2.5 -otype est_binary -coefs melcep -melcep_order 12 -fbank_order 24 -shift 0.01 -preemph 0.97 -pm /home/tharaka/LTRL/MaryTTS/voice_recording/pm/s20001.pm -o /home/tharaka/LTRL/MaryTTS/voice_recording/mcep/s20001.mcep /home/tharaka/LTRL/MaryTTS/voice_recording/wav/s20001.wav].`

What happens when you run that command in a terminal?

**Comment by Shandigutt** [comment]
It gives the same error. 

```WALLOC: failed to malloc -2 bytes```

I'm running on a 64bit system

**Comment by psibre** [comment]
What's the output of `soxi /home/tharaka/LTRL/MaryTTS/voice_recording/wav/s20001.wav`?

**Comment by Shandigutt** [comment]
It says,

```
tharaka@Tharaka-Laptop:~/LTRL/MaryTTS/voice_recording/wav$ soxi /home/tharaka/LTRL/MaryTTS/voice_recording/wav/s20001.wav

Input File     : '/home/tharaka/LTRL/MaryTTS/voice_recording/wav/s20001.wav'
Channels       : 1
Sample Rate    : 48000
Precision      : 32-bit
Duration       : 00:51:02.27 = 146989056 samples ~ 229670 CDDA sectors
File Size      : 588M
Bit Rate       : 1.54M
Sample Encoding: 32-bit Signed Integer PCM

tharaka@Tharaka-Laptop:~/LTRL/MaryTTS/voice_recording/wav$ 
```

I just got to know that the Sample Rate is not 16000. Will this be the mistake?

**Comment by Shandigutt** [comment]
I tried to convert the wav files from MaryTTS converter. It outputs the following error,

```
tharaka@Tharaka-Laptop:~/LTRL/MaryTTS/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ sudo ./audio_converter_GUI.sh 
[sudo] password for tharaka: 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Number of wave files to convert: 999
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input file
	at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1189)
	at marytts.util.data.audio.AudioConverterGUI$Converter.getMaxAbsAmplitude(AudioConverterGUI.java:922)
	at marytts.util.data.audio.AudioConverterGUI$Converter.run(AudioConverterGUI.java:671)
Audio conversion failed.

```

The snapshot of the Audio Converter GUI is,

![Image of Audio_converter](https://lh6.googleusercontent.com/79PECYPUKk4lHOgJA97pNFw0cH4NIqVCMAkAMMD3FN0Xcta2cr9EHJgdWw5K2mhoQyljZc6br7K5liQ=w1277-h537)

**Comment by psibre** [comment]
You're correct in realizing that you need to convert the wav files -- IIRC, the Edinburgh Speech Tools cannot handle 32-bit sample format.
However, the Audio Converter is somewhat buggy, and the code hasn't been maintained in years. With so many dedicated, open-source tools out there, the extra effort of maintaining the Audio Converter seems hard to justify, and it's slated for removal in the next major release.
Meanwhile, you should simply create 16-bit, 16 kHz versions of your recorded wav files for voicebuilding, using, e.g., [`sox`](http://sox.sourceforge.net/), or [Audacity](http://web.audacityteam.org/) if you prefer a GUI.
