### ISSUE TITLE
MaryTTS trims the last vowel in single word (Hindi lang)

### ISSUE THREAD

**Issue by badbob** [marytts/marytts#338]
Hello, everyone. 
I discover some kind of side effect (see the subject).

Examples: https://drive.google.com/file/d/0Bx5Pn1uR8NDJMlZHRlhLT2tmZ0E/view?usp=sharing (nadi with trimmed last 'i')

When it used 2 words with first 'nadi' it is much better: 
https://drive.google.com/file/d/0Bx5Pn1uR8NDJZldTUjZCLTlUMVU/view?usp=sharing

Even if 'nadi' is last word, the last i sounds much longer:
https://drive.google.com/file/d/0Bx5Pn1uR8NDJNHpKMFZwbU90S2M/view?usp=sharing

How can I force MaryTTS to play long "ii" at the end of single word?

**Comment by aitorme** [comment]
hi @badbob, are you still facing this issue or is it already solved?
