### ISSUE TITLE
Jphonemiser problem

### ISSUE THREAD

**Issue by gmiano** [marytts/marytts#358]
I'm using Italian voice to synthesize: "C'è qualcosa che non va!"

During phonemisation "C'è" is splitted good but with syllabification "C'" is translated in "k".
This is wrong but I really don't know if it is possible and how I could manage it.lts to correct this feature. Is this possible? There is a way to teach it the right way?

**Comment by seblemaguer** [comment]
Hello,

normally you can change the user dictionnary and add an entry.
