### ISSUE TITLE
 No known way of generating output (AUDIO) from input(RAWMARYXML), no processing path through modules.

### ISSUE THREAD

**Issue by lingvisa** [marytts/marytts#367]
Hello, I am new to marytts, and just imported the project into my eclipse. I started the server by running "/marytts-runtime/src/main/java/marytts/server/Mary.java" in Eclipse, and now I can access the Web client at http://localhost:59125/.

However, there is no any response. It desno't speak. Then I tried running /marytts-client/src/main/java/marytts/client/MaryClient.java, I received the following error. I didn't add or change any parameters in the code when start the server and the client. Just taking the default parameters configured in the code. What might cause the problem? Thank you.

Mary TTS client 5.2-SNAPSHOT (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.2-SNAPSHOT (impl. unknown)
java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.UnsupportedOperationException: No known way of generating output (AUDIO) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:506)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	......
         ......
	at java.lang.Thread.run(Thread.java:745)
</pre></body></html>
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:397)
	at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:439)
	at marytts.client.MaryClient.process(MaryClient.java:653)
	at marytts.client.MaryClient.main(MaryClient.java:949)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process

**Comment by psibre** [comment]
Did you follow the instructions at [in the wiki](../wiki/Eclipse)? What's the output of [http://localhost:59125/locales](http://localhost:59125/locales)?

**Comment by lingvisa** [comment]
Hi, psibre, 

The output of http://localhost:59125/locales on my CentOS 7 is blank (empty). Is that normal?

I didn't fully follow the instructions on the wiki. Instead, I git clone the project, and mvn install, which shows it's successful. Then in Eclipse, I right click "Mary" in the Server package and "run as Java application" to start the server, it started successfully. Then I went to the Client package and click "MaryClient"->"Run as Java application", to start the client. Then i got the error message.

Thank you.

**Comment by psibre** [comment]
What's the output of http://localhost:59125/locales?

**Comment by psibre** [comment]
> The output of http://localhost:59125/locales on my CentOS 7 is blank (empty). Is that normal?

No, and that's the problem. Like it says on the wiki page, you need to add at least one of the language component projects (e.g., `marytts-lang-en`), otherwise your can't use MaryTTS.
