### ISSUE TITLE
Different entries of the same word in the userdict

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#382]
Hi folks,

if I got more than one transcription of the same word in my userdict, is there a way of defining one entry as default? Or how will one of the entries be matched to the transcript & audio?

Let's say I got kind of a news corpus in German, which is about international sports or whatever. So there will be something like a NHL (pronounced English) and then those single letters pronounced German. I got transcriptions for those letters in English and German in my userdict. Is the system while building the voice able to distinguish between a German and English *H* ? Will it match the right dict entry?

Thanks

**Comment by seblemaguer** [comment]
Hello,

as far as I checked the german lexicon will be checked first and then the english one. However to activate the english lexicon you should define the following property in your voice.config 

  de.phonemiser.useenglish = true

Finally, if there are multiple entries on one lexicon is present only the first one is taken into account. Further

**Comment by entenbein** [comment]
Alright, thanks!
