### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by lagleki** [marytts/marytts#383]

**Comment by psibre** [comment]
There's now experimental support for [Luxembourgish](https://github.com/marytts/marytts/tree/master/marytts-languages/marytts-lang-lb)...

**Comment by chiliconsult** [comment]
I need Arabic language support  - best would be to have farsi and pashto also.
Any progress on that? 
It's for the app www.refuchat.com

**Comment by aitorme** [comment]
hi @chiliconsult, there have been people who have created voices in Arabic, but, to my knowledge, we haven't heard of anyone creating any voice neither in Farsi nor in Pashto, which would be more complicated to create and support, unfortunately

**Comment by chiliconsult** [comment]
hi @aitorme thanks. I found this one: https://github.com/bellegdi/marytts-lang-ar
but: can I simply import this ?

the workaround for farsi and pashto is currently getting volunteers to do manual voice recording

**Comment by aitorme** [comment]
@chiliconsult I don't know if you can import it, bear in mind that this is an outdated version with more than 500 commits behind master, so it may not work properly and you might have to fork that particular module
regarding the workaround, how long do you think it could take to get the recording? How many hours of speech?

**Comment by seblemaguer** [comment]
@chiliconsult I do not have any corpus for arabic so I can't test it. However, I manage to compile the file and make marytts add it. To achieve this process, you should simple do the following stages 

1. Replace the header by :
```xml
	<parent>
           <groupId>de.dfki.mary</groupId>
	  <artifactId>marytts</artifactId>
          <version>5.2-SNAPSHOT</version>
	</parent>
```

2. compile using ```mvn install```
3. add the jar achieved and present in target to the classpath to run mary.

For the remaining part, I suggest you to have a look to this : https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial

Of course don't forget to check the rules for arabic as I'm clearly not an arabic speaker :D

**Comment by aitorme** [comment]
Hi @chiliconsult, did you try this out? Did it work?

**Comment by linuxscout** [comment]
I work on arabic support for marytts,
I add files and follow steps mentionned in
https://github.com/marytts/marytts/wiki/New-Language-Support 
the work is forked from https://github.com/bellegdi/marytts-lang-ar with  updates from original marytts  
I have some questions:
- How I can trained marytts on other corpus instead of arabic wikipedia, because we need diactritized texts, I have the suitable corpus (Tashkeela, http://tashkeela.sf.net) 
- When I arrived to step  5. (Run feature maker with the minimal NLP components), 
I have an error in execution, 
```wkdb_featuremaker.sh wkdb.conf 
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

FeatureMaker parameters:
  -locale ar
  -mysqlHost localhost
  -mysqlUser root
  -mysqlPasswd root
  -mysqlDB wiki
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=ar
Mysql connection created successfully.
    TABLE = "ar_dbselection" already exists, should it be deleted (y/n)?y
Checking if ar_dbselection already exist.
TABLE = ar_dbselection already exist, adding sentences to this table.
Starting builtin MARY TTS... MARY TTS started.

Getting list of unprocessed clean_text records from ar_cleanText
Number of unprocessed clean_text records to process --> [9568]
Looping over unprocessed clean_text records from wikipedia...
TARGETFEATURES to extract: phone next_phone selection_prosody 
Starting time:20_12_2015_20:35:14

Exception in thread "main" java.lang.AssertionError
	at marytts.features.FeatureRegistry.determineBestFeatureProcessorManager(FeatureRegistry.java:158)
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:230)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:170)

```

I thinks that's looking for a determineBestFeatureProcessorManager, but it does not exist, 
How can make a Feater processor for arabic, or how can I solve the error

**Comment by linuxscout** [comment]
I have solved this problem, I had missed to add dependency to mary-builder/pom.xml

**Comment by Zeexum** [comment]
hi @linuxscout I am also working on adding arabic support to maryTTS, I would like to know how you dealt with diactritized text since wiki dump text is not fully diactritized.

**Comment by linuxscout** [comment]
Salam @Zeexum, there are a similar project at https://github.com/HaraldBerthelsen/marytts-lang-ar it's in an advanced stage, it use

- the  Arabic speech corpus to train the program http://en.arabicspeechcorpus.com/  , 

- and  Mishkal text diacritizer to diacritize text http://tahadz.com/mishkal.
Thanks
