### ISSUE TITLE
MCEPmaker trouble

### ISSUE THREAD

**Issue by Columbusaustria** [marytts/marytts#384]
Guten Morgen aus Wien,
 > vor kurzem habe ich marytts-builder mit voiceimport sowie die nötigen
 > anderen Requisiten installiert. Ich bin mir nicht ganz sicher, ob das alles
 > richtig geklappt hat.
 > Mein OS ist Windows 8 64bit, ich verwende cygwin64 in der Terminalversion.
 > Edinburgh Speech Tools musste ich natürlich mit make installieren, dabei
 > wurde ein Fehler angezeigt, x86_64-unknown-cygwin ist im
 > Systemverzeichnis nicht vorgesehen,
 > habe Konfiguration auf cygwin 1.7 geändert, dann ist es ohne weitere
 > Fehlermeldung gelaufen.
 > Beim Versuch, MCEPmaker zu starten, wird folgende Fehlermeldung angezeigt:
 >
 > java.lang.Exception: The component MCEPMaker produced the following
 > exception:
 >
 > at
 > marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
 >
 > Caused by: java.lang.RuntimeException: Running ch_wave from
 > [C:\cygwin64\home\hrl\marytts-builder-5.1.2\speech_tools\] failed.
 >
 > Please check your ESTDIR environment variable, your specific EST path or
 > the execution rights in this path.
 >
 > at marytts.tools.voiceimport.ESTCaller.checkEST(ESTCaller.java:103)
 >
 > at marytts.tools.voiceimport.ESTCaller.<init>(ESTCaller.java:73)
 >
 > at marytts.tools.voiceimport.MCEPMaker.compute(MCEPMaker.java:240)
 >
 > at
 > marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
 >
 > Caused by: java.io.IOException: Cannot run program
 > "C:\cygwin64\home\hrl\marytts-builder-5.1.2\speech_tools\/bin/ch_wave":
 > CreateProcess error=193, %1 ist keine zulässige Win32-Anwendung
 >
 > at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
 >
 > at java.lang.Runtime.exec(Runtime.java:620)
 >
 > at java.lang.Runtime.exec(Runtime.java:450)
 >
 > at java.lang.Runtime.exec(Runtime.java:347)
 >
 > at marytts.tools.voiceimport.ESTCaller.checkEST(ESTCaller.java:100)
 >
 > ... 3 more
 >
 > Caused by: java.io.IOException: CreateProcess error=193, %1 ist keine
 > zulässige Win32-Anwendung
 >
 > at java.lang.ProcessImpl.create(Native Method)
 >
 > at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
 >
 > at java.lang.ProcessImpl.start(ProcessImpl.java:137)
 >
 > at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
 >
 > ... 7 more
 >
 > Danach habe ich versucht, ch_wave aus dem bin-oder aus dem main-Ordner
 > von speech_tools direkt zu starten, beide Versuche sind gescheitert. Es
 > scheint, als wäre ch_wave keine executable.
 >
 > Jetzt merke ich gerade, dass ich früher andere Fehlermeldungen erhalten
 > habe, nämlich Create process error=5!
 >
 > Für jede Unterrstützung danke ich im voraus,
 >
 > herzliche Grüsse aus dem immer noch schwülen Wien,
 >
 > Christoph Lassmann
 >

**Comment by psibre** [comment]
The MCEPMaker, as well as a few other voicebuilding components, deviate from the common paradigm of having component-specific configuration properties, and instead rely on the *global* property `db.estDir`, configurable from the "Settings" dialog, and stored in the `database.config` file in your voicebuilding directory.

The `db.estDir` property also deviates by expecting the actual binaries to be located in a *subdirectory* of that, called `bin`. So if a component wants to run `ch_wave`, and you have your Edinburgh Speech Tools installed in `someplace/speech_tools`, then you set `db.estDir` to `someplace/speech_tools`, and the component will try to run `someplace/speech_tools/bin/ch_wave`.

This gets a bit weird if you use a package manager to install a precompiled version of EST:
* On Ubuntu/Debian **Linux**, you install with `sudo apt-get install speech-tools`, after which `ch_wave` is in `usr/bin`, so you would need to set `db.estDir` to `/usr`.
* On **OSX**, you can run `brew install speech-tools`, which puts symlinks to the tools into `/usr/local/bin`, so you would set `db.estDir` to `/usr/local`.

On Windows, you'll need to ensure that `${db.estDir}/bin/ch_wave` resolves to the successfully compiled binary. But first of course you should ensure that they really work.

**Comment by Columbusaustria** [comment]
Thank you for your Response. 
After studying the error Messages, meanwhile I believe cygwin64 or Windows 64 bit in General do not work with speech Tools. The ch_wave and the other binaries which were built cannot be launched.
Kind regards
Christoph

**Comment by seblemaguer** [comment]
Have you solved your problem or is it still going on ?
