### ISSUE TITLE
marytts 5.1.1 and 5.1.2 literally fails (fatal) more than a 10% of words. (EN)

### ISSUE THREAD

**Issue by smithtek** [marytts/marytts#385]
I tested less than a 100 words, totally random from the dictionary, not searching for any difficulty, random from a Database, all these failed so far, that means no sound no wav file, fatal error. If any text contain these, it will fail.

Aret
Deleted
Approachless
Fengite
Jasponyx
Bigly
Fratery
Arquebus
Decortication
Corseted
Introduced
Forwot
Haematogenous
Done
PD: Round 2, tested 73 random words, 14 fails, 19% Fail ratio = A joke.
Cullion
Dormice
Cheliferous
Cuca
Itch
Caparro
Bemaul
Incapable
Cingalese
Egotized
Bubo
Arrhizous
Homoeothermal
Asperifolious

Tested on 5.1.1 and 5.1.2 so at least it fails in this versions, I'm sure I can make a very very long list, it is unusable.
It works correctly with hsmm voices but these happens with all the "good ones" available in english GB and US.

I know this is a known problem, but did not expect the failure rate was so high, will it be solved any time soon? Can I fix it somehow?

**Comment by smithtek** [comment]
psibre you said a  solution was to install 5.1.1, not worked for me. What version really works?

**Comment by psibre** [comment]
This was indeed an open issue for a long time, but we did address several weeks ago, and it's been fixed.

Using the current master, I get:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<t g2p_method="rules" ph="' A - r E t" pos="NNP">
Aret
</t>
<t g2p_method="lexicon" ph="d I - ' l i - t @ d" pos="NNP">
Deleted
</t>
<t g2p_method="rules" ph="@ - p r @U - ' tS l E s" pos="NNP">
Approachless
</t>
<t g2p_method="rules" ph="' f E N - dZ AI t" pos="NNP">
Fengite
</t>
<t g2p_method="rules" ph="' dZ { s - p A - n I k s" pos="NNP">
Jasponyx
</t>
<t g2p_method="rules" ph="' b I - g l i" pos="NNP">
Bigly
</t>
<t g2p_method="rules" ph="' f r EI - t r= - i" pos="NNP">
Fratery
</t>
<t g2p_method="rules" ph="' A r k w - b @ s" pos="NNP">
Arquebus
</t>
<t g2p_method="rules" ph="' d E - k O r - t @ - k EI - S @ n" pos="NNP">
Decortication
</t>
<t g2p_method="rules" ph="' k O r - s @ - t I d" pos="NNP">
Corseted
</t>
<t g2p_method="lexicon" ph="' I n - t r @ - d u s t" pos="NNP">
Introduced
</t>
<t g2p_method="rules" ph="' f O r - w @ t" pos="NNP">
Forwot
</t>
<t g2p_method="rules" ph="' h m @ - t @ - dZ @ - n @ s" pos="NNP">
Haematogenous
</t>
<t g2p_method="lexicon" ph="' d V n" pos="NNP">
Done
</t>
<t g2p_method="rules" ph="' k V l - j @ n" pos="NNP">
Cullion
</t>
<t g2p_method="rules" ph="' d O r - m @ s" pos="NNP">
Dormice
</t>
<t g2p_method="rules" ph="' tS E - l I - f r= - @ s" pos="NNP">
Cheliferous
</t>
<t g2p_method="rules" ph="' k u - k @" pos="NNP">
Cuca
</t>
<t g2p_method="lexicon" ph="' I tS" pos="NNP">
Itch
</t>
<t g2p_method="rules" ph="' k A - p A - r @U" pos="NNP">
Caparro
</t>
<t g2p_method="rules" ph="' b I - m O l" pos="NNP">
Bemaul
</t>
<t g2p_method="lexicon" ph="I n - ' k EI - p @ - b @ l" pos="NNP">
Incapable
</t>
<t g2p_method="rules" ph="' s I N - g EI - l i z" pos="NNP">
Cingalese
</t>
<t g2p_method="rules" ph="' E - g @U - t AI z d" pos="NNP">
Egotized
</t>
<t g2p_method="rules" ph="' b j u - b @U" pos="NNP">
Bubo
</t>
<t g2p_method="rules" ph="' r= r - h @ z s" pos="NNP">
Arrhizous
</t>
<t g2p_method="rules" ph="' h @U - m @U - i - D r= - m @ l" pos="NNP">
Homoeothermal
</t>
<t g2p_method="rules" ph="' { s - p r= - r I - f @U - l i - @ s" pos=".">
Asperifolious
</t>
</s>
</p>
</maryxml>
```
I'm not saying the pronunciations here are perfect, but no errors occur.

**Comment by smithtek** [comment]
I want to comment how I solved it because I was not able to build it. The error during the build is:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin17:test (default-test) on project marytts-lang-en: There are test failures.
(I have enough Ram)

Anyways what I'm doing now is, if I detect a failure I just do Text to Phonemes with an hsmm voice and then phonemes to audio with the "good" voice, easy fix.
