### ISSUE TITLE
MCEPMaker: output file not accessible

### ISSUE THREAD

**Issue by aWelker** [marytts/marytts#386]
Hi,

I'm trying to create a new Mary voice for Dutch, but the MCEPMaker won't process my files. This is the error message I get:
```
Creating the directory [/Arbeit_Mary/dutch_voice/voice-dfki-antje/mcep/].
bkap10_001
/home/anna/Programme/speech-tools//bin/sig2fv: output file not accessible "/Arbeit_Mary/dutch_voice/voice-dfki-antje/mcep/bkap10_001.mcep"
Type -h for help on options.
java.lang.Exception: The component MCEPMaker produced the following exception:
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException: Mel-Cepstrum  computation failed on file [bkap10_001]!
Command line was: [/home/anna/Programme/speech-tools//bin/sig2fv -window_type hamming -factor 2.5 -otype est_binary -coefs melcep -melcep_order 12 -fbank_order 24 -shift 0.01 -preemph 0.97 -pm /home/anna/Arbeit_Mary/dutch_voice/voice-dfki-antje/pm/bkap10_001.pm -o /Arbeit_Mary/dutch_voice/voice-dfki-antje/mcep/bkap10_001.mcep /home/anna/Arbeit_Mary/dutch_voice/voice-dfki-antje/wav/bkap10_001.wav].
    at marytts.util.io.General.launchProc(General.java:543)
    at marytts.tools.voiceimport.ESTCaller.make_mcep(ESTCaller.java:239)
    at marytts.tools.voiceimport.MCEPMaker.compute(MCEPMaker.java:241)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```
It seems that there is a problem with speech-tools, I just don't know why.
I already tried "make test" as suggested in the install instructions of speech-tools, but no errors showed up. 
Is there anyone who also had this problem and / or knows how to solve it?

Any help is appreciated.

**Comment by aitorme** [comment]
Hi there,
could you please check your speech-tools version or whether it is installed?
run the following command on your terminal:
~$ dpkg -l | grep -E '^ii' | grep speech-tools
this will show the speech-tools version you have. If nothing appears, then you should proceed to install speech-tools, the following way from terminal:
~$ sudo apt-get install speech-tools

**Comment by aWelker** [comment]
Hi, thanks for answering.
My version is 1:2.1~release-6.

**Comment by psibre** [comment]
@aWelker please have a look at #384, specifically [this comment](384#issuecomment-131600491), which might be helpful here as well.

**Comment by aWelker** [comment]
@psibre: I'm pretty sure I got that part right, the directory was wrong at first and I got different errors . Then I changed the path so it really reaches speech-tools. As you can see in the stack trace the error occurs IN a speech-tools component

**Comment by seblemaguer** [comment]
Your output path is weird. It is /Arbeit_Mary/... and not /home/anna/Arbeit_Mary/... Can you check your builder configuration file again ?

**Comment by aWelker** [comment]
You are right, I forgot to use the whole part.
Now it works, thanks a lot!!!

**Comment by aitorme** [comment]
thank you for your help, @seblemaguer
