### ISSUE TITLE
Missing circumflex in Turkish lexicon and long vowels in AllophoneSet

### ISSUE THREAD

**Issue by geekdinazor** [marytts/marytts#390]
When I prepare new Turkish lexicon wordlist, I noticed there is no circumflex in Zemberek's wordlist.
But Turkish language have some critical words that circumflex change mean of word. For example "kar" (snow) and "kâr" (profit), "hala" (aunt) and "hâlâ" (still), "adet" (pieces) and "âdet" (tradition/menstruation) is most used similiar words in Turkish. Current `allophones.tr.xml` doesn't support circumflexes so, i add `a:` to it for testing purposes. [(Source)](https://www.phon.ucl.ac.uk/home/sampa/turkish.htm). And create binary files but MaryTTS doesn't read anything when this testing language is selected. Did i make something wrong or is this a bug ? Thank you for your attentions.

**Comment by psibre** [comment]
It's important to distinguish between written and phonetic diacritics.

If I understand correctly, words like *hâlâ* (pronounced /ha:la:/) and *hala* (/hala/) differ *typographically* in that the former happens to mark vowel length by adding a circumflex. The pronunciation is different, but this is marked by adding a length mark (/:/) to the phonetic transcription.

So yes, I believe that *hâlâ* and *hala* must be different in the pronciation lexicon, and the allophoneset would cover this by have both `a` and `a:` vowels. And if *â* is in the lexicon and always pronounced `a:`, then we should indeed rebuild the Turkish lexicon resources once more.

**Comment by geekdinazor** [comment]
Yes, you understand correctly. The letter â is always pronounced as `a:` in Turkish.

**PS:  lenght mark also change pithch of letter a, too. This pronounced lighter than "normal a". You can listen it from [here](https://translate.google.com/m/translate#tr/en/h%C3%A2l%C3%A2)**

**Comment by psibre** [comment]
Just a follow-up question: is the circumflex the only thing missing from Zemberek's word list? I ask because it seemed fully formed to me as a naive (non-Turkish speaking) user; ğ, ı, ç, ş, ö, ü, etc. are all in there.

**Comment by psibre** [comment]
Incidentally, pitch is modeled at the suprasegmental level, but having a different allophone that correlates with high pitch would of course also improve the prosody models.
Perhaps we should reopen this issue to indicate that the lexicon and allophoneset need to be tweaked to account for these effects.

**Comment by geekdinazor** [comment]
This Turkish spesific characters is part of offical Turkish alphabet but â is not, because it is phonetic letter  for Arabic and Farsi compatibility. In modern Turkish we don't use â and î much but in similiar words â is necessary, so there is no another missing.
