### ISSUE TITLE
JPhonemiser_de seems to do mistakes

### ISSUE THREAD

**Issue by Georgakopoulos** [marytts/marytts#391]
I work on maryTTS 5.2-SNAPSHOT and I have created my own german voice, which I try to improve.
I have observed that most of the mistakes in the speech synthesis process come from the JPhonemiser_de Module. 

For example: 
1.**Überdruckventil** - (JPhonemiser_de Output)

``` java
<phrase>
<t accent="H*" g2p_method="rules" ph="' ? y: 6 b - d R U N - k v E n - t I l" pos="NE">
```

2.**Hilfsbereit** 

``` java
2015-09-09 15:44:19,070 [main] INFO  marytts.R 1 Next module: JPhonemiser_de
2015-09-09 15:44:19,072 [main] DEBUG marytts.PhonemiseDenglish processFlection is starting with: hilfsbereit
2015-09-09 15:44:19,073 [main] DEBUG marytts.PhonemiseDenglish compoundAnalysis is starting with: hilfsbereit
2015-09-09 15:44:19,073 [main] DEBUG marytts.PhonemiseDenglish Pre: hilfsber
2015-09-09 15:44:19,073 [main] DEBUG marytts.PhonemiseDenglish Pre: hilfsbe
2015-09-09 15:44:19,074 [main] DEBUG marytts.PhonemiseDenglish Pre: hilfsb
2015-09-09 15:44:19,074 [main] DEBUG marytts.PhonemiseDenglish Pre: hilfs
2015-09-09 15:44:19,075 [main] DEBUG marytts.PhonemiseDenglish Pre: hilf
2015-09-09 15:44:19,075 [main] DEBUG marytts.PhonemiseDenglish Pre: hil
2015-09-09 15:44:19,076 [main] DEBUG marytts.PhonemiseDenglish compoundAnalysis is starting with: hilfsbereit
2015-09-09 15:44:19,076 [main] DEBUG marytts.PhonemiseDenglish Pre: hilfsber
2015-09-09 15:44:19,076 [main] DEBUG marytts.PhonemiseDenglish Pre: hilfsbe
2015-09-09 15:44:19,077 [main] DEBUG marytts.PhonemiseDenglish Pre: hilfsb
2015-09-09 15:44:19,077 [main] DEBUG marytts.PhonemiseDenglish Pre: hilfs
2015-09-09 15:44:19,078 [main] DEBUG marytts.PhonemiseDenglish Pre: hilf
2015-09-09 15:44:19,079 [main] DEBUG marytts.PhonemiseDenglish Pre: hil
2015-09-09 15:44:19,093 [main] DEBUG marytts.R 1 Handing the following data to the next module:
2015-09-09 15:44:19,094 [main] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t g2p_method="rules" ph="h I 6 l f s - ' b aI t" pos="ADJD">
hilfsbereit
```

Does anybody know how I can fix this, except by adding the words to the userdict?
Is it a problem of the SNAPSHOT-Version?

**Comment by Georgakopoulos** [comment]
I tried adding the words to the dictionary (de.txt FILE), but mary does not seem to apply the LetterToSoundRule! Do Have to do something for Mary to adopt the changes other than adding them to the List?

**Comment by seblemaguer** [comment]
I do not have time to check that before 2 weeks, can it waits so ?

**Comment by Georgakopoulos** [comment]
Ok, thank you. I will try to find a solution myself in the meantime, because we are stuck with it. If I have anything I will post it.

**Comment by entenbein** [comment]
I guess you would need to rebuild the lts file which is used for "guessing" the transcription of OOV words. Did you do that? Furthermore the MaryTTS Server isn't using your altered de.txt from the *marytts-languages/marytts-lang-de/src/[......]* folder. You would need to rebuild the source of MaryTTS with maven after adding entries to that file. Or add them to the userdict in the *target* folder.

**Comment by Georgakopoulos** [comment]
I tried adding them in the **userdict** in the *target* folder and it worked fine for the Marytts 5.1 Version. Though in my **5.2 SNAPSHOT** Version it simply ignores my changes!

Have there been any changes in the 5.2 Snapshot-Version that might cause that?

**Comment by entenbein** [comment]
What about the userdict file in the *user-dictionaries* folder in $MARY-BASE ?

**Comment by Georgakopoulos** [comment]
The same problem remains.I have checked them all: I can't seem to make MaryTTS respect my changes in the **userdict** 5.2-Snapshot-Version under Ubuntu (Linux), where as it does in the 5.1 Version under Windows.

**Comment by entenbein** [comment]
Did you change / double-check the settings in 
```
marytts-languages/marytts-lang-<lang>/src/main/resources/marytts/language/<lang>/<lang>.config
```

?

**Comment by Georgakopoulos** [comment]
I havent changed it and the path is set right....
```java
de.userdict = MARY_BASE/user-dictionaries/userdict-de.txt
de.lexicon = jar:/marytts/language/de/lexicon/de_lexicon.fst
```

**Comment by entenbein** [comment]
Did you train new lts rules with the new words and did you rebuild the sources with those rules?

**Comment by Georgakopoulos** [comment]
No, I was under the impression, I only need to add words to the **userdict-language.txt** to force maryTTS use my SAMPA tarnscription. 

How would I do that?

**Comment by entenbein** [comment]
If you got the relevant words in your userdict, the transcription will be taken from there. But adding yet unknown ones to your training lexicon for the lts rules will improve the transcription for other unknown ones (see the compoundAnalysis step mentioned in the first post).

Check this for training lts rules: http://mary.opendfki.de/wiki/TranscriptionTool

**Comment by Georgakopoulos** [comment]
Thanks for that. 

A remaining problem is that marytts does not take in consideration the transcriptions I added to the userdict. It does not take them from there and I cannot understand why..

**Comment by entenbein** [comment]
This should usually work quite fine. Did you check the server log for errors after restarting the server?

**Comment by Georgakopoulos** [comment]
I just did again, but couldn't find any. 

I did however find an anomaly which might have played a role:
I accidentally removed the **de.txt** file some time ago. Not from the *Mary_Base* but from the *marytts-lang-de* in the Package Explorer of Eclipse. Since that time I have a little **black asterisk** on this folder and I dont know how to fix this, or if it plays a role in my actual problem. I re added the de.txt File, but since then it has a question mark on it (untracked file). 

I am so descriptive, because I have little experience with eclipse and I can't know if this is relevant or not.

**Comment by entenbein** [comment]
Hi,

did you clone MaryTTS from Git into your eclipse/ imported it via maven? Not sure about the black asterisk though.
But maybe try to clone the current state into another directory, re-apply your changes and try invoking the mentioned tools from the terminal.

**Comment by Georgakopoulos** [comment]
I will try that, thank you

**Comment by Georgakopoulos** [comment]
I cloned the current SNAPSHOT-Version, added my changes *(simply copied the .java Files in the right directories)* and the problem is gone. Mary now accepts the changes I add to the **userdict**.
It was either not working on the earlier SNAPSHOT-version I had or I had messed sth. up in my eclipse directory. Maybe both. Thanks for the help.

**Comment by seblemaguer** [comment]
The problem is solved therefore ?

**Comment by Georgakopoulos** [comment]
Well the JPhonemizer_de still does mistakes using the g2p_method, but at least now I can transcribe words myself and add them to the userdict and marry uses those instead. The issue was opened because of these mistakes and because the temporarily solution that was proposed in earlier issues was to use the userdict.
