### ISSUE TITLE
Can't set up as a proxy repository in my Nexus server instance

### ISSUE THREAD

**Issue by lingvisa** [marytts/marytts#392]
Without using my own Nexus instance (using the Maven default setting.xml), I can compile MaryTTS successfully with the root POM.xml after checking out the whole package from github. It can download all artifcats needed from the repositories defined in $maryTTS_HOME/pom.xml. But I want to use my own Nexus server to host it, which means all dependencies required running MaryTTS will be downloaded from my Nexus server, so what I did was trying to set up a proxy repository in my Nexus, but it didn't work well.

There are two relevant URL in the two sections in the root pom.xml as below. In defining a proxy repository, I need to provide a URL for the remote repository location, and I assume the URL should be one of these. But Neither works. Any  idea of what's going on? Thank you.

```
<repositories>
                <repository>
                        <id>marytts-dependencies</id>
                        <name>marytts-dependencies</name>
                        <releases>
                                <enabled>true</enabled>
                        </releases>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                        <url>file://${project.local.repository.path}</url>
                </repository>
                <repository>
                        <id>central</id>
                        <name>jcenter</name>
                        <releases>
                                <enabled>true</enabled>
                        </releases>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                        <url>http://jcenter.bintray.com</url>
                </repository>
</repositories>

```

And

```
<distributionManagement>
                <site>
                        <id>DFKI</id>
                        <url>rsync:mary:/local/mary/www</url>
                </site>
                <downloadUrl>https://github.com/marytts/marytts/releases</downloadUrl>
                <repository>
                        <id>bintray</id>
                        <url>https://api.bintray.com/maven/marytts/marytts/marytts</url>
                </repository>
                <snapshotRepository>
                        <id>bintray</id>
                        <url>http://oss.jfrog.org/artifactory/oss-snapshot-local</url>
                </snapshotRepository>
</distributionManagement>

```

In Nexus, I tried the 3 URLs below, but it can't download all artificats successful:
http://jcenter.bintray.com
https://api.bintray.com/maven/marytts/marytts/marytts
http://oss.jfrog.org/artifactory/oss-snapshot-local

The error message when it tried to download from my Nexus:
Failed to execute goal on project marytts-common: Could not resolve dependencies for project de.dfki.mary:marytts-common:jar:5.2-SNAPSHOT: Could not find artifact com.twmacinta:fast-md5:jar:2.7.1 in nexus (http://www.bbword.com:8081/nexus/content/groups/public) -> [Help 1]

It would be great if it can be confirmed that it's possible to set up a proxy repository through which all dependencies for MaryTTS can be downloaded successfully through Nexus.

Thank you!

**Comment by psibre** [comment]
There are two repositories defined to retrieve artifacts, `marytts-dependencies` (project-local) and a custom `central` pointing to JCenter (a superset of Maven Central). These are used to *build* MaryTTS.

The `distributionManagement` section is used to *deploy* MaryTTS.

I'm not sure what you're trying to do, could you please clarify how you intend to use your Nexus instance?

**Comment by lingvisa** [comment]
Hi, Psibre:

Which URL should be used to define a proxy repository in Nexus? It sounds like it should be "a custom central pointing to JCenter"?

Please see here:

https://books.sonatype.com/nexus-book/3.0/reference/admin-repositories.html#proxy-repository

'''
Proxy
The configuration for proxy repositories in the Proxy section contains the following parameters:

Remote Storage
A proxy repository on the other hand requires the configuration of the Remote Storage. It needs to be configured with the URL of the remote repository, that should to be proxied. When selecting the URL to proxy it is beneficial to avoid proxying remote repository groups. Proxying repository groups prevents some performance optimization in terms of accessing and retrieving the content of the remote repository. If you require components from the group that are found in different hosted repositories on the remote repository server it is better to create multiple proxy repositories that proxy the different hosted repositories from the remote server on your Nexus server instead of simply proxying the group.
'''

**Comment by psibre** [comment]
We're using JCenter to host the stable MaryTTS artifacts; they are not in Maven Central. You should configure your Nexus to proxy JCenter for you.
Having said that, I'm still not sure why you need the Nexus at all -- what's wrong with the public repositories?

**Comment by lingvisa** [comment]
Nexus is for collaboration between developers. In my Maven setting.xml, 

<mirror>
      <id>nexus</id>
      <mirrorOf>*</mirrorOf>
      <url>http://www.bbword.com:8081/nexus/content/groups/public</url>
    </mirror>
  </mirrors>

I have my own mirrors of the public central repositories. So I need to proxy the MaryTTS's repository in my Nexus instance.  Does this make sense?

So I understand when configuring the proxy repository, I should fill "http://jcenter.bintray.com" in the "remote storage location" field and "release" in the Repository Policy. Right? Please see this screenshot.

![proxy](https://cloud.githubusercontent.com/assets/7905135/9838961/0efba03a-5a39-11e5-915e-d633858905ca.png)

**Comment by psibre** [comment]
I'm afraid I'm unable to help you there... I've never used Nexus (only Archiva and Artifactory). But I think you should seriously consider configuring your Nexus instance to proxy JCenter, for all kinds of stuff that's there and not in Maven Central (not just marytts).

Incidentally, you should always use https for remote repositories. See if that solves your issue.

**Comment by lingvisa** [comment]
I am relatively new to Maven stuff, but my impression is that Maven Central is the most comprehensive and official repository for hosting aritfacts and the definitive default repository to download many public libraries. JCenter is sort of a place I first heard of. Do you mean JCenter is even more comprehensive than Maven Central?

**Comment by psibre** [comment]
> Do you mean JCenter is even more comprehensive than Maven Central?

Exactly. See here: https://bintray.com/bintray/jcenter/

**Comment by lingvisa** [comment]
Good to know about that. But why does apache-maven tool use Maven Central as its default repository if users don't overwrite the settings.xml? 

In any case, i should still be able to proxy JCenter in my Nexus instance. Right? So that I can use both aritifacts from Maven Central and JCenter.

**Comment by psibre** [comment]
JCenter itself acts like a proxy for Maven Central, so you really only need the former.

Maven is obviously hardwired to resolve from Maven Central, but you can override it in your `settings.xml`.

I'm still not convinced why you need your Nexus, btw.

**Comment by lingvisa** [comment]
Are you saying you are not convinced why I need to use Nexus, or in general why is Nexus needed?

My understanding is that without using Nexus, you need to store third-party dependencies in Version Control system. Nexus published a book that explains the benefits of using Nexus in a team, not a single user of course.

**Comment by lingvisa** [comment]
If I want to user JCenter, is this the right version of the setting.xml:


```
<?xml version="1.0"?>
<settings>
  <mirrors>
    <mirror>
      <id>nexus</id>
      <mirrorOf>*</mirrorOf>
      <url>http://www.bbword.com:8081/nexus/content/groups/public</url>
    </mirror>
  </mirrors>
  <servers>
    <server>
      <id>nexus</id>
      <username>admin</username>
      <password>bbword</password>
    </server>
  </servers>
  <profiles>
    <profile>
      <id>nexus</id>
      <!--Enable snapshots for the built in central repo to direct -->
      <!--all requests to nexus via the mirror -->
      <repositories>
        <repository>
          <id>jcenter</id>
          <url>http://jcenter</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>jcenter</id>
          <url>http://jcenter</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  <activeProfiles>
    <!--make the profile active all the time -->
    <activeProfile>nexus</activeProfile>
  </activeProfiles>
                              
```

It's a little modification from the Maven central version of the setting.xml

**Comment by psibre** [comment]
Indeed, 3rd party dependencies do not belong in VCS. Which is why all of them are stored in, and resolved from, JCenter (and OJO). Please see our [example application](/marytts/marytts-txt2wav) on how this works.

...unless of course you have some custom, proprietary dependencies that are not in public repositories. In that case, you *do* want a Maven Repository Manager such as Nexus -- but only if you are locked into Maven. More advanced dependency resolution engines such as Ivy don't need a full MRM and can just as well resolve from a passive webserver or network share.

**Comment by lingvisa** [comment]
Hi, psibre:

My repository for (https://jcenter.bintray.com) almost works, and can successfully build most of the jar files. But it stopped at mary-tts builder:

INFO] Reactor Summary:
[INFO] 
[INFO] MaryTTS ............................................ SUCCESS [ 28.419 s]
[INFO] marytts-common ..................................... SUCCESS [ 11.401 s]
[INFO] marytts-signalproc ................................. SUCCESS [  3.160 s]
[INFO] marytts-runtime .................................... SUCCESS [ 17.977 s]
[INFO] marytts-lang-de .................................... SUCCESS [  2.746 s]
[INFO] marytts-lang-en .................................... SUCCESS [  6.028 s]
[INFO] marytts-lang-te .................................... SUCCESS [  1.851 s]
[INFO] marytts-lang-tr .................................... SUCCESS [  1.751 s]
[INFO] marytts-lang-ru .................................... SUCCESS [  0.403 s]
[INFO] marytts-lang-it .................................... SUCCESS [  1.399 s]
[INFO] marytts-lang-fr .................................... SUCCESS [  0.806 s]
[INFO] marytts-lang-sv .................................... SUCCESS [  0.358 s]
[INFO] marytts-lang-lb .................................... SUCCESS [  2.052 s]
[INFO] marytts-languages .................................. SUCCESS [  0.014 s]
[INFO] voice-cmu-slt-hsmm ................................. SUCCESS [  7.245 s]
[INFO] marytts-client ..................................... SUCCESS [  4.858 s]
[INFO] marytts-builder .................................... FAILURE [  2.576 s]
[INFO] marytts-redstart ................................... SKIPPED
[INFO] marytts-transcription .............................. SKIPPED
[INFO] marytts-assembly-builder ........................... SKIPPED
[INFO] marytts-assembly-runtime ........................... SKIPPED
[INFO] marytts-assembly ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:33 min
[INFO] Finished at: 2015-09-13T23:26:53-04:00
[INFO] Final Memory: 61M/464M
[INFO] ------------------------------------------------------------------------
*[ERROR] Failed to execute goal on project marytts-builder: Could not resolve dependencies for project de.dfki.mary:marytts-builder:jar:5.2-SNAPSHOT: The following artifacts could not be resolved: gov.noaa.pmel.sgt:sgt:jar:3.0, org.wikimedia:mwdumper:jar:1.16: Could not find artifact gov.noaa.pmel.sgt:sgt:jar:3.0 in nexus (http://www.bombword.com:8081/nexus/content/groups/public) *-> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by seblemaguer** [comment]
Hello,

these dependencies are local one. You can find that there are local repositories specifically for these packages in <marytts_dir>/lib/repo.

Therefore, your proxy configuration seems to ignore these ones.

**Comment by psibre** [comment]
You can also [exclude transitive dependencies](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) you don't need.
