### ISSUE TITLE
Skip words from transcript/audio

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#400]
Hi folks, 

I'd like to skip a word from the script as well as the part (because it was read/pronounced in a way that doesn't comply with my phoneset, or something different was read) of the audio when processing a particular sentence. By, let's say, marking that word with a *#skip#' or some other distinctive tag.

So in

_This is such a sentence#skip# where I'd like to skip a word._

only 

_This is such a where I'd like to skip a word._

should be processed. Is that possible without altering the audio file?

I gave it a try and added some code to _marytts-languages/marytts-lang-[lang]/src/main/java/marytts/language/[lang[/JTokeniser.java_'s **tokenizerFixes** class:

```
protected void tokenizerFixes(MaryData d) {
        Document doc = d.getDocument();
        NodeIterator ni = ((DocumentTraversal) doc).createNodeIterator(doc, NodeFilter.SHOW_ELEMENT, new NameNodeFilter(
                MaryXML.TOKEN), false);
        Element t = null;
        while ((t = (Element) ni.nextNode()) != null) {
            String s = MaryDomUtils.tokenText(t);
//-----------------------------------------------------------------------
            if (s.contains("#skip#")){
                System.out.println("Delete word from sentence: " + s);
                t.getParentNode().removeChild(t);
                doc.normalize();
                continue;
            } 
//------------------------------------------------------------------------
[...]

```

Anyway, that doesn't seem to be enough.

Any suggestions?

Thanks

**Comment by psibre** [comment]
I'm not sure if this answers your question, but there is a hidden "feature" that allows you to override the AllophonesGenerator component for selected utterances by providing the `ALLOPHONES` MaryXML youself. To do this, just place the corresponding files under `rawmaryxml` in your voicebuilding directory.

**Comment by entenbein** [comment]
AllophonesGenerator? Do you mean AllophonesExtractor? So when placing a file in ```rawmaryxml``` it would read the altered text from there, right? But the audio stays the same. Hence if the script is one word short wouldn't it map the audio signal of the removed word to the next word in the script?

Not sure if I got what you proposed though ...

**Comment by psibre** [comment]
> AllophonesGenerator? Do you mean AllophonesExtractor?

Sorry, yes. My bad.

**Comment by psibre** [comment]
The idea with the `rawmaryxml` files is that you can make the `ALLOPHONES`-level features "extracted" from the text match what was actually spoken.

**Comment by entenbein** [comment]
Alright, are there examples how such files should be formatted?

**Comment by psibre** [comment]
Run MaryTTS server locally and play around with it in your browser; set output type to `ALLOPHONES`.

**Comment by entenbein** [comment]
Ok, so that's the same format as for the files in the ```allophones``` folder. So I would put duplicates of those files, removing the words to be skipped, into ```rawmaryxml```, is that right?

**Comment by psibre** [comment]
Yes, that's the idea.

**Comment by entenbein** [comment]
Great, thanks! I'll give it a try

**Comment by entenbein** [comment]
At what stage of the voice building process should I place the files in the ```rawmaryxml``` folder?

**Comment by entenbein** [comment]
Hi,

would I have to change (Half)PhoneUnitFeatureComputer's input from `/allophones` to `/rawmaryxml` ?

**Comment by entenbein** [comment]
**bump**

**Comment by psibre** [comment]
@entenbein sorry I thought it was already clear. You need to put your MaryXML files into `rawmaryxml`, and the AllophonesExtractor uses them, overriding them any corresponding files in `text`. So you need to do this at the very beginning.

**Comment by entenbein** [comment]
Hi,

it wasn't clear to me that `rawmaryxml` files overwrite the ones in `text`. But just to be clear to get the ones for `rawmaryxml` I need to first run the Allophonextractor to get the desired format for the xml files, do my modifications and run the whole process again where the files in `rawmaryxml` overwrite the ones in `text`?!

**Comment by psibre** [comment]
No, you can just run a MaryTTS server and use the web interface to obtain the baseline MaryXML, which you can then edit and put into `rawmaryxml`.
