### ISSUE TITLE
Secure the URL requests to MaryTTS.

### ISSUE THREAD

**Issue by blsn** [marytts/marytts#413]
MaryTTS is running on my server and users can get audio as a URL to a wav file using the embedded HTML ```<audio>``` tag:
```HTML
<audio controls>
   <source src='http://myserver:59125/process?INPUT_TYPE=TEXT&AUDIO=WAVE_FILE&OUTPUT_TYPE=AUDIO&LOCALE=en_US&INPUT_TEXT=%22Hello%20world%22' type='audio/wav'>
</audio>
``` 
I wish to secure the requests so that a third party wouldn't use my text-to-speech server for audio clips not related to my website.   

Do I need to write a specific Java servlet for that, wrap it and deploy the app? If yes, just to get started.. ,could you advise how? What would you recommend me to do?

**Comment by seblemaguer** [comment]
Hello,
what do you mean exactly by securing ? not using parameters in the URL but in a POST part or something different ?

**Comment by psibre** [comment]
Sound like something that would be straightforward at the webserver level. Apache and nginx both have an easy way to restrict access by password etc.

**Comment by blsn** [comment]
My concern is that I might start seeing performance issues and out of memory errors, which would cause the TTS Synthesis platform server (but not the website) to crash every few days, apparently triggered by one or more entities abusing it as some sort of webservice for their own applications.

I can’t use IP whitelist or username/password, since I want that anybody that browsing my website to be able to use the embedded sound element, but I don’t want somebody to copy this URL (using the console log) and past it to his browser.. and now you’re using my server without permission, and you get audio clips processed on my server.

**Comment by blsn** [comment]
[SOLVED] Using Jetty HTTP Web server and securing requests with a hash function.

**Comment by seblemaguer** [comment]
ok perfect :)
