### ISSUE TITLE
How to improve the quality of a voice

### ISSUE THREAD

**Issue by aWelker** [marytts/marytts#414]
Hi all,

I have now succeeded in creating and compiling a new voice for Dutch, but am not completely satisfied with the result at some points.
The voice was build from a rather old audiobook, and it works perfectly fine when I test with texts similar in style to the original book. However, when I provide "modern", complicated words like "spraaksynthese", the outcome is rather strange.
Plus it has occured several times now that I copied a sentence into the textbox and what I got back was the sentence plus one or two words more, random words that definitely weren't part of the sentence - is this a bug with mary or is there something wrong with my voice?

The voice is a unit selection voice (I strictly followed the tutorial on GitHub) and at FeatureSelection I didn't change the proposed features.
Now, is there any way to improve the quality apart from completing the audio with modern terms (which I can't, unfortunately)?

Thanks in advance for any suggestions!

**Comment by seblemaguer** [comment]
Hello,

what do you mean by strange ?For the addition of the word, that's another problem I think. Can you please open another issue ?

Thanks

**Comment by aWelker** [comment]
Hi,

thanks for answering that fast! The word addition at the end of the sentence hasn't occurred for a time now, so I'd like to concentrate on the general problem for now.
Strange means that the prosody is absolutely awkward, plus it seems that in between the words, there are no pauses at all - two examples:

good: Had hij ook maar één stap opzij gezet, dan was hij er niet meer geweest.
With this example, everything is perfectly fine.

bad: De Citroën C4 Cactus, een uitgeproken auto en alleen dit jaar nog met 14% bijtelling.
Here, you can hardly recognize the words; there are no pauses between them. "dit jaar nog" for example seems like one word, the "en" in "outgeproken" is simply not there and the "telling" in "bijtelling" is pronounced that fast so you can hardly hear it.
Additionally, I could swear that there is a "has" between "Cactus" and een

**Comment by nshmyrev** [comment]
It is better to provide sound samples. You can share them on dropbox and give here a link.

The artifacts you describe come from incorrect phonetic labels. Those are assigned automatically and should be pretty accurate if your database is large but if database is small or there are some other issues like incorrect transcription, they may be wrong. You could verify labels assigned on EHMM/HTK step and try to fix them.

I would track the sources of the artifacts you hear and try to fix transcription/dictionary in the places you find. Actually such manual review is the most time consuming part of building a good quality voice.

**Comment by aWelker** [comment]
Hi nshmyrev,
thanks for the advice!
I put the two sentences on dropbox: https://www.dropbox.com/sh/hmt13un53z989g9/AABeoBTXw2U7JEqTjcZADwFSa?dl=0
However, I'll start verifying the labels now, hope that helps.

**Comment by seblemaguer** [comment]
Hello,

I think you are facing a segmentation and pitchmarking problem. So yes verifying the labels should exhibit that.

**Comment by aWelker** [comment]
Okay, thanks!

**Comment by seblemaguer** [comment]
I close the issue but if you find no mistake or you think everything is correct in your data, don't hesitate to reopen it

**Comment by aWelker** [comment]
Hi,

you were right that the labels were not good, but after studying my files for some time I think that manual verifying the labels is just treating the symptoms, not the disease.
Looking at the transcription has shown that there must be happening something very strange (or at least dumb) when the input text is transformed to phonetic symbols. The annotations just don't make sense ([a:a:], [nn] really should not be in there, should they?), and a lot of times the phonemes marked are simply wrong.
Can anyone tell me how (where) Mary transforms raw text into phonetic text, or does somebody have an idea why this doesn't work for me?

**Comment by aWelker** [comment]
Okay, I guess I finally found the mistake - I did not run the transcription tools as I already had a complete database, of course that had to affect the prediction. So it's no bug of Mary but an omission in my workflow.

**Comment by seblemaguer** [comment]
ok thanks for the notification
