### ISSUE TITLE
neural network, voice quality

### ISSUE THREAD

**Issue by naldir** [marytts/marytts#418]
Why not using neural networks to improve TTS quality, fluidity have a more natural speech like google, apple or microsoft does ?
Despite this is the best open-source TTS, maryTTS is sadly far behind proprietary ones in term of voice quality

**Comment by seblemaguer** [comment]
Hello,

because we need manpower to develop the support for deep neural network. However, as the system is open source, we will be is anyone could do it :)

**Comment by Saxenauts** [comment]
@seblemaguer : This might sound a little naive, but I want to experiment with implementing text to speech . I have a good amount of experience with writing and training deep neural networks especially the LSTMs. However, I have zero experience with writing a text to speech system. I can start experimentation with the 'front-end' part to get linguistic features from the text. 

I still don't know how to generate the waveform from those features. I am studying the research paper on the new techniques for SPSS but if you could give any pointers, that'd be great.

**Comment by seblemaguer** [comment]
@Saxenauts: you could have a look to heiga zen papers about DNN and to the merlin system (https://github.com/CSTR-Edinburgh/merlin)
