### ISSUE TITLE
Half-phone features file formatting seems to be wrong

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#426]
Hi folks,

computing half phone features in my current setup seems to go wrong. This shows when running `HalfPhoneLabelFeatureAligner`, which is giving me the `Non-matching units` error.

This is because for some of the halfphones the formatting in the hpfeats file seems to be wrong:

**__L** 0 0 0 0 0 0 L 0 g s - 0 0 0 0 ae1 + 1 3 s - q NE 0 0 0 0 - 0 0 0 0 g s 0 0 0 0 0 0 0 0 0 0 0 **_** L-% [...]
**__R** 0 0 0 0 0 0 R 0 g s - 0 0 0 0 ae1 + 1 3 s - q NE 0 0 0 0 - 0 0 0 0 g s 0 0 0 0 0 0 0 0 0 0 0 **_** L-% [...]
**q_L** 0 0 0 0 0 0 L 0 0 0 0 0 a f - s - 0 0 0 0 ae1 NE . 0 0 0 + 1 3 s - g s 0 0 onset g s - - 0 0 0 0 **q** L-% [...]
**q_R** 0 0 0 0 0 0 R 0 0 0 0 0 a f - s - 0 0 0 0 ae1 NE . 0 0 0 + 1 3 s - g s 0 0 onset g s - - 0 0 0 0 **q** L-% [...]
**ae1_L** 0 0 0 0 0 0 L 0 a f - 0 g s - q - 0 0 0 0 s NE . 0 0 0 - 0 0 0 0 g s 0 0 coda 0 0 0 + 1 3 s - **ae1** L-% [...]
**ae1_R** 0 0 0 0 0 0 R 0 a f - 0 g s - q - 0 0 0 0 s NE . 0 0 0 - 0 0 0 0 g s 0 0 coda 0 0 0 + 1 3 s - **ae1** L-% [...]

So far, so good. But the next two are wrong:

**0_L** 0 0 0 1 0 0 L 0 g s - 0 0 0 0 a1 + 2 3 s - q NE . 0 0 0 - 0 0 0 0 g s 0 0 coda a f - - 0 0 0 0 **s** L-% [...]
**0_R** 0 0 0 1 0 0 R 0 g s - 0 0 0 0 a1 + 2 3 s - q NE . 0 0 0 - 0 0 0 0 g s 0 0 coda a f - - 0 0 0 0 **s** L-% [...]

**q_L** 0 0 0 0 0 0 L 0 0 0 0 0 a l + l - 0 0 0 0 a1 APPR . 0 0 0 + 2 3 s - a n 0 0 onset g s - - 0 0 0 0 **q** L-% [...]
**q_R** 0 0 0 0 0 0 R 0 0 0 0 0 a l + l - 0 0 0 0 a1 APPR . 0 0 0 + 2 3 s - a n 0 0 onset g s - - 0 0 0 0 **q** L-% [...]
**a1_L** 0 0 0 0 0 0 L 0 a l + 0 0 0 0 a0 + 2 3 s - l APPR . 0 0 0 - 0 0 0 0 a n 0 0 onset 0 0 0 + 2 3 s - **a1** L-% [...]

What I did is post-processing the hpfeats files, which means replacing the first chars before **_** with the group just before **L-%**....

But do you have any idea why this happens in the first place?

Thanks for your help!

**Comment by Rootex** [comment]
Hello Entenbein, 

Can you give me more information, the text you used to compute hphones that threw that error and also if possible the complete Stacktrace of that error.

Thank you.

**Comment by entenbein** [comment]
Hi,

I guess the input type is allophones. Those files are created using the default voice import `HalfPhoneUnitFeatureComputer` call/algorithm. That's the first word from that allophone file:

```
<t accent="H*" g2p_method="userdict" ph="q ae1 s" pos="NE">
S
<syllable ph="q ae1 s">
<ph p="q"/>
<ph p="ae1"/>
<ph p="s"/>
</syllable>
</t>
```

Thanks!

**Comment by seblemaguer** [comment]
Hello,

can you provide us the full maryxml raw, it will be easier for us to investigate.

Thanks a lot

**Comment by entenbein** [comment]
Hi,

here is the maryxml raw:

<?xml version="1.0" encoding="UTF-8" ?>
<maryxml version="0.4"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://mary.dfki.de/2002/MaryXML"
xml:lang="de">
<boundary  breakindex="2" duration="100"/>

S siebzig von Allach nach Fürstenried West über Freiburg im Breisgau fährt heute ausnahmsweise von Gleis drei A E ab.
</maryxml>

**Comment by entenbein** [comment]
I use an altered allophone set. Could the feature file's wrong values in come from a *unsupported* allophone set? There are allophones of a length up to 4 (\w\w\w\d) and there are 158 (also because of different stress levels) phones total (so even more halfphones)...

**Comment by seblemaguer** [comment]
Can you put the allophoneset in order for us to try to replicate the bug ?

**Comment by entenbein** [comment]
There you go:

http://pastebin.com/wPMR1tyA

Thanks for your help!

**Comment by entenbein** [comment]
Might it be that phones of length 4 (with stress level) cause a problem?

**Comment by Rootex** [comment]
Hello, from the allophone set you provided there seem to be a problem there, because it cant seem to match the phones to features, however it works ok with our set from what i gathered!

**Comment by entenbein** [comment]
Well, that is good news. The features and phones can't be matched because the feature file is getting written wrong. Some lines/ halfphones are just incorrect. But it's not only the phones at line beginning. After fixing this, some other bytes are incomplete (there was an error like this in the `HalfPhoneUnitfileWriter` or `HalfPhoneFeatureFileWriter`. So it seems like the whole halfphone feature file is corrupted. PhoneFeature computation doesn't seem to be a problem though.

**Comment by Rootex** [comment]
Ok, thank you for that, i will take a look and then get back to you.

**Comment by entenbein** [comment]
Could you provide your **hpfeats** file?

**Comment by Rootex** [comment]
Hey, I really tried to get you a solution but I just can't seem to replicate your configuration. Sorry.

**Comment by entenbein** [comment]
Alright, thanks so far. Can you share your hpfeats file? Did you get that far?

**Comment by entenbein** [comment]
The problem is that **HALFPHONE_UNITNAME** is wrong. Replacing it with **PHONE**+"_"+**HALFPHONE_LR** in  *HalfPhoneUnitFeatureComputer.loadFeatureList* works. But then the following error occurs when running `HalfPhoneFeatureFileWriter`:
```
Exiting at index (14176).
Number of processed units: 14176
java.lang.Exception: The component HalfPhoneFeatureFileWriter produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.UTFDataFormatException: malformed input around byte 1807
	at marytts.util.io.StreamUtils.readUTF(StreamUtils.java:137)
	at marytts.features.FeatureDefinition.<init>(FeatureDefinition.java:398)
	at marytts.unitselection.data.FeatureFileReader.loadFromByteBuffer(FeatureFileReader.java:107)
	at marytts.unitselection.data.FeatureFileReader.load(FeatureFileReader.java:72)
	at marytts.unitselection.data.FeatureFileReader.<init>(FeatureFileReader.java:68)
	at marytts.unitselection.data.FeatureFileReader.getFeatureFileReader(FeatureFileReader.java:53)
	at marytts.tools.voiceimport.PhoneFeatureFileWriter.compute(PhoneFeatureFileWriter.java:119)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```

This happens when reading/loading `[voice-folder]/mary/halfphoneFeatures.mry`.

Any thoughts on that?
