### ISSUE TITLE
How to train existing languages?

### ISSUE THREAD

**Issue by suffrage** [marytts/marytts#427]
Can you create wiki page with instruction, How to train existing languages?
Russian language is heard quite poor, and in my interest to train it

**Comment by nshmyrev** [comment]
Wiki instructions for voice building are here:

https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial

For rebuilding Russian voice you will need a database which you can download here:

http://www.repository.voxforge1.org/downloads/Russian/Trunk/Audio/Original/16kHz_16bit/urp.tgz

You can also take bigger database from RHVoice

http://tiflo.info/rhvoice/

For example Elena or Irina. They are bigger in size (3 hours or so).

For the industrial quality you need to create voice from 50 hours of audiobook segmented data. For that you need to find a big audiobook or several audiobooks by same author.

**Comment by suffrage** [comment]
Thx!
And what about intonation? abbreviation? reduction?

**Comment by seblemaguer** [comment]
Hello,

For abbreviation you need to propose your own nlp tools or adding the abbreviations to the lexicon

For the intonation, it should be "captured" by the unit selection or the hsmm model. If you want to change globally you can have a look at the effect part. If you want to change in more details, you should develop your own module.

Concerning the reduction, do you mean corpus reduction ?

**Comment by proewer** [comment]
hi,
first: marytts is very nice. thanks a lot :)

my question: is it possible to create a voice from textfile and wav audio file under windows? maybe with a bat script? i want create voice and use it in my java programm.

best regards,
paul
