### ISSUE TITLE
Installation of components via command line (aka no GUI)

### ISSUE THREAD

**Issue by circulon** [marytts/marytts#43]
Installation of components on headless server impossible at this stage.

marytts server works fine on ubuntu 10.04-4 server but only 1 voice available.

Alternatively are there instructions on how to install components and voices manually so the server will recognise them?

Your Help is appreciated.

**Comment by Munzey** [comment]
please see the new [web installer package](http://mary.dfki.de/download/index.html) for 5.1.2. It uses gradle to download and install voices. Source code: https://github.com/marytts/marytts-installer

**Comment by benbucksch** [comment]
```
grep location.cmu-slt download/marytts-components.xml|sed -e "s|.href=\"||" -e "s|\".*||"
unzip voice-cmu-slt-5.2.zip
```
