### ISSUE TITLE
wrong reading of monetary units

### ISSUE THREAD

**Issue by aitorme** [marytts/marytts#430]
While running some tests in English, I noticed that if you give an input like `$1.473 billion` to MaryTTS it will read this as `one dollar and four hundred seventy three cents billion`, which does not make much sense, it should be able to look forward and check for the upcoming word, and if it is `billion` or `million` go back and read it differently

**Comment by psibre** [comment]
@aitorme nice catch, and good proposal for solution. This is a good case for adding some test parameters to the [PreprocessTest](https://github.com/marytts/marytts/blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-languages/marytts-lang-en/src/test/java/marytts/language/en/PreprocessTest.java).

**Comment by psibre** [comment]
We need to find a way to get from `TOKENS`
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<t>
$
</t>
<t>
1.4
</t>
<t>
million
</t>
</s>
</p>
</maryxml>
```
to `WORDS`
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<mtu orig="$1.4 million">
<t pos=".">
$
</t>
<t>
one
</t>
<t>
point
</t>
<t>
four
</t>
<t>
million
</t>
</mtu>
</s>
</p>
</maryxml>
```
Note how the `million` token is *inside* the `mtu` (multi-token unit).
**Before we pre-process**.

**Comment by Rootex** [comment]
@psibre I am wondering if you can give me a link to jtok latest versions, all the results i get only have the 1.9.1 version.

**Comment by Rootex** [comment]
@psibre  I found the site, so i changed the pom setting to use jtok 2.16, but as you predicted alot of things are broken with the tokenizer.

**Comment by psibre** [comment]
I think we should move this issue to a later milestone, since we should take care when updating the jtok dependency.
