### ISSUE TITLE
Pronunciation of common abbreviations in English laguage

### ISSUE THREAD

**Issue by bensonofjohn** [marytts/marytts#433]
MaryTTS seems to have issues with common abbreviations like Dr. for Doctor or Mr. for Mister, MRS. etc. Dr is pronounced like Drive, Mr is pronounced M R.

**Comment by Munzey** [comment]
can you give an example sentence where its mispronouncing? what version of mary are you using?

**Comment by aitorme** [comment]
Dr stands for "drive" in English street names, indeed, especially when it is not spelled with a period.

**Comment by bensonofjohn** [comment]
I had forgotten for a moment that dr stands for drive. With or without a period it is still pronounced drive. Unfortunately the sentence

"Dr. Smith welcomes Mr Brown". 

becomes

"Drive Smith welcomes M R Brown"

Which doesn't sound right and changes the meaning.

I am using the latest download from MaryTTS site.

**Comment by Munzey** [comment]
>I am using the latest download from MaryTTS site.

I guess then you are referring to version 5.1.2, which at this point is [significantly behind 5.x master](https://github.com/marytts/marytts/commits/v5.1.2) . The next release will have a new preprocess module for the English language which should iron out any abbreviation issues. In the meantime you could check out the master branch and build from there if you want the 'latest & greatest'.

**Comment by aitorme** [comment]
@bensonofjohn I tried on my system with the latest MaryTTS updates and it does pronounce "Doctor Smith welcomes Mister Brown".
Please update your MaryTTS to the latest commits.

**Comment by bensonofjohn** [comment]
Thank you for testing this. I'll build from the master.
