### ISSUE TITLE
numbers cannot be read

### ISSUE THREAD

**Issue by aitorme** [marytts/marytts#435]
related to #432, apart from English, French and Italian (German always works fine), the rest of the languages cannot handle a single number, so the general module `JPhonemiser` under `marytts-runtime` does not work activate in the latter scenario.

**Comment by psibre** [comment]
@aitorme could you be more specific? Please add example input and output to make the issue reproducible.

**Comment by Rootex** [comment]
@psibre I checked and this is an example for this issue, processing from `TEXT` to `WORDS`

`English`

```
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<mtu orig="345634">
<t>
three
</t>
<t>
hundred
</t>
<t>
forty
</t>
<t>
five
</t>
<t>
thousand
</t>
<t>
six
</t>
<t>
hundred
</t>
<t>
thirty
</t>
<t>
four
</t>
</mtu>
</s>
</p>
</maryxml>
```

`German`

```
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<mtu accent="last" orig="345634">
<t>
drei
</t>
<t>
Hundert
</t>
<t>
fünfundvierzig
</t>
<t>
Tausend
</t>
<t>
sechs
</t>
<t>
Hundert
</t>
<t>
vierunddreißig
</t>
</mtu>
</s>
</p>
</maryxml>
```

`Russian`

```
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="ru">
<p>
<s>
<t>
345634
</t>
</s>
</p>
</maryxml>
```

Notice how the Russian didn't handle the number. It is the same for `lb`, `sv`, `te` and `tr`.

I think this is more of a feature than a bug.

**Comment by Munzey** [comment]
there is no number processing for most of these languages. lb does have a preprocess class written in groovy. I believe @HaraldBerthelsen has done some work on creating a number processor for sv in his mary branch. The others could probably be easily implemented in a simple manner like the english preprocess class using ibm's icu number formatter. so if that is what this issue is related to, then yes its a feature issue.
