### ISSUE TITLE
Adding/duplicating an Output Type (MARY Web Client)

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#438]
Hi folks,

for debugging a voice I'd like to duplicate the `REALISED_ACOUSTPARAMS` output type and reduce the information given there. Just to clarify the audio source of the used phones.

I started duplicating it in `marytts-runtime/src/main/java/marytts/datatypes/MaryDataType.java` and I guess I'd have to add the new type to `outputTypesWithAudio` in several classes.  But where configure which output types to load/show in the drop down menu of the web client?

Thanks!

**Comment by Rootex** [comment]
Hey,

So there is a javascript:
 marytts-runtime/src/main/resources/marytts/server/HTTP/mary.js - this is what fills in the data types and gets selected values. from and to the index.html in the same directory.

But is looks like defining your dataTypes in maryDataType.java is enough and also of course any other place needed.

Take a look at this two files, you might find what you are looking for there.

Best.

**Comment by entenbein** [comment]
Hi,

thanks for your reply. I looked into `mary.js` but not all of the output types are mentioned there. Is there another source/place?

Thanks

**Comment by seblemaguer** [comment]
Hello,

currently, all the types have been defined in marytts-runtime/src/main/java/marytts/datatypes/MaryDataType.java

**Comment by entenbein** [comment]
Alright, thanks! But where can I find how the Realised_Acoustparams output is made up?

**Comment by seblemaguer** [comment]
It seems to be in this class : marytts-runtime/src/main/java/marytts/modules/RealisedAcoustparamsExtractor.java

**Comment by attacomsian** [comment]
Hi, 

If you want to add / remove input or output types in web client, I would advise to check `fillTypes` function in `mary.js`. You can define your own datatypes over there.
