### ISSUE TITLE
Mary Transcription tool ...cant train and predict

### ISSUE THREAD

**Issue by Yamin372** [marytts/marytts#439]
![desktop](https://cloud.githubusercontent.com/assets/15828708/11652020/1d000944-9dbb-11e5-834a-0b84c7c48123.jpeg)
Line number coming from 20....please help....please

**Comment by entenbein** [comment]
Looks like that (some of) the phones in those words marked red are not in your phone set.

**Comment by Munzey** [comment]
this tool is on its way out, as a temporary solution you could try use [LTSLexiconPOSBuilder.java](https://github.com/marytts/marytts/tree/master/marytts-transcription/src/main/java/marytts/tools/transcription) to generate your lexicon, however as you're using the old voicebuilder plugin I dont think this will fit into the plugin's pipeline as it uses a db to store everything . There is also a new separate [gradle repo](https://github.com/marytts/gradle-marytts-voicebuilding-plugin) intended to replace this legacy tool, however im unsure of how stable it is, maybe @psibre can fill us in.

**Comment by Yamin372** [comment]
Its fixed..Thank you @Munzey  @entenbein

**Comment by Nandutu** [comment]
@Yamin372 how did you overcome the above issue. I am encountering the same problem
could any person help please.

Thanks

**Comment by Nandutu** [comment]
I after solved mine, solution is at #529
