### ISSUE TITLE
Add option to allow creating a socket with a specific IP address

### ISSUE THREAD

**Issue by pqyptixa** [marytts/marytts#442]
As the title says, please add an option to allow binding the server socket to a specific IP address.
I have some patches that I want to submit. However, I'm not sure if there are good and complete enough for merging:
https://github.com/marytts/marytts/compare/master...pqyptixa:pqyptixa-socket-host
This should work with the HTTP server (I have another version of these patches that is running in my server without problem).

**Comment by pqyptixa** [comment]
By the way, do you people have an IRC channel where we could talk? I wanted to discuss how to write this patch, but I couldn't find any way to contact a dev through IRC. IMO, you should make a new channel in Freenode.

**Comment by pqyptixa** [comment]
Any input? Does anyone care about this?

**Comment by nshmyrev** [comment]
You'd better create a complete pull request instead of an issue. It might not be ideal, but at least show what do you propose.

**Comment by pqyptixa** [comment]
OK, thanks.

**Comment by psibre** [comment]
@pqyptixa Like @nshmyrev said, please open a new PR for this.

**Comment by TwizzyDizzy** [comment]
Quick question: has this been implemented? I also don't want to listen on 0.0.0.0.

Cheers
Thomas

**Comment by pqyptixa** [comment]
Well, as you can see, I did have the patches, but never sent the PR. I'm not sure if they apply cleanly.
You can take mine and submit them yourself if you want to.
