### ISSUE TITLE
Do transcription.sh functionality using command line

### ISSUE THREAD

**Issue by samehkamaleldin** [marytts/marytts#446]
`transcription.sh` tool opens GUI tool window to do its functionality, how to do this functionality without using the GUI, only using command line.

Is this even possible ?

**Comment by psibre** [comment]
Perhaps the [LTSLexiconPOSBuilder](../blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-transcription/src/main/java/marytts/tools/transcription/LTSLexiconPOSBuilder.java) class is what you're looking for?

**Comment by psibre** [comment]
(assuming resolved)
