### ISSUE TITLE
Android usage

### ISSUE THREAD

**Issue by prechtelm** [marytts/marytts#450]
Hi,
I would like to use mary TTS in my android project (embedded). Does anyone have experience with the usage/import? I could't figure out how to set it up.

Best,
Michael

**Comment by wanwjing** [comment]
@prechtelm  you find out the solution ady ? please sharing with me. Thank you

**Comment by prechtelm** [comment]
@wanwjing I didn't find a solution... But I will let you know, if there is any success.

**Comment by wanwjing** [comment]
@prechtelm  you may try to use it. same as tts open source. I am testing on this open source. 
http://www.festvox.org/flite/

**Comment by AstonBraham** [comment]
HI @prechtelm ! Please, have you been able to implement it ?

**Comment by Munzey** [comment]
firstly I would start by downloading the latest marytts runtime package from [here](http://marytts.github.io/download/index.html) to get an idea of what modules are necessary. I would then spend some time exploring the codebase to really understand how marytts processes an input starting with how mary starts up a [server](https://github.com/marytts/marytts/blob/master/marytts-runtime/src/main/java/marytts/server/Mary.java). Once you understand this it should be simple enough to import what you need and start up an instance using  [LocalMaryInterface.java](https://github.com/marytts/marytts/blob/master/marytts-runtime/src/main/java/marytts/LocalMaryInterface.java). How you install voices is up to you.

**On a side note**: this isn't a marytts code issue and should really be discussed via the [mary mailing list](http://marytts.github.io/mail-lists.html)

**Comment by NeptunSun** [comment]
Need spend a lot of time to fix code for android. Start with LocalMaryInterface.java. delete some plugins and change some structures. and also needed add different library to fix mary code for android. also need get source code of jar files which added like library and fixed it. And at last i want to say thank mary team which written such system.

**Comment by NeptunSun** [comment]
yes. I took the source code from here and spent 2 month to run mary tts in android app and  at last i received.   but  I fixed really a lot of codes. i say real thank that you have written such tool.  But i didn't change data model mary.  after make good lib I can shared source code.

**Comment by wanwjing** [comment]
@NeptunSun can you sharing your code or how to do it on localmaryinterface.java ? thanks

**Comment by NeptunSun** [comment]
/**
 * Copyright 2011 DFKI GmbH.
 * All Rights Reserved.  Use is subject to license terms.
 * <p/>
 * This file is part of MARY TTS.
 * <p/>
 * MARY TTS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 * <p/>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package marytts;

import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import lib.sound.sampled.AudioFileFormat;
import lib.sound.sampled.AudioFormat;
import lib.sound.sampled.AudioInputStream;
import lib.sound.sampled.AudioSystem;
import marytts.config.LanguageConfig;
import marytts.config.MaryConfig;
import marytts.datatypes.MaryData;
import marytts.datatypes.MaryDataType;
import marytts.exceptions.MaryConfigurationException;
import marytts.exceptions.SynthesisException;
import marytts.modules.synthesis.Voice;
import marytts.server.Request;
import marytts.util.MaryRuntimeUtils;
import mf.org.w3c.dom.Document;

/**
 * This class and its subclasses are intended to grow into a simple-to-use, unified interface for both the local MARY server and a MARY client.
 *
 * @author marc
 */
public class LocalMaryInterface implements MaryInterface {

    private MaryDataType inputType;
    private MaryDataType outputType;
    private Locale locale;
    private Voice voice;
    private AudioFileFormat audioFileFormat;
    private String effects;
    private String style;
    private String outputTypeParams;
    private boolean isStreaming;


    public LocalMaryInterface() throws MaryConfigurationException {
        try {
            MaryRuntimeUtils.ensureMaryStarted();
        } catch (Exception e) {
            throw new MaryConfigurationException("Cannot start MARY server", e);
        }

        init();
    }

    protected void init() {
        setReasonableDefaults();
    }

    protected void setReasonableDefaults() {
        inputType = MaryDataType.TEXT;
        outputType = MaryDataType.AUDIO;
        locale = new Locale("en");
        voice = Voice.getDefaultVoice(locale);
        setAudioFileFormatForVoice();
        effects = null;
        style = null;
        outputTypeParams = null;
        isStreaming = false;

    }

    private void setAudioFileFormatForVoice() {
        if (voice != null) {
            AudioFormat af = voice.dbAudioFormat();
            audioFileFormat = new AudioFileFormat(AudioFileFormat.Type.WAVE, af, AudioSystem.NOT_SPECIFIED);
        } else {
            audioFileFormat = null;
        }
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#getInputType()
     */
    @Override
    public String getInputType() {
        return inputType.name();
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#setInputType(java.lang.String)
     */
    @Override
    public void setInputType(String newInputType) throws IllegalArgumentException {
        inputType = MaryDataType.get(newInputType);
        if (inputType == null) {
            throw new IllegalArgumentException("No such type: " + newInputType);
        } else if (!inputType.isInputType()) {
            throw new IllegalArgumentException("Not an input type: " + newInputType);
        }
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#getOutputType()
     */
    @Override
    public String getOutputType() {
        return outputType.name();
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#setOutputType(java.lang.String)
     */
    @Override
    public void setOutputType(String newOutputType) throws IllegalArgumentException {
        outputType = MaryDataType.get(newOutputType);
        if (outputType == null) {
            throw new IllegalArgumentException("No such type: " + newOutputType);
        } else if (!outputType.isOutputType()) {
            throw new IllegalArgumentException("Not an output type: " + newOutputType);
        }
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#getLocale()
     */
    @Override
    public Locale getLocale() {
        return locale;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#setLocale(java.util.Locale)
     */
    @Override
    public void setLocale(Locale newLocale) throws IllegalArgumentException {
        if (MaryConfig.getLanguageConfig(newLocale) == null) {
            throw new IllegalArgumentException("Unsupported locale: " + newLocale);
        }
        locale = newLocale;
        voice = Voice.getDefaultVoice(locale);
        setAudioFileFormatForVoice();
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#getVoice()
     */
    @Override
    public String getVoice() {
        if (voice == null) {
            return null;
        }
        return voice.getName();
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#setVoice(java.lang.String)
     */
    @Override
    public void setVoice(String voiceName) throws IllegalArgumentException {
        voice = Voice.getVoice(voiceName);
        if (voice == null) {
            throw new IllegalArgumentException("No such voice: " + voiceName);
        }
        locale = voice.getLocale();
        setAudioFileFormatForVoice();
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#getAudioEffects()
     */
    @Override
    public String getAudioEffects() {
        return effects;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#setAudioEffects(java.lang.String)
     */
    @Override
    public void setAudioEffects(String audioEffects) {
        effects = audioEffects;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#getStyle()
     */
    @Override
    public String getStyle() {
        return style;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#setStyle(java.lang.String)
     */
    @Override
    public void setStyle(String newStyle) {
        style = newStyle;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#getOutputTypeParams()
     */
    @Override
    public String getOutputTypeParams() {
        return outputTypeParams;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#setOutputTypeParams(java.lang.String)
     */
    @Override
    public void setOutputTypeParams(String params) {
        this.outputTypeParams = params;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#isStreamingAudio()
     */
    @Override
    public boolean isStreamingAudio() {
        return isStreaming;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#setStreamingAudio(boolean)
     */
    @Override
    public void setStreamingAudio(boolean newIsStreaming) {
        isStreaming = newIsStreaming;
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#generateText(java.lang.String)
     */
    @Override
    public String generateText(String text) throws SynthesisException {
        verifyInputTypeIsText();
        verifyOutputTypeIsText();
        MaryData in = getMaryDataFromText(text);
        MaryData out = process(in);
        return out.getPlainText();
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#generateText(org.w3c.dom.Document)
     */
    @Override
    public String generateText(Document doc) throws SynthesisException {
        verifyInputTypeIsXML();
        verifyOutputTypeIsText();
        MaryData in = getMaryDataFromXML(doc);
        MaryData out = process(in);
        return out.getPlainText();
    }


    /* (non-Javadoc)
     * @see marytts.MaryInterface#generateXML(java.lang.String)
     */
    @Override
    public Document generateXML(String text) throws SynthesisException {
        verifyInputTypeIsText();
        verifyOutputTypeIsXML();
        MaryData in = getMaryDataFromText(text);
        MaryData out = process(in);
        return out.getDocument();
    }


    /* (non-Javadoc)
     * @see marytts.MaryInterface#generateXML(org.w3c.dom.Document)
     */
    @Override
    public Document generateXML(Document doc) throws SynthesisException {
        verifyInputTypeIsXML();
        verifyOutputTypeIsXML();
        MaryData in = getMaryDataFromXML(doc);
        MaryData out = process(in);
        return out.getDocument();
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#generateAudio(java.lang.String)
     */
    @Override
    public AudioInputStream generateAudio(String text) throws SynthesisException {
        verifyInputTypeIsText();
        verifyOutputTypeIsAudio();
        verifyVoiceIsAvailableForLocale();
        MaryData in = getMaryDataFromText(text);
        MaryData out = process(in);
        return out.getAudio();
    }

    /* (non-Javadoc)
     * @see marytts.MaryInterface#generateAudio(org.w3c.dom.Document)
     */
    @Override
    public AudioInputStream generateAudio(Document doc) throws SynthesisException {
        verifyInputTypeIsXML();
        verifyOutputTypeIsAudio();
        verifyVoiceIsAvailableForLocale();
        MaryData in = getMaryDataFromXML(doc);
        MaryData out = process(in);
        return out.getAudio();
    }

    private void verifyOutputTypeIsXML() {
        if (!outputType.isXMLType()) {
            throw new IllegalArgumentException("Cannot provide XML output for non-XML-based output type " + outputType);
        }
    }

    private void verifyInputTypeIsXML() {
        if (!inputType.isXMLType()) {
            throw new IllegalArgumentException("Cannot provide XML input for non-XML-based input type " + inputType);
        }
    }

    private void verifyInputTypeIsText() {
        if (inputType.isXMLType()) {
            throw new IllegalArgumentException("Cannot provide plain-text input for XML-based input type " + inputType);
        }
    }

    private void verifyOutputTypeIsAudio() {
        if (!outputType.equals(MaryDataType.AUDIO)) {
            throw new IllegalArgumentException("Cannot provide audio output for non-audio output type " + outputType);
        }
    }

    private void verifyOutputTypeIsText() {
        if (outputType.isXMLType() || !outputType.isTextType()) {
            throw new IllegalArgumentException("Cannot provide text output for non-text output type " + outputType);
        }
    }

    /**
     * Synthesis will fail if {@link MaryDataType#AUDIO AUDIO} is requested but no voice is available for the requested Locale.
     * Moreover, the {@linkplain #audioFileFormat} will be null because {@linkplain #setAudioFileFormatForVoice()} silently
     * ignores if {@linkplain #voice} is null.
     *
     * @throws IllegalArgumentException which should actually be a {@link MaryConfigurationException}.
     */
    private void verifyVoiceIsAvailableForLocale() {
        if (outputType.equals(MaryDataType.AUDIO)) {
            if (getAvailableVoices(locale).isEmpty()) {
                throw new IllegalArgumentException("No voice is available for Locale: " + locale);
            }
        }
    }

    private MaryData getMaryDataFromText(String text) throws SynthesisException {
        MaryData in = new MaryData(inputType, locale);
        try {
            in.setData(text);
        } catch (Exception ioe) {
            throw new SynthesisException(ioe);
        }
        return in;
    }

    private MaryData getMaryDataFromXML(Document doc) throws SynthesisException {
        MaryData in = new MaryData(inputType, locale);
        try {
            in.setDocument(doc);
        } catch (Exception ioe) {
            throw new SynthesisException(ioe);
        }
        return in;
    }

    private MaryData process(MaryData in) throws SynthesisException {
        Request r = new Request(inputType, outputType, locale, voice, effects, style, 1, audioFileFormat, isStreaming, outputTypeParams);
        r.setInputData(in);
        try {
            r.process();
        } catch (Exception e) {
            throw new SynthesisException("cannot process", e);
        }
        return r.getOutputData();
    }

    @Override
    public Set<String> getAvailableVoices() {
        Set<String> voices = new HashSet<String>();
        for (Voice v : Voice.getAvailableVoices()) {
            voices.add(v.getName());
        }
        return voices;
    }

    @Override
    public Set<String> getAvailableVoices(Locale aLocale) {
        Set<String> voices = new HashSet<String>();
        for (Voice v : Voice.getAvailableVoices(aLocale)) {
            voices.add(v.getName());
        }
        return voices;
    }

    @Override
    public Set<Locale> getAvailableLocales() {
        Set<Locale> locales = new HashSet<Locale>();
        for (LanguageConfig lc : MaryConfig.getLanguageConfigs()) {
            locales.addAll(lc.getLocales());
        }
        return locales;
    }

    @Override
    public Set<String> getAvailableInputTypes() {
        return new HashSet<String>(MaryDataType.getInputTypeStrings());
    }

    @Override
    public Set<String> getAvailableOutputTypes() {
        return new HashSet<String>(MaryDataType.getOutputTypeStrings());
    }

    @Override
    public boolean isTextType(String dataType) {
        MaryDataType d = MaryDataType.get(dataType);
        if (d != null) {
            return d.isTextType() && !d.isXMLType();
        }
        return false;
    }

    @Override
    public boolean isXMLType(String dataType) {
        MaryDataType d = MaryDataType.get(dataType);
        if (d != null) {
            return d.isXMLType();
        }
        return false;
    }

    @Override
    public boolean isAudioType(String dataType) {
        return "AUDIO".equals(dataType);
    }
}

**Comment by jogrimst** [comment]
@NeptunSun Is your Android code available as open source?

**Comment by Kmeo** [comment]
@NeptunSun I'm also interrested. Please share your code if you can.

**Comment by tusharmakkar08** [comment]
@NeptunSun  Is your Android code available as open source? Please share your code.

**Comment by danilosoba** [comment]
@NeptunSun Is your Android code available as open source?

**Comment by mokgonyanetb** [comment]
Is your Android code available as open source? Please share your code. It would really help with my honours research project

**Comment by prechtelm** [comment]
Did somebody make any progress in implementing it in android?
@NeptunSun

**Comment by jogrimst** [comment]
@prechtelm @wanwjing @AstonBraham @Munzey @Kmeo @tusharmakkar08 @danilosoba @mokgonyanetb 

There seems to be a high interest for adding Android support to MaryTTS. Would all of you be interested in collaborating on creating a new GitHub project for this purpose?

**Comment by tusharmakkar08** [comment]
@jogrimst 👍

**Comment by jogrimst** [comment]
I created this fork: https://github.com/literacyapp-org/marytts-android

We need to plan how to structure the Android-specific code.

Can you help add issues that will be necessary at https://github.com/literacyapp-org/marytts-android/issues ?

**Comment by psibre** [comment]
@jogrimst Just to chime in, here's what I told the guys over at [AndroidMaryTTS](/AndroidMaryTTS/AndroidMaryTTS), and I think the same applies to you:
> I can see that you forked marytts directly as "marytts-android-app" without modification. From a software engineering perspective, I would suggest that you keep your app code separate from the core marytts repo.
> The idea is that your app code pulls in MaryTTS dependencies, but it doesn't actually contain all of the code, most of which would be useless for the app.

**Comment by farizaghayev** [comment]
He have already start to integrate MaryTTS code to android and have already first version. we tested this with android lollipop 5.1 version without any problem. But the audio is lagging with the version marshmallow. Can test this from here : https://github.com/AndroidMaryTTS

**Comment by jogrimst** [comment]
I'm getting `W/AudioTrack: releaseBuffer() track 0xf5b74448 disabled due to previous underrun, restarting` on Android 6.

Copied from https://developer.android.com/reference/android/media/AudioTrack.html#getUnderrunCount() which was added in API level 24:

> int getUnderrunCount ()

> Returns the number of underrun occurrences in the application-level write buffer since the AudioTrack was created. An underrun occurs if the application does not write audio data quickly enough, causing the buffer to underflow and a potential audio glitch or pop.

> Underruns are less likely when buffer sizes are large. It may be possible to eliminate underruns by recreating the AudioTrack with a larger buffer. Or by using setBufferSizeInFrames(int) to dynamically increase the effective size of the buffer.

**Comment by farizaghayev** [comment]
@jogrimst @psibre This **AudioTrack** warn means that  tts audio data not fast enough generating. The error is generated when the buffer is not completely filled with data on time. Problem is not so simple to solve quickly. 

In this class **ProducingDoubleDataSource**  **MaryTTS** team used **ArrayBlockingQueue<Double>(1024)** to put and take generated data. After a long time monitor can say that putOneDataPoint wait a lot to put new data. 

Maybe put function of this blockingQueue wait a lot therefore this queue is full of or maybe take function is running. these two function is executing by different thread.  In final we think that there is something wrong in this producer consumer architect. maybe to create a main BlockingQueue reference this for consumer and producers. actually producer and consumer is same class   ProducingDoubleDataSource.  need to separate this class maybe as consumer and producer.Should fixed a lot of code with starting to delete extend **BufferedDoubleDataSource** in ProducingDoubleDataSource class. this is our first version to fixe this bug. 

Our second option is that generating data for runtime processing not keeping in ram and that is why taking long time **htsMLSAVocoder**  function in class **HTSVocoder**. Should test these two options

**Comment by jogrimst** [comment]
@farizaghayev Maybe increasing from 1024 to 8192 like the buffer size value used in [BlockingAudioTrack.java](https://android.googlesource.com/platform/frameworks/base/+/c80f952/core/java/android/speech/tts/BlockingAudioTrack.java) might help?

**Comment by farizaghayev** [comment]
@jogrimst  No, problem is not in the playing part therefore not important using MediaPlayer or AudioTrack or BlockingAudioTrack.   Should speed up the generating process as i wrote above . 

1. Change the architecture as **producer-consumer**. Actually producer consumer are same class "ProducingDoubleDataSource " and one **blockingQueue** without reference. 

2.  **htsMLSAVocoder** function taking long time in class HTSVocoder with marshmallow version. Don;t know why? MAybe generating data for runtime processing not keeping in ram. etc.

**Comment by frehman15** [comment]
@farizaghayev @jo-elimuai  @psibre   can anybody guide me how can i add other voice in android marytts e.g urdu need this urgently.Thanks in anticipation

**Comment by adityagoel19** [comment]
@jo-elimuai have you guys found a solution to the audio underrun?
