### ISSUE TITLE
Build in Android

### ISSUE THREAD

**Issue by wanwjing** [marytts/marytts#451]
anyone can sharing the idea how to implement marytts in android? thank for sharing

**Comment by AstonBraham** [comment]
HI @wanwjing ! I also need this. Have you been able to implement it ?

**Comment by wanwjing** [comment]
@AstonBraham i doing a lot of research, but no solution. you maybe can try others?

**Comment by AstonBraham** [comment]
I have looked for Flite. There's already an android port but it seems way
more complex to create a new language|voice with it.

**Comment by wanwjing** [comment]
Actually what are you want to do on this open source?

**Comment by AstonBraham** [comment]
I want to create a language for my natal language. Can you help ? :-)

**Comment by seblemaguer** [comment]
see #450
