### ISSUE TITLE
marytts.exceptions.MaryConfigurationException: No such property: as_IN.allophoneset

### ISSUE THREAD

**Issue by Yamin372** [marytts/marytts#454]
![error](https://cloud.githubusercontent.com/assets/15828708/12273346/6bdba776-b98b-11e5-8ded-d943ab0fd764.jpeg)

**Comment by seblemaguer** [comment]
Hello,

apparently your configuration file is not correct. Can you copy the text of the stacktrace and you configuration file (instead of a screenshot) ?

**Comment by Yamin372** [comment]
Sir @seblemaguer , the problem is solved.There was a mistake in my config file.Thanks for your help.
Regards,
Yamin Alam
