### ISSUE TITLE
Exception in database selection step

### ISSUE THREAD

**Issue by Yamin372** [marytts/marytts#457]
/sampa/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_database_selector.sh wkdb.conf
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.91-b01, mixed mode)

Starting Database Selection...
Reading arguments ...
Current directory: /home/yamin/sampa/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin  MARY_BASE=/home/yamin/sampa/marytts-master/target/marytts-builder-5.2-SNAPSHOT
  locale : as
  mysqlHost : localhost
  mysqlUser : mary
  mysqlPasswd : wiki123
  mysqlDB : wiki
  selectedSentencesTable name: test
  tableDescription: Testing table for selected sentences. Wikipedia locale:  
  stop criterion : numSentences 90 simpleDiphones simpleProsody 
  logCoverageDevelopment
  verbose

Checking if there is [locale]_featureDefinition.txt in the current directory
Using as_featureDefinition.txt in current directory.

Checking if there is already a covDef.config in the current directory
Using covDef.config in current directory.
covDefConfigFileName = /home/yamin/sampa/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/covDef.config

Checking stop criterion:
Stop: num sentences 90
Stop: simpleDiphones
Stop: simpleProsody

Mysql driver loaded, set locale=as
Current selected sentences table name = as_test_selectedSentences
Mysql connection created successfully.

Loading feature definition...
TARGETFEATURES:3 =  phone next_phone selection_prosody
Getting a list of ids for all the sentences in the DB...
(if the number of sentences is large, this can take a while)

Will also load feature vectors into memory (increase memory if this fails)
1105 sentences to retrieve...

Initiating coverage...
TARGETFEATURES used:
  feature(0)=phone
  feature(1)=next_phone
  feature(2)=selection_prosody

Checking if as_test_selectedSentences already exist.
  TABLE = as_test_selectedSentences already exist. New selected sentences will be added to this table.
  A description for the table as_test_selectedSentences already exist in TABLE = tablesDescription.

Analysing feature vectors of 1105 sentences:
Exception in thread "main" java.lang.NullPointerException
    at marytts.tools.dbselection.CoverageDefinition.initialiseCoverage(CoverageDefinition.java:439)
    at marytts.tools.dbselection.DatabaseSelector.main2(DatabaseSelector.java:238)
    at marytts.tools.dbselection.DatabaseSelector.main(DatabaseSelector.java:113)

**Comment by Yamin372** [comment]
@psibre @Munzey @entenbein @sathishpc please help guys. I have been doing this for Assamese language.Please help.
Regards,
Yamin Alam

**Comment by Yamin372** [comment]
@psibre @sathishpc @cosmix @Munzey Help please.

**Comment by psibre** [comment]
The code there has been pretty much untouched for ten years. I'm afraid you're going to have to debug on your own, as I'm not familiar with the SQL-based new language stuff.
We do have plans to re-implement that functionality at some point, but for lack of resources, that's on the back burner for now.

**Comment by Rootex** [comment]
@attacomsian

**Comment by attacomsian** [comment]
@Rootex Thank you. I will look into it.

**Comment by BibekBazaz** [comment]
@attacomsian  Hello there, were you able to solve the problem above?? It seems I too have got stuck in the same problem for Hindi language. Please help.

**Comment by BibekBazaz** [comment]
This was solved by eliminating the sentences that were giving null values at the particular step.
I used a try catch and in the catch section i allowed to skip the sentences that were generating the error and continued executing for the other sentences.

**Comment by BaimAT** [comment]
@BibekBazaz could you elaborate more or give an example, please?

**Comment by BaimAT** [comment]
@BibekBazaz Thanks for the reply. I applied your code suggestion, but it seems all the selection gives out `java.lang.NullPointerException` and the `/current-dir/selected.log` were not produced possibly because there are no selected sentences? Did you experience this too before?

**Comment by MomnaSaeed** [comment]
@BibekBazaz
