### ISSUE TITLE
Tokens mistakenly POS-tagged as punctuation cause wrong boundary insertion

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#460]
Another side effect of the issue discussed in #309 is that non-punctuation tokens that are mistakenly part-of-speech-tagged as punctuation cause a boundary to be inserted at the INTONATION level where there shouldn't be a boundary. This can lead to random, unnatural pauses in the middle of sentences.

**Comment by Rootex** [comment]
@psibre I went through the last issue and the commits you made on them, it seems with the new procedure you wrote, there is no problem anymore of pos-tagging as punctuation. 

However i am not clear about boundary insertion, do you mean during the selection of speech sounds? If possible to have a little more information so i can try to figure out how to handle this.

**Comment by psibre** [comment]
@s9mmober Do you have an example handy where this happened?

**Comment by psibre** [comment]
@Rootex The problem in #309 was that the tokens marked as punctuation were being silently dropped from the pronunciation. However, *independently* the punctuation influences the prosody prediction and pause insertion, so that's another problem.
We could go back and use the approach from the solution #309 to actually *fix* the `pos` attribute when the OpenNLP POS tagger screws up.

**Comment by s9mmober** [comment]
Basically, the error occurs everywhere where a comma exists. One example sentence:
Her name was Duchess, but he often called her Pet. 
It give you the following POS for but. Every following tag is incorrect as well, since the pos is shifted:
<t g2p_method="lexicon" ph="' b V t" pos=",">
<t g2p_method="lexicon" ph="' h i" pos="CC">
...

**Comment by Rootex** [comment]
I check with your example, it seems the pos are being shifted when the sentence contains a `,` thus making all after the coma with wrong POS tag. I will look into it.

**Comment by Rootex** [comment]
@psibre Just to confirm if there is a latest upgrade on the server? Because i don't get this on mary server, only on local server?

**Comment by psibre** [comment]
The demo server at [mary.dfki.de](http://mary.dfki.de:59125/) is still running v5.1.1 at the moment, so it's more than likely that this issue was introduced as a side-effect of removing the FreeTTS dependencies in #228. I think you might be onto something regarding the apparent misalignment between tokens and POS tags.
@Rootex Could we perhaps write a unit test to isolate this phenomenon, so that we can confirm that it occurs systematically, and then fix it?

**Comment by Rootex** [comment]
@psibre yea sure we can do that.

**Comment by psibre** [comment]
Fixed by #517
