### ISSUE TITLE
convert a large number of txt files to audio

### ISSUE THREAD

**Issue by ducktil** [marytts/marytts#462]
Hi, anyone knows how can I batch convert text to speech (convert a large number of .txt files to audio ).  thanks in advance for any help.

**Comment by seblemaguer** [comment]
Hello,

assuming they are on the same language, you can process in this way.

1. load the interface with something like that
2. and then loop on the text files to synthesize them

For that, I suggest you to have a look at this file: https://github.com/marytts/marytts-txt2wav/blob/maven/src/main/java/de/dfki/mary/Txt2Wav.java

and to adapt it to your need

**Comment by psibre** [comment]
You can also start your `marytts-server` and then connect to it from your scripting language of choice, since all you need is to send an HTTP request and dump the response to a file, which of course you can do in a loop.

**Comment by qwertologe** [comment]
Hi ducktil,

if you use Linux, i would make a script using curl and a local mary server.
I need some details ...

- can i move the textfiles (write access)?
  - if not: details
- are the files all in one directory?
  - if not: details
- which audioformat do you want (ogg, mp3)?
- my preferred audio conversion tool would be sox
  - if not: details

**Comment by qwertologe** [comment]
anyway - here is a solution for Linux (wget, curl, sox and a running marytts-server is needed):

```
#!/bin/bash -eu
# txt2ogg
# - starts as many threads as cores are available
# - converts all textfiles in one directory to ogg-vorbis
# - builds the audio filenames according to the textfiles (x.txt->x.ogg)
# - renames textfiles during conversion to *.work
# - renames finished textfiles to *.done
# - comments successful conversion on stdout
# - comments failed conversion on stderr

textextension='txt'
audioformat='ogg'
lang='de'
maryserver='http://localhost:59125'
voice='dfki-pavoque-styles'

cores=`grep ^processor /proc/cpuinfo |wc -l`
curl_data="INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&AUDIO=WAVE_FILE&LOCALE=$lang&VOICE=$voice"                                                                                                  

fail() {
  echo "$*" >&2
  exit 1
}

txt2ogg() {
  for textfile in *.$textextension; do
    if mv "$textfile" "$textfile.work" 2>/dev/null; then
      audiofile="${textfile%%.$textextension}.$audioformat"
      if sox --no-show-progress <(curl --silent --get --data "$curl_data" --data-urlencode "INPUT_TEXT@$textfile.work" $maryserver/process) --type wav "$audiofile" 2>/dev/null; then
        echo "converted $textfile"
      else
        echo "failed $textfile" >&2
      fi
      mv "$textfile.work" "$textfile.done"
    fi
  done
}

wget $maryserver -o /dev/null || fail "marytts-server ($maryserver) not started"
cd "$1" || fail "folder '$1' not found or no access"

echo "`date` start"

for thread in `seq 1 $cores`; do
  txt2ogg &
done

wait

echo "`date` end"
```

**Comment by seblemaguer** [comment]
I will review it soon and see if we integrate that into https://github.com/marytts/marytts-txt2wav

**Comment by seblemaguer** [comment]
Thanks it is added here : https://github.com/marytts/marytts-txt2wav/tree/sh
