### ISSUE TITLE
Q: Skipping some processing steps

### ISSUE THREAD

**Issue by kingjr** [marytts/marytts#463]
Dear all,

I am just discovering your great package.

I'm trying to synthesize sentences devoid of any syntactic cues (for research purposes): i.e. no intonation, prosody, pause after comas and dots etc; just a long sequence of regularly interleaved phonemes. 

I was wondering whether there was a way to skip some of the [processing steps](http://mary.dfki.de/documentation/module-architecture.html) to generate such sounds.

In any case, thanks a lot for this rep.

**Comment by entenbein** [comment]
Which voice do you want to use to synthesize those sentences? A pre-build one?

**Comment by kingjr** [comment]
Yes, ideally `dfki-preudence en_GB female`. Would such non-conventional synthesis only work with some types of voices?

**Comment by psibre** [comment]
Why don't you just use diphone synthesis ([MBROLA](http://tcts.fpms.ac.be/synthesis/mbrola.html)) or formant synthesis (e.g., [espeak](http://espeak.sourceforge.net/)) for this?
You *could* use a unit-selection (`dfki-prudence`) or statistical parametric (`dfki-prudence-hsmm`) voice for this and manually enforce your prosody by requesting constant values for the `d` and `f0` attributes in the MaryXML, but it would sound... I don't have a word for it.

**Comment by kingjr** [comment]
> Why don't you just use diphone synthesis (MBROLA) or formant synthesis (e.g., espeak) for this?

I have indeed used epseak so far; but it seemed easier with maryttx to i) control specific features (e.g. prosody) ii) get the precise time information about each phoneme and iii) it integrates multiple features such as word to phoneme translation within a consistent API.

> You could use a unit-selection (dfki-prudence) or statistical parametric (dfki-prudence-hsmm) voice for this and manually enforce your prosody by requesting constant values for the d and f0 attributes in the MaryXML, but it would sound... I don't have a word for it.

Yes I can imaging it'll sound pretty bad. Any chance you could make a toy example? I'm trying to write one from the [documentation](http://mary.dfki.de/documentation/maryxml/index.html), unfortunately without any success.. 

Thanks!

**Comment by psibre** [comment]
You'll want to convert from TEXT to ACOUSTPARAMS, then manually edit the resulting MaryXML, and then paste that back as the RAWMARYXML input.
If that works, automate it -- which you could do with anything that can send HTTP requests and manipulate XML.

**Comment by kingjr** [comment]
Thanks, it works, I just had to set the input to `ACOUSTPARAMS` and not `RAWMARYXML` to generate the `AUDIO`.

**Comment by psibre** [comment]
@kingjr right, sorry.
Glad it's working for you.
