### ISSUE TITLE
How to add new voice language ?

### ISSUE THREAD

**Issue by reutorah** [marytts/marytts#477]
Hi,

I have 3 questions.

1) how do i install marry tts on website ? what are the requirements ?

2) how do i add new voice languages like adding urdu voice language or hindi voice language ?

3) how do i create my own voice synthesis recognition into marrytts, i mean is there a way i can add my own voice into text to speech which will convert any text using my voice ?

Thanks for answering.

Ahmed.

**Comment by psibre** [comment]
In the future, please open a separate issue for each topic.
Having said that, the answers to your questions are documented in the wiki:
> 1) how do i install marry tts on website ? what are the requirements ?

[Local MaryTTS Server Installation](../wiki/Local-MaryTTS-Server-Installation)

> 2) how do i add new voice languages like adding urdu voice language or hindi voice language ?

[New Language Support](../wiki/New-Language-Support)

> 3) how do i create my own voice synthesis recognition into marrytts, i mean is there a way i can add my own voice into text to speech which will convert any text using my voice ?

[VoiceImportToolsTutorial](../wiki/VoiceImportToolsTutorial)

**Comment by FrontierDK** [comment]
Any chance these guides could be done for Microsoft Windows as well? When the voices have been created, both Windows and Linux users will bennefit from them.

**Comment by psibre** [comment]
@FrontierDK If you happen to have a Windows server, nothing prevents you from running MaryTTS on it.

The lexicon compiler and voicebuilding is *mostly* compatible with Windows as well, but a few external tools need to be installed, including SoX and Edinburgh Speech Tools. If you have those working, you should be able to build new language components and voices on Windows as well.

But seriously, with so many ways to run Linux on Windows, why would you want to waste your time trying to get it working natively?
