### ISSUE TITLE
unable to add new language

### ISSUE THREAD

**Issue by imty1000** [marytts/marytts#478]
Dear, i was trying to add a new language Bengali with your system. However, i have tried everything that is said in the documentation but could not start working. as i am pretty new to this system, is there any video that describes the steps adding new language. Please it would be really helpful.

**Comment by seblemaguer** [comment]
Hello,

which error do you have ?

**Comment by imty1000** [comment]
Thank you, i have downloaded the bnwiki directly from wikipedia. but now its not splitting.

**Comment by imty1000** [comment]
Can any one help please?

**Comment by aitorme** [comment]
hi @imty1000 , unfortunately that does not tell us much about the error, could you please paste all the information that the terminal is showing, or activate the logger and paste the log file? That could give us a better idea of what is exactly going wrong. Thanks

**Comment by imty1000** [comment]
Thank you for your reply, this is the link of the snapshot of cmd please help me.
[http://sigmaitinstitute.com/f/error.png](url)

**Comment by seblemaguer** [comment]
Hello, the snapshot of your command is not useful. Can you just past the command you used in a text format?

**Comment by imty1000** [comment]
The commands that i used are:
After installing marytts using "mvn install" at F:\imtiaz\system\tts\mary\marytts-master\marytts-master, i created a folder "marytts" at F:\imtiaz\system\tts\mary\marytts-master
then run the following commands at F:\imtiaz\system\tts\mary\marytts-master\marytts\
1. wkdb_setup.sh ./ bn bn
this worked and created wkdb.conf in my directory
2. wkdb_download_wikidump.sh wkdb.conf 
this worked and downloaded the bnwiki-latest-pages-articles.xml.bz2 and extracted
3. now when i give this wkdb_split_dump.sh wkdb.conf  the cmd shows
Error: could not find or load main class marytts.tools.dbselection.WikipediaDumpSplitter
and closes immanently.

**Comment by psibre** [comment]
Unfortunately, the shell script is written in such a way that it cannot be expected to work under Windows. I recommend that you follow the workflow on a linux machine (even a virtual machine should do).

Alternatively it might be possible to mimic the intended functionality using PowerShell or something else, but I'm afraid that's outside the support we can provide.

However, if you manage to get it working under Windows, please do feel free to share your solution!

**Comment by imty1000** [comment]
Thank you all, i have figured it out to run in windows. just changed the shell script commands and now it works.

**Comment by Nandutu** [comment]
Hello imty1000, I have got the same error you got a solution. Kindly could you give in more details on how you overcame it, which areas you changed in the shell script.
I will be grateful.

**Comment by Avinash01111992** [comment]
@imty1000  Hello imty i'm getting the same error and i'm running on Linux 
This is my error 
avinash@lb:~/lb-work/text-to-speach-engine/marytts/marytts-assembly/assembly-builder/src/builder/bin$ sudo ./wkdb_cleaning_up.sh /home/avinash/wiki_data/wkdb.conf

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Error: Could not find or load main class marytts.tools.dbselection.WikipediaProcessor

Please help me out

**Comment by psibre** [comment]
@Avinash01111992 You can't run the script from the src folder -- you need to build MaryTTS first, then run it from the target folder.

**Comment by Avinash01111992** [comment]
@psibre Thanks for your response. I'm not able build the MaryTTS using - 
**mvn install** Command 
and i'm facing the issue 
**Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test)**
and i couldn't able produce requires scripts in target folder.

**Comment by psibre** [comment]
@Avinash01111992 please open a new issue about your problem running `mvn install`, and don't forget to provide the full error message.

**Comment by psibre** [comment]
Incidentally, there's a new paper at [arXiv:1712.04787](https://arxiv.org/abs/1712.04787) outlining the workflow for new language component/voice creation in MaryTTS 6. You read it here first. =)
