### ISSUE TITLE
New language phonems help

### ISSUE THREAD

**Issue by imty1000** [marytts/marytts#479]
Hello, can anyone please explain the following parameters a little more, i have found some one is explaining some of them but that did not help that much as i have looked the IPA of my language Bengali. If there is any documentation or instruction of how to use http://mary.opendfki.de/wiki/TranscriptionTool/allophones_en-US.xml for my language.
 parameters are
vlng, vheight, vfront, vrnd, ctype, cplace, cvox
What do i put in ph="A", my language letters? or the letter that represent my language phonemes?

**Comment by imty1000** [comment]
Can anybody please help me?

**Comment by nshmyrev** [comment]
You need to describe the phoneset you are going to use. For every phone in your phoneset you need to describe its properties. For example, the phone "A", is it short or long. You set vlng (vovel length) to either s(short) or l(long). For your experiments I recommend you to use the following Indic phoneset from festvox package:

```
   ;; vowel length: short long dipthong schwa
   (vlng s l d a 0)
   ;; vowel height: high mid low
   (vheight 1 2 3 0 -)
   ;; vowel frontness: front mid back
   (vfront 1 2 3 0 -)
   ;; lip rounding
   (vrnd + - 0)
   ;; consonant type: stop fricative affricative nasal liquid approximant
   (ctype s f a n l r 0)
   ;; place of articulation: labial alveolar palatal
   ;; labio-dental dental velar glottal
   (cplace l a p b d v g 0)
   ;; consonant voicing
   (cvox + - 0)
   (asp  + - 0)
   (nuk + - 0)


   ;; Vowels
   (      A   -   +   s   2   2   -   0   0   0   -   0   ) ; अ
   (     A:   -   +   l   3   2   -   0   0   0   -   0   ) ; आ
   (      i   -   +   s   1   1   -   0   0   0   -   0   ) ; इ
   (     i:   -   +   l   1   1   -   0   0   0   -   0   ) ; ई
   (      u   -   +   s   1   3   +   0   0   0   -   0   ) ; उ
   (     u:   -   +   l   1   3   +   0   0   0   -   0   ) ; ऊ
   (    9r=   -   +   s   1   3   -   0   0   0   -   0   ) ; ऋ
   (    lr=   -   +   d   2   3   -   0   0   0   -   0   ) ; ऌ

   (      E   -   +   a   2   1   -   0   0   0   -   0   ) ; the schwa in hindi worde rEhna
   (      e   -   +   s   2   1   -   0   0   0   -   0   ) ; ए
   (     e:   -   +   l   2   1   -   0   0   0   -   0   ) ; ए long
   (     aI   -   +   d   2   1   -   0   0   0   -   0   ) ; ऐ
   (      o   -   +   s   2   3   +   0   0   0   -   0   ) ; ओ
   (     o:   -   +   l   2   3   +   0   0   0   -   0   ) ; ओ long
   (     aU   -   +   d   1   3   +   0   0   0   -   0   ) ; औ
   (      M   -   -   0   0   0   0   0   0   0   -   0   ) ; अं
   (      h   -   -   0   0   0   0   f   v   -   +   -   ) ; अः
   (     ay   -   +   s   2   2   -   0   0   0   -   0   ) ; अॅ
   (     ow   -   +   l   3   3   +   0   0   0   -   0   ) ; ऑ

   ;; Consonants
   ;; Velar
   (      k   -   -   0   0   0   0   s   v   -   -   -   ) ; क
   (     kh   -   -   0   0   0   0   s   v   -   +   -   ) ; ख
   (      g   -   -   0   0   0   0   s   v   +   -   -   ) ; ग
   (     gh   -   -   0   0   0   0   s   v   +   +   -   ) ; घ
   (      N   -   -   0   0   0   0   n   v   +   -   -   ) ; ङ

   ;; Palatal
   (      c   -   -   0   0   0   0   a   p   -   -   -   ) ; च
   (     ch   -   -   0   0   0   0   a   p   -   +   -   ) ; छ
   (      J   -   -   0   0   0   0   a   p   +   -   -   ) ; ज
   (     Jh   -   -   0   0   0   0   a   p   +   +   -   ) ; झ
   (     n~   -   -   0   0   0   0   n   p   +   -   -   ) ; ञ

   ;; Retroflex
   (     tr   -   -   0   0   0   0   s   a   -   -   -   ) ; ट
   (     tR   -   -   0   0   0   0   s   a   -   +   -   ) ; ठ
   (     dr   -   -   0   0   0   0   s   a   +   -   -   ) ; ड
   (     dR   -   -   0   0   0   0   s   a   +   +   -   ) ; ढ
   (     nr   -   -   0   0   0   0   n   a   +   -   -   ) ; ण
   
   ;; Dental
   (     tB   -   -   0   0   0   0   s   d   -   -   -   ) ; त
   (    tBh   -   -   0   0   0   0   s   d   -   +   -   ) ; थ
   (     dB   -   -   0   0   0   0   s   d   +   -   -   ) ; द
   (    dBh   -   -   0   0   0   0   s   d   +   +   -   ) ; ध
   (     nB   -   -   0   0   0   0   n   d   +   -   -   ) ; न

   ;; Labial
   (      p   -   -   0   0   0   0   s   l   -   -   -   ) ; प
   (     ph   -   -   0   0   0   0   s   l   -   +   -   ) ; फ
   (      b   -   -   0   0   0   0   s   l   +   -   -   ) ; ब
   (     bh   -   -   0   0   0   0   s   l   +   +   -   ) ; भ
   (      m   -   -   0   0   0   0   n   l   +   -   -   ) ; म

   ;; Approximants
   (      j   -   -   0   0   0   0   r   p   +   -   -   ) ; य
   (     9r   -   -   0   0   0   0   r   a   +   -   -   ) ; र
   (      l   -   -   0   0   0   0   r   d   +   -   -   ) ; ल
   (     lr   -   -   0   0   0   0   r   a   +   -   -   ) ; ळ
   (      v   -   -   0   0   0   0   r   l   +   -   -   ) ; व

   ;; Fricatives
   (     c}   -   -   0   0   0   0   f   p   -   +   -   ) ; श
   (     sr   -   -   0   0   0   0   f   a   -   +   -   ) ; ष
   (      s   -   -   0   0   0   0   f   d   -   +   -   ) ; स
   (     hv   -   -   0   0   0   0   f   v   +   +   -   ) ; ह
	  
   ;; More consonants
   (      q   -   -   0   0   0   0   s   g   -   -   +   ) ; क़
   (      x   -   -   0   0   0   0   s   g   -   +   +   ) ; ख़
   (      G   -   -   0   0   0   0   s   g   +   -   +   ) ; ग़
   (      z   -   -   0   0   0   0   f   d   +   -   +   ) ; ज़
   (     rr   -   -   0   0   0   0   s   a   +   -   +   ) ; ड़ 
   (    rrh   -   -   0   0   0   0   s   a   +   +   +   ) ; ढ़ 
   (      f   -   -   0   0   0   0   f   b   -   -   +   ) ; फ़ 
   (      nX   -   -   0   0   0   0   n   v   +   -   -   )


   ;; Nasalized vowels
   (  Anas    -   +   s   2   2   -   0   0   0   -   0   ) ; अ
   ( A:nas    -   +   l   3   2   -   0   0   0   -   0   ) ; आ
   (  inas    -   +   s   1   1   -   0   0   0   -   0   ) ; इ
   ( i:nas    -   +   l   1   1   -   0   0   0   -   0   ) ; ई
   (  unas    -   +   s   1   3   +   0   0   0   -   0   ) ; उ
   ( u:nas    -   +   l   1   3   +   0   0   0   -   0   ) ; ऊ
   (  enas    -   +   s   2   1   -   0   0   0   -   0   ) ; ए
   ( e:nas    -   +   l   2   1   -   0   0   0   -   0   ) ; ए long
   ( aInas    -   +   d   2   1   -   0   0   0   -   0   ) ; ऐ
   (  onas    -   +   s   2   3   +   0   0   0   -   0   ) ; ओ
   ( o:nas    -   +   l   2   3   +   0   0   0   -   0   ) ; ओ long
   ( aUnas    -   +   d   1   3   +   0   0   0   -   0   ) ; औ
   ( aynas    -   +   s   2   2   -   0   0   0   -   0   ) ; अॅ
   ( ownas    -   +   s   3   3   +   0   0   0   -   0   ) ; ऑ
```

**Comment by nshmyrev** [comment]
You can also review the publications about Indic festvox here:

http://ravi.iiit.ac.in/~speech/publications/C58.pdf

**Comment by nshmyrev** [comment]
I also recommend you to download existing Bengali database to import into OpenMary, that will save you a lot of time on prompts design:

http://festvox.org/databases/iiit_voices/iiit_ben_ant.tar.gz

**Comment by imty1000** [comment]
Thank you so much.. that was really helpful. i am working on it now and will share the result with you.

**Comment by imty1000** [comment]
Hello, i have made the allphone.xml for Bengali but getting this error.
alignment ... 
iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
alignment completed.
training ... 
      Training decision tree for: এ
      Training decision tree for: ব
      Training decision tree for: ং
java.lang.RuntimeException: couldn't train decisiontree using weka: 
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:240)
	at marytts.tools.transcription.TranscriptionTable.trainLTS(TranscriptionTable.java:178)
	at marytts.tools.transcription.TranscriptionTable.trainPredict(TranscriptionTable.java:212)
	at marytts.tools.transcription.TranscriptionGUI.trainPredictActionPerformed(TranscriptionGUI.java:816)
	at marytts.tools.transcription.TranscriptionGUI.access$8(TranscriptionGUI.java:810)
	at marytts.tools.transcription.TranscriptionGUI$8.actionPerformed(TranscriptionGUI.java:372)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.j48.C45PruneableClassifierTreeWithUnary: Cannot handle multi-valued nominal class!
	at weka.core.Capabilities.test(Capabilities.java:940)
	at weka.core.Capabilities.test(Capabilities.java:1109)
	at weka.core.Capabilities.test(Capabilities.java:1022)
	at weka.core.Capabilities.testWithFail(Capabilities.java:1301)
	at weka.classifiers.trees.j48.C45PruneableClassifierTree.buildClassifier(C45PruneableClassifierTree.java:120)
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:238)
	... 41 more



My allphone.xml is

<allophones name="sampa" xml:lang="bn"
		features="vlng vheight vfront vrnd ctype cplace cvox">
	<silence ph="_"/>

	<vowel ph="a" vlng="s" vheight="2" vfront="2" vrnd="-"/>
	<vowel ph="aa" vlng="l" vheight="3" vfront="2" vrnd="-"/>
	<vowel ph="i" vlng="s" vheight="1" vfront="1" vrnd="-"/>
	<vowel ph="ii" vlng="l" vheight="1" vfront="1" vrnd="-"/>

	<vowel ph="u" vlng="s" vheight="1" vfront="3" vrnd="+"/>
	<vowel ph="uu" vlng="l" vheight="1" vfront="3" vrnd="+"/>
	<vowel ph="rx" vlng="s" vheight="1" vfront="3" vrnd="+"/>
	<vowel ph="e" vlng="s" vheight="2" vfront="1" vrnd="-"/>
	<vowel ph="ai" vlng="d" vheight="2" vfront="1" vrnd="-"/>

	<vowel ph="h:" vlng="0" vheight="0" vfront="0" vrnd="-"/>
	<vowel ph="o" vlng="s" vheight="2" vfront="3" vrnd="+"/>

	<vowel ph="au" vlng="d" vheight="1" vfront="3" vrnd="+"/>
	

	<consonant ph="k" ctype="s" cplace="v" cvox="-"/>
	<consonant ph="kh" ctype="s" cplace="v" cvox="-"/>
	<consonant ph="g" ctype="s" cplace="v" cvox="+"/>
	<consonant ph="gh" ctype="s" cplace="v" cvox="+"/>
	<consonant ph="ng~" ctype="n" cplace="v" cvox="+"/>
	<consonant ph="ch" ctype="a" cplace="p" cvox="-"/>

	<consonant ph="chh" ctype="a" cplace="p" cvox="-"/>
	<consonant ph="j" ctype="a" cplace="p" cvox="+"/>

	<consonant ph="jh" ctype="a" cplace="p" cvox="+"/>
	<consonant ph="nj~" ctype="n" cplace="p" cvox="+"/>
	<consonant ph="t" ctype="s" cplace="d" cvox="-"/>
	<consonant ph="th" ctype="s" cplace="d" cvox="-"/>
	<consonant ph="d" ctype="s" cplace="d" cvox="+"/>
	<consonant ph="dh" ctype="s" cplace="d" cvox="+"/>
	<consonant ph="n" ctype="n" cplace="d" cvox="+"/>
	<consonant ph="t:" ctype="s" cplace="a" cvox="-"/>
	<consonant ph="t:h" ctype="s" cplace="a" cvox="-"/>

	<consonant ph="d:" ctype="s" cplace="a" cvox="+"/>
	<consonant ph="d:h" ctype="s" cplace="a" cvox="+"/>
	<consonant ph="nd~" ctype="n" cplace="a" cvox="+"/>
	<consonant ph="p" ctype="n" cplace="l" cvox="-"/>
	<consonant ph="ph" ctype="s" cplace="l" cvox="-"/>
	<consonant ph="b" ctype="s" cplace="l" cvox="+"/>
	<consonant ph="bh" ctype="s" cplace="p" cvox="+"/>
	<consonant ph="m" ctype="n" cplace="l" cvox="+"/>
	
	<consonant ph="y" ctype="l" cplace="v" cvox="+"/>
	<consonant ph="r" ctype="l" cplace="p" cvox="+"/>

	<consonant ph="l" ctype="l" cplace="d" cvox="+"/>
	<consonant ph="sh" ctype="f" cplace="v" cvox="-"/>
	<consonant ph="shh" ctype="f" cplace="p" cvox="+"/>
	<consonant ph="s" ctype="f" cplace="d" cvox="-"/>
	<consonant ph="h" ctype="f" cplace="v" cvox="-"/>
	<consonant ph="n:" ctype="n" cplace="d" cvox="+"/>
	<consonant ph="n~" ctype="n" cplace="d" cvox="+"/>
	<consonant ph="t:k" ctype="s" cplace="a" cvox="-"/>
</allophones>

**Comment by seblemaguer** [comment]
Did you manage to solve your problem ?

**Comment by imty1000** [comment]
Hello everyone, i am sorry that i could not finish it for many reasons and now i need your help. I have already used the mary build tools for building the environment. However, i am stuck with transcription tool. i corrected 12,000 words and press train button it trained and when i reopen it i loss all data though i saved them before closing. and i had faced this problem many times and could not finish it. Now can anyone tell me what is the wrong am i doing? 

@nshmyrev, sir you said to import existing Bengali database into OpenMary however i did try a lot of search on the internet but could not find how to do so if you kindly help me, i would be really great full to you.

**Comment by imty1000** [comment]
@nshmyrev sir after downloading http://festvox.org/databases/iiit_voices/iiit_ben_ant.tar.gz i could not run the program which is having 1000 wav. can you please help me by instructing how to run it?

**Comment by imty1000** [comment]
Can anyone help me please?

**Comment by imty1000** [comment]
Hello, please i really need your help

**Comment by Nandutu** [comment]
@nshmyrev  Which location is the phoneset file saved?
I saved mine at /home/irene/TTS/mary/marytts/target/marytts-builder-5.2-SNAPSHOT/bin as allophones.lug.xml but when i select it on the transcription GUI tool nothing no results are  seen
Am using ubuntu 14.04
Are there any hidden insights i can have towards saving this file.

[allophones.lug.txt](https://github.com/marytts/marytts/files/337793/allophones.lug.txt)

**Comment by nshmyrev** [comment]
@Nandutu your allophones file is ok. You should not see anything when you select it in transcription tool, you can proceed with adding words and their transcription.

**Comment by Nandutu** [comment]
@nshmyrev After reading https://mary.opendfki.de/trac/wiki/TranscriptionTool, i understand i need to work with my wordlist-freq.txt file in adding words. This file has both english and luganda words.
Question:
1. Does the adding words process mean we add words that might have the same meaning in the list of words then remove the frequencies that appear besides a particular word?
Some more insights with adding words and their transcription, am really grateful.
