### ISSUE TITLE
Testenvironment

### ISSUE THREAD

**Issue by qwertologe** [marytts/marytts#483]
Please consider to provide 2 additional mary tts demo server (as http://mary.dfki.de:59125/):
- daily build
- newest beta version

This would reduce the time to check the errors and save bandwidth

**Comment by psibre** [comment]
The current plan is to replace the full git clone of marytts with just the installer, and running that in "continuous" mode. The main bottleneck I foresee is the storage needed -- probably the non-stable demo server(s) will only have a few voices installed.

**Comment by qwertologe** [comment]
maybe it is possible to share the voices with several versions?

**Comment by psibre** [comment]
Indeed, the plan is to attach them to releases in dedicated repositories.
