### ISSUE TITLE
POST example not working

### ISSUE THREAD

**Issue by fahadonline** [marytts/marytts#494]
The POST example is not working at http://mary.dfki.de:59125/documentation.html
It seems to generate 2 requests, 1st one is POST but the 2nd one is GET.
POST request contains the data but the 2nd GET does not.
Same issue persist in my local installation as well.

Any advice ?

**Comment by seblemaguer** [comment]
Hello,

on my side it is working, I have only one post request. What makes you think that you have a second request ?

**Comment by fahadonline** [comment]
Thanks for prompt reply.

That's strange, when audio was not playing for POST example
I used developer toolbar in chrome to see the request status.
It lists two requests, 1st one is POST that succeeded
but the 2nd one is GET that fails because no data is passed.

Please go through following screenshots.

![screenshot marytts 2016-03-03 20 02 24](https://cloud.githubusercontent.com/assets/1949992/13498469/f3a7fa66-e17b-11e5-9637-23f952552661.png)
![screenshot from marytts 3 2016-03-03 20 19 53](https://cloud.githubusercontent.com/assets/1949992/13498847/70d43c6a-e17d-11e5-962c-6f2fa4fa6e09.png)
![screenshot marytts 2 2016-03-03 20 15 47](https://cloud.githubusercontent.com/assets/1949992/13498848/70d6063a-e17d-11e5-952e-c2c69b369214.png)

**Comment by seblemaguer** [comment]
Ok I got it on chromium too. I think it is because the HTML page is not correct at all (going through the validator leads to a tremendous numbers of error). However in marytts 6.x this server part will be deprecated and this documentation dropped. Normally the POST request should work, it is just something specific for the documentation.

**Comment by fahadonline** [comment]
In MARY TTS Tutorial eNTERFACE 2010, Amsterdam, Marc Schröder,
it mentioned that there are two options for accessing the MARY server.
One is using a Java API and the other using URL for your request.
I need to convert text from a file to speech.
Say I can not use the JAVA API, what other option will be available marytts 6.x. ?

Also in case of present version of marytts 5.x, if data set is large I would like to prefer POST over GET.
Any idea how I can get this POST access to URL work ?

**Comment by seblemaguer** [comment]
No you didn't get my point. You can still use POST request like I did here for example : https://gist.github.com/seblemaguer/1519eeed84d47242d4ac

**Comment by fahadonline** [comment]
Thanks for clarification.
However it seems that following line in call_mary.py sends request parameters in query string though the method is POST.
`resp, content = h_mary.request("http://%s:%s/process?" % (mary_host, mary_port), "POST", query)`

Can you share the request URL generated by above mentioned line of code ?

**Comment by seblemaguer** [comment]
This is the address built : http://localhost:59125/process. Parameters are transmitted by POST. I just check using wireshark.

**Comment by fahadonline** [comment]
Yup it seems to work for POST with php curl as well.
Thanks for helping out.
