### ISSUE TITLE
MaryTTS & opus codec

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#501]
Hi guys,

did anyone play around with opus encoded input so far?

Cheers

**Comment by seblemaguer** [comment]
Hello,

what do you mean by "play around" ? MaryTTS support only wav output for now.

**Comment by entenbein** [comment]
I mean just giving it a try... Same goes for the input I guess, only wav?!

**Comment by seblemaguer** [comment]
sorry I'm kind of confused, input of which part ? Because except the building voice part, you don't use signal as an input

**Comment by entenbein** [comment]
Sorry, that's what I meant: the input for the voice building.

**Comment by seblemaguer** [comment]
ok for now only wav is accepted. Flac support is in process and I don't think other one are planned for now. However, you can transcode your mp3/ogg/... to wav really easily using ffmpeg or mencoder if you are on a unix os

**Comment by psibre** [comment]
Opus combines SILK for speech and CELT for music, and switches dynamically between the two.
Obviously music is not so relevant for speech synthesis.

Informal feedback from a colleague who "played around" with Opus for speech synthesis indicates that the SILK part of opus does not work as well as Speex (despite the fact that Opus was intended to replace Speex).

Another blocker however is the lack of a native java Opus decoder library.
