### ISSUE TITLE
Rate adjustment not working in 5.2-beta2

### ISSUE THREAD

**Issue by andreas-weise** [marytts/marytts#509]
Hi, I've been using Mary 5.1.2 for a while and was able to adjust the speech rate through SSML just fine using the solutions suggested in #97. Today I downloaded 5.2-beta2 and the same SSML I use in 5.1.2 has no effect on the rate in 5.2-beta2. I tried with or without enclosing <p> tag, with or without a silent leading token (".") and with rate keywords (e.g. "x-fast") and as relative changes. Nothing had any effect.

Here's an example that works in 5.1.2 but not in 5.2-beta2 (cmu-slt-hsmm both times):
<?xml version="1.0"?><speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/10/synthesis http://www.w3.org/TR/speech-synthesis/synthesis.xsd" xml:lang="en-US">.<p><prosody rate="x-fast">This is a short example sentence.</prosody></p></speak>
 
I would really like to move to 5.2-beta2, since I have been having trouble with #285 in 5.1.2, but I absolutely need the rate adjustment. Please let me know if there is any fix. Thanks

**Comment by seblemaguer** [comment]
Can you indicate the document how you specify the rate by putting an example ?

**Comment by andreas-weise** [comment]
Sorry, I copied the xml for the example in the wrong way before.
Here it is now

```xml
<?xml version="1.0"?><speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/10/synthesis http://www.w3.org/TR/speech-synthesis/synthesis.xsd" xml:lang="en-US">.<p><prosody rate="x-fast%">This is a short example sentence.</prosody></p></speak>
```

**Comment by psibre** [comment]
I cannot reproduce any of this. Specifying `<prosody rate=...>` work for me, both with `SSML` and `RAWMARYXML` input types.
