### ISSUE TITLE
Editor with autocompletion for EMOTIONML or SSML or MARYXML tags?

### ISSUE THREAD

**Issue by zenny** [marytts/marytts#514]
There is a rudimentary js script to edit emotionml at https://github.com/rektide/emotion-l

Appreciate what do you guys use to tag the EmotionML or SSML or MARYXML? Is there any tool or IDE with auto-completion feature?

Thanks!

**Comment by Rootex** [comment]
I don't clearly understand what you mean here, those are datatypes defined in the marytts project even though EmotionML is an external markup, but maybe i got your question wrong, please clearify.

As for tools for the autocompletion of those tags, i am not sure if it exists.

**Comment by zenny** [comment]
@Rootex Thanks.

What I am trying to do is create a text and tag it, but it is a PITA to learn the entire tags by heart. However, tools like this https://github.com/rektide/emotion-l helps a bit. 

I am searching for something IDE like any html editor or a plugin to existing text editors like vim/geany etc.

Else, appreciate if any of you share your workflow for TTS with MaryTTS on a day-to-day basis.

**Comment by seblemaguer** [comment]
I'm using emacs and know that people in the team are using eclipse or intellij. However, there is no such things as a marytts  xml completion system except the base "tag" one you have in any basic editor
