### ISSUE TITLE
Marytts within tomcat application server creates a memory leak

### ISSUE THREAD

**Issue by netzverb** [marytts/marytts#521]
I'm testing marytts to run within a web application on tomcat application server. There is a servlet that converts the text request to an audio response. All needed marytts libs are in the WEB-INF/lib directory.

```
public void doGet(HttpServletRequest _request, HttpServletResponse _response) {
  ...
  MaryInterface marytts = new LocalMaryInterface();
  AudioInputStream in = marytts.generateAudio("This is my text.");
  ServletOutputStream out = _response.getOutputStream();
  AudioSystem.write(in, AudioFileFormat.Type.WAVE, op);
  ...
}
```
Each request to the web application starts a new marytts thread which doesn't stops. These threads are idle, but after 100 and more requests all memory of the application server is used and the server goes down.

```
Thread: Thread-15 WAITING Priority: 5 Daemon
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(Unknown Source)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
java.util.concurrent.ArrayBlockingQueue.put(Unknown Source)
marytts.util.data.ProducingDoubleDataSource.putOneDataPoint(ProducingDoubleDataSource.java:75)
marytts.htsengine.HTSVocoder.htsMLSAVocoder(HTSVocoder.java:495)
marytts.htsengine.HTSVocoder$HTSVocoderDataProducer.run(HTSVocoder.java:1651)
java.lang.Thread.run(Unknown Source)
```
It seems that the local marytts runtime isn't reused or there is a problem to stop the threads. Here a log entry of catalina.log:
```
The web application [] appears to have started a thread named [Thread-15] but has failed to stop it. This is very likely to create a memory leak.
```
Any idea? Thanks :-)
Andreas

**Comment by psibre** [comment]
@netzverb Could you start just a single MaryInterface outside of your `doGet` method, and reuse it?

**Comment by netzverb** [comment]
Did you mean the following? I create the MaryInterface once and reuse it.
```
private static MaryInterface marytts;
public void doGet(HttpServletRequest _request, HttpServletResponse _response) {
  ...
  synchronized (this.getClass()) {
    if (marytts == null)
      marytts = new LocalMaryInterface();
  }
  AudioInputStream in = marytts.generateAudio("This is my text.");
  ServletOutputStream out = _response.getOutputStream();
  AudioSystem.write(in, AudioFileFormat.Type.WAVE, op);
  ...
}
```
This code causes the same problem :-/

**Comment by FabianWelz** [comment]
@netzverb: I think I remember using the 'server' or 'standalone' version of the marytts-class (not sure how its called), not the local one, but I could be wrong..

**Comment by FabianWelz** [comment]
@netzverb: and yes also just using one single instance, not multiple

**Comment by netzverb** [comment]
@psibre: You can close this question. I found a configuration wich works. Now I use the German voice `bits3` an set the mary base with `System.setProperty("mary.base", "P:\ath")`. I think, the mary base was the key. Without this, the threads goes in an undefined state.

@FabianWelz + @psibre: Thanks for your answers :-)

**Comment by netzverb** [comment]
**Example MaryTTS within tomcat**

Put the following libraries in the WEB-INF/lib or the %TOMCAT%/lib directory:
- `marytts-lang-de-5.1.2.jar`
- `marytts-lang-en-5.1.2.jar`
- `marytts-runtime-5.1.2-jar-with-dependencies.jar`
- `serializer.jar`
- `xalan.jar`
- `voice-bits3-5.1.jar`

Create a mary base directory on the tomcat server. Note that the web application must have write permissions on this directory, since mary will create a `logs` directory. Put there at least the bits3 files:
- `lib/voices/bits3/*.mry`

Now, the following servlet can transform an text (parameter `text`) into an binary wav stream.

```
public class MaryServlet extends HttpServlet {
	public void doGet(HttpServletRequest _request, HttpServletResponse _response)
			throws IOException, ServletException {
		try {
			System.setProperty("mary.base", "P:\ath");
			MaryInterface mary = new LocalMaryInterface();
			mary.setVoice("bits3");
			AudioInputStream ins = mary.generateAudio(_request.getParameter("text"));
			_response.setContentType("audio/wav");
			AudioSystem.write(ins, AudioFileFormat.Type.WAVE, _response.getOutputStream());
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}
	public void doPost(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {
		doGet(request, response);
	}
}
```
