### ISSUE TITLE
Require pom file for marytts 4.3.1.

### ISSUE THREAD

**Issue by Yamin372** [marytts/marytts#522]
Hello Sir, We are trying to build our project using marytts 4.3.1. but we require the pom file for the same. So we request you to share it with us if you have the pom file for 4.3.1. available with you.

Thanks and Regards.

**Comment by Yamin372** [comment]
@psibre @sathishpc please help.

**Comment by psibre** [comment]
Versions prior to v5.0 are not built using Maven, and do not have POM files. Please consider using a more recent version of MaryTTS.
