### ISSUE TITLE
new language support issue

### ISSUE THREAD

**Issue by vishalranapatgiri** [marytts/marytts#529]
i have created a database for bengali language.  after transcribing the words ,the words are not able to load in the mary transcription tool

![screenshot from 2016-05-12 11 01 34](https://cloud.githubusercontent.com/assets/17155227/15204956/19cdc568-1831-11e6-99ca-07ba6656bb07.png)

the words are loaded but the trainpredict button is not enabled..

**Comment by vishalranapatgiri** [comment]
![screenshot from 2016-05-12 11 01 34](https://cloud.githubusercontent.com/assets/17155227/15204956/19cdc568-1831-11e6-99ca-07ba6656bb07.png)

**Comment by vishalranapatgiri** [comment]
the words are loaded but the trainpredict button is not enabled..

**Comment by vishalranapatgiri** [comment]
help anyone?????????

**Comment by nshmyrev** [comment]
Which version are you using?

I believe it is a bug in one of the newer versions, you can try older one like 4.2, I remember it was working. You can look closer on the code why the button is not enabled too, it should be easy problem to solve.

**Comment by vishalranapatgiri** [comment]
i am using version 5.2 . i tried it with the older version. same problem.sir, by code do you mean LSTrainer.java file??

**Comment by nshmyrev** [comment]
Did you load the phoneset? Button got enabled when you load both phoneset and transcription.

**Comment by vishalranapatgiri** [comment]
yup i loaded both the phoneset and transcription. I transcribed the first 150 words manually.

**Comment by nshmyrev** [comment]
Ok, please share both phoneset and transcription file.

**Comment by vishalranapatgiri** [comment]
﻿<allophones name="sampa" xml:lang="as-BN"
		features="vlng vheight vfront vrnd ctype cplace cvox">
	<silence ph="_"/>

	<vowel ph="O" vlng="s" vheight="2" vfront="2" vrnd="+"/>
	<vowel ph="a" vlng="l" vheight="2" vfront="2" vrnd="-"/>
	<vowel ph="i" vlng="l" vheight="3" vfront="2" vrnd="-"/>
	<vowel ph="i" vlng="s" vheight="1" vfront="1" vrnd="-"/>
	<vowel ph="u" vlng="s" vheight="1" vfront="3" vrnd="+"/>
	<vowel ph="u" vlng="l" vheight="2" vfront="1" vrnd="+"/>
	<vowel ph="ri" vlng="s" vheight="1" vfront="3" vrnd="+"/>
	<vowel ph="e" vlng="l" vheight="2" vfront="1" vrnd="-"/>
	<vowel ph="oj" vlng="l" vheight="2" vfront="1" vrnd="-"/>
	<vowel ph="u" vlng="l" vheight="2" vfront="3" vrnd="+"/>
	<vowel ph="ow" vlng="l" vheight="1" vfront="3" vrnd="+"/>


	<consonant ph="k" ctype="s" cplace="v" cvox="-"/>
	<consonant ph="k_h" ctype="s" cplace="v" cvox="-"/>
	<consonant ph="ɡ " ctype="s" cplace="v" cvox="+"/>
	<consonant ph="ɡʱ" ctype="s" cplace="v" cvox="+"/>
	<consonant ph="N" ctype="n" cplace="v" cvox="+"/>
	<consonant ph="tS" ctype="a" cplace="p" cvox="-"/>
	<consonant ph="tS_h" ctype="a" cplace="p" cvox="-"/>
	<consonant ph="dZ" ctype="a" cplace="p" cvox="+"/>
	<consonant ph="dZʱ" ctype="a" cplace="p" cvox="+"/>
	<consonant ph="t" ctype="s" cplace="d" cvox="-"/>
	<consonant ph="t_h" ctype="s" cplace="d" cvox="-"/>
	<consonant ph="d" ctype="s" cplace="d" cvox="+"/>
	<consonant ph="r`" ctype="s" cplace="d" cvox="+"/>
	<consonant ph="dʱ" ctype="s" cplace="d" cvox="+"/>
	<consonant ph="r`ʱ" ctype="s" cplace="d" cvox="+"/>
	<consonant ph="n" ctype="n" cplace="d" cvox="+"/>
      <consonant ph="t_d" ctype="s" cplace="l" cvox="-"/>
	<consonant ph="t_d_h" ctype="s" cplace="l" cvox="-"/>
	<consonant ph="d_d" ctype="s" cplace="l" cvox="+"/>
	<consonant ph="d_dʱ" ctype="s" cplace="l" cvox="+"/>
	<consonant ph="p" ctype="s" cplace="l" cvox="-"/>
	<consonant ph="p_h" ctype="s" cplace="l" cvox="-"/>
	<consonant ph="b" ctype="s" cplace="l" cvox="+"/>
	<consonant ph="bʱ" ctype="s" cplace="l" cvox="+"/>
	<consonant ph="m" ctype="n" cplace="l" cvox="+"/>
	<consonant ph="e_^" ctype="f" cplace="d" cvox="+"/>
	<consonant ph="r" ctype="s" cplace="d" cvox="+"/>
	<consonant ph="l" ctype="l" cplace="d" cvox="+"/>
	<consonant ph="S" ctype="l" cplace="v" cvox="+"/>
	<consonant ph="s" ctype="s" cplace="d" cvox="-"/>	
      <consonant ph="h" ctype="f" cplace="v" cvox="-"/>
	
	

</allophones>

**Comment by vishalranapatgiri** [comment]
[wordlist-freq.txt](https://github.com/marytts/marytts/files/261745/wordlist-freq.txt)

**Comment by nshmyrev** [comment]
Phoneset file is corrupted, could you attach it instead?

**Comment by vishalranapatgiri** [comment]
[allophones.txt](https://github.com/marytts/marytts/files/261768/allophones.txt)

**Comment by nshmyrev** [comment]
Ok, there are number of issues with your file and with openmary:

1) Your allphone file contains phone `i` two times and `u` three times, during load there is an exception in terminal. You need to fix those issues first

2) I wouldn't use unicode symbols like ` or ʱ in phone names. It is better to stick with letters. 

3) Use "Open file" menu instead of "Add words from file"

Then "Train and Predict" button will be active, but there will be other issues since not all of your words are properly transcribed.

I also see you are using too many dashes. Dash should separate syllables, not every letter.

**Comment by vishalranapatgiri** [comment]
Thanku sir... I will recheck every problem you mentioned.  Will inform you
of my proceedings.

**Comment by vishalranapatgiri** [comment]
hello,,i completed the tasks you mentioned. the trainpredict button is enabled, but now it shows cannot syllabify empty phone string

**Comment by vishalranapatgiri** [comment]
java.lang.IllegalArgumentException: Cannot syllabify empty phone string

**Comment by vishalranapatgiri** [comment]
prev: Serif
next: Serif
alignment ... 
iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
alignment completed.
training ... 
      Training decision tree for: ু
      Training decision tree for: ঁ
      Training decision tree for: ং
      Training decision tree for: আ
      Training decision tree for: ে
      Training decision tree for: ই
      Training decision tree for: ো
      Training decision tree for: ্
      Training decision tree for: এ
      Training decision tree for: ক
      Training decision tree for: ছ
      Training decision tree for: জ
      Training decision tree for: ট
      Training decision tree for: ত
      Training decision tree for: থ
      Training decision tree for: দ
      Training decision tree for: ধ
      Training decision tree for: ন
      Training decision tree for: প
      Training decision tree for: ব
      Training decision tree for: ভ
      Training decision tree for: ম
      Training decision tree for: য
      Training decision tree for: র
      Training decision tree for: ল
      Training decision tree for: null
      Training decision tree for: শ
      Training decision tree for: স
      Training decision tree for: হ
      Training decision tree for: ়
      Training decision tree for: া
      Training decision tree for: ি
training completed.
java.lang.IllegalArgumentException: Cannot syllabify empty phone string
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:479)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:176)
	at marytts.tools.transcription.TranscriptionTable.trainPredict(TranscriptionTable.java:221)
	at marytts.tools.transcription.TranscriptionGUI.trainPredictActionPerformed(TranscriptionGUI.java:816)
	at marytts.tools.transcription.TranscriptionGUI.access$8(TranscriptionGUI.java:810)
	at marytts.tools.transcription.TranscriptionGUI$8.actionPerformed(TranscriptionGUI.java:372)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nshmyrev** [comment]
Some of your words is transcribed with empty string without phones. You need to find that word and fix it.

**Comment by yusufardi97** [comment]
hello @nshmyrev, i got the same issue even thought i didn't see any of empty string within my transcription (100 words)

here is the [file] (https://db.tt/J1Q4JkyY), what should i do to resolve it?
thanks in advance

**Comment by psibre** [comment]
Which version of MaryTTS are you using?

**Comment by yusufardi97** [comment]
5.2, should be the lastest one.

**Comment by psibre** [comment]
5.2 has not been released yet. Could you please double-check?

**Comment by yusufardi97** [comment]
umm, after i run mvn install command the one i got in target folder is marytts-5.2-SNAPSHOT and its builder, so i assume its version 5.2, is there any other way to check the version i used?

**Comment by psibre** [comment]
Thanks for the clarification, you are using version `5.2-SNAPSHOT`, which is to say, a development build *towards* release v5.2.
Could you please confirm that you are up to date with the [upstream repo](..)?

**Comment by yusufardi97** [comment]
yes i am, i do pull upstream after done cloning the repo

**Comment by psibre** [comment]
Do you have all your code and data in some public repo, so that we can try to reproduce your issues?

**Comment by yusufardi97** [comment]
i push it all in my fork and put some resources in the in_resource folder, let me know if you need more resource to do the check

**Comment by psibre** [comment]
Thanks for posting your Indonesian component code. The critical thing is that you have actual transcriptions for the word list which forms the training data for the lexicon, but I can't find any transcribed words in your `in_resource` directory.

**Comment by psibre** [comment]
On the other hand, I suspect that Indonesian has a very straightforward correspondence between the written and spoken form, right? If so, you may be able to get pretty far by writing a rule-based phonemiser class.

**Comment by yusufardi97** [comment]
sorry, didn't see the notification for your reply.

i don't quite understand the difference transcription (from transcription.sh) and the transcribed words. isn't file in.txt contain result of transcript process (exclude licenses rows)?

yes, Indonesian has quite straightforward correspondence between those form. I automate some of transcription process by applying rule based for the transcription process which resulting in in.txt. If i do have the rule-based phonemiser, could i skip some process in script selection process?

**Comment by psibre** [comment]
Indeed, your `in_resource/in.txt` does contain some transcriptions. I was confused by your `marytts-languages/marytts-lang-in/lib/modules/in/lexicon/in.txt`, which does not.

If you implement a rule-based phonemiser, you could theoretically do without the whole buggy TranscriptionGUI stuff. Inevitably there would be exceptions to the rule-based pronunciation (foreign and loan words mostly, I would imagine), and you could handle those with a simple text file, similar to the `userdict`.

**Comment by psibre** [comment]
Incidentally, and this is a completely separate issue, you'll want to refactor everything to use the correct ISO 639-1 language code for Indonesian, which I believe should be `id`.

**Comment by yusufardi97** [comment]
ah, i see, actually marytts-lang-in folder was from previous experiment, which i used id locale as stated in [my past issue](https://github.com/marytts/marytts/issues/279). Basically i retry the experiment with in locale as munzy suggested.

Another question, after transription process, i've seen there are 3 runtime file which is in.lst, in.fst, and in_lexicon.fst. How do i get or create those file if i use the phonemiser? or i just don't need those file if i get another rule to rely on (which is what phonemiser do, i think)

**Comment by psibre** [comment]
> i just don't need those file if i get another rule to rely on (which is what phonemiser do, i think)

This.
