### ISSUE TITLE
Weird behaviour when using a hmm voice

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#530]
Hi folks,

I got one `htk` and one `hmm` voice based on the same data. When synthesizing a text using the web interface the `hmm` voice really mixes things up*, the `htk` voice doesn't. When saving the text to a (wav) file both voices work fine.

The German default text is:
*Willkommen in der Welt der Sprachsynthese!*
The hmm voice rather says:
*Wiolkommen in der Wua der Spuachschyntesse!*

The **Phonemes** output looks good though. Log file looks similar for both requests.

This happens when using Firefox, Chrome or the included client. 

The even funnier part is that this hasn't been that way from the start/ since I built this voice. I didn't change any of the source code concerning those parts of the marytts server though..

Any guesses?

Thanks!

Update: Now the wav download also returns mixed up speech....

**Comment by psibre** [comment]
I'm confused by several points:
- the issue title mentions the "Play" button in the *web client* [emphasis mine], but you say this also occurs with the "included client", presumably the Java GUI;
- I don't understand what you mean by "`htk` voice".

I suspect that this has nothing at all to do with the Play button or the client.

Please explain, and consider updating the issue title to be more relevant.

**Comment by entenbein** [comment]
Alright, I updated the title.

To clarify things:
- When I first stumbled upon this, it only affected the output generated by the `Play` button. Processing and downloading a wav file worked. Since that seemed weird I double-checked shortly after and then the same stuff happend when downloading an audio file.
- *htk* means I used the `htk-Labeler`
- *hmm* was wrong, what I meant was that I used the `ehmm-Labeler`

**Comment by psibre** [comment]
@entenbein Thanks for the clarification!

Sounds like the result of your forced alignment is bad. I recommend inspecting the label files along with the corresponding audio (using tools such as [Praat](http://praat.org/) or [WaveSurfer](http://www.speech.kth.se/wavesurfer/)). But it's nothing we can fix from our side.

**Comment by entenbein** [comment]
Ok,

the strange thing is, that this worked some time ago. I guess I would have erased and rebuilt the voice otherwise.

I know, things don't just break without someone fiddling around... But is there any explanation?

**Comment by psibre** [comment]
I'm afraid I can't think of an obvious reason. It's all very vague and non-specific, and I don't think it's feasible to get to the bottom of this without some serious onsite debugging.
