### ISSUE TITLE
voice preferred modules

### ISSUE THREAD

**Issue by seblemaguer** [marytts/marytts#535]
Hello,

@psibre based on the discussion on #533, is it normal that we have this line in voice.java :  

``` java
        preferredModulesClasses = MaryProperties.getProperty(header + ".preferredModules");
```

I mean : 
- preferredModules => name does not respect the convention
- getProperty instead of getList ?

**Comment by psibre** [comment]
Indeed, it seems to diverge from the convention used in the config files. But the property name itself uses the voice "namespace" (the `header` in the code snippet), which I think makes sense.

**Comment by seblemaguer** [comment]
Ok, and actually yes there is after a tokenizer used. (from line 212)
