### ISSUE TITLE
Mary Transcription Tool: Cannot syllabify empty phone string

### ISSUE THREAD

**Issue by jogrimst** [marytts/marytts#536]
(This might relate to the existing issue https://github.com/marytts/marytts/issues/529)

Hi, 

I'm trying to transcribe phones for the Norwegian language.

I've downloaded the most frequent words from Wikipedia.

I've imported a phoneset file, and loaded the Wikipedia words from a MySQL database (about 490.000 words in total).

And I manually transcribed a few words:

![screen shot 2016-05-19 at 14 33 14](https://cloud.githubusercontent.com/assets/1451036/15393647/c5445fcc-1dce-11e6-9434-d2f6fe016aa7.png)

Then, when I click the "Train and Predict" button, I get:

`java.lang.IllegalArgumentException: Cannot syllabify empty phone string
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:479)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:179)
	at marytts.tools.transcription.TranscriptionTable.trainPredict(TranscriptionTable.java:221)`

Is the fact that most of the words are missing transcription causing this error?

This is what the wiki says:
> If you transcribe some data, click 'trainpredict' button to predict transcription for remaining words.

How much is "some data"? Do I have to transcribe a minimum amount of words to avoid the "Cannot syllabify empty phone string" error?

Thanks.

**Comment by jogrimst** [comment]
I got a step further now. I guess I just had to add a few more words. We should probably add some information about this in the wiki and the error message? I.e. the minimum number of words that should be transcribed to get it working.

![screen shot 2016-05-19 at 14 52 46](https://cloud.githubusercontent.com/assets/1451036/15394160/88aaa082-1dd1-11e6-9d45-8043eec60b5f.png)

**Comment by nshmyrev** [comment]
It is better to take existing dictionary [here](https://www.nb.no/sprakbanken/show?serial=oai%3Anb.no%3Asbr-23&lang=en)
