### ISSUE TITLE
SimplePhoneme2AP

### ISSUE THREAD

**Issue by seblemaguer** [marytts/marytts#537]
Using a SimplePhoneme2AP leads to produce partial acoustparams. Duration is included but no F0. Therefore, when we want to generate the audio it crashes (on the server) or produce an horror movie speech (on the my current branch)

**Comment by psibre** [comment]
Ah, I didn't notice that when I fixed #467 =( Sorry!

**Comment by psibre** [comment]
I think SimplePhonemes2AP is completely borked anyway. The rule-based duration prediction is a joke, and the lack of F0 prediction is a blatant bug. We should just refactor it so that it outputs `ALLOPHONES`, drop the duration prediction, and rename the module (?).

**Comment by psibre** [comment]
Or better yet, put the whole class in the boneyard.

**Comment by seblemaguer** [comment]
I think that in marytts 6 we will distinguish : 
  - modules which are doing an operation (get the POS, phonemise, ...)
  - serializer which are going to import/export specific format to the inner data.

Therefore, I suggest that, later, we transform this module into a serializer
