### ISSUE TITLE
How to deal with digraphs for new languages

### ISSUE THREAD

**Issue by nberisha** [marytts/marytts#539]
Hi,

I am adding new language, which has digraphs like "dh", "sh", "th", "xh", etc and during transcription with GUI tool it is not doing correctly transcription when we do hit Train and predict.
For instance "sh" is transcribed as "sE" , instead of "S" which is how should be correctly transcribed.

What should I do to fix this issue?

I appreciate if you could help me .

Best

**Comment by psibre** [comment]
The problem might be that the transcription tool tries to greedily find the longest substring match. So if you have allophones `x` and `y` and also use a digraph for another allophone `xy`, then a sequence of `x y` may become replaced with `xy`.

The code underlying the transcription tool and the letter-to-sound prediction has a number of issues, and we're investigating a replacement. In the meantime, it's best if you try to redefine your phonetic inventory with only single-character symbols per sound.

**Comment by nberisha** [comment]
Hi psibre,

Thank you for you replay.

I solved the issue, and I posted the fix on the issue  
#434, which is similar with this issue.

regards!
