### ISSUE TITLE
mary TTS Voice Varition

### ISSUE THREAD

**Issue by nagaraj329550** [marytts/marytts#541]
I am using the mary TTS 5.1.2 in the my system .In the mary tts I am using the dfki-prudence(English female) voice .But in this voice variation is not  working like(happy, sad,angry,prosody,rate,pitch). anyone know how to make voice variation in dfki-prudence(English female) voice. replay me. 
see the below example .
<emotionml version="1.0" xmlns="http://www.w3.org/2009/10/emotionml" 
category-set="http://www.w3.org/TR/emotion-voc/xml#everyday-categories">
Hello and good afternoon.

<emotion><category name="angry"/>
What was that all about?
</emotion>

<emotion><category name="happy"/>
Nice to see you again!
</emotion>

<emotion><category name="sad"/>
Yeah I also had something else in mind than this.
</emotion>

<emotion><category name="content"/>
Well at least there is something nice to see.
</emotion>

  <emotion dimension-set="http://www.w3.org/TR/emotion-voc/xml#pad-dimensions">
  I'm calm.
    <dimension name="arousal" value="0.3"/>
    <dimension name="pleasure" value="0.9"/>
    <dimension name="dominance" value="0.8"/>
  </emotion>

  <emotion dimension-set="http://www.w3.org/TR/emotion-voc/xml#pad-dimensions">
  I'm nervous!
    <dimension name="arousal" value="0.9"/>
    <dimension name="pleasure" value="0.2"/>
    <dimension name="dominance" value="0.2"/>
  </emotion>
    

</emotionml>

**Comment by psibre** [comment]
The `dfki-prudence` voice does not support the expressive styles. Only `dfki-pavoque-styles` has this feature.

**Comment by nagaraj329550** [comment]
In dfki-prudence(English female) where(which file) I have change  for the voice variation(expressive Styles). and Which female voice is better for the supporting Expressive Style.
