### ISSUE TITLE
mary TTS Voice Varition issue.

### ISSUE THREAD

**Issue by nagaraj329550** [marytts/marytts#542]
I  am using the  mary tts 5.1.2 .In this mary tts i am using the dfki-prudence voice. In this voice I am not able to change the voice varation. whenever I am using the single word wow!,Wow? is working. but 
I am using whole sentence (Wow!. This wonderful place.) .it's not  working any one know reply.

**Comment by attacomsian** [comment]
Please avoid opening multiple issues. You had already opened an issue #541.We are currently finalizing  `5.2` version. I would suggestion you to download the [latest release](https://github.com/marytts/marytts/releases) of MaryTTS `5.2-beta3` and test it again. If you are facing any difficulty while running at your local machine, you may want to test it at MaryTTS [online version](http://mary.dfki.de:59125/).
