### ISSUE TITLE
MaryTTS McepMaker Issue.

### ISSUE THREAD

**Issue by BibekBazaz** [marytts/marytts#543]
I am having issues in running the VoiceImportTools.sh file.

While installing the speech tools it shows successful installation and is here: usr/share/man/man1/speech-tools.tar.gz file. But when i point the estDir to this location it shows error in execution saying it does not get the file. This error comes when I run the MCEPMaker. The stack trace is:

matarani@matarani-Lenovo-G580:/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin$ ./voiceimport.sh 
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Loading database layout:
Reading config file /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/database.config
Loading basename list from file /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst
Found 6 files in basename list
Computing Mel cepstra for [6] utterances.
java.lang.Exception: The component MCEPMaker produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException: Running ch_wave from [/usr/share/man/man1/speech-tools.1.gz/] failed.
Please check your ESTDIR environment variable, your specific EST path or the execution rights in this path.
	at marytts.tools.voiceimport.ESTCaller.checkEST(ESTCaller.java:103)
	at marytts.tools.voiceimport.ESTCaller.<init>(ESTCaller.java:73)
	at marytts.tools.voiceimport.MCEPMaker.compute(MCEPMaker.java:262)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
Caused by: java.io.IOException: Cannot run program "/usr/share/man/man1/speech-tools.1.gz//bin/ch_wave": error=20, Not a directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at marytts.tools.voiceimport.ESTCaller.checkEST(ESTCaller.java:100)
	... 3 more
Caused by: java.io.IOException: error=20, Not a directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 7 more

What should i do to resolve this issue? Please help. @psibre @giuliopaci

**Comment by psibre** [comment]
Please [RTFM](../wiki/VoiceImportToolsTutorial) about configuring for your installation of the Edinburgh Speech Tools.

**Comment by BibekBazaz** [comment]
@psibre  the error says that ESTDIR environment variable is not set. Do i need to configure and compile the speech tools? If yes then how? I read the manual but I could not understand what it meant. Its all too confusing. Please simplify it.

**Comment by psibre** [comment]
```
$ sudo apt-get install speech-tools
```
Then set your `db.estDir` to `/usr`.

**Comment by BibekBazaz** [comment]
I did as you suggested. the new error shows:

WALLOC: failed to malloc -2 bytes
java.lang.Exception: The component MCEPMaker produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException: Mel-Cepstrum  computation failed on file [s01]!
Command line was: [ /usr//bin/sig2fv -window_type hamming -factor 2.5 -otype est_binary -coefs melcep -melcep_order 12 -fbank_order 24 -shift 0.01 -preemph 0.97 -pm  /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/s01.pm -o /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/mcep/s01.mcep /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav/s01.wav].
	at marytts.util.io.General.launchProc(General.java:550)
	at marytts.tools.voiceimport.ESTCaller.make_mcep(ESTCaller.java:253)
	at marytts.tools.voiceimport.MCEPMaker.compute(MCEPMaker.java:263)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

**Comment by psibre** [comment]
Again my request, what's the output of running `soxi *.wav` in your `wav` directory?

**Comment by BibekBazaz** [comment]
The output is
matarani@matarani-Lenovo-G580:~$ soxi /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/*.wav

Input File     : '/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/s1.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:05.31 = 84960 samples ~ 398.25 CDDA sectors
File Size      : 170k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM


Input File     : '/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/s2.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:04.49 = 71840 samples ~ 336.75 CDDA sectors
File Size      : 144k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM


Input File     : '/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/s3.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:03.98 = 63680 samples ~ 298.5 CDDA sectors
File Size      : 127k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM


Input File     : '/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/s4.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:03.61 = 57760 samples ~ 270.75 CDDA sectors
File Size      : 116k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM


Input File     : '/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/s5.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:03.38 = 54080 samples ~ 253.5 CDDA sectors
File Size      : 108k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM


Input File     : '/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/s6.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:03.73 = 59680 samples ~ 279.75 CDDA sectors
File Size      : 119k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM

Total Duration of 6 files: 00:00:24.50
matarani@matarani-Lenovo-G580:~$

**Comment by psibre** [comment]
OK, thanks for the `soxi` output. Looks like your wav files have the expected format, but it doesn't give details of the RIFF headers. It's possible that your wav files have some header field or format that EST doesn't expect and cannot handle, which may be the reason for the `sig2fv` crash.
Please run your wav files through `sox` just to make sure.

**Comment by psibre** [comment]
Incidentally, I hope that you have more data than just those six short utterances, because building a TTS voice less than 20 s of speech data would be completely pointless.

**Comment by BibekBazaz** [comment]
my text files included sentences with their ids. for example

35427 इस बारे में उन्होंने स्वयं तो कुछ भी नहीं लिखा.
26530 उनकी जीवन प्रणाली, कला, साहित्य, दर्शन सब भारतीय संस्कृति है.
172369 ऐसा करने वाली वह पहली भारतीय कंपनी बनी.
212140 किसी भी कार्य को होने में समय लगता है.
156628 विभिन्न क्षेत्रों भारत में प्रथम.
147033 का इस्तेमाल करने की अनुमति प्रदान की.

I recorded the wav files for them but never said anything about the ids. I only recoreded for the hindi text leaving the ids out.
Is that a problem??

And about the sentences I am parallely doing two projects for the same language Hindi using two different allophone sets. One have 6 sentences and locale hn , the other have 32 sentences with locale hi.

**Comment by psibre** [comment]
Sorry, I'm not sure that you mean by ids.

Note that you need at least an hour of speech data to have any chance at creating a useful TTS voice. Your six-sentence voice project is doomed to fail, and things don't look good for the 32-sentence one, either.

**Comment by BibekBazaz** [comment]
okay then i will train another corpus and come back with better results. but for now, by the ids I mean 
the number that precedes the sentences.

**Comment by psibre** [comment]
Please still go ahead and test of processing your wav files with `sox` will solve the issue, so that we can close this.

**Comment by BibekBazaz** [comment]
sorry i did not understand you. So can you please explain me again.

**Comment by psibre** [comment]
Something like
```
$ cd wav
$ for w in *.wav; do mv $w $w~; sox $w~ $w; done
```
Then rerun the PraatPitchmarker and MCEPMaker.

**Comment by BibekBazaz** [comment]
i have to do this for all the files individually. ryt?
like for s01.wav

mv $s01.wav $s01.wav~;
sox  $s01.wav $s01.wav~;

**Comment by psibre** [comment]
Yes, if you prefer to do it file by file, instead of pasting the command I provided that does it in a loop, then be my guest.

**Comment by psibre** [comment]
>  sox $s01.wav $s01.wav~;

Note that you messed up the order.

**Comment by BibekBazaz** [comment]
Thanks. I will go and paste the command in terminal and redo my job. Thanks for the help

**Comment by BibekBazaz** [comment]
Thank you. it solved the problem Thanks again.
