### ISSUE TITLE
PraatPitchMaker Memory Issue.

### ISSUE THREAD

**Issue by BibekBazaz** [marytts/marytts#544]
When I run the voiceimporttools.sh file and run the praatpitchmaker following error is displayed.

Computing pitchmarks for 6 utterances.
Running Praat as: praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500
Error: Out of memory: there is not enough room for 2147483647 more elements whose sizes are 8 bytes each.
Matrix of elements not created.
Sound not created.
Sound not read from sound file “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav//s1.wav”.
Script line 66 not performed or completed:
« wav = Read from file... 'wavFile$' »
Script “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat” not completed.
Praat: command file “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500” not completed.

java.lang.Exception: The component PraatPitchmarker produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException: PraatPitchmarker computation failed on file []!
Command line was: [praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500].
	at marytts.util.io.General.launchProc(General.java:549)
	at marytts.tools.voiceimport.PraatPitchmarker.compute(PraatPitchmarker.java:294)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

Now the error as I understand is because of the sound objects. My sampling rate is 44100 and that needs round 16GB space and I have 500GB available space. So free memory is available. But the sound objects are "long sound objects " that dont seem to process automatically in praat. 
When I manually open them in Praat GUI using the "open long sound objects " options they get loaded but I dont understand what I should do next so that I can proceed with my MaryTTS project of adding support for HINDI language.
It also shows that it cannot read the sound files; that line no 66in script.praat is not executed. Please tell me how to edit that.
Also the praat execution failure on file [ ] is not clear to me. 

Please help @giuliopaci  @psibre 

Thank you.

**Comment by psibre** [comment]
1. Please understand that memory is not the same as disk space.
2. You will probably run into problems if you don't downsample your audio to 16 kHz. This is a known limitation, and will hopefully be solved in the future.
3. Praat cannot run pitch analysis on LongSound objects.
4. In case you're using the 32-bit version of Praat, consider switching to 64-bit, because it significantly raises the memory caps.
5. You seem to have only six utterances in total. Perhaps these are each really long, which will also cause problems. Try splitting your data into short utterances of one utterance each.

**Comment by BibekBazaz** [comment]
Ok let me try your suggestions. I will get back to you with the results. Thanx for helping.

**Comment by BibekBazaz** [comment]
@psibre 
Hello again,

I have down sampled my audio to 16khz, and am running 64 bit Praat software. My utterances are

35427 इस बारे में उन्होंने स्वयं तो कुछ भी नहीं लिखा.
26530 उनकी जीवन प्रणाली, कला, साहित्य, दर्शन सब भारतीय संस्कृति है.
172369 ऐसा करने वाली वह पहली भारतीय कंपनी बनी.
212140 किसी भी कार्य को होने में समय लगता है.
156628 विभिन्न क्षेत्रों भारत में प्रथम.
147033 का इस्तेमाल करने की अनुमति प्रदान की.

These are taken as long sound objects. I am new to praat and did not find any guidelines how to split these utterances into small utterances. So please guide me to this.

Also , these sentences were generated directly by the system after the database selection step. So breaking these sentences into short sentences , will that not create problems in the future execution of the program?

**Comment by BibekBazaz** [comment]
@psibre 

Hello the memory issue is resolved. however there are still problems with the system that it cannot read the files from the wav directory. how to solve that?

matarani@matarani-Lenovo-G580:/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin$ ./voiceimport.sh 
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Loading database layout:
Reading config file /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/database.config
Loading basename list from file /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst
Found 6 files in basename list
Computing pitchmarks for 6 utterances.
Running Praat as: praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500
**Error: Cannot open file “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav//s1.wav”.**
Script line 66 not performed or completed:
« wav = Read from file... 'wavFile$' »
Script “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat” not completed.
Praat: command file “/media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500” not completed.

java.lang.Exception: The component PraatPitchmarker produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException: PraatPitchmarker computation failed on file []!
Command line was: [praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/temp/script.praat /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/ /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/ 100 500].
	at marytts.util.io.General.launchProc(General.java:549)
	at marytts.tools.voiceimport.PraatPitchmarker.compute(PraatPitchmarker.java:294)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

**Comment by psibre** [comment]
What's the output when you run
```
$ soxi /media/matarani/01CEB84761F97410/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/myvoice/wav/*.wav
```

**Comment by BibekBazaz** [comment]
@psibre  the main error in this step was conversion and downsampling of my audio files. Once i did that as per your suggestions, I successfully completed the praatpitchmaker step. Thank you so much.

But i request you to kindly stick with me for the next few steps as I will need your help.
Thanks again.
