### ISSUE TITLE
Error in HTK installation

### ISSUE THREAD

**Issue by BibekBazaz** [marytts/marytts#546]
Hello there,

I downloaded the HDecode-3.4.1.tar.gz and HTK-3.4.1.tar.gz packages and unpacked them in my home folder. Then I renamed the extracted HDecode-3.4.1.tar.gz folder which was named htk(2) to hts. Next I tried to make the patch by using the command

$ patch -p1 < HTS-2.2_for_HTK-3.4.1.patch

But it shows that I do not have the file present. I do not understand what am I missing. I followed the steps given by @seblemaguer  in issue #244 . Please guide me how to install the htk.

Also when i run the ./check_install_external_programs.sh file ,the output is : 
matarani@matarani-Lenovo-G580:~/marytts-master/lib/external$ ./check_install_external_programs.sh -install
MARY_BASE=/home/matarani/marytts-master

option=-install
awk: /usr/bin/awk
ok

perl: /usr/bin/perl
ok

tclsh: /usr/bin/tclsh
tclsh was found and supports snack
ok

bc: /usr/bin/bc
bc: checking -l (mathlib)
ok

sox: /usr/bin/sox
ok

HTK 3.4 and HDecode do not exist
HTK 3.4 and HDecode-3.4.1.tar.gz can be downloaded from: http://htk.eng.cam.ac.uk/download.shtml 
once HTK has been downloaded, apply the HTS patch, compile and install:
suggested commands:
  mkdir -p /home/matarani/marytts-master/lib/external/sw
  cp HTK-3.4.1.tar.gz /home/matarani/marytts-master/lib/external/sw
  cp HDecode-3.4.1.tar.gz /home/matarani/marytts-master/lib/external/sw
  cd /home/matarani/marytts-master/lib/external/sw
  mkdir HTS-patch
  cd HTS-patch
  wget http://hts.sp.nitech.ac.jp/archives/2.2/HTS-2.2_for_HTK-3.4.1.tar.bz2
  tar -jxvf HTS-2.2_for_HTK-3.4.1.tar.bz2
  cd ..
  tar -zxf HTK-3.4.1.tar.gz
  tar -zxf HDecode-3.4.1.tar.gz
  cd htk
  cp /home/matarani/marytts-master/lib/external/sw/HTS-patch/HTS-2.2_for_HTK-3.4.1.patch .
  patch -p1 -d . < HTS-2.2_for_HTK-3.4.1.patch
  ./configure --prefix=/home/matarani/marytts-master/lib/external/ MAXSTRLEN=2048
  make
  make install
The previous commands will be executed, it assumes that the files:
  HTK-3.4.1.tar.gz
  HDecode-3.4.1.tar.gz 
are in the current directory. continue (y/n)?
y
file: HTK-3.4.1.tar.gz and/or HDecode-3.4.1.tar.gz not found
download or copy HTK-3.4.1.tar.gz in the current directory
HTK 3.4 can be downloaded from: http://htk.eng.cam.ac.uk/download.shtml 

so please guide me through the steps i need to undergo to solve the issue.

**Comment by BibekBazaz** [comment]
@psibre Need your guidance again.

**Comment by seblemaguer** [comment]
Please, next time, try to solve your issue first and only if you can't solve it report your problem. Otherwise, it creates some useless notification on our side and prevents us to be efficient
