### ISSUE TITLE
WaveTimelineMaker (VoiceBuilding) issue.

### ISSUE THREAD

**Issue by BibekBazaz** [marytts/marytts#547]
Hello again, while running the WaveTimelineMaker and BasenameTimelineMaker I found the following exception:

Loading database layout:
Reading config file /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/database.config
Loading basename list from file /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst
Found 30 files in basename list
Loading features from file /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/mary/features.txt
---- Making a pitch synchronous waveform timeline

Processing [30] utterances.

---- Detected a global sample rate of: [44100] Hz.
---- Folding the wav files according to the pitchmarks...
Will create the waveform timeline in file [/home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/mary/timeline_waveforms.mry].
s01
java.lang.Error: EST track file [ /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/s01.pm] was not found.	java.io.FileNotFoundException:  /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/pm/s01.pm (No such file or directory)
	at marytts.util.data.ESTTrackReader.<init>(ESTTrackReader.java:90)
	at marytts.tools.voiceimport.WaveTimelineMaker.compute(WaveTimelineMaker.java:122)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

It says that the file does not exist. But they exist. And the location is correct. Still the problem exists. However when I run McepTimelineMaker, it works fine. So can you please tell me what is wrong with these two modules?
@psibre @giuliopaci

**Comment by BibekBazaz** [comment]
@psibre  pls guide me

**Comment by psibre** [comment]
Please attach your `database.config`.

**Comment by BibekBazaz** [comment]
@psibre  Here is my databse config file
[databse_congfig.txt](https://github.com/marytts/marytts/files/314659/databse_congfig.txt)

please look through this and suggest me the solutions.

**Comment by psibre** [comment]
I can see several issues, any of which might be causing problems, including the fact that you're using 44.1 kHz files.
The main problem is probably that you have an invalid `estDir`. I gave you [instructions](543#issuecomment-224840765) over in #543, but your config file still contains the invalid property. I don't see how you could have run MCEPMaker successfully, so I can only assume that your files are invalid/missing/corrupt.

More importantly, please understand the difference between the MaryTTS source code, the `target` directory under which it is built, and the voicebuilding directory, *which should be in another location entirely* as it has nothing to do with the MaryTTS source code.

I strongly recommend you start over in a clean voicebuilding directory, and make sure that your wav files are resampled to 16 kHz.

**Comment by BibekBazaz** [comment]
@psibre  Hello again,

I started voice building again. But now new error shows in LabelPauseDeleter Step. No files are generated and stored in the lab directory made by EHMM labeler. The stack trace is:

Loading database layout:
Reading config file /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/database.config
Reading external binaries config file /home/matarani/marytts-master/lib/external/externalBinaries.config
Loading basename list from file /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/basenames.lst
Found 30 files in basename list
Copying label files into lab directory ...
java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at marytts.tools.voiceimport.UnitLabel.getLabelUnitData(UnitLabel.java:177)
	at marytts.tools.voiceimport.UnitLabel.readLabFile(UnitLabel.java:124)
	at marytts.tools.voiceimport.LabelPauseDeleter.convertSingleLabelFile(LabelPauseDeleter.java:148)
	at marytts.tools.voiceimport.LabelPauseDeleter.getProperLabelFormat(LabelPauseDeleter.java:106)
	at marytts.tools.voiceimport.LabelPauseDeleter.compute(LabelPauseDeleter.java:88)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
     cannot read s01
30 out of 30 could not be read:
    s01
    s02
    s03
    s04
    s05
    s06
    s07
    s08
    s09
    s10
    s11
    s12
    s13
    s14
    s15
    s16
    s17
    s18
    s19
    s20
    s21
    s22
    s23
    s24
    s25
    s26
    s27
    s28
    s29
    s30
done.


So I dont understand what is the error now. The .lab files are not generated. So help me. 
The databse config file is as follows:

# GlobalProperties:
db.allophonesDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/allophones/
db.basenameFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/basenames.lst
db.domain general
db.estDir /usr/
db.gender male
db.halfphoneFeatureDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/halfphonefeatures/
db.halfphoneLabDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/halfphonelab/
db.hplabExtension .hplab
db.labDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/lab/
db.labExtension .lab
db.locale hi
db.maryServerHost localhost
db.maryServerPort 59125
db.marybase /home/matarani/marytts-master/
db.marybaseversion 5.2-SNAPSHOT
db.maryxmlDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/rawmaryxml/
db.maryxmlExtension .xml
db.phoneFeatureDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/phonefeatures/
db.phoneLabDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/phonelab/
db.pmDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/pm/
db.pmExtension .pm
db.promptAllophonesDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/prompt_allophones/
db.ptcDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/ptc/
db.ptcExtension .ptc
db.rootDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/
db.samplingrate 16000
db.textDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/text/
db.textExtension .txt
db.vocalizationsDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/vocalizations/
db.voicename my_voice
db.wavDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/wav/

# Properties for module PraatPitchmarker:
PraatPitchmarker.command praat
PraatPitchmarker.maxPitch 300
PraatPitchmarker.minPitch 75
PraatPitchmarker.pmDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/pm/
PraatPitchmarker.waveDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/wav/

# Properties for module MCEPMaker:
MCEPMaker.mcepDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mcep/

# Properties for module Festvox2MaryTranscripts:
Festvox2MaryTranscripts.transcriptFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/txt.done.data

# Properties for module AllophonesExtractor:
AllophonesExtractor.styleDefinitionFile 

# Properties for module EHMMLabeler:
EHMMLabeler.doAlignment true
EHMMLabeler.doTraining true
EHMMLabeler.eDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/ehmm/
EHMMLabeler.ehmmDir /home/matarani/marytts-master/lib/external/ehmm/
EHMMLabeler.nonDetEndFlag 0
EHMMLabeler.outputLabDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/lab/
EHMMLabeler.prepareFiles true
EHMMLabeler.promtallophonesDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/prompt_allophones/
EHMMLabeler.reTrainFlag false
EHMMLabeler.startEHMMModelDir /

# Properties for module HTKLabeler:
HTKLabeler.awkbin /usr/bin/awk
HTKLabeler.htDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices//htk/
HTKLabeler.htkDir /usr/bin/
HTKLabeler.maxNoOfIterations 150
HTKLabeler.maxshortPauseIteration 10
HTKLabeler.outputLabDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices//htk/lab/
HTKLabeler.promtallophonesDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices//prompt_allophones/

# Properties for module LabelPauseDeleter:
LabelPauseDeleter.eDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/ehmm/
LabelPauseDeleter.outputLabDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/lab/
LabelPauseDeleter.pauseDurationThreshold 100

# Properties for module HalfPhoneUnitLabelComputer:
HalfPhoneUnitLabelComputer.energyBasedTransientSplitting false

# Properties for module FeatureSelection:
FeatureSelection.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/features.txt
FeatureSelection.maryServerHost localhost
FeatureSelection.maryServerPort 59125

# Properties for module PhoneUnitFeatureComputer:
PhoneUnitFeatureComputer.allophonesDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/allophones/
PhoneUnitFeatureComputer.featureDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/phonefeatures/
PhoneUnitFeatureComputer.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/features.txt
PhoneUnitFeatureComputer.maryServerHost localhost
PhoneUnitFeatureComputer.maryServerPort 59125

# Properties for module HalfPhoneUnitFeatureComputer:
HalfPhoneUnitFeatureComputer.allophonesDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/allophones/
HalfPhoneUnitFeatureComputer.featureDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/halfphonefeatures/
HalfPhoneUnitFeatureComputer.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/features.txt
HalfPhoneUnitFeatureComputer.maryServerHost localhost
HalfPhoneUnitFeatureComputer.maryServerPort 59125

# Properties for module WaveTimelineMaker:
WaveTimelineMaker.waveTimeline /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/timeline_waveforms.mry

# Properties for module BasenameTimelineMaker:
BasenameTimelineMaker.timelineFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/timeline_basenames.mry

# Properties for module MCepTimelineMaker:
MCepTimelineMaker.mcepDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mcep/
MCepTimelineMaker.mcepTimeline /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/timeline_mcep.mry

# Properties for module PhoneUnitfileWriter:
PhoneUnitfileWriter.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/phoneUnits.mry

# Properties for module PhoneFeatureFileWriter:
PhoneFeatureFileWriter.featureDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/phonefeatures/
PhoneFeatureFileWriter.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/phoneFeatures.mry
PhoneFeatureFileWriter.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/phoneUnits.mry
PhoneFeatureFileWriter.weightsFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/phoneUnitFeatureDefinition.txt

# Properties for module DurationCARTTrainer:
DurationCARTTrainer.durTree /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/dur.tree
DurationCARTTrainer.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/phoneFeatures.mry
DurationCARTTrainer.isHnmTimeline false
DurationCARTTrainer.stepwiseTraining false
DurationCARTTrainer.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/phoneUnits.mry
DurationCARTTrainer.waveTimeline /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/timeline_waveforms.mry

# Properties for module F0CARTTrainer:
F0CARTTrainer.f0LeftTreeFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/f0.left.tree
F0CARTTrainer.f0MidTreeFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/f0.mid.tree
F0CARTTrainer.f0RightTreeFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/f0.right.tree
F0CARTTrainer.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/phoneFeatures.mry
F0CARTTrainer.isHnmTimeline false
F0CARTTrainer.stepwiseTraining false
F0CARTTrainer.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/phoneUnits.mry
F0CARTTrainer.waveTimeline /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/timeline_waveforms.mry

# Properties for module HalfPhoneUnitfileWriter:
HalfPhoneUnitfileWriter.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneUnits.mry

# Properties for module HalfPhoneFeatureFileWriter:
HalfPhoneFeatureFileWriter.featureDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/halfphonefeatures/
HalfPhoneFeatureFileWriter.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneFeatures.mry
HalfPhoneFeatureFileWriter.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneUnits.mry
HalfPhoneFeatureFileWriter.weightsFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneUnitFeatureDefinition.txt

# Properties for module F0PolynomialFeatureFileWriter:
F0PolynomialFeatureFileWriter.f0FeatureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/syllableF0Polynomials.mry
F0PolynomialFeatureFileWriter.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneFeatures.mry
F0PolynomialFeatureFileWriter.interpolate true
F0PolynomialFeatureFileWriter.isHnmTimeline false
F0PolynomialFeatureFileWriter.maxPitch 300
F0PolynomialFeatureFileWriter.minPitch 75
F0PolynomialFeatureFileWriter.polynomOrder 3
F0PolynomialFeatureFileWriter.showGraph false
F0PolynomialFeatureFileWriter.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneUnits.mry
F0PolynomialFeatureFileWriter.waveTimeLine /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/timeline_waveforms.mry

# Properties for module AcousticFeatureFileWriter:
AcousticFeatureFileWriter.acFeatDef /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneUnitFeatureDefinition_ac.txt
AcousticFeatureFileWriter.acFeatureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneFeatures_ac.mry
AcousticFeatureFileWriter.contourFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/syllableF0Polynomials.mry
AcousticFeatureFileWriter.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneFeatures.mry
AcousticFeatureFileWriter.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneUnits.mry

# Properties for module JoinCostFileMaker:
JoinCostFileMaker.acfeatureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneFeatures_ac.mry
JoinCostFileMaker.joinCostFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/joinCostFeatures.mry
JoinCostFileMaker.mcepDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mcep/
JoinCostFileMaker.mcepTimeline /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/timeline_mcep.mry
JoinCostFileMaker.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneUnits.mry
JoinCostFileMaker.weightsFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/joinCostWeights.txt

# Properties for module CARTBuilder:
CARTBuilder.acFeatureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneFeatures_ac.mry
CARTBuilder.callWagon false
CARTBuilder.cartFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/cart.mry
CARTBuilder.featureSeqFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/featureSequence.txt
CARTBuilder.maxLeafSize 10000000
CARTBuilder.mcepTimeline /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/timeline_mcep.mry
CARTBuilder.numProcesses 1
CARTBuilder.readFeatureSequence true
CARTBuilder.topLevelTreeFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/topLevel.tree
CARTBuilder.unitFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/halfphoneUnits.mry

# Properties for module HMMVoiceDataPreparation:
HMMVoiceDataPreparation.adaptScripts false
HMMVoiceDataPreparation.userRawDirectory 
HMMVoiceDataPreparation.userUttDirectory 

# Properties for module HMMVoiceConfigure:
HMMVoiceConfigure.adaptF0Ranges 'bdl 40 210 clb 130 260 jmk 50 180 rms 40 200 slt 110 280'
HMMVoiceConfigure.adaptHead b05
HMMVoiceConfigure.adaptScripts false
HMMVoiceConfigure.adaptSpkr slt
HMMVoiceConfigure.adaptSpkrMask */cmu_us_arctic_%%%_*
HMMVoiceConfigure.adaptTrainSpkr 'bdl clb jmk rms'
HMMVoiceConfigure.adaptTransKind feat
HMMVoiceConfigure.adaptTreeKind dec
HMMVoiceConfigure.configureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/hts/configure
HMMVoiceConfigure.dataSet cmu_us_arctic
HMMVoiceConfigure.fftLen 512
HMMVoiceConfigure.frameLen 400
HMMVoiceConfigure.frameShift 80
HMMVoiceConfigure.freqWarp 0.42
HMMVoiceConfigure.gamma 0
HMMVoiceConfigure.lf0BandWidth 1
HMMVoiceConfigure.lnGain 1
HMMVoiceConfigure.lowerF0 110
HMMVoiceConfigure.mgcBandWidth 35
HMMVoiceConfigure.mgcOrder 34
HMMVoiceConfigure.normalize 1
HMMVoiceConfigure.numIterations 5
HMMVoiceConfigure.numState 5
HMMVoiceConfigure.numTestFiles 5
HMMVoiceConfigure.questionsNum 001
HMMVoiceConfigure.sampfreq 16000
HMMVoiceConfigure.speaker slt
HMMVoiceConfigure.strBandWidth 5
HMMVoiceConfigure.strFilterFileName filters/mix_excitation_5filters_99taps_16Kz.txt
HMMVoiceConfigure.strOrder 5
HMMVoiceConfigure.upperF0 280
HMMVoiceConfigure.version 1
HMMVoiceConfigure.windowType 1

# Properties for module HMMVoiceFeatureSelection:
HMMVoiceFeatureSelection.featureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/features.txt
HMMVoiceFeatureSelection.hmmFeatureFile /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/hmmFeatures.txt

# Properties for module HMMVoiceMakeData:
HMMVoiceMakeData.adaptScripts false
HMMVoiceMakeData.featureListFile mary/hmmFeatures.txt
HMMVoiceMakeData.featureListMapFile mary/hmmFeaturesMap.txt
HMMVoiceMakeData.makeCMPMARY 1
HMMVoiceMakeData.makeLABELMARY 1
HMMVoiceMakeData.makeLF0 1
HMMVoiceMakeData.makeLIST 1
HMMVoiceMakeData.makeMGC 1
HMMVoiceMakeData.makeQUESTIONSMARY 1
HMMVoiceMakeData.makeSCP 1
HMMVoiceMakeData.makeSTR 1
HMMVoiceMakeData.questionsFile hts/data/questions/questions_qst001.hed
HMMVoiceMakeData.questionsUttFile hts/data/questions/questions_utt_qst001.hed
HMMVoiceMakeData.trickyPhonesFile mary/trickyPhones.txt

# Properties for module VoiceCompiler:
VoiceCompiler.compileDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice/
VoiceCompiler.mavenBin /usr/bin/mvn

# Properties for module HMMVoiceCompiler:
HMMVoiceCompiler.compileDir /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice-hsmm/
HMMVoiceCompiler.mavenBin /usr/bin/mvn

**Comment by BibekBazaz** [comment]
@psibre  Please reply as soon as possible as I have to meet a deadline. Thanks.

**Comment by BibekBazaz** [comment]
@seblemaguer @sathishpc @giuliopaci  please look into this problem

**Comment by psibre** [comment]
@BibekBazaz seriously, if you have a deadline, that's not our problem!

**Comment by BibekBazaz** [comment]
I did not mean to be rude or offensive. Sorry anyways @psibre . I appreciate all the help that you provided during the project.


Also about the issue here, I checked the generated lab files by EHMM Labeler and found that theyb were leaving a fourth component in the lines generated within the lab files. So that was the problem. I used HTK Labeler and the problem is solved.

**Comment by psibre** [comment]
@BibekBazaz no worries.

Thanks for following up. If you have time, could you please open a new issue about the EHMMLabeler generating malformed lab files?

**Comment by BibekBazaz** [comment]
First I will check for myself why it is malfunctioning. If I did not find
something of value I will open an issue.

**Comment by psibre** [comment]
So if I understand correctly, the issue here is solved by ensuring that the required files are not missing.
