### ISSUE TITLE
LoadHTKList: Label Name Expected

### ISSUE THREAD

**Issue by aWelker** [marytts/marytts#548]
Hi, its me again...

So, after getting the first three voicebuilding steps to work, I'm stuck with HTK at the moment. Terminal output looks like this:

```
Preparing voice database for labelling using HTK :
Setting up HTK directory ...
 ... done.
( /home/anna/Programme/htk/HTKTools//HLEd -l '*' -i /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones4.mlf /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/mkphone1.led /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones3.mlf; exit )

( /home/anna/Programme/htk/HTKTools//HLEd -l '*' -i /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones5.mlf /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/mkphone1.led /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones4.mlf; exit )

( /home/anna/Programme/htk/HTKTools//HLEd -l '*' -i /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones6.mlf /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/mkphone1.led /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones5.mlf; exit )

( /home/anna/Programme/htk/HTKTools//HLEd -l '*' -i /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones7.mlf /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/mkphone1.led /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones6.mlf; exit )

( /home/anna/Programme/htk/HTKTools//HLEd -l '*' -i /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones3.mlf /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/mkphone1.led /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones7.mlf; exit )

Feature Extraction:
( cd /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk/; /home/anna/Programme/htk/HTKTools//HCopy -T 1 -C /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/featEx.conf -S /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/featEx.list > log_featureExtraction.txt; exit )

... Done.
HTK Training:
( cd /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk/ ; mkdir hmm/hmm-dummy ;  mkdir hmm/hmm-final ; /home/anna/Programme/htk/HTKTools//HCompV -A -D -V -T 1 -C /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/htkTrain.conf -f 0.01 -m -S /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htkTrain.list -M /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//hmm/hmm-dummy /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/htk.proto > log_initialiseHTKTrain.txt; exit )

( cd /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk/; sh etc/htkTrainScript.sh > log_htkTrainScript.txt; exit )

Iteration number: 1
( cd /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk/; /home/anna/Programme/htk/HTKTools//HERest -A -D -V -T 1 -C /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//config/htkTrain.conf -I /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phones.mlf -t 250.0 150.0 1000.0 -S /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htkTrain.list -H /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//hmm/hmm0/macros -H /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//hmm/hmm0/hmmdefs -M /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//hmm/hmm1 /home/anna/DFKI/Arbeit_Mary/voice-dfki-antje/htk//etc/htk.phone.list >> log_herestTraining_1.txt; exit )

java.lang.Exception: The component HTKLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.MaryConfigurationException:   ERROR [+6550]  LoadHTKList: Label Name Expected
	at marytts.tools.voiceimport.HTKLabeler.herestTraining(HTKLabeler.java:1020)
	at marytts.tools.voiceimport.HTKLabeler.compute(HTKLabeler.java:247)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```
What I found out:
- the error is thrown by htk because there are lines (= labels) in htk.phones.mlf that start with a number
- htk.phones.mlf contains the phonemes corresponding to all basenames, one line per phoneme, and as SAMPA uses digits, most allophone sets will sooner or later run into this problem
- the usual way to solve this problem seems to be to escape all digits in the .mlf file using \
- the .mlf file is created automatically by HTKLabeler before running the HTKTools, so changing them manually has no effect
- the .mlf file is created from from all files in voicebuildingdirectory/prompt_allophones/
- escaping the digits in those xml files will cause HTKLabeler to crash

So, before I start messing around with HTKLabeler, is there any solution for this problem?

Thanks for any advice!

**Comment by psibre** [comment]
The HTKLabeler is experimental code to say the least. I'm afraid if you encounter errors using it, we don't have the resources to support you...
Having said that, perhaps you could replace your "tricky" phone names with non-numeric labels?

**Comment by aWelker** [comment]
That would be a possibility, but actually I just found a solution for it:
Someone already encountered this problem for German and created two methods in HTKLabeler, namely replaceTrickyPhonemes and replaceBackTrickyPhonemes. Anyone who is also struggeling with letters HTK cannot digest: add them to the list in both methods, this will allow you to keep your allophones.xml as it is and have HTK running as it is supposed to

**Comment by BenjaminPoilve** [comment]
Had the same issue in French.. Updated the file to support it: https://github.com/BenjaminPoilve/marytts/blob/master/marytts-builder/src/main/java/marytts/tools/voiceimport/HTKLabeler.java#L1775

Should I make a pull request?

**Comment by psibre** [comment]
@BenjaminPoilve thanks for the update! Please be aware that development on this part of the MaryTTS code ceased long ago. But if if helps between now and the complete removal of the corresponding module, please feel free to open a PR, but make it go into the 5.x branch.
