### ISSUE TITLE
as_pos.fst file not generated after transcription

### ISSUE THREAD

**Issue by Yamin372** [marytts/marytts#549]
All the other files are generated for my Locale Assamese language but the as_pos.fst is not generated and hence unable to proceed to the next step.

Any help will be appreciated.Thank you.@psibre

**Comment by psibre** [comment]
Please don't expect support if you don't provide any information about your problem.

**Comment by Yamin372** [comment]
@psibre I've solved the problem as of now.I will let you know with full details if i face another problem for sure.

**Comment by psibre** [comment]
@Yamin372 In the future, please consider trying to solve the problem first, and only opening a *meaningful* issue if you cannot.
