### ISSUE TITLE
marytts voice variation

### ISSUE THREAD

**Issue by nagaraj329550** [marytts/marytts#551]
I have installed marytts-5.2beta3. and i  am using dfki-prudence(English female) voice. while using the emotionml there is no voice variation differ(slight differ) between the sad,happy.angry,content tags. see the below examples using the dfki-prudence(English female)voice. Attached is the voice files. Please let us know if any settings or configurations to make.

``` xml
<emotionml version="1.0" xmlns="http://www.w3.org/2009/10/emotionml" 
category-set="http://www.w3.org/TR/emotion-voc/xml#everyday-categories">
Hi! Goodmorning.

<emotion><category name="angry"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="happy"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="sad"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="content"/>
Hi! Goodmorning..
</emotion>

  <emotion dimension-set="http://www.w3.org/TR/emotion-voc/xml#pad-dimensions">
Hi! Goodmorning.
    <dimension name="arousal" value="0.3"/><!-- lower-than-average arousal -->
    <dimension name="pleasure" value="0.9"/><!-- very high positive valence -->
    <dimension name="dominance" value="0.8"/><!-- relatively high potency    -->
  </emotion>

  <emotion dimension-set="http://www.w3.org/TR/emotion-voc/xml#pad-dimensions">
Hi! Goodmorning.
    <dimension name="arousal" value="0.9"/><!-- high arousal -->
    <dimension name="pleasure" value="0.2"/><!-- negative valence -->
    <dimension name="dominance" value="0.2"/><!-- low potency    -->
  </emotion>


</emotionml>
```

``` xml
<emotionml version="1.0" xmlns="http://www.w3.org/2009/10/emotionml" 
category-set="http://www.w3.org/TR/emotion-voc/xml#everyday-categories">
<emotion><category name="angry" value="0.25"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="angry" value="0.50"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="angry" value="0.75"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="angry" value="1.00"/>
Hi! Goodmorning.
</emotion>

</emotionml>
```

``` xml
<emotionml version="1.0" xmlns="http://www.w3.org/2009/10/emotionml" 
category-set="http://www.w3.org/TR/emotion-voc/xml#everyday-categories">
<emotion><category name="happy" value="0.25"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="happy" value="0.50"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="happy" value="0.75"/>
Hi! Goodmorning.
</emotion>

<emotion><category name="happy" value="1.00"/>
Hi! Goodmorning.
</emotion>

</emotionml>
```

[marytts-voice_sample.tar.gz](https://github.com/marytts/marytts/files/318175/marytts-voice_sample.tar.gz)

**Comment by psibre** [comment]
@nagaraj329550 please have a look at the markdown help, or at least use the nice toolbar right above the text box when you compose an issue or comment.

**Comment by psibre** [comment]
I'm not sure what you're asking, nor how this question is different from #541.

When you use different emotional categories, you get different prosodic parameter values. Those different prosodic paramter values lead to different acoustic parameters, and hence, different audio.

**Comment by nagaraj329550** [comment]
Which female voice is better for the supporting Expressive Style.

**Comment by psibre** [comment]
EmotionML input has nothing to do with the voice. It just predicts different prosodic paramters.

Sorry, I don't open Microsoft office files people link to on the internet.

**Comment by nagaraj329550** [comment]
I have attached the file with my observations
![marytts1](https://cloud.githubusercontent.com/assets/19771617/16152335/02a67d4e-34bf-11e6-8125-3ea19c0bef02.PNG)

**Comment by psibre** [comment]
Sorry, I don't understand what the table is supposed to tell us.

EmotionML is just one input type for MaryTTS.
1. The **EmotionmlParser** module converts `EMOTIONML` to `RAWMARYXML`.
2. Then, the `RAWMARYXML` is converted to `INTONATION` using the normal processing chain, *which has nothing to do with EmotionML*.
3. Finally, the `ACOUSTPARAMS` are predicted from the `INTONATION` and rendered to `AUDIO`, using whichever voice you select.

You have a lot of "not working" boxes etc. What would be helpful is if you could provide a reproducible example of what you believe is "not working", or how the "voice is breaking". Then we can try and figure out what is going on, and verify any bugs you might encountering which are otherwise unclear.

**Comment by nagaraj329550** [comment]
I tried marytts Rawmaryxml with below examples.
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<maryxml version="0.4"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://mary.dfki.de/2002/MaryXML"
xml:lang="en-US">
<prosody rate="+20%" pitch="+20%" range="-10%" volume="loud">
This is something you have to see!
</prosody>
</maryxml>
```
In the above example I tried different prosody rate, pitch,range values -10%,-20%,-60%,-80%,+20%,+40%,+60%, +100%, and volume am used "loud,soft,low,medium". no voice variation .


```xml
<?xml version="1.0" encoding="UTF-8" ?>
<maryxml version="0.5"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://mary.dfki.de/2002/MaryXML"
xml:lang="en-US">
Can you <boundary duration="100"/>
<t accent="H*">please</t> <boundary duration="100"/>
<t accent="unknown">listen</t> to <t accent="none">John</t>!
</maryxml>
```
in this above  example also no voice varition.
