### ISSUE TITLE
Hindi VoiceCompiler Issues

### ISSUE THREAD

**Issue by BibekBazaz** [marytts/marytts#552]
Hello, I am almost at the last step of Adding support for Hindi Language and I am stuck at voice compiler step. It shows the following error:
```
matarani@matarani-Lenovo-G580:~/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices$ ./voiceimport.sh 
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Loading database layout:
Reading config file /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/database.config
Reading external binaries config file /home/matarani/marytts-master/lib/external/externalBinaries.config
Loading basename list from file /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/basenames.lst
Found 29 files in basename list
Loading features from file /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/features.txt
INFO  VoiceCompiler: Creating directories
INFO  VoiceCompiler: Copying template files
INFO  VoiceCompiler: Copying voice files
INFO  VoiceCompiler: Compiling with Maven
maven out>[INFO] Scanning for projects...
maven out>[INFO]                                                                         
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Building voice-my_voice 5.2-SNAPSHOT
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] 
maven out>[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-java-7-or-higher) @ voice-my_voice ---
maven out>[INFO] 
maven out>[INFO] --- buildnumber-maven-plugin:1.3:create (default) @ voice-my_voice ---
maven out>[INFO] Executing: /bin/sh -c cd /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice && git rev-parse --verify HEAD
maven out>[INFO] Working directory: /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice
maven out>[INFO] Storing buildNumber: null at timestamp: 1466143335817
maven out>[WARNING] Cannot get the branch information from the git repository: 
maven out>Detecting the current branch failed: fatal: Not a git repository (or any parent up to mount point /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT)
maven out>Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
maven out>
maven out>[INFO] Executing: /bin/sh -c cd /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice && git rev-parse --verify HEAD
maven out>[INFO] Working directory: /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice
maven out>[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
maven out>[INFO] 
maven out>[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ voice-my_voice ---
maven out>[INFO] Using 'UTF-8' encoding to copy filtered resources.
maven out>[INFO] Copying 9 resources
maven out>[INFO] 
maven out>[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ voice-my_voice ---
maven out>[INFO] Changes detected - recompiling the module!
maven out>[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
maven out>[INFO] 
maven out>[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ voice-my_voice ---
maven out>[INFO] Using 'UTF-8' encoding to copy filtered resources.
maven out>[INFO] skip non existing resourceDirectory /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice/src/test/resources
maven out>[INFO] 
maven out>[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ voice-my_voice ---
maven out>[INFO] Changes detected - recompiling the module!
maven out>[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
maven out>[INFO] 
maven out>[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ voice-my_voice ---
maven out>[INFO] 
maven out>[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ voice-my_voice ---
maven out>[INFO] Building jar: /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice/target/voice-my_voice-5.2-SNAPSHOT.jar
maven out>[INFO] 
maven out>[INFO] --- maven-assembly-plugin:2.5.5:single (make-assembly) @ voice-my_voice ---
maven out>[INFO] Reading assembly descriptor: src/main/descriptors/installable.xml
maven out>[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /
maven out>[INFO] Building zip: /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice/target/voice-my_voice-5.2-SNAPSHOT.zip
maven out>[INFO] 
maven out>[INFO] --- groovy-maven-plugin:2.0:execute (default) @ voice-my_voice ---
maven out>[INFO] 
maven out>[INFO] --- build-helper-maven-plugin:1.9.1:attach-artifact (attach-artifacts) @ voice-my_voice ---
maven out>[INFO] 
maven out>[INFO] --- maven-failsafe-plugin:2.18.1:integration-test (integration-test) @ voice-my_voice ---
maven out>[INFO] Failsafe report directory: /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice/target/failsafe-reports
maven out>
maven out>-------------------------------------------------------
maven out> T E S T S
maven out>-------------------------------------------------------
maven out>Running marytts.voice.My_voice.LoadVoiceIT
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.082 sec <<< FAILURE! - in marytts.voice.My_voice.LoadVoiceIT
maven out>marytts.voice.My_voice.LoadVoiceIT  Time elapsed: 1.08 sec  <<< ERROR!
maven out>java.lang.Exception: Problem starting module Synthesis
maven out>	at marytts.unitselection.select.FFRTargetCostFunction.load(FFRTargetCostFunction.java:262)
maven out>	at marytts.unitselection.select.DiphoneFFRTargetCostFunction.load(DiphoneFFRTargetCostFunction.java:68)
maven out>	at marytts.unitselection.select.DiphoneFFRTargetCostFunction.load(DiphoneFFRTargetCostFunction.java:58)
maven out>	at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:111)
maven out>	at marytts.unitselection.UnitSelectionSynthesizer.startup(UnitSelectionSynthesizer.java:94)
maven out>	at marytts.modules.Synthesis.startupSynthesizers(Synthesis.java:73)
maven out>	at marytts.modules.Synthesis.startup(Synthesis.java:65)
maven out>	at marytts.server.Mary.startModules(Mary.java:149)
maven err>Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
maven out>	at marytts.server.Mary.startup(Mary.java:297)
maven err>	at marytts.server.Mary.shutdown(Mary.java:371)
maven out>	at marytts.server.Mary.startup(Mary.java:204)
maven err>	at marytts.server.Mary$2.run(Mary.java:290)
maven out>	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
maven out>	at marytts.voice.My_voice.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>
maven out>
maven out>Results :
maven out>
maven out>Tests in error: 
maven out>  LoadVoiceIT.beforeClass:14 »  Problem starting module Synthesis
maven out>
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
maven out>
maven out>[INFO] 
maven out>[INFO] --- maven-failsafe-plugin:2.18.1:verify (verify) @ voice-my_voice ---
maven out>[INFO] Failsafe report directory: /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice/target/failsafe-reports
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] BUILD FAILURE
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Total time: 14.534s
maven out>[INFO] Finished at: Fri Jun 17 11:32:26 IST 2016
maven out>[INFO] Final Memory: 23M/119M
maven out>[INFO] ------------------------------------------------------------------------
maven out>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify (verify) on project voice-my_voice: There are test failures.
maven out>[ERROR] 
maven out>[ERROR] Please refer to /home/matarani/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices/mary/voice-my_voice/target/failsafe-reports for the individual test results.
maven out>[ERROR] -> [Help 1]
maven out>[ERROR] 
maven out>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
maven out>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
maven out>[ERROR] 
maven out>[ERROR] For more information about the errors and possible solutions, please read the following articles:
maven out>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
java.lang.Exception: The component VoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:375)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:95)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
matarani@matarani-Lenovo-G580:~/marytts-master/target/marytts-builder-5.2-SNAPSHOT/voices$ 
```

Now , I have used HTK Labeler. Please tell me how can I solve this problem. Thanks in advance.

**Comment by BibekBazaz** [comment]
@sathishpc @psibre Need your help. Please help.

**Comment by seblemaguer** [comment]
As said in a previous issue, we are not here at your disposal for your deadline. Spamming by creating issues at every stage of the processing especially finding the solution 2h after dedicating little bit of effort on it. Tagging users just for help and spamming their notification management is not acceptable. Next time, I report an user abuse

**Comment by BibekBazaz** [comment]
I apologized for that already.And I put an issue here because I think there myt be a solution already. Sorry if that caused a problem. But right now I need your help. So please excuse mt ignorances and help me out.

**Comment by psibre** [comment]
If you think there might be a solution already, then please use the search functionality provided by GitHub for this repository, where you will discover any similar issues that were opened -- and hopefully solved -- in the past.

**Comment by psibre** [comment]
The maven output you pasted gives you a stacktrace, and refers to a report which may provide clues as to what is going wrong. Please attach that report.

**Comment by BibekBazaz** [comment]
[reports.zip](https://github.com/marytts/marytts/files/321613/reports.zip)

I believe these are the reports that the stack trace is referring to. Please check them. And thanks for informing about the search feature. I am new to github and this is my very first project, so I did create some problems for you guys. I am sorry for the inconvenience.

**Comment by BibekBazaz** [comment]
this is the contents of my voice.config

# Auto-generated config file for voice my_voice

name = my_voice
locale = hi

####################################################################
####################### Module settings  ###########################
####################################################################
# For keys ending in ".list", values will be appended across config files,
# so that .list keys can occur in several config files.
# For all other keys, values will be copied to the global config, so
# keys should be unique across config files.

unitselection.voices.list = \
	my_voice

# If this setting is not present, a default value of 0 is assumed.
# More means higher assumed quality.
voice.my_voice.wants.to.be.default = 0


# Set your voice specifications
voice.my_voice.gender = male
voice.my_voice.locale = hi
voice.my_voice.domain = general
voice.my_voice.samplingRate = 16000

# Relative weight of the target cost function vs. the join cost function
voice.my_voice.viterbi.wTargetCosts = 0.7

# Beam size in dynamic programming: smaller => faster but worse quality.
# (set to -1 to disable beam search; very slow but best available quality)
voice.my_voice.viterbi.beamsize = 100

# Java classes to use for the various unit selection components
voice.my_voice.databaseClass            = marytts.unitselection.data.DiphoneUnitDatabase
voice.my_voice.selectorClass            = marytts.unitselection.select.DiphoneUnitSelector
voice.my_voice.concatenatorClass        = marytts.unitselection.concat.OverlapUnitConcatenator
voice.my_voice.targetCostClass          = marytts.unitselection.select.DiphoneFFRTargetCostFunction
voice.my_voice.joinCostClass            = marytts.unitselection.select.JoinCostFeatures
voice.my_voice.unitReaderClass          = marytts.unitselection.data.UnitFileReader
voice.my_voice.cartReaderClass          = marytts.cart.io.MARYCartReader
voice.my_voice.audioTimelineReaderClass = marytts.unitselection.data.TimelineReader

# Voice-specific files
voice.my_voice.featureFile       = MARY_BASE/lib/voices/my_voice/halfphoneFeatures_ac.mry
voice.my_voice.targetCostWeights = jar:/marytts/voice/My_voice/halfphoneUnitFeatureDefinition_ac.txt
voice.my_voice.joinCostFile      = MARY_BASE/lib/voices/my_voice/joinCostFeatures.mry
voice.my_voice.joinCostWeights   = jar:/marytts/voice/My_voice/joinCostWeights.txt
voice.my_voice.unitsFile         = MARY_BASE/lib/voices/my_voice/halfphoneUnits.mry
voice.my_voice.cartFile          = jar:/marytts/voice/My_voice/cart.mry
voice.my_voice.audioTimelineFile = MARY_BASE/lib/voices/my_voice/timeline_waveforms.mry
voice.my_voice.basenameTimeline  = MARY_BASE/lib/voices/my_voice/timeline_basenames.mry

# Modules to use for predicting acoustic target features for this voice:

voice.my_voice.acousticModels = duration F0 midF0 rightF0

voice.my_voice.duration.model = cart
voice.my_voice.duration.data = jar:/marytts/voice/My_voice/dur.tree
voice.my_voice.duration.attribute = d

voice.my_voice.F0.model = cart
voice.my_voice.F0.data = jar:/marytts/voice/My_voice/f0.left.tree
voice.my_voice.F0.attribute = f0
voice.my_voice.F0.attribute.format = (0,%.0f)
voice.my_voice.F0.predictFrom = firstVowels
voice.my_voice.F0.applyTo = firstVoicedSegments

voice.my_voice.midF0.model = cart
voice.my_voice.midF0.data = jar:/marytts/voice/My_voice/f0.mid.tree
voice.my_voice.midF0.attribute = f0
voice.my_voice.midF0.attribute.format = (50,%.0f)
voice.my_voice.midF0.predictFrom = firstVowels
voice.my_voice.midF0.applyTo = firstVowels

voice.my_voice.rightF0.model = cart
voice.my_voice.rightF0.data = jar:/marytts/voice/My_voice/f0.right.tree
voice.my_voice.rightF0.attribute = f0
voice.my_voice.rightF0.attribute.format = (100,%.0f)
voice.my_voice.rightF0.predictFrom = firstVowels
voice.my_voice.rightF0.applyTo = lastVoicedSegments

**Comment by psibre** [comment]
> I am new to github

In that case, welcome. Please take a moment to learn about [markdown](https://guides.github.com/features/mastering-markdown/), and also **Preview** your posts before you submit them.

**Comment by psibre** [comment]
It seems the report doesn't provide anything beyond what the original Maven output already said...
```
java.lang.Exception: Problem starting module Synthesis
	at marytts.unitselection.select.FFRTargetCostFunction.load(FFRTargetCostFunction.java:262)
	at marytts.unitselection.select.DiphoneFFRTargetCostFunction.load(DiphoneFFRTargetCostFunction.java:68)
	at marytts.unitselection.select.DiphoneFFRTargetCostFunction.load(DiphoneFFRTargetCostFunction.java:58)
	at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:111)
	at marytts.unitselection.UnitSelectionSynthesizer.startup(UnitSelectionSynthesizer.java:94)
	at marytts.modules.Synthesis.startupSynthesizers(Synthesis.java:73)
	at marytts.modules.Synthesis.startup(Synthesis.java:65)
	at marytts.server.Mary.startModules(Mary.java:149)
	at marytts.server.Mary.startup(Mary.java:297)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
	at marytts.voice.My_voice.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
```
The actual exception message is unfortunately gobbled, but the relevant lines of code are:
```java
			if (!newWeights.featureEquals(featureDefinition)) {
				throw new IOException("Weights file: feature definition incompatible with feature file");
			}
```
So something is wrong with your features. You may have to rebuild again, but if the problem persists, you'll need to debug. You can do that in Eclipse (see [the wiki](../wiki/Eclipse_5.X)).

**Comment by BibekBazaz** [comment]
i need a suggestion, the cart wagon step produces the files viz :
 cart.mry,dur.tree, f0.left.tree,f0.mid.tree,f0.right.tree etc ,
 i need to know and view the content of these files ? can anyone help me in the same cause.

**Comment by psibre** [comment]
@BibekBazaz I don't see what the CART files have to do with anything in this issue.

**Comment by BibekBazaz** [comment]
Hello @psibre . Thank you so much for all the help all along the way. But now that I have worked with MaryTTS once, I would like to know more about the outputs of each and every step, and how the data is flowing through the entire system so that I can yield better results when adding support for Hindi langauge again. So please guide me as to how can I get to know about the outputs of the voice building step like about .pm, .mcep files etc. in detail.

**Comment by psibre** [comment]
@BibekBazaz you mean something like this?

http://www.coli.uni-saarland.de/~steiner/teaching/2016/summer/voicebuilding/slides/#/task-execution-graph

**Comment by BibekBazaz** [comment]
yes thanks.
