### ISSUE TITLE
HTKLabelerException

### ISSUE THREAD

**Issue by Yamin372** [marytts/marytts#553]
yamin@YaminHP:~/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin$ ./voiceimport.sh 
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
OpenJDK Server VM (build 24.95-b01, mixed mode)

Loading database layout:
Reading config file /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/database.config
Reading external binaries config file /home/yamin/iamnew/marytts-master/lib/external/externalBinaries.config
Loading basename list from file /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin/basenames.lst
Found 11 files in basename list
Preparing voice database for labelling using HTK :
Setting up HTK directory ...
 ... done.
( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones4.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones3.mlf; exit )

( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones5.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones4.mlf; exit )

( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones6.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones5.mlf; exit )

( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones7.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones6.mlf; exit )

( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones3.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones7.mlf; exit )

Feature Extraction:
( cd /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk/; /home/yamin/iamnew/marytts-master/lib/external/bin//HCopy -T 1 -C /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/featEx.conf -S /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/featEx.list > log_featureExtraction.txt; exit )

... Done.
HTK Training:
( cd /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk/ ; mkdir hmm/hmm-dummy ;  mkdir hmm/hmm-final ; /home/yamin/iamnew/marytts-master/lib/external/bin//HCompV -A -D -V -T 1 -C /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/htkTrain.conf -f 0.01 -m -S /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htkTrain.list -M /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//hmm/hmm-dummy /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/htk.proto > log_initialiseHTKTrain.txt; exit )

( cd /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk/; sh etc/htkTrainScript.sh > log_htkTrainScript.txt; exit )

Iteration number: 1
( cd /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk/; /home/yamin/iamnew/marytts-master/lib/external/bin//HERest -A -D -V -T 1 -C /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/htkTrain.conf -I /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones.mlf -t 250.0 150.0 1000.0 -S /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htkTrain.list -H /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//hmm/hmm0/macros -H /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//hmm/hmm0/hmmdefs -M /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//hmm/hmm1 /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phone.list >> log_herestTraining_1.txt; exit )

java.lang.Exception: The component HTKLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.MaryConfigurationException:   ERROR [+5013]  ReadString: String too long
	at marytts.tools.voiceimport.HTKLabeler.herestTraining(HTKLabeler.java:1020)
	at marytts.tools.voiceimport.HTKLabeler.compute(HTKLabeler.java:247)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
Preparing voice database for labelling using HTK :
Setting up HTK directory ...
 ... done.
( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones4.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones3.mlf; exit )

( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones5.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones4.mlf; exit )

( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones6.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones5.mlf; exit )

( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones7.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones6.mlf; exit )

( /home/yamin/iamnew/marytts-master/lib/external/bin//HLEd -l '*' -i /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones3.mlf /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/mkphone1.led /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones7.mlf; exit )

Feature Extraction:
( cd /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk/; /home/yamin/iamnew/marytts-master/lib/external/bin//HCopy -T 1 -C /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/featEx.conf -S /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/featEx.list > log_featureExtraction.txt; exit )

... Done.
HTK Training:
( cd /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk/ ; mkdir hmm/hmm-dummy ;  mkdir hmm/hmm-final ; /home/yamin/iamnew/marytts-master/lib/external/bin//HCompV -A -D -V -T 1 -C /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/htkTrain.conf -f 0.01 -m -S /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htkTrain.list -M /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//hmm/hmm-dummy /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/htk.proto > log_initialiseHTKTrain.txt; exit )

( cd /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk/; sh etc/htkTrainScript.sh > log_htkTrainScript.txt; exit )

Iteration number: 1
( cd /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk/; /home/yamin/iamnew/marytts-master/lib/external/bin//HERest -A -D -V -T 1 -C /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//config/htkTrain.conf -I /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phones.mlf -t 250.0 150.0 1000.0 -S /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htkTrain.list -H /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//hmm/hmm0/macros -H /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//hmm/hmm0/hmmdefs -M /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//hmm/hmm1 /home/yamin/iamnew/marytts-master/target/marytts-builder-5.2-SNAPSHOT/bin//htk//etc/htk.phone.list >> log_herestTraining_1.txt; exit )

java.lang.Exception: The component HTKLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.MaryConfigurationException:   ERROR [+5013]  ReadString: String too long
	at marytts.tools.voiceimport.HTKLabeler.herestTraining(HTKLabeler.java:1020)
	at marytts.tools.voiceimport.HTKLabeler.compute(HTKLabeler.java:247)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

Please help me with this @psibre @sathishpc @entenbein

**Comment by psibre** [comment]
Please don't spam people by mentioning them if they have nothing to do with the issue.

The HTKLabeler is experimental, and not supported. Use something else if it doesn't work for you.
