### ISSUE TITLE
ASL 2.0 | MIT | BSD

### ISSUE THREAD

**Issue by sirinath** [marytts/marytts#554]
Is it possible to relicense this under more permissive license like ASL 2.0?

**Comment by seblemaguer** [comment]
hello,

why would you need to have a more permissive license ?

**Comment by sirinath** [comment]
There are many instances we cannot use *GPL licenses. Generally ASL 2.0, MIT, BSD are the most commonly whitelisted libraries.

**Comment by seblemaguer** [comment]
I'm not a specialist about license, but in order to discuss with my colleagues about it, I need to know more precisely why do you need to have a more permissive license. Is it for a future plan already defined ? Or is it for more general purposes ?

**Comment by sirinath** [comment]
More general purpose. Want to add ability to give voice instruction in an app.

**Comment by psibre** [comment]
Please see [the FAQ](http://mary.dfki.de/faq.html#commercial-use). If that is not sufficient, please provide a compelling reason why you would need a different license.

**Comment by sirinath** [comment]
The points are:
 - many organisations have whitelisted licenses
 - lesser number of orgs have *GPL whitelisted
 - when *GPL components are used you have to spend time explaining why a particular *GPL component is acceptable. This time can be better used doing more productive / billable work.

**Comment by psibre** [comment]
OK, but the fact that some hypothetical org might not have LGPL whitelisted is not really our problem. We'd rather spend *our* time with more productive/billable work than to renegotiate the MaryTTS license with *our* legal department.
