### ISSUE TITLE
Acronym/Abbrev handling

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#556]
Hi guys,

let's say I got _JP_ in my abbrev list with a transcription that differs from the one for the single letters _J_ and _P_. This works fine for the voice build and the occurrence of _JP_ I got in my training script.

When I synthesize _JPG_ it will be deconstructed to _J P G_, so far so good. If I synthesize _J P G_ it will come out as _JP G_ (with the transcription for my _JP_ abbrev). 

a) Why are those single upper case letters put together if they are explicitly typed in with blanks in between?
b) Why does _J P G_ matches _JP_ and _JPG_ does not?

Thanks for your help!

PS: This happens to me using the locale **de**.

**Comment by seblemaguer** [comment]
Hello

a) I don't have manage to reproduce the same behaviour, on my side "J P G" leads to :
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t g2p_method="lexicon" ph="' j O t" pos="NN">
J
</t>
<t g2p_method="lexicon" ph="' p e:" pos="NE">
P
</t>
<t g2p_method="lexicon" ph="' g e:" pos="NE">
G
</t>
</s>
</p>
</maryxml>
```

**Comment by entenbein** [comment]
That worked out in the end. Thanks!

But I came across another case:

In a sentence which ends with **Pertl.** (that's the maiden name of Mozarts mother...), **Pertl.** will be recognized as acronym and will every letter will be spelled separately. The entry is not in the lexicon. So far so good.
I checked `AbbrevEP.java` and modified the `isAbbrev` method: out of the checked patterns only *isLetterDot* matches. Still reproducible.

But then **Perdl.** is processed like any other unknown word. Again **Paktr.** behaves like **Pertl.** .

Can you explain that?

**Comment by seblemaguer** [comment]
Hello,

in order for me to reproduce properly, can you indicate the whole sentence ?

**Comment by entenbein** [comment]
Hi,

the full sentence would be 

> Sein Vater war der aus Augsburg zum Studium an der Benediktineruniversität nach Salzburg gezogene, fürstbischöfliche Kammermusikus (ab 1757 Hofkomponist und ab 1763 Vizekapellmeister) Leopold Mozart, seine Mutter die in Sankt Gilgen aufgewachsene Anna Maria Pertl. 

I guess 
> seine Mutter die in Sankt Gilgen aufgewachsene Anna Maria Pertl. 

works just as well.

In the last post I should probably have mentioned that this occurs for German.

Thank you!

**Comment by entenbein** [comment]
@seblemaguer any ideas?

**Comment by seblemaguer** [comment]
The main problem is the following : how do deal with unknown word and unknown acronyms. The current strategy is any word ending with a dot is treated like an acronym. I have a strategy to deal with acronyms which consists considering only uppercase (full uppercase) unknown word as an acronym. But I don't know if it is accurate for german

**Comment by seblemaguer** [comment]
we will check that while addressing #608. In between you can add your unknown words in a personnal lexicon

**Comment by nshmyrev** [comment]
There must be a database first like a dictionary but expanding to words, then things could be learned from it. But database is always a primary source. It could also serve as a test case for machine learning algorithms. Overall, it going to be an important resource.

**Comment by seblemaguer** [comment]
@nshmyrev I was thinking about that but I also want to see what is the strategy propose by the icu library (if there is something in it)

**Comment by entenbein** [comment]
@seblemaguer I'd say that upper-case only words have a high probability to be acronyms in German and they should be split down into the single letters. But then there is **NATO** and **UNO**, which you can perfectly spell/read. Camel-case words should be treated as acronyms as well, e.g. **GmbH**.

All quite comprehensible, but do you got any idea why **Pertl.** behaves different than **Perkl.**?

Thanks!

**Comment by psibre** [comment]
> All quite comprehensible, but do you got any idea why Pertl. behaves different than Perkl.?

Because of [this line](../blob/a3d635efc3019be67a67f3dc7a5633cbb6f1a73e/marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/preprocess/AbbrevEP.java#L103) that identifies "Pertl." as a token consisting of letters *with a dot attached*.

The cause of the weird behavior you reported is actually earlier, where the tokenizer fails to split off the period after "Pertl", but *does so* for "Perkl".

**Comment by entenbein** [comment]
Alright, so that is just a tokenizer _misfunction_. So if the tokenzier works correctly and the period is recognized as a separate token, for which case will `isLetterDot` return `true` then?

**Comment by psibre** [comment]
Digging deeper, I notice that the [tokenizer determines the `tokenEnd`](../blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-runtime/src/main/java/marytts/modules/JTokeniser.java#L156) to be 5 for "Perkl.", but 6 for "Pertl.", which causes the dot in the latter case to remained attached to the token, causing the downstream misclassification as an acronym. I have no idea why this happens.
