### ISSUE TITLE
Where do i find marytts-server.sh script

### ISSUE THREAD

**Issue by Nandutu** [marytts/marytts#562]
Hello 
Am adding a new language luganda to marytts i have done previous steps successfully and partially step 4 of  Minimal NLP components for the new language.
I use ubuntu 14.04 
After building the project successfully with mvn install. I am now failing to run the server , i find no shell script from both location /home/irene/TTS/mary/marytts/target/marytts-5.2-SNAPSHOT/bin and /home/irene/TTS/mary/marytts/target/marytts-builder-5.2-SNAPSHOT/bin.
Is there any location i can find the script.?
I request for some guidance on this.
I will be grateful

**Comment by psibre** [comment]
`marytts-server`

It was renamed back in 3d84d8e27dd2b3946f80cf607e40c0251bebe231

**Comment by Nandutu** [comment]
I was later successful, i used locations /home/irene/TTS/mary/marytts/target/marytts-5.2-SNAPSHOT/bin and typed ./marytts-server in the prompt.
Server was up and running
Thanks
