### ISSUE TITLE
Server cannot access my added locale-lg

### ISSUE THREAD

**Issue by Nandutu** [marytts/marytts#563]
Hello i have been following https://github.com/marytts/marytts/wiki/New-Language-Support to add new language luganda to marytts.
I have successfully finished step 3. On step 4 Minimal NLP components for the new language
i managed to build my language as 
$ cd marytts-lang-lg
$ mvn test
After  adding my language module to marytts-assembly/assembly-builder/pom.xml. I also succeeded on building the full project as 
$ cd marytts
$ mvn install

When i run the server all seems well as below
/TTS/mary/maryttz/target/marytts-5.2-SNAPSHOT/bin$ ./marytts-server
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

MARY server 5.2-SNAPSHOT starting as a HTTP server... started in 5.872 s on port 59125

The issue is when  i try to access the port on locale as http://localhost:59125/locales i get the output minus my locale lg
fr
lb
it
ru
de
en_US
en_GB
tr
sv
te

Can some one help, i will be very gratefull.

**Comment by seblemaguer** [comment]
Assuming you have managed to create the language jar, it means that you haven't added it to the classpath of the server.

**Comment by Nandutu** [comment]
After checking my path /home/irene/TTS/mary/maryttz/target/marytts-5.2-SNAPSHOT/lib . I cannot find the .jar file associated to my language. 
kindly some insights on creating .jar file and adding it on the class path of the server
Thanks

**Comment by Nandutu** [comment]
Hello, can some one help me on the above issue.
Thanks

**Comment by seblemaguer** [comment]
are youo sure the process of the voice creation succeeded ?

**Comment by psibre** [comment]
Two things:

1. You should make sure that your `marytts-lang-lg` component actually passes its tests. If you haven't, take a look at how the other languages have a `*ConfigTest` class, and make sure that your component can be loaded; you can inspect your `marytts-lang-lg/target/surefire-reports/testng-junit-results/index.html` or similar.
2. The `bin/*` startup scripts have no notion of artifacts or dependencies; they just try to load whatever is in `lib/*`. To hook your new `marytts-lang-lg` into the `package` tasks that copy the jar files to those locations, you'll need to ensure that they are mentioned in the right places in the POMs and build scripts under `marytts-assembly`.

**Comment by Nandutu** [comment]
Hello may be to start with, these are the results i get when i build the new language. 

irene@irene-HP-650-Notebook-PC:~/TTS/mary/maryttz/marytts-languages/marytts-lang-lg$ mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-lang-lg 5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-lang-lg ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-lang-lg ---
[INFO] Executing: /bin/sh -c cd '/home/irene/TTS/mary/maryttz/marytts-languages/marytts-lang-lg' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/irene/TTS/mary/maryttz/marytts-languages/marytts-lang-lg
[INFO] Storing buildNumber: null at timestamp: 1467900205777
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

[INFO] Executing: /bin/sh -c cd '/home/irene/TTS/mary/maryttz/marytts-languages/marytts-lang-lg' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/irene/TTS/mary/maryttz/marytts-languages/marytts-lang-lg
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ marytts-lang-lg ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 12 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ marytts-lang-lg ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ marytts-lang-lg ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/irene/TTS/mary/maryttz/marytts-languages/marytts-lang-lg/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ marytts-lang-lg ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ marytts-lang-lg ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running marytts.language.lg.LugandaConfigTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.175 sec - in marytts.language.lg.LugandaConfigTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.484 s
[INFO] Finished at: 2016-07-07T17:03:30+03:00
[INFO] Final Memory: 14M/181M
[INFO] ------------------------------------------------------------------------
irene@irene-HP-650-Notebook-PC:~/TTS/mary/maryttz/marytts-languages/marytts-lang-lg$ 

I just know some thing is wrong i have failed to trace.

**Comment by Nandutu** [comment]
Although when i was working on this step all was okay
$ cd marytts/marrytts-languages
$ cp -r marytts-lang-tr marytts-lang-xy
$ cd marytts-lang-xy

but with this step i just deleted manually the target folder and typed ls-as to see the generated files. i failed to trace  .project and .classpath in my output.
$ rm target .project .classpath # these are generated files
Could the issue generate from here.
My POMs where included as here which i know is correct
adding the language project as a new subproject into the master pom:
marytts/marytts-languages/pom.xml

<module>marytts-lang-lg</module>  

include it as a dependency in the assembly-plugin:
marytts/marytts-assembly/assembly-runtime/pom.xml

<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>marytts-lang-lg</artifactId>
			<version>${project.version}</version>
		</dependency>

**Comment by psibre** [comment]
OK, it looks like your tests are passing, but the assembly is not packaging your language component.
I think it would be easiest, if you could push a feature branch to your fork of marytts, so that we can have a look at what's going on.

**Comment by Nandutu** [comment]
Hi @psibre @seblemaguer here is the link to my fork of marytts https://github.com/Nandutu/marytts/tree/8e9e4d65e27e7c87d57f69ca56ac59740618df89
Areas modified: 
	modified:   marytts-assembly/assembly-runtime/pom.xml
	modified:   marytts-languages/pom.xml
Areas added:
	marytts-languages/marytts-lang-lg/
	marytts-languages/pom.xml~
	wiki_data/
Am using 
1. java version "1.7.0_101"
2. Apache Maven 3.2.1 
3. Ubuntu 14.04
4. Marytts 5.2

Am grateful

**Comment by psibre** [comment]
@Nandutu git submodules are cool and I use them a lot, but we can't help if we can't access yours.

**Comment by Nandutu** [comment]
submodules are really teasing me being its my first time - its only that i have to update marytts-lang-lg that am finding an issue, i afforded to fork marytts while doing an upstream. Let me know if this can be helpful
https://github.com/Nandutu/marytts
Thanks

**Comment by Nandutu** [comment]
After keenly analysing @seblemaguer first comment i have come to realise this path /home/irene/TTS/mary/maryttz/marytts-languages/marytts-lang-lg/target has both marytts-lang-lg-5.2-SNAPSHOT-sources.jar and marytts-lang-lg-5.2-SNAPSHOT.jar but path /home/irene/TTS/mary/maryttz/target/marytts-5.2-SNAPSHOT/lib has no my new language .jar files yet i find other .jar files for other mary languages.
At this point, what next do you think i can do to have my language .jar file in /home/irene/TTS/mary/maryttz/target/marytts-5.2-SNAPSHOT/lib

Thanks

**Comment by psibre** [comment]
@Nandutu I still don't see your git submodule anywhere, but regardless I should point out that the assembly modules actually call gradle to substitute for the maven-assembly-plugin, which was causing severe issues with our builds.

Gradle has its own notion of subprojects, so to have your language component picked up, you should add to `settings.gradle` the line
```
include 'marytts-languages:marytts-lang-lg'
```
This may solve the issue for you.

**Comment by Nandutu** [comment]
You are right...submodules is a new area am understanding am working on it...pull requests are the ones i had ventured.

Wow!!! Thanks my local lg appeared after adding to the include 'marytts-languages:marytts-lang-lg'.
However if i proceed all still goes well, on step 7 after wkdb_synthesis_script_GUI.sh wkdb.conf 
the sysnthetic script gui opens but does not load data if i open Run DatabaseSelector or Load selected sentences table.

commandline shows this error
irene@irene-HP-650-Notebook-PC:~/github/project/maryttslg/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_synthesis_script_GUI.sh wkdb.conf 
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

Mysql driver loaded, set locale=lg
Mysql connection created successfully.
WARNING empty list for: SELECT dbselection_id FROM lg_test_selectedSentences where unwanted=false;

**Comment by Nandutu** [comment]
@psibre ,
I cloned my submodule git submodule add  https://github.com/Nandutu/marytts.git marytts from a forked marytts
I think I a challenge with creating submodules to use with this project. Bellow is what I have done I need help.
1. Created an empty project repository.
2. I cloned marytts as a submodule from my forked marytts project using this 
`irene@irene-HP-650-Notebook-PC:~/github/project$ git submodule add  https://github.com/Nandutu/marytts.git marytts
`
3. I did all the necessary things need for me to work with the created submodules as per this  [example](https://chrisjean.com/git-submodules-adding-using-removing-and-updating/)
4. After all that, I went into the submodule directory and pushed the changes that I had commited to the my master branch[here](https://github.com/Nandutu/marytts/commit/4a53cbe9f8599762ee3465d9e047239ce299dcba)

Am wondering whenther I did the submodule creation correctly! Do I have to push the changes to my forked version or the main marytts version? 
Could you please guide me on how best to do it incase the link I have given above does not have the correct pushed submodule.

**Comment by Nandutu** [comment]
Hello i just failed to successfully have git submodule. Am requesting you help me using marytts forked repo since you still can access my changes
I was wondering if my error came because of transcription stage.
How long does it take to transcribe 243 words.

when i write transcription.sh in commandline.....the output runs minus stopping as here.
What could be the problem? The program doesnot stop


irene@irene-HP-650-Notebook-PC:~/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ ./transcription.sh 
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

prev: Serif
next: Serif
alignment ... 
iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
alignment completed.
training ... 
      Training decision tree for: f
      Training decision tree for: g
      Training decision tree for: d
      Training decision tree for: e
      Training decision tree for: b
      Training decision tree for: a
      Training decision tree for: n
      Training decision tree for: o
      Training decision tree for: l
      Training decision tree for: m
      Training decision tree for: j
      Training decision tree for: k
      Training decision tree for: i
      Training decision tree for: w
      Training decision tree for: v
      Training decision tree for: u
      Training decision tree for: t
      Training decision tree for: s
      Training decision tree for: r
      Training decision tree for: p
      Training decision tree for: z
      Training decision tree for: y
      Training decision tree for: null
training completed.

I will be grateful
