### ISSUE TITLE
Querying HMM voices for REALISED_ACOUSTPARAMS leaks threads and memory

### ISSUE THREAD

**Issue by timobaumann** [marytts/marytts#567]
We use LocalMaryInterface to query text for realised acoustic parameters. This works fine with concatenative voices but with HMM voices, memory eventually fills up and I see lots of waiting threads (one per query?) holding on to lots of double[]s. I use a somewhat outdated after-5.1.2 version (to avoid the LTS regressions) but the code still looks the same in the repository.

The following seems to happen: 
- HTSEngine.process is called also for REALISED_ACOUSTPARAMS because durations depend on HMM states (which are probably determined by htsMaximumLikelihoodParameterGeneration); 
- HTSEngine.process does not check whether any audio needs to be produced and calls HTSVocoder.htsMLSAVocoder regardless of whether it needs to.
- HTSVocoder.htsMLSAVocoder then creates the waiting threads by calling and starting HTSVocoderDataProducers which produce lots of data.
- nobody ever reads from the DataProducers' AudioInputStreams and memory eventually spills over. (It would be interesting to test this on mary.dfki.de, but not on a Friday afternoon...)

After some thinking, I don't see the "right" way of fixing this. I don't know how HTSEngine could easily check whether it should or should not produce audio. HMMSynthesizer.synthesize() still has this information (outputParams), but could only drain the audio to get rid of it. While this would fix my out-of-memory problem, it's far from efficient. After all, there's no need to vocode when I just want the acoustparams. 

Of course, we could tell HTSEngine.process whether audio is desired (add a boolean parameter) and I'd volunteer to send a patch if this sounds like an acceptable solution.

**Comment by psibre** [comment]
@timobaumann Thanks very much for investigating this. It sounds like it is also related to various chronic issues we observed with the http://mary.dfki.de:59125 demo instance crashing under load every few days. We worked around that with a cronjob that respawns the service when it crashes. Our various informal profiling attempts never really got to the bottom of the issue, but led to the same murky classes that you mention.

When @seblemaguer was recently working to fix #555, we noticed various other issues with the marytts.htsengine package, and I'm not sure how much of it we can (or want to) salvage for 6.x. But if you happen to have a patch ready, please do submit a PR! =)

**Comment by psibre** [comment]
Incidentally, we have a dormant [stress-testing project](/marytts/marytts-testing), which might help with the profiling, although we haven't updated it in a looong time...

**Comment by timobaumann** [comment]
apparently, outputparams is not what I expected (it's not the same as outputType), so I don't have a solution.

The real problem is that HTSEngine confounds two processing steps in one module: HTS parameter estimation and vocoding from these parameters. Of course, the module is able to produce audio and (as far as I can tell) it doesn't have a way of knowing whether it should. As a consequence, it doesn't really follow the MaryModule interface but implements its own process (with different signature). It's called from HMMSynthesizer which is a WaveformSynthesizer (which doesn't even bother being a module) and I don't know who calls that guy. It turns out that Synthesizer (the module calling WaveformSynthesizers) also creates audio (including concatenation) when REALISED_ACOUSTPARAMS is queried. Although only the search (not concatenation) would be required for concat synthesis. These should be separate modules!

**Comment by psibre** [comment]
FWIW, the output params were introduced back in 4353ef7eaa94e7f360945107cc701e1afa0b3dde (cf. also https://mary.opendfki.de/trac/ticket/190), but never systematically utilized.

But I completely agree with your assessment... the amount of cruft that's grown over the years is maddening.

**Comment by timobaumann** [comment]
the pull request from above uses outputParam to pass a "noAudio" option. Let me know what you think.
