### ISSUE TITLE
Built voice didn't show up as an option voice in marytts-component-installer to install or uninstall

### ISSUE THREAD

**Issue by yusufardi97** [marytts/marytts#569]
Hello,

I'm testing to build voice using voice building tools and already have all files (.zip, .jar, and component.xml). I move both .zip and component.xml into /marytts/target/marytts-5.2-SNAPSHOT/download, but i don't see the voice when i run marytts-component-installer from bin folder. What should i do to see the voice?

**Comment by psibre** [comment]
You need to run the `bin/marytts-component-installer` script, which will launch the GUI tool that allows to to "install" your voice from the files you provided under `download`. This tool uses the component XML descriptor to verify the integrity of the zip file, then makes you agree to the license, and then unzips the zip file under `lib`.

After the voice is installed in this manner, it will be available in a newly started MaryTTS server.

**Comment by yusufardi97** [comment]
the files i have within `download` didn't show up after i run the `bin/marytts-component-installer` script, it's just show the usual list and not the addition voice. For the record, i'm using the recompiled cmu-slt-us for the voice but naming it voice-in_voice (as if it is an Indonesian voice) even tho the content in the component.xml still recognize it as english voice.

here is the content of the component.xml with the change in location so it download from public storage (dropbox)
```
<?xml version="1.0" encoding="UTF-8"?><marytts-install xmlns="http://mary.dfki.de/installer">
  <voice gender="female" locale="en-US" name="voice-in_voice" type="marytts.unitselection.UnitSelectionVoice" version="5.2-SNAPSHOT">
    <description>A female English general voice</description>
    <license href="http://mary.dfki.de/download/by-nd-3.0.html"/>
    <package filename="voice-in_voice-5.2-SNAPSHOT.zip" md5sum="ddd45a619201e1cb813fb02a6d33f272" size="104710635">
      <location folder="true" href="https://www.dropbox.com/s/jrkk8lkae3iq7jf/"/>
    </package>
    <files>lib/voice-in_voice-5.2-SNAPSHOT.jar</files>
    <depends language="en" version="5.2-SNAPSHOT"/>
  </voice>
</marytts-install>
```

**Comment by psibre** [comment]
There are problems with your XML descriptor.

1. The `type` attribute of your `voice` element should be either "unit selection" or "hsmm"; the fully qualified class name `marytts.unitselection.UnitSelectionVoice` should not be used there.
2. The `locale` attribute of the `voice` and the `language` attribute of the `depends` element must be the locale of the voice -- in your case, `id` for Indonesian.

How was your XML descriptor created?

**Comment by yusufardi97** [comment]
thank you, so basically i solve this by changing the locale into "en_US", depend language into "en-US", type into "unit selection" and the href location folder into the default one from `marytts-builder-5.2-SNAPSHOT/bin/voiceimport.sh`

here are the complete xml content 
```
<?xml version="1.0" encoding="UTF-8"?><marytts-install xmlns="http://mary.dfki.de/installer">
  <voice gender="female" locale="en_US" name="voice-in_voice" type="unit selection" version="5.2-SNAPSHOT">
    <description>A female English general voice</description>
    <license href="http://mary.dfki.de/download/by-nd-3.0.html"/>
    <package filename="voice-in_voice-5.2-SNAPSHOT.zip" md5sum="ddd45a619201e1cb813fb02a6d33f272" size="104710635">
      <location folder="true" href="http://mary.dfki.de/download/5.2-SNAPSHOT/"/>
    </package>
    <files>lib/voice-in_voice-5.2-SNAPSHOT.jar</files>
    <depends language="en-US" version="5.2-SNAPSHOT"/>
  </voice>
</marytts-install>
```

and for the actual work, yes, i'm going to use the id locale for Indonesian, but since this is just test run, i think it is ok to use either one in or id

**Comment by psibre** [comment]
OK, if this is just for testing the voice, you can simply unpack your zip file under `lib`.

I was mainly concerned that your voice could not be installed normally, but re-reading your comments it seems you just manually edited the XML for the cmu-slt voice, which caused various inconsistencies.

I believe this is therefore an invalid issue. If you go and build your Indonesian voice, and try to install it using the actual XML descriptor that is automatically generated by the voicebuilding tools, and then that doesn't work as advertised, then please open another issue.

**Comment by yusufardi97** [comment]
just for the sake of clarification. I used the cmu-slt-us voice as my base voice for running necessary action in voice import process (as suggested by [tutorial](https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial)). the component xml i got from that process is the one in [this comment](https://github.com/marytts/marytts/issues/569#issuecomment-231943922) minus edit in location (because i thought that was the problem), but not the other.

After i read your comment, i edit it out as you suggested in type field, language field, and filling the blank in name field. After i edit that out it solved the issue. I still don't know if wrong type in the xml is caused by voice import or not, by saying that what i mean is this one `type="marytts.unitselection.UnitSelectionVoice"` and not `type="unit selection"`.

that is my explanation, sorry for the inconvenience and my bad writing.

**Comment by psibre** [comment]
@yusufardi97 OK, thanks for the clarification. Good luck with the actual voice packaging!
