### ISSUE TITLE
Transcription file runs to infinity

### ISSUE THREAD

**Issue by Nandutu** [marytts/marytts#572]
Hi am adding a new language luganda to marytts but when i run transcription, it runs minus stopping yet no error.
Where might the problem be?

~/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ ./transcription.sh
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

prev: Serif
next: Serif
alignment ... 
iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
alignment completed.
training ... 
      Training decision tree for: f
      Training decision tree for: g
      Training decision tree for: d
      Training decision tree for: e
      Training decision tree for: b
      Training decision tree for: a
      Training decision tree for: n
      Training decision tree for: o
      Training decision tree for: l
      Training decision tree for: m
      Training decision tree for: j
      Training decision tree for: k
      Training decision tree for: i
      Training decision tree for: w
      Training decision tree for: v
      Training decision tree for: u
      Training decision tree for: t
      Training decision tree for: s
      Training decision tree for: r
      Training decision tree for: p
      Training decision tree for: z
      Training decision tree for: y
      Training decision tree for: null
training completed.

Attached is the screen shot for the transcription tool
![transcription](https://cloud.githubusercontent.com/assets/7518308/16986354/b039a2b8-4e8e-11e6-8c95-7191023161b7.png)

**Comment by Nandutu** [comment]
Could some one help me
What output am i expected to see in the terminal while running ./transcription.sh

**Comment by entenbein** [comment]
Did you save those results after this step?

**Comment by Nandutu** [comment]
@entenbein i have no saved any thing. Am new to marytts kindly which kind of rules am i supposed to write? Give me an example of the rules please.

Attached is a clear screen shot of the terminal , it looks like it expects me to write something and hit enter. 
Thanks
![writerules](https://cloud.githubusercontent.com/assets/7518308/17074692/2f203fd4-5087-11e6-9068-962969c105f8.png)

**Comment by psibre** [comment]
@Nandutu looks to me that everything is fine. "Training completed" means it's done without errors.

**Comment by Nandutu** [comment]
@psibre this sounds good news to me..... Is it okay for me to ctrl+c to be able to access the terminal were i can type like in the screen shot . ??? ![break](https://cloud.githubusercontent.com/assets/7518308/17079322/188e310c-5115-11e6-95d3-f7295b304edd.png)

**Comment by psibre** [comment]
@Nandutu You should probably check the GUI, and close that normally, which should also return you to the prompt in the terminal.

**Comment by Nandutu** [comment]
Closed it normally thanks, however when i reach to feature maker step all is not well. check #575
