### ISSUE TITLE
Low count of sentences in DBselection step.

### ISSUE THREAD

**Issue by BibekBazaz** [marytts/marytts#573]
Hello,

I tried to make TTS using MARY for Bengali and Hindi. I am mainly stuck at the point that though I am repeatedly trying with different corpus sizes and number of training words, everytime after running the dbselection step, I get around 7 , 8 or 30 sentences but not more than that. I request someone to please tell me how to increase the number of sentences in db selection step to atleast 80 to 100 sentences so thatI ca build an effective TTS for both the languages.
Thankyou beforehand for help.

**Comment by nshmyrev** [comment]
There is no need to select sentences or record a new corpus neither for Bengali, nor for Hindi, you can download existing corpora here:

http://www.iitm.ac.in/donlab/tts/index.php

and build upon it
