### ISSUE TITLE
Adding New Characters to SAMPA.

### ISSUE THREAD

**Issue by Zeexum** [marytts/marytts#574]
Hi, We re a group of people working on adding a new language to MaryTTS `Moroccan Arabic` and we would like to add new characters to use in allophones.dr.xml, those characters are : â, û and î.

The problem is when we use the transcription.sh tool, the words that are transcribed manually and, have the above characters in them, they appear in red.

So I suppose that the problem is that SAMPA doesn't recognize these characters as a part of it's alphabet, and so my qst is how do I add these new characters to allophones.tr.xml without having trouble in the following step `transcription.sh`. also, I wish I could change these characters to smtg that SAMPA would recognize but I have no choice since people has already started working with these characters and I HAVE TO use them.

Thanks :)

**Comment by psibre** [comment]
Please have a look at http://www.phon.ucl.ac.uk/home/sampa/arabic.htm

**Comment by Zeexum** [comment]
@psibre, I have

**Comment by Zeexum** [comment]
Thank You ; it was just a typo in the allophones file
