### ISSUE TITLE
FeatureMaker Step predicts almost all words as unreliable 

### ISSUE THREAD

**Issue by Nandutu** [marytts/marytts#575]
Hello, All the steps using this [tutorial](https://github.com/marytts/marytts/wiki/New-Language-Support) where okay. But when it came to feature maker step. Almost all words are unreliable. What could be the problem? 

~/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_featuremaker.sh wkdb.conf
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

FeatureMaker parameters:
  -locale lg
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=lg
Mysql connection created successfully.
    TABLE = "lg_dbselection" does not exist, it will be created.Checking if lg_dbselection already exist.
TABLE = lg_dbselection succesfully created.
Starting builtin MARY TTS... MARY TTS started.

Getting list of unprocessed clean_text records from lg_cleanText
Number of unprocessed clean_text records to process --> [30]
Looping over unprocessed clean_text records from wikipedia...
TARGETFEATURES to extract: phone next_phone selection_prosody 
Starting time:25_07_2016_00:11:25

Created featureDefinition file:lg_featureDefinition.txt
Processing(0) text id=1 text length=15435
Inserted 224 sentences from text id=1 (Total unreliable = 224)
Inserted 0 sentences from text id=1 (Total reliable = 0) 

Processing(1) text id=2 text length=15204
Inserted 200 sentences from text id=2 (Total unreliable = 424)
Inserted 0 sentences from text id=2 (Total reliable = 0) 

Processing(2) text id=3 text length=5478
Inserted 73 sentences from text id=3 (Total unreliable = 497)
Inserted 0 sentences from text id=3 (Total reliable = 0) 

Processing(3) text id=4 text length=7072
Inserted 45 sentences from text id=4 (Total unreliable = 542)
Inserted 0 sentences from text id=4 (Total reliable = 0) 

Processing(4) text id=5 text length=15020
Inserted 102 sentences from text id=5 (Total unreliable = 644)
Inserted 0 sentences from text id=5 (Total reliable = 0) 

Processing(5) text id=6 text length=15229
Inserted 110 sentences from text id=6 (Total unreliable = 754)
Inserted 0 sentences from text id=6 (Total reliable = 0) 

Processing(6) text id=7 text length=9364
Inserted 70 sentences from text id=7 (Total unreliable = 824)
Inserted 0 sentences from text id=7 (Total reliable = 0) 

Processing(7) text id=8 text length=15070
Inserted 88 sentences from text id=8 (Total unreliable = 912)
Inserted 0 sentences from text id=8 (Total reliable = 0) 

Processing(8) text id=9 text length=1912
Inserted 9 sentences from text id=9 (Total unreliable = 921)
Inserted 0 sentences from text id=9 (Total reliable = 0) 

Processing(9) text id=10 text length=15739
Inserted 147 sentences from text id=10 (Total unreliable = 1068)
Inserted 0 sentences from text id=10 (Total reliable = 0) 

Processing(10) text id=11 text length=15024
Inserted 142 sentences from text id=11 (Total unreliable = 1210)
Inserted 0 sentences from text id=11 (Total reliable = 0) 

Processing(11) text id=12 text length=15068
Inserted 152 sentences from text id=12 (Total unreliable = 1362)
Inserted 0 sentences from text id=12 (Total reliable = 0) 

Processing(12) text id=13 text length=15361
Inserted 154 sentences from text id=13 (Total unreliable = 1516)
Inserted 0 sentences from text id=13 (Total reliable = 0) 

Processing(13) text id=14 text length=15010
Inserted 157 sentences from text id=14 (Total unreliable = 1673)
Inserted 0 sentences from text id=14 (Total reliable = 0) 

Processing(14) text id=15 text length=15054
Inserted 165 sentences from text id=15 (Total unreliable = 1838)
Inserted 0 sentences from text id=15 (Total reliable = 0) 

Processing(15) text id=16 text length=15075
Inserted 164 sentences from text id=16 (Total unreliable = 2002)
Inserted 0 sentences from text id=16 (Total reliable = 0) 

Processing(16) text id=17 text length=15056
Inserted 155 sentences from text id=17 (Total unreliable = 2157)
Inserted 0 sentences from text id=17 (Total reliable = 0) 

Processing(17) text id=18 text length=4278
Inserted 34 sentences from text id=18 (Total unreliable = 2191)
Inserted 0 sentences from text id=18 (Total reliable = 0) 

Processing(18) text id=19 text length=1711
Inserted 1 sentences from text id=19 (Total unreliable = 2192)
Inserted 0 sentences from text id=19 (Total reliable = 0) 

Processing(19) text id=20 text length=9897
Inserted 26 sentences from text id=20 (Total unreliable = 2218)
Inserted 0 sentences from text id=20 (Total reliable = 0) 

Processing(20) text id=21 text length=13359
Inserted 25 sentences from text id=21 (Total unreliable = 2243)
Inserted 0 sentences from text id=21 (Total reliable = 0) 

Processing(21) text id=22 text length=7377
Inserted 29 sentences from text id=22 (Total unreliable = 2272)
Inserted 0 sentences from text id=22 (Total reliable = 0) 

Processing(22) text id=23 text length=11788
Inserted 3 sentences from text id=23 (Total unreliable = 2275)
Inserted 0 sentences from text id=23 (Total reliable = 0) 

Processing(23) text id=24 text length=15016
Inserted 56 sentences from text id=24 (Total unreliable = 2331)
Inserted 0 sentences from text id=24 (Total reliable = 0) 

Processing(24) text id=25 text length=11052
Inserted 48 sentences from text id=25 (Total unreliable = 2379)
Inserted 0 sentences from text id=25 (Total reliable = 0) 

Processing(25) text id=26 text length=5082
Inserted 2 sentences from text id=26 (Total unreliable = 2381)
Inserted 0 sentences from text id=26 (Total reliable = 0) 

Processing(26) text id=27 text length=15009
Inserted 52 sentences from text id=27 (Total unreliable = 2433)
Inserted 1 sentences from text id=27 (Total reliable = 1) 

Processing(27) text id=28 text length=1377
Inserted 3 sentences from text id=28 (Total unreliable = 2436)
Inserted 0 sentences from text id=28 (Total reliable = 1) 

Processing(28) text id=29 text length=11841
Inserted 20 sentences from text id=29 (Total unreliable = 2456)
Inserted 0 sentences from text id=29 (Total reliable = 1) 

Processing(29) text id=30 text length=14254
Inserted 75 sentences from text id=30 (Total unreliable = 2531)
Inserted 0 sentences from text id=30 (Total reliable = 1) 

Mysql connection closed.
numSentencesInText;=1
Start time:25_07_2016_00:11:25  End time:25_07_2016_00:13:31
Done

Checking the server.log file, all words have an error related to this
2016-07-25 00:11:57,347 [main] ERROR marytts.JPhonemiser Problem with token <y'akawuka> [Zakauka1]: Found unknown symbol `Z' in phonetic string `Zakauka1' -- ignoring.
What could be the problem....???

**Comment by Nandutu** [comment]
Hello, some help and insights on this please.

Thanks

**Comment by MomnaSaeed** [comment]
Hi ,
Seems like  i am getting the same error as yours in feature maker step ,please let me if you have solved it or how you did it ?
![3](https://cloud.githubusercontent.com/assets/9119099/22802553/099b2bca-ef33-11e6-87bc-cd747a4b1038.JPG)

Thanks

**Comment by Nandutu** [comment]
@MomnaSaeed i just inserted manually words in mysql database. It is tiresome but i just used a small dataset to test.
