### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by peterbsmith2** [marytts/marytts#576]
Hey all,

I want to use Mary TTS server but it has some limitations for public use:

It doesnt have any authentication or rate limiting, etc..

My initial thought was to build a server in node.js that locally communicates with Mary TTS and then have the node.js server interact with the outside world. It seems convoluted because of how I'm moving around wav files.

Thoughts on this?

**Comment by psibre** [comment]
We've discussed this in the past (especially for the greylisting of abusive clients). Our conclusion was that these are features best implemented at the web server level (see also [the wiki](../wiki/Local-MaryTTS-Server-Installation)).

In fact, for MaryTTS 6, we plan to strip the HTTP server code from the core MaryTTS modules and instead provide one or more artifacts that "wrap" the MaryTTS core in a standalone HTTP server (as before), or as a WAR servlet or whatever. But of course, any contribution that adds relevant features is always appreciated!

**Comment by peterbsmith2** [comment]
I couldn't more in agreement with your approach to MaryTTS 6. Having the core of Mary being separate from the HTTP server is a useful separation of code. I will be writing a node client for my current project that, with a non-major amount of effort, could easily go into the example repository to bolster the python, the ruby, and the other examples there as well.

For the moment I am going to solve my problem by effectively proxying the output of MaryTTS on port 59125 through a node.js client that interacts with the end-client. My in-experience with Java is the main reason for this.

Could you confirm that if I knew Java I could write my own HTTP server that would directly interact with MaryTTS? 

I'll mark this as closed because you've addressed my core question.

**Comment by psibre** [comment]
> Could you confirm that if I knew Java I could write my own HTTP server that would directly interact with MaryTTS?

Yes, the idea in the 5.x generation of MaryTTS is to use a [marytts.MaryInterface](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-common/src/main/java/marytts/MaryInterface.java) implementation ([local](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-runtime/src/main/java/marytts/LocalMaryInterface.java) or [remote](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-client/src/main/java/marytts/client/RemoteMaryInterface.java)). This can be done in a lightweight manner, similarly to [our example project](/marytts/marytts-txt2wav), to provide MaryTTS functionality to node.
