### ISSUE TITLE
Preprocessing for new languages.

### ISSUE THREAD

**Issue by BaimAT** [marytts/marytts#581]
I successfully created a new voice and a new library for Malay (ms). After doing some testing I notice several imperfections in my work. Therefore, I want to ask whether I can control how the input is preprocessed.

1) numbers and symbols: numbers cannot be computed. It will return as empty syllables in the projected xml file. I noticed in `marytts-lang-it` directory, there are several java files that are used to preprocess symbols, numbers, time and for english there are preprocessors for abbreviations like 'Mr.' to 'mister'. So, how can I replicate these and apply to my library?

2) incorrect allophones selection: related to my question #580 mostly for digraphs. example, digraph 'ng' is represented as 'N', 'kh' is 'x'. but when Mary want to syllabify, aside from the words I transcribed in the lexicon, it does it wrongly. So, is there a method to ensure the allophones are projected correctly?

3) single words with multiple pronunciations. Not really important for now but would be great to have. In Malay, some words have different meanings based on how it is pronounce. Mainly because there are 2 ways to pronounce the letter 'e'. I tried putting both pronunciations in lexicon but it will return error. So, is there a way to control it?

Thanks.

**Comment by psibre** [comment]
> 1) numbers and symbols: numbers cannot be computed. It will return as empty syllables in the projected xml file. I noticed in marytts-lang-it directory, there are several java files that are used to preprocess symbols, numbers, time and for english there are preprocessors for abbreviations like 'Mr.' to 'mister'. So, how can I replicate these and apply to my library?

Have a look at the [*English* Preprocess class](../blob/6d6e1bcc6e03b42a2ded2492b81489eeded71707/marytts-languages/marytts-lang-en/src/main/java/marytts/language/en/Preprocess.java), which is much more recent than the Italian code, some of which in turn was copied from German (the oldest, cruftiest NLP code in MaryTTS).
Regarding numbers, you could leverage [ICU4J's RuleBasedNumberFormat](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/RuleBasedNumberFormat.html) and friends to avoid reinventing the wheel.

> 2) incorrect allophones selection: related to my question #580 mostly for digraphs. example, digraph 'ng' is represented as 'N', 'kh' is 'x'. but when Mary want to syllabify, aside from the words I transcribed in the lexicon, it does it wrongly. So, is there a method to ensure the allophones are projected correctly?

We not happy with the way the lexicon code is working. It trains a model on data, so first of all, you need to have good, consistent data. But then it also fails to reproduce that 100%, which is of course a problem. We worked around this issue some time ago, but the solution cannot be properly integrated until we migrate the build system to gradle after releasing v5.2.
But even after that, redesigning the lexicon code is still on our todo list.

> 3) single words with multiple pronunciations. Not really important for now but would be great to have. In Malay, some words have different meanings based on how it is pronounce. Mainly because there are 2 ways to pronounce the letter 'e'. I tried putting both pronunciations in lexicon but it will return error. So, is there a way to control it?

Homograph disambiguation is currently "solved" (somewhat) by looking at the part of speech. So you train the lexicon with the transcription *and POS* for each lemma, which may help somewhat.

**Comment by BaimAT** [comment]
Sorry for late reply. @psibre does the other files that can be found in the same folder of preprocess needed to?
