### ISSUE TITLE
 EHMMlabeler and hts/htk path

### ISSUE THREAD

**Issue by Nandutu** [marytts/marytts#584]
Hello,
I need some help on how to add the ehmm path and hts/htk path
I have added festvox to the path as export FESTVOXDIR=~/marytts/target/voice/sources/festvox but not successful when i check external libararies
Output here
`Programs status (detailed information above):
The following paths should be in the PATH variable
  awk: /usr/bin
  perl: /usr/bin
  bc: /usr/bin
The following paths are used when running HMMVoiceConfigure
  tclsh: /usr/bin
  sox: /usr/local/bin
  hts/htk: misising path
  hts_engine: /usr/local/bin
  sptk: /home/irene/marytts/lib/external/bin
This path is used when running the EHMMlabeler
  ehmm: missing path`

I will be greatful

**Comment by psibre** [comment]
First of all, the EHMMlabeler has nothing at all to do with building HMM voices.

Having said that, to run the HMM voicebuilding components, I assume you've read through the [instructions on the wiki](../wiki/HMMVoiceCreation)?

To elaborate on the setup: you need to ensure the availability of the `$MARY_BASE/lib/external/externalBinaries.config` file, where `$MARY_BASE` is your marytts **source** directory. This file provides the paths to all of the required external binaries. In my experience, an easy way to create this file is to put all required binaries on your `PATH`, then run the `$MARY_BASE/lib/external/check_install_external_programs.sh` with the `-check` option.

**Comment by Nandutu** [comment]
Hello @psibre if i do add ehmm to path :~/marytts/lib/external$ $MARY_BASE ./check_install_external_programs.sh -check /home/irene/marytts/target/voice/sources/festvox/src/ehmm/bin my output shows ehmm is added to the path as below
Programs status (detailed information above):
The following paths should be in the PATH variable
  awk: /usr/bin
  perl: /usr/bin
  bc: /usr/bin
The following paths are used when running HMMVoiceConfigure
  tclsh: /usr/bin
  sox: /usr/local/bin
  hts/htk: /usr/local/bin
  hts_engine: /usr/local/bin
  sptk: /home/irene/marytts/lib/external/bin
This path is used when running the EHMMlabeler
  ehmm: /home/irene/marytts/target/voice/sources/festvox/src/ehmm/bin

List of paths in: /home/irene/marytts/lib/external/externalBinaries.config

But if i check availability of ehmm ~/marytts/lib/external$ ./check_install_external_programs.sh -check
my output shows that i have no ehmm as below
Programs status (detailed information above):
The following paths should be in the PATH variable
  awk: /usr/bin
  perl: /usr/bin
  bc: /usr/bin
The following paths are used when running HMMVoiceConfigure
  tclsh: /usr/bin
  sox: /usr/local/bin
  hts/htk: /usr/local/bin
  hts_engine: /usr/local/bin
  sptk: /home/irene/marytts/lib/external/bin
This path is used when running the EHMMlabeler
  ehmm: missing path

List of paths in: /home/irene/marytts/lib/external/externalBinaries.config

What do you think is the issue here.
Thanks

**Comment by psibre** [comment]
I'm not sure why you need `ehmm`, but the sources are under `lib/external/ehmm`. You need to build it yourself.

**Comment by finiteautomata** [comment]
@psibre got a question related to this. In order to build an HMM Voice, do I have to get the *sources* of `marytts` or is it fine with the downloaded snapshots (builder and runtime)? 

I've succeeded building it from the sources, but failed with the downloaded snapshots. When compiling  

```
HMMVoiceDataPreparation:
Checking paths of external programs
  *Missing path for awk
  *Missing path for perl
  *Missing path for bc
  *Missing path for tclsh
  *Missing path for sox
  *Missing path for hts/htk
  *Missing path for hts_engine
  *Missing path for sptk
  *Missing path for ehmm
Please run MARYBASE/lib/external/check_install_external_programs.sh and check/install the missing programs
```

although awk and others are accesible through the $PATH. Snapshots lack this `lib/external` directory.

**Comment by psibre** [comment]
In theory the `marytts-builder` distribution package should be working; *however* the hacky little shell script is not included, so the easiest way to get around that is to just clone the MaryTTS repository with git and build from source.

Alternatively, if for some reason you really want to use *only* the distribution package, you *can* configure all of the paths to those external programs by hand.
