### ISSUE TITLE
Memory leak over long period of time

### ISSUE THREAD

**Issue by SirSkaro** [marytts/marytts#586]
Using version 5.2-beta3

I'm using MaryTTS in a bot for the social application Discord. MaryTTS allows my bot to speak to users in voice chat. My bot is becoming more popular every day. However, if my bot runs for about 2 or 3 days straight, I get the below error and my processes quit. The more popular my bot becomes, the less time it takes for this to happen.

`Exception in thread "Thread-1249" java.lang.OutOfMemoryError: Java heap space

```
    at marytts.htsengine.HTSVocoder.htsMLSAVocoder(HTSVocoder.java:330)

    at marytts.htsengine.HTSVocoder$HTSVocoderDataProducer.run(HTSVocoder.java:1882)

    at java.lang.Thread.run(Thread.java:745)`
```

I'm wondering if this is a mismanagement of resources on my part or if this issue is not my fault. In my code I am using the MaryInterface class. There is one instance of this class in the entirety of my code. How it works is that every time someone sends a message in the Discord application a new thread is opened to deal with that message. If necessary I use the MaryInterface to convert some text to an AudioOutputStream. I have not seen this error happen right after the MaryInterface is used, it will just happen.

Please let me know if there's anything I can do about it or if this error is not my fault.

**Comment by psibre** [comment]
This seems to be related to an old issue we observed some time ago. There is a pull request which may or may not fix this, but we're still in the process of profiling it...

**Comment by psibre** [comment]
@attacomsian could you please provide a status update for profiling marytts-testing before/after #568?
