### ISSUE TITLE
HMMVoiceMakeVoice

### ISSUE THREAD

**Issue by Nandutu** [marytts/marytts#589]
Hello i have got as issue when i run HMMVoiceMakeVoice, yet i have 149 utterances
What could be the problem.

`~/marytts/target/redstart/output/hts$   ERROR [+2121]  HInit: Too Few Observation Sequences [0]
 FATAL ERROR - Terminating program /usr/local/bin/HInit
Error in /usr/local/bin/HInit     -A    -C /home/irene/marytts/target/redstart/output/hts/configs/trn.cnf -D -T 1 -S /home/irene/marytts/target/redstart/output/hts/data/scp/train.scp                -m 1 -u tmvw    -w 5000  -H /home/irene/marytts/target/redstart/output/hts/models/qst001/ver1/cmp/init.mmf -M /home/irene/marytts/target/redstart/output/hts/models/qst001/ver1/cmp/HInit -I /home/irene/marytts/target/redstart/output/hts/data/labels/mono.mlf -l mm -o mm /home/irene/marytts/target/redstart/output/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt
`

**Comment by Nandutu** [comment]
Hello.
Can some one help me on this. ..
I know my sentences are not recognised by  wondering why???
What could be the problem....

**Comment by psibre** [comment]
I don't think this is a MaryTTS issue -- you can STFW and may find support on hts-users.

**Comment by seblemaguer** [comment]
Hello, this is definitelly not a marytts issues. It just means that your corpus doesn't contain enough instances of "mm" (maybe not at all).

**Comment by Nandutu** [comment]
Hello @seblemaguer i have added mm instances in my corpus to about more than 80 times but am experiencing the same error. mm is one of the consonants in my phonetic file. What do you think am missing out. ???

**Comment by Nandutu** [comment]
@seblemaguer do you think using a different speaker could help since my wav files are the ones not recognised. may be the recording will be more clear to be recognised.
When recording which measures do i need to follow to detect quality of the recording?

**Comment by Nandutu** [comment]
This "Hello, this is definitelly not a marytts issues. It just means that your corpus doesn't contain enough instances of "mm" (maybe not at all)."

Worked
