### ISSUE TITLE
HMM Voice Creation: Cannot open perl script getwavlist.pl

### ISSUE THREAD

**Issue by finiteautomata** [marytts/marytts#592]
I'm trying to create an HMM example voice following the [steps in the wiki](https://github.com/marytts/marytts/wiki/HMMVoiceCreation). I managed to start the voice import tools, but when it is the time of running the EHMMLabeler, I'm getting this error:

```
Preparing voice database for labelling using EHMM :
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Setting up EHMM directory ...
 ... done.
Getting Phone Sequence from Phone Features...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Dumping required files ....
( cd /home/marat/voice/data/example/ehmm; perl /home/marat/voice/sources/festvox/src/ehmm/bin/phfromutt.pl /home/marat/voice/data/example/ehmm/etc/ehmm.align /home/marat/voice/data/example/ehmm/etc/ehmm.phoneList 5; perl /home/marat/voice/sources/festvox/src/ehmm/bin/getwavlist.pl /home/marat/voice/data/example/ehmm/etc/ehmm.align /home/marat/voice/data/example/ehmm/etc/ehmm.waveList; exit )

ERR> Can't open perl script "/home/marat/voice/sources/festvox/src/ehmm/bin/getwavlist.pl": No such file or directory
java.lang.Exception: The component EHMMLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
Caused by: marytts.exceptions.MaryConfigurationException: dumpRequiredFiles computation failed.
Error: null
	at marytts.tools.voiceimport.EHMMLabeler.dumpRequiredFiles(EHMMLabeler.java:274)
	at marytts.tools.voiceimport.EHMMLabeler.compute(EHMMLabeler.java:160)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
```

In fact, no file with that name exists in the installed software. Any idea of what is happening here?

I'm using Mary TTS (Server and Builder) 5.1.2. The example set used is [CMU Arctic](http://www.speech.cs.cmu.edu/cmu_arctic/packed/cmu_us_slt_arctic-0.95-release.tar.bz2).

**Comment by entenbein** [comment]
Is there any other file in the `bin` (*/home/marat/voice/sources/festvox/src/ehmm/bin/*) folder?

**Comment by finiteautomata** [comment]
Yes, there are. 

```bash
$ l /home/marat/voice/sources/festvox/src/ehmm/bin/
check_lab.pl*  ConvertFeatsFileToBinaryFormat*  edec*  FeatureExtraction*  phfromutt.pl*  rem_ssil.pl*  ScaleBinaryFeats*  seqproc.pl*  sym2nm.pl*
comp_dcep.pl*  do_ehmm*                         ehmm*  Makefile            phseq.scm      rm_nan_utts*  scale_feat.pl*     sl2nm.pl*
```

**Comment by finiteautomata** [comment]
By the way, I haven't compiled the source code of MaryTTS. I just downloaded the snapshots from the page.

**Comment by seblemaguer** [comment]
hello, I think the main problem is actually that the version of ehmm we are using is a little bit different. It is currently in process of evolution but for now you have to use the one packed in marytts there : https://github.com/marytts/marytts/tree/master/lib/external/ehmm

we are aware that it is not good in term of architecture and we are currently changing that :)

**Comment by psibre** [comment]
EHMM has nothing to do with HMM voice building -- the former is one of many ways to get phonetic segmentation. The latter is the synthesis backend. See also #584

**Comment by finiteautomata** [comment]
Thanks @seblemaguer, now it seems to be working. Excuse me for very basic questions, but why I don't need to run `EHMM` labeler? The guide in the wiki has it as a step to build an HMM Voice.

By the ways, is there any other channel to ask these things? Is the mailing list dead? I've subscribed and received nothing so far

**Comment by seblemaguer** [comment]
the problem is actually you are not in the same level. If you have aligned labels you can build HMM or US voice. EHMM is to get this alignment. Therefore it is not specific to HMM voice. 

Considering the mailing, yes kind of. We prefer to have the questions on github it is easier to monitor.
