### ISSUE TITLE
Russian and Spanish languages support

### ISSUE THREAD

**Issue by gnom7** [marytts/marytts#595]
Hello, I have some questions about Russian and Spanish languages support.
Hope you take the time to answer them.
1) On the home page http://mary.dfki.de/ states "As of version 5.2-SNAPSHOT, MaryTTS supports German, British and American English, French, Italian, Swedish, Russian, Turkish, and Telugu; more languages are in preparation." So I downloaded v5.2 and I cannot find russian language there. What I did is manually added info (which I found in google) about russian into `marytts-components.xml` and used it in `marytts-component-installer.bat`. So is it OK or I misunderstood something and there could be better support for russian (may be there are better voices from Mary for russian, but I can't find them? or there is another way to get russian available by default with the maximum possible support for this language?)
2) I searched info about spanish language support in MaryTTS, but I can't find _anything_ about it. 
Is there spanish language support? And if officially not, may be you now some voice or smth that I can use whith Marry to add this language support (exclude [this](https://github.com/marytts/marytts/wiki/New-Language-Support), which I already now)?
3) By now I'm working on machine with Windows installed and all works fine (thank you for that), but later I would like to deploy Mary server to machine with Ubuntu, there are any known problems with compability or smth or all works just fine? (yes I have read about "MaryTTS is a client-server system written in pure Java, so it runs on many platforms." but just to clarify)
Thank you

**Comment by entenbein** [comment]
1) There is a module for the Russian language (`marytts/marytts-languages/marytts-lang-ru/
`), which allows you to build and use Russian voices. That doesn't necessarily mean that there is a Russian voice available. Maybe someone that already built a Russian voice, reads your post and maybe shares.

2) In the current sources (`marytts/marytts-languages/`) it doesn't look like there is a module for the Spanish language. But again, maybe someone else already did that.

3) Building a voice on one system and using the server and voice on a different OS shouldn't be a problem as long as the correct java environment is present. Using the compiled tools from your Windows machine to run a voice build on your Ubuntu machine will probably not work.

**Comment by gnom7** [comment]
1) exactly, I wondered if there is Russian voice, not just language module; do I understand correctly that there is no such voice providen by Mary?
2) thnx
3) again thnx) it was just to stay calm)
4) and I have one more question, just to surely know, is it possible to give to Mary text and Mary to recognize language by itself? I didn't find such functionallity, if not, maybe this is a good idea to implement in 6.x milestone)
Thank you for your answers

**Comment by entenbein** [comment]
1) Didn't see one so far. But maybe the devs know more.
4) Didn't see that feature as well in the current version. But I guess there a lots of language guessers out there which you could implement and *daisy-chain* with MaryTTS.

**Comment by gnom7** [comment]
Thank you for answers again

**Comment by psibre** [comment]
For the record:

1. The **Russian** voice `voxforge-ru-nsh` was not rebuilt for v5.2; we had trouble locating the original recordings. However, the [previous version of this Russian voice](../blob/6c0fba8ad25e13e17a28f5313508352df185c197/download/marytts-components.xml#L203-L210) is still available and can be used as before.
2. There is a **Spanish** voice and language component built by @marcelach1 but this data has not been published yet. We hope to get this done in the future.

Regarding cross-platform portability, some of the voicebuilding tools are not supported well under Windows. But everything else (runtime, voices) is identical on each platform.

**Comment by nshmyrev** [comment]
> we had trouble locating the original recordings. 

Original recordings are hosted on Voxforge:

http://www.repository.voxforge1.org/downloads/Russian/Trunk/Audio/Original/16kHz_16bit/urp.tgz

Also on sourceforge:

https://sourceforge.net/projects/festlang.berlios/files/msu_ru_nsh_clunits-0.5.tar.bz2/download

**Comment by farizaghayev** [comment]
Is HMM-based voice exist for Russian language?

**Comment by psibre** [comment]
@nshmyrev thanks very much for the links! I was mistakenly trying to rebuild the voice from the nsh data, which includes only a small subset. I was going to ask you about that, but you've beaten me to it! =)

**Comment by psibre** [comment]
@farizaghayev No, I don't think we ever built an HSMM version of the Russian voice.

**Comment by psibre** [comment]
For the record, @jamesssss opened an issue for Russian (#603), and I've created a feature request for Spanish (#605).
