### ISSUE TITLE
5.2 missing Russian voice

### ISSUE THREAD

**Issue by jamesssss** [marytts/marytts#603]
The Russian voice is missing from 5.2

**Comment by seblemaguer** [comment]
Hello,

we have lost the data for the russian voice and we are currently trying to get them to build the voice.

**Comment by nshmyrev** [comment]
If you don't have resources for that I may take a look, it might just take some time. There is a woman voice data too, http://tiflo.info/rhvoice/databases/Russian/irina.zip both must be processed for hsmm and unitsel voices.

**Comment by farizaghayev** [comment]
I can help you to generate Russian hsmm voice. will share the voice soon

**Comment by nshmyrev** [comment]
Hi

Please clone https://github.com/cmusphinx/voice-ac-elena and https://github.com/cmusphinx/voice-ac-nsh, those are new male and female voices. I'll work on hsmm voices meanwhile.

**Comment by nshmyrev** [comment]
Also https://github.com/cmusphinx/voice-ac-irina

**Comment by psibre** [comment]
@nshmyrev I've mirrored the data files under http://mary.dfki.de/repo so that they can be resolved from there as well.

**Comment by nshmyrev** [comment]
Great, thank you!

**Comment by psibre** [comment]
Closed by 4ffab2c19926576d40a85febe2141e99b826a995 on 5.x branch.

**Comment by psibre** [comment]
Also added these to the web installer for good measure, see marytts/marytts-installer#5.

**Comment by Des-Nerger** [comment]
@farizaghayev @nshmyrev 
Any news on hsmm?

**Comment by rik43** [comment]
no working link left
