### ISSUE TITLE
Support for Spanish

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#605]
Occasionally requested, we should have support for Spanish. There is a long-abandoned [es-branch on the old Trac](https://mary.opendfki.de/trac/browser/branches/es-branch), and somewhat more recent work (including the "Jorge" voice) by @marcelach1 but nothing was released.

**Comment by aitorme** [comment]
would it make more sense to build the voice from scratch, rather than using a very old Spanish branch, because of the outdated Mary version it was started on?

**Comment by kaiserjp** [comment]
Do you plan to make totally new one or import a Festival or some other flavor resource? I'm planing to make a Spanish voice in short and I don't have still a clear strategy.

**Comment by bonisthegreat** [comment]
@kaiserjp Are you working on it? I am interested in using MaryTTS in spanish and could help out if necessary

**Comment by kaiserjp** [comment]
@bonisthegreat Hi, as these days I have been working on another project, I have not finished the Spanish voice. My work plan is to have a minimum operative version this month. If you can collaborate I could study some way to do that.

**Comment by mdmartinezpad** [comment]
Hi guys!.. a question , any of you managed to use MaryTTS in Spanish? Thank you!
