### ISSUE TITLE
array out of bounds in over-eager email-preprocessor (de)

### ISSUE THREAD

**Issue by timobaumann** [marytts/marytts#606]
As @fhennig found out, speaking "mp3@64" doesn't work and results in:

> java.lang.Exception: Module Preprocess: Problem processing the data.
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
>	at java.lang.String.substring(String.java:1967)
>	at marytts.language.de.preprocess.NetEP.expandDomain(NetEP.java:216)
>	at marytts.language.de.preprocess.NetEP.expandNetEmail(NetEP.java:184)
>	at marytts.language.de.preprocess.NetEP.expand(NetEP.java:149)
>	at marytts.language.de.preprocess.ExpansionPattern.process(ExpansionPattern.java:270)
>	at marytts.language.de.Preprocess.matchAndExpandPatterns(Preprocess.java:105)
>	at marytts.language.de.Preprocess.process(Preprocess.java:61)
>	at marytts.server.Request.processOneChunk(Request.java:568)

The reason is that "64" is seen as a domain (ok) and then checked for whether it's a two-letter domain using `domain.lastIndexOf(".") == domain.length() - 3`. Which, given that lastIndex returns -1 matches the length of "64". Later, the pre-domain-name part is to be split off using domain.substring which fails. 

The following oneline patch fixes the problem -- I hope a patch is ok rather than a pull request?
Also, we skipped the part about writing a test first to then fix the code to make the test pass...

```diff
diff --git a/marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/preprocess/NetEP.java b/marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/preprocess/NetEP.java
index 8135285..d248593 100644
--- a/marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/preprocess/NetEP.java
+++ b/marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/preprocess/NetEP.java
@@ -210,7 +210,7 @@
 		if (domain.endsWith(".com")) {
 			toExpand = domain.substring(0, domain.length() - 4);
 			domainSuffix = " dot['dOt] com['kOm]";
-		} else if (domain.lastIndexOf(".") == domain.length() - 3) {
+		} else if (domain.lastIndexOf(".") != -1 && domain.lastIndexOf(".") == domain.length() - 3) {
 			// Domains consisting of two characters (de, ch, uk, ...)
 			// are to be spelled out
 			toExpand = domain.substring(0, domain.length() - 3);
```

**Comment by seblemaguer** [comment]
Thanks, I added that as a pull request :)

Seb
