### ISSUE TITLE
Working on MaryTTS 5.2 in Eclipse has a problem

### ISSUE THREAD

**Issue by nirvandy** [marytts/marytts#614]
hi sir,
i ran the project in eclipse according to the document.
(https://github.com/marytts/marytts/wiki/Eclipse_5.X#working-on-marytts-52-in-eclipse)
When on step:
    Running (or Debugging) the MaryTTS Server:
      7.In the Classpath tab, select User Entries, then click Add Projects... and select marytts-lang-en and voice-cmu-slt-hsmm, then click OK.

"Add Projects"button can't be clicked.
![image](https://cloud.githubusercontent.com/assets/4739525/19334659/24460582-9130-11e6-85e7-fc24a1dfaf72.png)

Why does this problem occur?

**Comment by psibre** [comment]
Your screenshot doesn't show which project you have selected. In any case, this is an issue with the Eclipse UI, not with MaryTTS.

**Comment by nirvandy** [comment]
![image](https://cloud.githubusercontent.com/assets/4739525/19340959/00439c02-915e-11e6-81fc-892fb1da92db.png)

hi sir,maybe i should change the description:

1. I import the project by Existing Maven projects.
2.Run->Maven install  ==>build success.
3.Run->Run Configuration.
Select Java Application and click the little New button.
In Main tab, i wanna set project to marytts-runtime.

As shown in the picture,project selection is null. Alike,Classpatch tab button is useless.

Does it means eclipse don't recognize projects?

**Comment by nirvandy** [comment]
I did some try.
In Run Configuration->JavaApplication, it seems that only java project can be selected.
So,if i import the MaryTTS as a maven project, how can "Running (or Debugging) the MaryTTS Server" step 4/5 work?

**Comment by psibre** [comment]
You could try creating a new Run configurations by right-clicking directly on the Mary class in the marytts.server package of the src/main/java source folder of the marytts-runtime project in the Package Explorer. But it could also be some issue with your Eclipse version, or some Eclipse plugin, or whatever. Also, I don't use Windows, so I'm afraid I can't help you further with this. Perhaps search the web?
