### ISSUE TITLE
Issue with HTK-3.4.1 and HDecode

### ISSUE THREAD

**Issue by LefterisStamellos** [marytts/marytts#615]
Hello everyone, 
I've been trying to follow the HMMVoiceCreation recipe and in the process I've encountered a problem with two of the external required files, namely HTK-3.4.1 and HDecode. 

I am aware that, since this is third party software, this here might not be the best place to report an issue. Nevertheless, I have informed the people who maintain the HTK project but I haven't got any response yet, so I thought that maybe someone could give me a hint here.

To the point: after filling in my personal details and pressing Yes in response to the License Agreement in the Registration Form here: http://htk.eng.cam.ac.uk/register.shtml , I do not get the expected result (according to the site, I should receive an email with my password). 
Instead, one of the two following happens:

1)A message appears showing the following:
htk_open_db(): Lost connection to MySQL server at 'reading initial communication packet', system error: 111
2) A pop up window appears which asks me for my User ID and password, which I obviously cannot provide at this point, since I haven't received any mail!

Has this happened to anyone else? 
Even more: can anyone somehow provide me with those two files I'm looking for (HTK-3.4.1.tar.gz and HDecode-3.4.1.tar.gz)? I am well aware that I am not permitted to acquire these files without registering, but given the situation I am not given any other option from the people in charge!

Thanks in advance!

**Comment by nshmyrev** [comment]
You'd better share your email for that.

As for the problem, it's better to contact 

Anna Langley
Control Group & Machine Intelligence Laboratory, IT Manager
Department of Engineering
University of Cambridge
Trumpington Street
CB2 1PZ

Tel: 44 (0)1223 748 255

jal58 at cam.ac.uk

She is in charge of this thing.

**Comment by LefterisStamellos** [comment]
> You'd better share your email for that.

Yes, you're right. If anyone is willing to provide me with those files, please contact me in the following address:
vgichuskin@gmail.com

> As for the problem, it's better to contact Anna Langley

I just did. Thank you very much for the contact info Nickolay.

**Comment by psibre** [comment]
@nshmyrev Thanks for your fast help!

However, @LefterisStamellos is correct:
> I am aware that, since this is third party software, this here might not be the best place to report an issue.

We have no control over the HTK website...
