### ISSUE TITLE
help me to create automatic allophones to transcript.sh

### ISSUE THREAD

**Issue by baaslaawe** [marytts/marytts#618]
My name is Awale , and I am currently trying to develop MaryTTS . so I am currently stuck with Mary Transcription tool.so mostly **so language** used arabic ALPHABETIC (phones sampa ) ,for me it's difficult to write or change every word to convert by manually allophones(using _transcript.sh_) ,please help me if you know any way that convert automatic

thank you

**Comment by nshmyrev** [comment]
Simple script should be enough, the mapping is here:

https://en.wikipedia.org/wiki/Wadaad_writing

You can share the list of words, I'll convert it for you.

**Comment by baaslaawe** [comment]
thank you bro @nshmyrev so this is list of words
[somali.txt](https://github.com/marytts/marytts/files/532117/somali.txt)

**Comment by nshmyrev** [comment]
pick [so.dict](http://alphacephei.com/test/tts/so.dict)

**Comment by baaslaawe** [comment]
thank you bro 
but what i want is like this  ,_X-SAMPA_
_this is arabic most somali and arabic_ it's same only different is somali is latin ,i am confused. **this is arabic (**https://github.com/bellegdi/marytts-lang-ar/blob/master/lib/modules/ar/lexicon/allophones.ar.xml
https://github.com/bellegdi/marytts-lang-ar/blob/master/lib/modules/ar/lexicon/ar.txt)
**Somali phonology(X-SAMPA)
http://aboutworldlanguages.com/somali**
please help me and also if you help any **script(code) or program** that to convert like the arabic to allophones.so.xml
thank you
