### ISSUE TITLE
StringUtils.toStringArray behavior inconsistent across platforms

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#62]
`marytts.util.string.StringUtils#toStringArray` in `marytts-common` has different results on Mac than on Windows. This becomes a problem when it is used to process resources with CRLF line endings, leading to #61.

**Comment by Munzey** [comment]
perhaps it should be removed as part of a larger refactoring of the code later on with #327

**Comment by seblemaguer** [comment]
I plan to remove a lot of this class and relied more on standard class for that

**Comment by psibre** [comment]
@seblemaguer I agree 100% to drop hand-rolled utility classes in favor of [Apache Commons](https://commons.apache.org/) etc., but it will be tedious to refactor the code. I propose to first annotate them as `@Deprecated` and then delegate the refactoring to ensure nothing breaks. #61 is closed (and irrelevant for the future), but similar side-effects may creep in.
