### ISSUE TITLE
Error with HMM feature extraction on French computer

### ISSUE THREAD

**Issue by BenjaminPoilve** [marytts/marytts#632]
Hi, 
There seems to be an issue related to HMM feature extraction while voicebuilding. 
Basically while extracting the f0, it does this:
```

Extracting f0 from raw/1.raw
/bin/sh: line 0: printf: 80.000: invalid number
```
I let it run for a few minutes and the temp file was already 8GB! 
It turned out the problem is related to number formatting. In France we are used to use comma instead of point for decimals. So 80.000 is an invalid number while 80,000 is not. 
So this printf returned 0 , which create an infinite loop for the script.
Quick fix: change your bash to use English Locale (see [here](http://askubuntu.com/questions/724338/how-to-set-lc-numeric-to-english-permanently))
In the long run... Stop using this stupid French locale when configuring computers I guess! Joking aside, I don't know if there is a solution to fix the script.

**Comment by psibre** [comment]
Thanks for raising the issue, but it's really the HTS scripts that were imported years ago. Perhaps you can add a note about setting the locale [in the wiki](../wiki/HMMVoiceCreation)?

@seblemaguer seems like something that would have come up on hts-users?

**Comment by BenjaminPoilve** [comment]
Sure would be glad to contribute! 
I came across another bug, and it seems like I am [not the only one](https://github.com/marytts/marytts/issues/612). Should I also add that or should it be the subject of a pull request (I don't have the knowledge to make the bugfix myself, but I could document the quick fix)?

**Comment by psibre** [comment]
Feel free to contribute to the wiki if you spot documentation that is incomplete or out of date. Unlike the main code repo, you don't need to open PRs for that.

**Comment by seblemaguer** [comment]
Hello,

@psibre never seen that on the hts-mailing list but by definition I never use the french local in the terminal for coding neither.
