### ISSUE TITLE
WaveTimeLineMaker Array out of bound exception

### ISSUE THREAD

**Issue by TahreemSaleem** [marytts/marytts#634]
while running WaveTimeLineMaker I got this exception

Processing [10] utterances.

---- Detected a global sample rate of: [44100] Hz.
---- Folding the wav files according to the pitchmarks...
Will create the waveform timeline in file [/home/tahreem/Speech_stuff/marytts-master/my_voice/mary/timeline_waveforms.mry].
ur01

ur02
ur03
ur05
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

my database config file is 
[database.config.txt](https://github.com/marytts/marytts/files/569927/database.config.txt)

**Comment by psibre** [comment]
Please provide the full stacktrace of the error.

**Comment by psibre** [comment]
This is actually related to what @moitreebasu1990 and @pradiptadeb1990 are currently working on. They may be able to debug this.

**Comment by moitreebasu1990** [comment]
@TahreemSaleem please provide us with the full stack trace of the error.

**Comment by TahreemSaleem** [comment]
Error resolved when i restarted the voicebuilding.sh and did all the steps again
