### ISSUE TITLE
marytts-component-installer doesn't show my language or voice

### ISSUE THREAD

**Issue by TahreemSaleem** [marytts/marytts#636]
I added a new language successfully by following the tutorial then i build a unit selection voice using tutorial([https://github.com/marytts/marytts/wiki/UnitSelectionVoiceCreation]). but at third step of 'publishing marytts voice'[https://github.com/marytts/marytts/wiki/Publishing-a-MARY-TTS-Voice] i ran marytts-component-installer , i couldn't see my language. my locale's jar is in lib and voice is in download folder. I cant seem to find the problem.

**Comment by psibre** [comment]
Glad to hear you got so far! This is just a trivial annoyance I think.

First, a sanity check: In your `MARYBASE` directory, if you have your new language jar in `MARYBASE/lib`, then you start `MARYBASE/bin/maryserver`, what is the response if you go to http://localhost:59125/locales in your browser? Does the list contain your locale? If not, please see #587 for possible solutions.

If your language components *are* loaded successfully, then you can just unzip your unitselection voice under `MARYBASE/lib` as well, restart the `maryserver`, and double-check that it's loaded by going to http://localhost:59125/voices.

If all of this works, then it's probably an issue with the installer, and we can debug that next.

**Comment by TahreemSaleem** [comment]
Thank you for responding this quickly.
I started the Server, response that i got from http://localhost:59125/locales  is 
lb
de
ru
fr
ur
sv
en_US
en_GB
te
tr
it

My language is Urdu(ur) and its there.When i checked http://localhost:59125/voices. it gave me following response:
my_voice ur female unitselection general
cmu-slt-hsmm en_US female hmm

my_voice is the voice i built.

**Comment by psibre** [comment]
OK, that's great! So everything can be loaded properly, and you can try to actually use it.

The issue you describe above is essentially a UI issue with the old InstallerGUI. It checks at startup for any `marytts-lang-*-component.xml` in `MARYBASE/installed`. If it finds one (and it can be parsed correctly) *then* it adds a UI panel with the corresponding locale in the left half of the InstallerGUI, which (when clicked) lists the available voices for that locale in the right half. So without a specially crafted `marytts-lang-ur-VERSION-component.xml` file in the right place, the UI won't show your language or the voice that you built for it.

Have a look at, e.g., the `marytts-lang-de-VERSION-component.xml` file; you could use it as a template to create such a file for Urdu.

**Comment by TahreemSaleem** [comment]
Alright Thanks a lot for your help. I will have a look at that file.
