### ISSUE TITLE
How is speech rate measured internally?

### ISSUE THREAD

**Issue by andreas-weise** [marytts/marytts#640]
This is not an issue but rather a question about the inner workings of MaryTTS. 

For my work I need to be able to control the speech rate of the synthesis as closely as possible. I am using SSML with the "prosody" tag to do that. However, the speech rate of different texts, as measured by number of syllables divided by output length, can vary pretty widely for the same "rate" setting. 

For instance, using MaryTTS 5.2 with the "cmu-rms-hsmm" voice at the default rate I synthesized the following two example sentences:
"Caldwell's resignation had been expected for some time." 
"Under committee rules it went automatically to a subcommittee for one week."
For the first sentence of 14 syllables I get an output of 4.345s, for the second sentence of 22 syllables I get 5.235 seconds of output. That makes for speech rates of about 3.2 syllables per second and 4.2 syllables per second, respectively, so the second is over 30 percent faster than the first when measured this way. As far as I can tell this is mostly due to the fact that "committee" is pronounced pretty quickly both times it occurs in the second sentence.

Now, my question is, how does MaryTTS measure speech rate internally - as phoneme rate, syllable rate, word rate, any linear combination of the three or something else? Perhaps measured differently the above examples actually have close to the same rate? Or, alternatively, is keeping the rate the same for the same "rate" setting actually not a priority and a 30 percent variation is just "normal"?

**Comment by nshmyrev** [comment]
Speech is not "measured". Voice is trained from a database where many recordings have approximately similar speech rate. On TTS speech is reproduced with approximately same rate. You can make speech faster or slower thus changing the rate.

In speech there could be timing variations, you say some syllables, for example function words, faster. Accented syllables are longer. So some sentences are pronounced faster, some slower. To measure rate reliably you need much longer texts than you tried, probably 100-200 syllables. Accented syllable count probably will give you better estimation since English tends to keep rhythmic structure, but for longer texts estimation from syllable count and from accented syllable count should converge.

**Comment by andreas-weise** [comment]
Thanks for the quick response and the explanation. It makes sense to me that for the default rate you would not need to measure anything but rather use the lengths as they were in the training data, as you describe.
I also understand that for long texts this will converge but unfortunately in my application I am limited to utterances of roughly the same lengths as those of the examples above, so I will have to make it work with that as well as possible. I will look into using accented syllable counts, thanks for the suggestion.

Could you also explain what MaryTTS does for non-default rates? As far as I recall, speech rate can be manipulated by finding periodic segments of the signal (voiced phonemes) and changing their length. How exactly is the factor from SSML, e.g., "+30%", used in that, though? 
Using a small corpus of the same 100 sentences each time and determining their average rate (which is basically what you suggested), I noticed a while ago that the change in rate is not really linear. I can get virtually the same average for some consecutive rates, let's say "+14%", "+15%" and "+16%" and then at "+17%" it suddenly "jumps" by almost 10%. Can you explain what is causing that?

**Comment by psibre** [comment]
MaryTTS predicts segment durations, not speech (or articulation) rate. It can do this using statistical models (HMMs or CARTs) or rules (e.g., Klatt). If you want to precisely enforce some sophisticated notion of speech rate on the synthesized output, you'll need to figure out on your own how to convert that into segment durations, then you can override the corresponding attributes in the MaryXML and use that as `ACOUSTPARAMS` input.

For unit-selection voices, you are then at the mercy of what the database and cost function coefficients provide. In very nearly all cases, the *realized* durations will be different from the target durations you requested. I suspect this is what you noticed, and it disqualifies unit-selection from your scenario.

On the other hand, you should be able to synthesize audio where the segment durations are realized according to your target specification using MBROLA and (to a lesser degree) HMM-based synthesis.

**Comment by andreas-weise** [comment]
Thanks for the explanation. 
The example I mentioned was not for a unit selection voice but for HMM. Anyway, I guess this means that theoretically, if I specify segment durations myself, an HMM voice should be able to realize the target specification pretty closely. However, since I am currently specifying merely a target rate, the change is not quite as linear as I would like it to be, even for HMM voices.
