### ISSUE TITLE
Problem with transation tool for new language

### ISSUE THREAD

**Issue by imty1000** [marytts/marytts#642]
Hello everyone, i am sorry that i could not finish it for many reasons and now i need your help. I have already used the mary build tools for building the environment. However, i am stuck with transcription tool. i corrected 12,000 words and press train button it trained and when i reopen it i loss all data though i saved them before closing. and i had faced this problem many times and could not finish it. Now can anyone tell me what is the wrong am i doing? 

NB: i have done all the installation process for many times as i might miss any thing. please help me with this issue. what do i do?

**Comment by psibre** [comment]
I'm sorry to say the Transcription GUI Tool has not been maintained for many years, and we don't have the resources to fix issues with it.

I would recommend that you have a look at the [LTSLexiconPOSBuilder](../blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-transcription/src/main/java/marytts/tools/transcription/LTSLexiconPOSBuilder.java), which might be less unstable.

**Comment by imty1000** [comment]
Thank you for your reply sir. I am a little bit confused, how do i use it?

**Comment by psibre** [comment]
There is a wrapper script in the **marytts-builder** package, at `bin/lexicon_lts_pos_builder.sh`.

From the [API documentation](http://mary.dfki.de/javadoc/marytts/tools/transcription/LTSLexiconPOSBuilder.html#main(java.lang.String[])):
> first argument, PhoneSet file name; second argument, Transcriptions file name
