### ISSUE TITLE
voiceimport EHMMLabeler  baumWelchEHMM computation failed.

### ISSUE THREAD

**Issue by baaslaawe** [marytts/marytts#643]
hello i got this error please help me 

Preparing voice database for labelling using EHMM :
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Setting up EHMM directory ...
 ... done.
Getting Phone Sequence from Phone Features...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Dumping required files ....
( cd /home/abdullahi/voice/somali/ehmm; perl /home/abdullahi/voice/sources/marytts/lib/external/ehmm//bin/phfromutt.pl /home/abdullahi/voice/somali/ehmm/etc/ehmm.align /home/abdullahi/voice/somali/ehmm/etc/ehmm.phoneList 5; perl /home/abdullahi/voice/sources/marytts/lib/external/ehmm//bin/getwavlist.pl /home/abdullahi/voice/somali/ehmm/etc/ehmm.align /home/abdullahi/voice/somali/ehmm/etc/ehmm.waveList; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Computing MFCCs ...
( cd /home/abdullahi/voice/somali/ehmm; /home/abdullahi/voice/sources/marytts/lib/external/ehmm//bin/FeatureExtraction /home/abdullahi/voice/somali/ehmm/etc/ehmm.featSettings /home/abdullahi/voice/somali/ehmm/etc/ehmm.waveList >> log.txt; perl /home/abdullahi/voice/sources/marytts/lib/external/ehmm//bin/comp_dcep.pl /home/abdullahi/voice/somali/ehmm/etc/ehmm.waveList /home/abdullahi/voice/somali/ehmm/feat mfcc ft 0 0 >> log.txt ; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Scaling Feature Vectors ...
( cd /home/abdullahi/voice/somali/ehmm; perl /home/abdullahi/voice/sources/marytts/lib/external/ehmm//bin/scale_feat.pl /home/abdullahi/voice/somali/ehmm/etc/ehmm.waveList /home/abdullahi/voice/somali/ehmm/feat /home/abdullahi/voice/somali/ehmm/mod ft 4 >> log.txt; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Converting Feature Vectors to Binary Format ...
( cd /home/abdullahi/voice/somali/ehmm/feat; for file in *.ft; do /home/abdullahi/voice/sources/marytts/lib/external/ehmm//bin/ConvertFeatsFileToBinaryFormat $file ${file%%.ft}.bft >> ../log.txt; done; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Intializing EHMM Model ...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
EHMM baum-welch re-estimation ...
It may take more time (may be 1 or 2 days) depending on voice database ...
( cd /home/abdullahi/voice/somali/ehmm; /home/abdullahi/voice/sources/marytts/lib/external/ehmm//bin/ehmm /home/abdullahi/voice/somali/ehmm/etc/ehmm.phoneList.int /home/abdullahi/voice/somali/ehmm/etc/ehmm.align.int 1 0 /home/abdullahi/voice/somali/ehmm/feat bft /home/abdullahi/voice/somali/ehmm/mod 0 0 0 48 4 >> log.txt; exit )

java.lang.Exception: The component EHMMLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.MaryConfigurationException: baumWelchEHMM computation failed.
Error: null
	at marytts.tools.voiceimport.EHMMLabeler.baumWelchEHMM(EHMMLabeler.java:534)
	at marytts.tools.voiceimport.EHMMLabeler.compute(EHMMLabeler.java:205)
	at marytts.tools.voiceimport
.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

this is log
[log.txt](https://github.com/marytts/marytts/files/604683/log.txt)

**Comment by psibre** [comment]
This is specific to EHMM, which is from [FestVox](http://festvox.org) and was bundled, but not created or maintained, by the MaryTTS developers. You may be able to find a solution if you search the web.

Otherwise, please note that EHMM is only one of many tools to apply phone-level forced alignment. You can just as well use [WebMAUS](http://clarin.phonetik.uni-muenchen.de/BASWebServices/#/services/WebMAUSMultiple), or HTK or Kaldi or whatever. Just be aware that you may have to convert the symbol sets, but that should be straightforward.

**Comment by baaslaawe** [comment]
thank you but another question
1- what minimum and maximum  audio for example my voice some of more then 0.17 sec(17) some are two sec 
can i know what min and max 
 is there effective 
2- can i use IPA for transcript or requirement x-samp only 
 any advice 
than you

**Comment by psibre** [comment]
>1- what minimum and maximum audio for example my voice some of more then 0.17 sec(17) some are two sec
can i know what min and max

There's some useful discussion of such design considerations in #628.

>  2- can i use IPA for transcript or requirement x-samp only

Since this seems to be a completely unrelated question, please open a new issue for it.

**Comment by baaslaawe** [comment]
thank you  @psibre
 i was used HTKLabeler but also i was try but it's same
**this website i did't get my language somali  WebMAUS**
please help me i am confused
`this is output  `
cd /home/abdullahi/voice/somali//htk/; /home/abdullahi/voice/sources/htk/HTKTools//HERest -A -D -V -T 1 -C /home/abdullahi/voice/somali//htk//config/htkTrain.conf -I /home/abdullahi/voice/somali//htk//etc/htk.phones.mlf -t 250.0 150.0 1000.0 -S /home/abdullahi/voice/somali//htk//etc/htkTrain.list -H /home/abdullahi/voice/somali//htk//hmm/hmm0/macros -H /home/abdullahi/voice/somali//htk//hmm/hmm0/hmmdefs -M /home/abdullahi/voice/somali//htk//hmm/hmm1 /home/abdullahi/voice/somali//htk//etc/htk.phone.list >> log_herestTraining_1.txt; exit )

java.lang.Exception: The component HTKLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.MaryConfigurationException:   ERROR [+5013]  ReadString: String too long
	at marytts.tools.voiceimport.HTKLabeler.herestTraining(HTKLabeler.java:1020)
	at marytts.tools.voiceimport.HTKLabeler.compute(HTKLabeler.java:247)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

**Comment by baaslaawe** [comment]
still i need you guys

**Comment by nshmyrev** [comment]
It will help you to provide your files, otherwise it is hard to guess.

**Comment by baaslaawe** [comment]
ok thankn bro 

https://github.com/baaslaawe/somTTS.git

**Comment by baaslaawe** [comment]
ok thankn bro @nshmyrev 
i don't have more knowledge github but i was try to my best 
****# 

**1. marytts-lang-so** 
**2. somali**
https://github.com/somTTS/somTTS
****	

thank you

**Comment by baaslaawe** [comment]
HELLO @nshmyrev

**Comment by nshmyrev** [comment]
Hello @baaslaawe , Its better for your to provide your folder `/home/abdullahi/voice/somali/` compressed including htk files, not simply source files you put on github.

**Comment by baaslaawe** [comment]
thank you bro @nshmyrev 

this is full https://www.dropbox.com/s/obcqsqu7iwju0ba/somali.tar.gz?dl=0

thank you

**Comment by baaslaawe** [comment]
HELLLO @nshmyrev

**Comment by nshmyrev** [comment]
I'm looking on your archive, it does not contain htk files. I only see ehmm attempt and it is broken mostly due marytts bug, it does not insert ssil properly after each word. Do you want to continue with ehmm instead of htk or what?

**Comment by baaslaawe** [comment]
YES I WANT TO continue  ehmm

**Comment by baaslaawe** [comment]
i just fallow steps of mary wiki ,so can i send htk file

**Comment by baaslaawe** [comment]
thank you alot @nshmyrev  

this is htk files https://drive.google.com/open?id=0B0AS2DD8i5DcdmtKV1RRbEllVlE

**Comment by baaslaawe** [comment]
hello sir @nshmyrev  is there any update

**Comment by baaslaawe** [comment]
please help me 
hello bro @nshmyrev  is there any update ,

thank you

**Comment by baaslaawe** [comment]
hello BRO @nshmyrev is there any update ,

thank you

**Comment by psibre** [comment]
@baaslaawe you can do it yourself or you try out this thing called patience.

**Comment by baaslaawe** [comment]
thank you bro @psibre 
I AM CONFUSED WHAT IS WRONG , i am trying to do more then 4 months ,but still some think ,and also my language there are no more resources ,that is may problem ,
i am the first person who can do it for this project 
please help me 
tnaks

**Comment by nshmyrev** [comment]
Your HTK training fails because you have a special symbol "\" in the phone name "X\" in your phoneset. I recommend you to rename that phone. Overall I recommend you to use simple letter-only phone names without punctuation marks.

We can try to fix EHMM too.

**Comment by baaslaawe** [comment]
OK THANK YOU BROTHER @nshmyrev ,
BUT when i check sampa my language are used X\ ,so how 

thnaks alot

**Comment by seblemaguer** [comment]
just adapt "\" using another symbol which is not special character

**Comment by baaslaawe** [comment]
thank you bro @seblemaguer  i was remove \  but still i am getting same error

java.lang.Exception: The component EHMMLabeler produced the following exception:
at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.MaryConfigurationException: baumWelchEHMM computation failed.
Error: null
at marytts.tools.voiceimport.EHMMLabeler.baumWelchEHMM(EHMMLabeler.java:534)
at marytts.tools.voiceimport.EHMMLabeler.compute(EHMMLabeler.java:205)
at marytts.tools.voiceimport
.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

**Comment by nshmyrev** [comment]
@baaslaawe , you need to run htk after phoneme name fix, not ehmm.

**Comment by baaslaawe** [comment]
thank you for helping brother @nshmyrev  
**successful it's done**

**Comment by baaslaawe** [comment]
i got this error **HMMVoiceMakeVoice**

The training procedure can take several hours...
Detailed information about the training status can be found in the logfile:
  /home/abdullahi/voice/somali/hts/log-2016.12.12-21:11:37

Training voice: my_voice
The following is general information about execution of training steps:

Step: Start preparing environments at Mon Dec 12 21:11:37 EAT 2016

Step: Start computing variance floors at Mon Dec 12 21:11:37 EAT 2016
java.lang.Exception: The component HMMVoiceMakeVoice produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException:  computation failed on file [/home/abdullahi/voice/somali/]!
Command line was: [/usr/bin/perl /home/abdullahi/voice/somali/hts/scripts/Training.pl /home/abdullahi/voice/somali/hts/scripts/Config.pm].
	at marytts.tools.voiceimport.HMMVoiceMakeVoice.launchProcWithLogFile(HMMVoiceMakeVoice.java:189)
	at marytts.tools.voiceimport.HMMVoiceMakeVoice.compute(HMMVoiceMakeVoice.java:127)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

**Comment by nshmyrev** [comment]
@baaslaawe 1) open a new issue about new problem 2) learn to provide the files and logs, the more information you provide the faster you get an answer.
