### ISSUE TITLE
New Language Support issue 

### ISSUE THREAD

**Issue by haquynh1505** [marytts/marytts#644]
Hi there,
I've been trying to run New Language Support for my own language Vietnamese. 
I followed the instruction from https://github.com/marytts/marytts/wiki/New-Language-Support, successfully creating config file, downloading and extracting the dump xml file. However, while I was trying to split it, I bumped into this error 

-------------------------------------------------------

/marytts/sources/marytts-5.x/target/marytts-builder-5.3-SNAPSHOT/bin/wkdb_split_dump.sh: 61: /marytts/sources/marytts-5.x/target/marytts-builder-5.3-SNAPSHOT/bin/wkdb_split_dump.sh: java: not found

----------------------------------------------------------

Does anybody know what is going on here? Thanks a lot in advance!
p/s: I attach here the split_dump file

[wkdb_split_dump.txt](https://github.com/marytts/marytts/files/608042/wkdb_split_dump.txt)

**Comment by psibre** [comment]
![ae7rxqo_700b_v1](https://cloud.githubusercontent.com/assets/1278639/20551589/1eaaa538-b142-11e6-9ec3-2c69ed8d6be3.jpg)

**Comment by psibre** [comment]
Seriously though, you need a JDK installed, and possibly `export JAVA_HOME` with the correct path.

**Comment by haquynh1505** [comment]
@psibre : Thank you so much for your response. I fixed it by correcting the JAVA_HOME.
However, while I was trying to use the TranscriptionTool, I had another error, which is:
java.lang.IllegalArgumentException: Allophone `,' could not be found in AllophoneSet `sampa' (Locale: vi_VI)
I then checked both my wordList and my Allophones file but seeing nothing like ',' 
Could you please tell me what I'm having now? 
Thanks a lot in advance!

**Comment by psibre** [comment]
If you have a fork of marytts, could you push your Vietnamese feature branch? Then it would be easier to reproduce and debug your error.

**Comment by haquynh1505** [comment]
@psibre : sorry, I have yet to have many experiences with the fork function. Therefore, I attach here my allophones.xml file and wordlist.txt. 
Please take a look. I hope you could find something out from these! 
Thank you so much for your endless help!
[wordlist.txt](https://github.com/marytts/marytts/files/609452/wordlist.txt)
[Allophones_vi.txt](https://github.com/marytts/marytts/files/609453/Allophones_vi.txt)

**Comment by psibre** [comment]
Thanks for attaching your wordlist and allophone set!

The problem here is an internal one. Previously (based on the conventions in [CMUdict](http://www.speech.cs.cmu.edu/cgi-bin/cmudict)), syllable stress was encoded with a trailing **1** (or **2** for secondary stress) after the vowel symbols. So at the version of the code you're using, these trailing digits are being converted into stress marks (`'` in MaryTTS notation), but not only is that causing errors, it's also wrong because you're using the digits to encode tone, not stress.

As a quick workaround, could you try to convert your transcription in such a way that you don't have those numeric digits, but encode tone in a different way?

**Comment by haquynh1505** [comment]
@psibre : thank you so much for your help! I figured it out myself and have fixed it this already. Sorry for not informing you earlier, because I've been busy to fix another problem, that is kind of the same as #72 and #577 
Some guys said that they tried to build v4.3.1 and ran the transcription tool successfully with it. Therefore, I tried to build that version too, using the tag that you gave me. I built it by Ant as your suggestion. Although the console said the building task was successful after approximately 20 secs (???), I couldn't find the transcription tool to transcript my words. And it looks nothing like the more familiar versions that I've been working with. Therefore, I supposed that this wouldn't help either. 
Do you have any idea about this? 
Thank you so much!

**Comment by JSefara** [comment]
Same problem. I attach here my allophones file and word list file. Please check them and get back to me.

[tso.txt](https://github.com/marytts/marytts/files/719616/tso.txt)


[allophones.tso.xml.txt](https://github.com/marytts/marytts/files/719620/allophones.tso.xml.txt)
