### ISSUE TITLE
Issue with webserver configuration

### ISSUE THREAD

**Issue by lgw24** [marytts/marytts#649]
Hi all,

please check here: http://alifba.org/joomla_3/index.php/dictionary

-> enter the word "schnell"
-> after click to play sound you are going to http://www.alifba.org:59125/process?INPUT_TEXT=schn&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&AUDIO=WAVE_FILE&LOCALE=de_DE

How to fix this issue?

Regards,

**Comment by psibre** [comment]
Could you be more specific? Please describe the error so that we can understand what is going wrong without having to click on your link.

**Comment by lgw24** [comment]
Hi, please visit the links, after live checking you will see the error, configuration issue.

**Comment by psibre** [comment]
Please provide the error message.

**Comment by lgw24** [comment]
Hi,

link: http://www.alifba.org:59125/process?INPUT_TEXT=schn&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&AUDIO=WAVE_FILE&LOCALE=de_DE

Error: Fehler: Verbindung fehlgeschlagen

Firefox kann keine Verbindung zu dem Server unter www.alifba.org:59125 aufbauen.

    Die Website könnte vorübergehend nicht erreichbar sein, versuchen Sie es bitte später nochmals.
    Wenn Sie auch keine andere Website aufrufen können, überprüfen Sie bitte die Netzwerk-/Internetverbindung.
    Wenn Ihr Computer oder Netzwerk von einer Firewall oder einem Proxy geschützt wird, stellen Sie bitte sicher, dass Firefox auf das Internet zugreifen darf.

**Comment by psibre** [comment]
Sounds like a problem with your web server configuration. Is the MaryTTS server running? Is the port open?

Did you follow the [instructions in the wiki](../wiki/Local-MaryTTS-Server-Installation) that explain how to avoid common pitfalls?
