### ISSUE TITLE
Normalization for "oz" and "km" does not work 

### ISSUE THREAD

**Issue by fhennig** [marytts/marytts#651]
Hey, 

I'm looking at german here, but maybe the bug occurs in other languages as well. "300km" is not normalized properly, while "300m" or "300dm" is.

The Problem [is in the MeasureEP file](https://github.com/marytts/marytts/blob/497548b263b4ec15095ae1ad1209b55dbaa5755c/marytts-languages/marytts-lang-de/src/main/java/marytts/language/de/preprocess/MeasureEP.java#L119):
```
		for (int i = 2; i < _nuDeFeMeasureSymbolNames.length; i += 2) {
			_sMeasureSymbol.append("|" + _nuDeFeMeasureSymbolNames[i]);
		}
		if (_maMeasureSymbolNames.length > 0)
			_sMeasureSymbol.append(_maMeasureSymbolNames[0]);
```
Between the for loop and the if, a `|` needs to be inserted into the regex, because now it contains "..|ozkm|.." instead of "...|oz|km|...". This also means that "300ozkm" is normalized to "Drei Hundert null"

**Comment by psibre** [comment]
Thanks for the meticulous report! In fact, as you have already debugged this issue and provided a solution, please feel free to reap the glory by opening a pull request! =)

**Comment by fhennig** [comment]
I made the pull request. I also grepped a little for similar issues but couldn't find any, and I tested it to make sure it works!

**Comment by psibre** [comment]
@fhennig Thanks very much for your contribution!
