### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by datomnurdin** [marytts/marytts#659]
After generated custom language, can load it in android app?

**Comment by seblemaguer** [comment]
Technically yes. We haven't done anything about android on the current project but you can find some issues talking about it

**Comment by farizaghayev** [comment]
@seblemaguer , Thank maryTTS was  created such repo. 

@datomnurdin  With using this  repo we have created  Android version of this repo. Of course there are a lot of task to fix.   [https://github.com/AndroidMaryTTS](AndroidMaryTTS ).

**Comment by datomnurdin** [comment]
@farizaghayev 404?

**Comment by farizaghayev** [comment]
??? 404???

**Comment by nshmyrev** [comment]
@farizaghayev, the link you gave previously should point to [https://github.com/AndroidMaryTTS](https://github.com/AndroidMaryTTS), not to [https://github.com/marytts/marytts/issues/AndroidMaryTTS](https://github.com/marytts/marytts/issues/AndroidMaryTTS) as it points currently and returns 404 error.

**Comment by farizaghayev** [comment]
@nshmyrev  thanks for correction.
