### ISSUE TITLE
Online web demo is down

### ISSUE THREAD

**Issue by RyanRamchandar** [marytts/marytts#660]
http://mary.dfki.de:59125/ is down.

**Comment by seblemaguer** [comment]
Thanks it is back

**Comment by ulasb** [comment]
Seems to be down again ?

**Comment by seblemaguer** [comment]
yup it was, it is back :)

**Comment by BernardTeske** [comment]
Seems again to be broken. Or does it not work on iPad?

**Comment by psibre** [comment]
For the record, if it breaks, it usually restarts automatically. So please try again in a few minutes before you raise an issue.

**Comment by kibeb** [comment]
It's broken again, since yesterday at least, so waiting minutes didn't help this time. ;) 
TIA.

**Comment by psibre** [comment]
@kibeb Thanks for the notification! This time, it was apparently locked up and didn't restart. Fixed now.

**Comment by leondroidgeeks** [comment]
It seems like the demo is broken. It won't load the drop-downs for Voice and Audio-Out.

**Comment by arantzapozo** [comment]
It seems to be back again, could you have a look please?

**Comment by Pierstoval** [comment]
Down for me today 😕

**Comment by king-dahmanus** [comment]
uh-oh, looks like it's down!

**Comment by lestofante** [comment]
it is down again!

**Comment by Zireael07** [comment]
Demo is down again

**Comment by rakotomandimby** [comment]
Down as of today
