### ISSUE TITLE
HTS Voice Build failed at Synthesis step

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#661]
Hi all,

I have been trying to build a trial voice using marytts. The database I am using is my own, but all the other settings are by default US English. All the steps worked fine upto the HTS build. The HMMVoiceMake failed when I ran it from the GUI, so I ran the script from the terminal as instructed.

But some errors occurred in the end:
The logfile looks like this:

================================================================================
Start synthesizing waveforms using hts_engine at Wed Dec 14 17:14:54 NZDT 2016
================================================================================

Synthesizing a speech waveform from /home/jjam194/mary/akl_nz_cw_cgm/hts/data/labels/gen/gen_uoa_nz_mansfield_cw_0026.lab using hts_engine...

The errors in the terminal is:

x2x : warning: input data is over the range of type 'short'!
.
.
.
.
x2x : warning: input data is over the range of type 'short'!
x2x : warning: input data is over the range of type 'short'!
Error: HTS voices cannot be loaded.
Error in /usr/local/bin/hts_engine -td /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/tree-dur.inf -tf /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/tree-lf0.inf -tm /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/tree-mgc.inf -tl /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/tree-lpf.inf -md /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/dur.pdf -mf /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/lf0.pdf -mm /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/mgc.pdf -ml /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/lpf.pdf -dm /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/mgc.win1 -dm /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/mgc.win2 -dm /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/mgc.win3 -df /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/lf0.win1 -df /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/lf0.win2 -df /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/lf0.win3 -dl /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/lpf.win1 -s 16000 -p 80 -a 0.42 -g 0 -l -b 0.4 -cm /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/gv-mgc.pdf -cf /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/gv-lf0.pdf -k /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/gv-switch.inf -em /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/tree-gv-mgc.inf -ef /home/jjam194/mary/akl_nz_cw_cgm/hts/voices/qst001/ver1/tree-gv-lf0.inf -b 0.0  -or /home/jjam194/mary/akl_nz_cw_cgm/hts/gen/qst001/ver1/hts_engine/gen_uoa_nz_mansfield_cw_0026.raw -ot /home/jjam194/mary/akl_nz_cw_cgm/hts/gen/qst001/ver1/hts_engine/gen_uoa_nz_mansfield_cw_0026.trace /home/jjam194/mary/akl_nz_cw_cgm/hts/data/labels/gen/gen_uoa_nz_mansfield_cw_0026.lab

I am using :
 MaryTTS 5.2
java version "1.8.0_111"
HTS-2.2_for_HTK-3.4.1.patch 
SPTK-3.4.1
sox 14.0.0

Please provide me some suggestions.

Regard

Jesin

**Comment by jesinj** [comment]
Hi,

I found that the /home/jjam194/mary/akl_nz_cw_cgm/hts/gen/qst001/ver1/hts_engine/gen_uoa_nz_mansfield_cw_0026.trace  and  /home/jjam194/mary/akl_nz_cw_cgm/hts/gen/qst001/ver1/hts_engine/gen_uoa_nz_mansfield_cw_0026.raw are not being generated, which could be the reason for the failure. But I did not find any other errors in the previous steps or in the log file.

Jesin

**Comment by nshmyrev** [comment]
> I found that the /home/jjam194/mary/akl_nz_cw_cgm/hts/gen/qst001/ver1/hts_engine/gen_uoa_nz_mansfield_cw_0026.trace and /home/jjam194/mary/akl_nz_cw_cgm/hts/gen/qst001/ver1/hts_engine/gen_uoa_nz_mansfield_cw_0026.raw are not being generated

You can remove this particular utterance from the database and proceed.

>  But I did not find any other errors in the previous steps or in the log file.

You could share your data folder if you need more help on this. Without seeing the logs and the data it is hard to suggest you something.

**Comment by jesinj** [comment]
Hi,

I did the installations again just to be sure about the versions etc, and the voice got built now (even though its of poor quality..which is another problem to handle.

Thankyou for the ideas.

Jesin
