### ISSUE TITLE
Improve documentation about loading non-hmms voices

### ISSUE THREAD

**Issue by raginggoblin** [marytts/marytts#667]
In the wiki there is a page named MaryInterface (https://github.com/marytts/marytts/wiki/MaryInterface). This page explains how you can load a hmms voice on the classpath and use the MaryInterface to select this language. There is however no explanation about loading unit selection voices. Though I send a request to the mailing list, I think this is something that should be part of the wiki as well.

**Comment by psibre** [comment]
Thanks for the suggestion. Note that the wiki is open to editing from any GitHub user, so you can contribute directly.

**Comment by seblemaguer** [comment]
the pointed page is actually not really about the loading of the voice but more about how to call the server.
