### ISSUE TITLE
Error in building new language [createdFiles.lst (Permission denied)]

### ISSUE THREAD

**Issue by MomnaSaeed** [marytts/marytts#668]
I am working on new language support in marytts for Urdu, The error i am getting in building new language is in the target folder.
![image](https://cloud.githubusercontent.com/assets/9119099/21740518/b8c713ea-d4dd-11e6-9c85-18e28a7132d6.png)
this happens when i execute the command "mvn test" from new language folder, 
![image](https://cloud.githubusercontent.com/assets/9119099/21740520/e386c9cc-d4dd-11e6-9328-a054ab2b1cbd.png)
I dont know what should be placed in target folder and what are the generated files . 
If anyone knows how to sort it out please suggest.
Thanks

**Comment by seblemaguer** [comment]
it seems that you don't have the permission to write in this the directory. Please check the permissions

**Comment by MomnaSaeed** [comment]
![image](https://cloud.githubusercontent.com/assets/9119099/21740589/ab062000-d4df-11e6-9347-0a64f8c2e210.png)
This is the permission status , can you please suggest what to change and how to ?

**Comment by seblemaguer** [comment]
you should not change from read to write but change the user owner of this directory using chown (man chown for the documentation).
I really suggest you take a linux/unix course (either online either in your university) because it is going to be compllicated for you to deal with the system

**Comment by MomnaSaeed** [comment]
Thank you for your suggestion , i changed the user and it worked.

**Comment by JuliusSweetland** [comment]
@MomnaSaeed did you ever get Urdu writing in Mary TTS? If you did I would love to get access to it? I have two users with muscular dystrophy who I would like to help. Thank you, Julius
