### ISSUE TITLE
Cannot execute target folder command 

### ISSUE THREAD

**Issue by MomnaSaeed** [marytts/marytts#669]
![image](https://cloud.githubusercontent.com/assets/9119099/21740607/61baad52-d4e0-11e6-82d7-b2fe6b806d7d.png)
 i have to execute this command
$ rm target .project .classpath
but there are these errors i get
![image](https://cloud.githubusercontent.com/assets/9119099/21740616/c8334ce2-d4e0-11e6-8958-b1115331721e.png)
i think there is some problem in the command that i am not getting it right , please suggest a solution becuase this folder is creating problems in building of new language.Thanks

**Comment by seblemaguer** [comment]
really take a linux course before. What you are pointing is basic user problem for linux that would be solved easily if you take a linux course (or search for google)

**Comment by MomnaSaeed** [comment]
Thanks.
