### ISSUE TITLE
Prosody model for new langauge

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#670]
Hi all,

I am trying to build a prosody model for New Zealand English, and this needs an overall idea of how prosody is implemented in Marytts. 

I have been studying the structure of prosody implemented in other languages like german and italian. I want to know if there is a framework already available in marytts to develop a prosody model (duration/intonation model). Or should we develop our own model for the language and try to make it to the marytts format?

And insights or links to more reading material as welcome.

Regards

Jesin

**Comment by seblemaguer** [comment]
you can use the CART trained by WAGON or the HMM trained using HTS (but only version 2.2 for now)

**Comment by jesinj** [comment]
Thanks for the reply.

Are you suggesting we do the modelling outside marytts, and later on implement it in mary? or is there code to do the modelling within marytts itself?
