### ISSUE TITLE
Exception in "$ wkdb_database_selector.sh wkdb.conf" command

### ISSUE THREAD

**Issue by MomnaSaeed** [marytts/marytts#672]
![image](https://cloud.githubusercontent.com/assets/9119099/21789201/10974ea0-d6f5-11e6-9cd6-f116e684b1e4.png)
There is an error in executing the above command while working on tts for urdu language, if anyone knows how to correct this please let me know,
thanks .

**Comment by seblemaguer** [comment]
this is part of the #674 issues so still based on the comment for the previous one, this is also affiliated to #652.
