### ISSUE TITLE
Select voices to use into java application

### ISSUE THREAD

**Issue by CatMonster** [marytts/marytts#673]
Is there a way to pick as input a jar voice and put into an already compiled java project?

**Comment by seblemaguer** [comment]
Hello,

can you mean be more precise ?

**Comment by CatMonster** [comment]
I'm writing a basic TTS launcher, from now i put all voices I need by adding them from maven in the pom.xml, then I use LocalMaryInterface to get all voices and read what i need to. Is there a way to specify to MaryInterface a list of voices downloaded from Marytts component installer?

**Comment by seblemaguer** [comment]
technically, you just need to put the jar in the classpath to be accessible on runtime. If this is a unit-selection voice, you also have to put the zip containing the data in the path indicated in the config file of this voice. You can have a look at the config file in the jar file.

**Comment by CatMonster** [comment]
so I can set a custom classpath and put in there all voices I need and use them, can't I?

**Comment by seblemaguer** [comment]
yes. But remember that the classpath is resolved first before actually Mary runs. This means you can't add any voice after that the system is started

**Comment by CatMonster** [comment]
ok, thank you very much for all your explanations

**Comment by CatMonster** [comment]
Hi, I tried to give all folder of marytts runtime package and seeing how maven put into the compiled jar but nothing works. Can anyone explain me which folders marytts need and their structure? Maven puts all marytts' dependencies in the jar but voices are not retrieved correctly, how can I fix that?
I'm using intellijIDEA and java 8.

**Comment by seblemaguer** [comment]
are you trying to use HMM or Unit Selection voice ? If they are HMM normally it should be fine. If it is Unit Selection, it is because you get the data also in a zip file format. You can have a look at this project to see how it is achieved for this part : https://github.com/marytts/marytts-installer

**Comment by CatMonster** [comment]
@seblemaguer all voices that I'm using are hsmm

**Comment by seblemaguer** [comment]
ok. Si what do you mean by "not retrieved correctly" ? If you have the jar, are you sure they are on your classpath while you are *running* the system ?

**Comment by psibre** [comment]
@CatMonster just a hunch, but in case you're trying to pack multiple voices (and/or marytts artifacts) into a "fat" jar, you need to be sure you're merging the service loaders correctly. Please see [here](/marytts/marytts-txt2wav/blob/dfc7d2dbf9eec7a0c12d98415eebe6e6e4df6df7/pom.xml#L63) or [here](/marytts/marytts-txt2wav/blob/e6961667167cb3175acdea6bfa98805967e74e83/build.gradle#L24) for example solutions for Maven and Gradle, respectively.
