### ISSUE TITLE
Tobi and POS accent priorities

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#675]
Hi,
Can anyone tell me how the tobipredparams_english.xml and POSAccentPriorities.en.properties are made for a specific language? Is it done by just analysing the database and rules for your language, or is there another method? I guess these files are required for prosody modelling.

**Comment by seblemaguer** [comment]
I think it is just a rule base class.

**Comment by jesinj** [comment]
Thankyou.

I shall look at it further.
