### ISSUE TITLE
Missing italian user dictionary

### ISSUE THREAD

**Issue by CatMonster** [marytts/marytts#678]
Why there's not italian user dictionary in marytts?
https://github.com/marytts/marytts/tree/master/src/main/dist/user-dictionaries

**Comment by seblemaguer** [comment]
Hello,

because nobody in the team is speaking italian and nobody beside the team proposed one.

**Comment by CatMonster** [comment]
Is there a possibility to create one? How does characters work in your dictionary?

**Comment by seblemaguer** [comment]
hello, yes it is. You can have a look at the other ones. The format is the same and I think the phone alphabet is close to the other languages

**Comment by CatMonster** [comment]
- What do you mean for "phone alphabet"?
