### ISSUE TITLE
Tagger folder for new language

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#679]
Hello,

Can anyone advice me on how to form the tagger folder for a new language in Marytts? 
The tagset can be decided based on the language, and I did find the maximum entropy binary models for some languages using OpenNLP, but how do we develop it for a new language?

Also, once the tagger folder is ready for the language, can you suggest which part of the voice building is using this component?

Regards

Jesin

**Comment by seblemaguer** [comment]
Hello,

are we talking about POS tagging or another kind of tagging ?

**Comment by jesinj** [comment]
Hi,

I mean the POS tagger.
In marytts-5.2/marytts-languages/marytts-lang-de/target/classes/marytts/language/xy/tagger,
there is a tagger folder with a model file in it. How is it created for a
language?


On 8/02/2017 6:10 PM, "Sébastien Le Maguer" <notifications@github.com>
wrote:

Hello,

are we talking about POS tagging or another kind of tagging ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/marytts/marytts/issues/679#issuecomment-278230840>, or mute
the thread

**Comment by psibre** [comment]
Following [Maven conventions](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), the code for `marytts/language/xy/tagger` on the classpath is versioned under `src/main/java/marytts/language/xy/tagger` and the resources are copied from `src/main/resources/marytts/language/xy/tagger`.
Note that Gradle allows us to easily *generate* or even *resolve* tagger resources using dependencies from external repositories and custom configurations and tasks.

**Comment by jesinj** [comment]
Thankyou.

I shall have a look at it.
