### ISSUE TITLE
Feature maker issue :Internal server error ,processing failed. no known way of generating output(PHONEMES) from input (RAWMARYXML)

### ISSUE THREAD

**Issue by MomnaSaeed** [marytts/marytts#681]
![16507740_1845604065683042_996700438_n](https://cloud.githubusercontent.com/assets/9119099/22682319/de37de02-ed33-11e6-91e4-1a6fab1f3b6f.png)
 getting this error in feature maker step while building module for urdu language.
Please suggest if someone knows the solution .
Thank you

**Comment by seblemaguer** [comment]
Hello,

your phonetisation module is not in the classpath

**Comment by MomnaSaeed** [comment]
Thanks , by  phonetisation module you mean allophones file ? I know how to add java class path but i don't know about adding the  phonetisation module , can please tell something about it ? 
Also,
[allophones.ur.txt](https://github.com/marytts/marytts/files/757121/allophones.ur.txt)
This is the allophones file i am using (in xml originally)
![image](https://cloud.githubusercontent.com/assets/9119099/22685398/fddcf112-ed41-11e6-8ef3-904e563e626b.png)

in the highlighted part 
xml:lang="en-US" should i use "ur-PK" as it is the locale for my Urdu language or should leave it as it is ?
Please suggest something 
Thank you very much

**Comment by seblemaguer** [comment]
Hello,

yes you should try to change the lang of the XML. Worst case scenario that is not solving the problem but the xml is consistent as it is not the case now

**Comment by MomnaSaeed** [comment]
Thanks.Alright i will repeat the initial steps after changing lang but still i didnt get what to do for adding classpath. Please help in it

**Comment by seblemaguer** [comment]
you don't have to do anything. In the first place I thought you forgot to put the phonetisation module in the classpath but after your comment I think that's the XML file which was the origin of the problem

**Comment by MomnaSaeed** [comment]
Great THANKS.Was just wondering in classpaths. 
 This is wkdb.conf , I want to know ,in xml:lang should it be ur_PK or just ur ?
![image](https://cloud.githubusercontent.com/assets/9119099/22727579/6a4c57e8-edfb-11e6-8864-c6b030dd0441.png)

**Comment by psibre** [comment]
Before you attempt to run the Feature Maker, please **test** your `marytts-lang-ur` component and verify that it works.
Like [the wiki](../wiki/New-Language-Support#5-run-feature-maker-with-the-minimal-nlp-components) says:
> To run the feature maker, you *must* have the new language components available in `marytts/target/marytts-<version>/` as described in the previous step. DO NOT TRY TO PROCEED before having achieved step 4.

**Comment by MomnaSaeed** [comment]
@seblemaguer
Please reply to above comment , there is a confusion that should the lang in allophones.xml be "ur" or "ur_PK" in the case of urdu language?
Thanks

**Comment by MomnaSaeed** [comment]
@psibre
Thanks
Everything builds finely .all the issue is in feature maker. For that i have figured a mistake , for now i want to know that what should be the lang of urdu language in allophones file as all the other languages have just wkdb locale which is ur in my case.?

**Comment by psibre** [comment]
So just go ahead and use "ur".

**Comment by MomnaSaeed** [comment]
@seblemaguer @psibre 
Hi, 
    Still I am on the same issue , i was doing it right and tested the marytts-lang-ur componenet as you suggested above , It works fine according to my understanding , i can see locale "ur" in the locale list ,also test request responds fine. Just getting the errors in next step as mentioned in https://github.com/marytts/marytts/issues/683 .Please suggest sometinhg to sort it out I am badly stuck on it.
Thanks

**Comment by MomnaSaeed** [comment]
I have checked my ur.config ,it seems fine but the error in #683 says "No such property: ur_PK.allophoneset", but the locale i am using is ur not ur_PK.
![image](https://cloud.githubusercontent.com/assets/9119099/22995118/53663dd2-f3eb-11e6-9b14-34addd72fba2.png)
What could be possibly causing this error ?

**Comment by psibre** [comment]
Changing the locale opens up many pitfalls. Check your `wkdb.conf`.

**Comment by MomnaSaeed** [comment]
![image](https://cloud.githubusercontent.com/assets/9119099/23015638/6b1736b0-f455-11e6-97c4-c0420ac337f7.png)

This is the generated wkdb.conf, i myself didnt changed any locale anywhere.

**Comment by psibre** [comment]
You generated that file when your locale was `ur_PK`, then you changed the locale to just `ur`, but if you don't update the `wkdb.conf` to match, the feature maker has no way of know that. Which is why you're still getting the error even though your `marytts-lang-ur` is functioning fine.

**Comment by MomnaSaeed** [comment]
![image](https://cloud.githubusercontent.com/assets/9119099/23032225/8fb7ff6e-f495-11e6-82aa-e6d3a729d12c.png)
According to this step i used the command like this 
$ marytts/target/marytts-builder-<VERSION>/bin/wkdb_setup.sh ./ ur ur_PK
as ur=wkdb locale:
ur_PK=mary locale:
This command has generated the wkdb.conf shown above ,
This is the allophones.ur.xml 
![image](https://cloud.githubusercontent.com/assets/9119099/23032992/3c41db68-f498-11e6-89d8-33673dbaa9f4.png)

[allophones.ur.txt](https://github.com/marytts/marytts/files/780986/allophones.ur.txt)
(in xml not txt)
here is used xml:lang="ur" .
 Can i know where exactly i did wrong?

**Comment by psibre** [comment]
You need to be consistent and use the same locale everywhere. `ur` and `ur_PK` are not identical, and if you use both, you will continue to have these errors.

**Comment by MomnaSaeed** [comment]
@psibre 
Alright , it means i should use this command 
$ marytts/target/marytts-builder-/bin/wkdb_setup.sh ./ ur ur  to generate the wkdb.conf  instead of the mentioned above and keep the wkdb locale and mary loacale same (ur)  ?
