### ISSUE TITLE
Speed up Audio generation

### ISSUE THREAD

**Issue by CarloBenussi** [marytts/marytts#682]
Hi,

I am using Mary as a local application (Italian Voice). After the initialization `LocalMaryInterface mary = new LocalMaryInterface();` , I send to the program a String (from a C++ app) to translate into audio, by the following commands:

```
                        try {
				audio = mary.generateAudio(inputText);
			} catch (SynthesisException e) {
				System.err.println("Synthesis failed: " + e.getMessage());
				System.exit(1);
			}

			double[] samples = MaryAudioUtils.getSamplesAsDoubleArray(audio);

			System.out.println("MaryTTS generated");

			try {
				MaryAudioUtils.writeWavFile(samples, FIFO_OUTPUT, audio.getFormat());
				System.out.println("Output written to " + FIFO_OUTPUT);
			} catch (IOException e) {
				System.err.println("Could not write to file: " + FIFO_OUTPUT + "\n" + e.getMessage());
				System.exit(1);
			}
```

However, I find the audio generation `(mary.generateAudio(inputText))` is sensitively slow. Is there a way to speed up this?

Thanks in advance

**Comment by seblemaguer** [comment]
Hello,

for now there is no solution to speed up this part. The next version will include a massive refactoring which will lead to a simplification of the source code. Therefore before the next version we won't profile the system. However, on the server side, you can see which part is taking most of the time on the log normally.

**Comment by CarloBenussi** [comment]
Hi,

Thanks for the answer. I am looking at the source code (especially Request.java) where the input is processed.  Is there a modification to the method to make the process of generating audio asynchronous, so that it can gives audio result while still processing the input? This would be a really nice feature.

Thanks in advance

**Comment by CatMonster** [comment]
@CarloBenussi I had the same problem with a copule lines of text. If you want to play the generated audio a simple way to speedup the generation is to split the text, in my case I do that when it find a full stop to create a better pronunciation, put all pieces into a queue and call a thread that get the queue and render piece by piece while is playing the first one etc.

**Comment by psibre** [comment]
@CarloBenussi have a look at [InproTK](http://inpro.tk/). @timobaumann made some modifications to MaryTTS to enable incremental synthesis; they were merged some time ago.

**Comment by CarloBenussi** [comment]
@CatMonster I thought also about splitting the text, but since my sentences are short, that is not feasible for me. I have currently enabled the cache usage as a temporary solution.

**Comment by CatMonster** [comment]
@CarloBenussi How do you have enabled the "cache usage"?

**Comment by CarloBenussi** [comment]
After I have downloaded the marytts-master, I modified the marybase.conf, in particular the lines:

```
# Cache synthesis results
# true | false
cache = false
cache.file = MARY_BASE/tmp/cache
cache.clearOnStart = false
```

to 
```
# Cache synthesis results
# true | false
cache = true
cache.file = MARY_BASE/tmp/cache
cache.clearOnStart = false
```

Then , after building the marytts-5.2 release (mvn install), while using Marytts (i use it locally with localMaryTTS class), a tmp folder will be created, which will contain a cache file that helps speeding up the synthesis after some phrases have already been synthesized. Since my sentences are limited, the cache will not grow too much.

**Comment by CatMonster** [comment]
@CarloBenussi thanks for your answer

**Comment by seblemaguer** [comment]
I think we won't get further than this so I close this issue for now
