### ISSUE TITLE
How to create a dictionary for an existing language

### ISSUE THREAD

**Issue by CatMonster** [marytts/marytts#686]
How can I create a dictionary for an existing language that has no dictionary like italian one?

**Comment by seblemaguer** [comment]
you create manually the userdict file following the conventions indicated in the files present in https://github.com/marytts/marytts/tree/master/src/main/dist/user-dictionaries : 

1. your file should be named userdict-it.txt
2. Inside your file, you should have the following syntax:
    - 1 line = 1 word
    -  you should follow structure for one line: <word> | <phonemes>

**Comment by CatMonster** [comment]
@seblemaguer what do you mean with "phonemes"? I'm not specialised in languages, but from some researches on google (https://www.google.it/search?q=phonemes+english&biw=1440&bih=715&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj6ivrKjpnSAhVHkRQKHT9MDsIQ_AUIBigB#tbm=isch&q=english+phonemes&imgrc=_) I don't think that english dictionaries and other dictionaries are following the equivalent language phonemes. What phonemes I need to use?

**Comment by seblemaguer** [comment]
the ones declared in https://github.com/marytts/marytts/blob/master/marytts-languages/marytts-lang-it/src/main/resources/marytts/language/it/lexicon/allophones.it.xml

**Comment by CatMonster** [comment]
@seblemaguer ok, thank you very much

**Comment by seblemaguer** [comment]
can I/you close this issue ?
