### ISSUE TITLE
Audio effects over server url?

### ISSUE THREAD

**Issue by JPM87** [marytts/marytts#687]
I am not able to find any documentation about the audio effect url parameter for the server. Is it possible to send the audio effects over the url? What url request is needed?

**Comment by psibre** [comment]
This info is in the built-in server documentation. You can click on the [Interactive documentation of the HTTP interface to MARY TTS](http://mary.dfki.de:59125/documentation.html) in the web interface.
For the audio effects, the parameters are documented under [audioeffects](http://mary.dfki.de:59125/audioeffects).

**Comment by JPM87** [comment]
I saw the section of the audioeffects but i do not understand how the url has to look like.
For example im using this url:
http://mary.dfki.de:59125/process?INPUT_TEXT=Hello+world&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&AUDIO=WAVE_FILE&LOCALE=en_US

What parameter needs to be added for the effects of if want to define the audio volume?

**Comment by psibre** [comment]
> You can click on the [Interactive documentation of the HTTP interface to MARY TTS](http://mary.dfki.de:59125/documentation.html) in the web interface.

From the section **Synthesis requests**:
> - `effect_(effectname)_selected` (optional) can be used to indicate whether the named effect should be applied (value is `on`) or not (value is `off`).
> - `effect_(effectname)_parameters` (optional) can be used to transport the parameters to use for the named effect.
