### ISSUE TITLE
5.2 De Translation Error

### ISSUE THREAD

**Issue by hoenickf** [marytts/marytts#691]
Hi, 

I tried to get the pronunciation of the German words "Art" and "ethisch", but its not working correctly. 
art,' ? a 6 t
ethisch,' ? t I S
1. There is an "e" missing at start of the phonetic transcription of "ethisch"
2. There are question marks within the result. 

I'm using marytts-lang-de v.5.2
```java
marytts.setOutputType("PHONEMES");
marytts.setLocale(Locale.forLanguageTag("de"));
Document a = marytts.generateXML("art ethisch");
```

**Comment by psibre** [comment]
The missing "e" is indeed a bug. Incidentally, I'm currently refactoring the lexicon build process, and (in lieu of fixing the syllabification problem, which gobbles the "e") adding "ethisch" to the lexicon patches this particular issue.

The "question marks" are [glottal stops](https://en.wikipedia.org/wiki/Glottal_stop), and correct.

**Comment by hoenickf** [comment]
@psibre thanks for your reply. Good to hear that you are already working on the problem.
In case its helping you:
I discovered that we have this problem with almost all words starting with 'e'.
Here is a list containing 4000 examples where the transcription failed. 
[de_missing_e.txt](https://github.com/marytts/marytts/files/791245/de_missing_e.txt)

**Comment by hoenickf** [comment]
Any Feedback regarding my comment?
(I just want to make sure that you actually had the chance to read it)
@psibre

**Comment by seblemaguer** [comment]
yes we have seen it :). For now @psibre is focusing on the refactoring. I don't know in which stage he is but we do not ignore your comment :). Thanks for the feedback

**Comment by hoenickf** [comment]
thanks :)
