### ISSUE TITLE
Fail on HMM Voice Trainer (HMMVoiceMakeVoice) -- Need to provide more description of exception

### ISSUE THREAD

**Issue by trangntt** [marytts/marytts#70]
Dear,

I have encountered an exception in HMMVoiceMakeVoice component. Could you please help me clarify that? Thanks a lot.
1. Some environment & technical information:
   - Mac OS X (10.7.4)
   - HTK-3.4.1
   - HTS-2.2_for_HTK-3.4.1
   - Language: Vietnamese (I have built a minimal NLP component for Vietnamese using MaryTTS). Locale: vi
2. Stack trace:
   Training voice: VNVoiceNew
   The following is general information about execution of training steps:

Step: Start preparing environments at Thu Aug  9 13:44:46 CEST 2012

Step: Start computing variance floors at Thu Aug  9 13:44:46 CEST 2012

Step: Start initialization & reestimation at Thu Aug  9 13:44:48 CEST 2012

Step: Start making a monophone mmf at Thu Aug  9 13:47:39 CEST 2012

Step: Start embedded reestimation (monophone) at Thu Aug  9 13:47:40 CEST 2012

Step: Start copying monophone mmf to fullcontext one at Thu Aug  9 13:54:30 CEST 2012

Step: Start embedded reestimation (fullcontext) at Thu Aug  9 13:54:42 CEST 2012

Step: Start tree-based context clustering at Thu Aug  9 13:56:19 CEST 2012
java.lang.Exception: The component HMMVoiceMakeVoice produced the following exception: 
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.lang.RuntimeException:  computation failed on file [/MaryTTS/VNVoiceNew/]!
Command line was: [/usr/bin/perl /MaryTTS/VNVoiceNew/hts/scripts/Training.pl /MaryTTS/VNVoiceNew/hts/scripts/Config.pm].
    at marytts.tools.voiceimport.HMMVoiceMakeVoice.launchProcWithLogFile(HMMVoiceMakeVoice.java:185)
    at marytts.tools.voiceimport.HMMVoiceMakeVoice.compute(HMMVoiceMakeVoice.java:124)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)

Added on 10th August: I can fix the above exception by modifying the number of questions from 001 to 1. But now, it raises another exception:

Training voice: VNVoiceNew
The following is general information about execution of training steps:

Step: Start preparing environments at Thu Aug  9 17:58:44 CEST 2012

Step: Start computing variance floors at Thu Aug  9 17:58:44 CEST 2012

Step: Start initialization & reestimation at Thu Aug  9 17:58:49 CEST 2012

Step: Start making a monophone mmf at Thu Aug  9 18:01:38 CEST 2012

Step: Start embedded reestimation (monophone) at Thu Aug  9 18:01:38 CEST 2012

Step: Start copying monophone mmf to fullcontext one at Thu Aug  9 18:08:30 CEST 2012

Step: Start embedded reestimation (fullcontext) at Thu Aug  9 18:08:41 CEST 2012

Step: Start tree-based context clustering at Thu Aug  9 18:10:17 CEST 2012

Step: Start embedded reestimation (clustered) at Thu Aug  9 18:30:08 CEST 2012

Step: Start untying the parameter sharing structure at Thu Aug  9 18:35:26 CEST 2012

Step: Start embedded reestimation (untied) at Thu Aug  9 18:35:32 CEST 2012

Step: Start tree-based context clustering at Thu Aug  9 18:36:37 CEST 2012

Step: Start embedded reestimation (re-clustered) at Thu Aug  9 18:55:11 CEST 2012

Step: Start forced alignment for no-silent GV at Thu Aug  9 18:59:55 CEST 2012

Step: Start making global variance at Thu Aug  9 19:05:54 CEST 2012

Step: Start making unseen models (GV) at Thu Aug  9 19:11:42 CEST 2012

Step: Start making unseen models (1mix) at Thu Aug  9 19:11:45 CEST 2012

Step: Start generating speech parameter sequences (1mix) at Thu Aug  9 19:11:49 CEST 2012

Step: Start synthesizing waveforms (1mix) at Thu Aug  9 19:13:09 CEST 2012
java.lang.Exception: The component HMMVoiceMakeVoice produced the following exception: 
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.lang.RuntimeException:  computation failed on file [/MaryTTS/VNVoiceNew/]!
Command line was: [/usr/bin/perl /MaryTTS/VNVoiceNew/hts/scripts/Training.pl /MaryTTS/VNVoiceNew/hts/scripts/Config.pm].
    at marytts.tools.voiceimport.HMMVoiceMakeVoice.launchProcWithLogFile(HMMVoiceMakeVoice.java:185)
    at marytts.tools.voiceimport.HMMVoiceMakeVoice.compute(HMMVoiceMakeVoice.java:124)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)

I think MaryTTS should provide the exact exception, not the general one like above. It is so difficult to find the reason. Thanks.

**Comment by jmabala** [comment]
[Hmmvoicemakevoice error.txt](https://github.com/marytts/marytts/files/7821494/Hmmvoicemakevoice.error.txt)
i am also experiencing such a problem, how can i go about it
