### ISSUE TITLE
Question about non hsmm voices

### ISSUE THREAD

**Issue by candelrg** [marytts/marytts#701]
Hello.
On jcenter (https://jcenter.bintray.com/de/dfki/mary/), I can see the hsmm voices, but not the other ones (described in marytts-components.xml).
Is it normal?
I would expect being able to depend on any available voice in a Java project using maven, but maybe there is a reason why it is not possible...

**Comment by psibre** [comment]
The unitselection voices require significant resources unpacked to the filesystem, and storing them on bintray would break our budget. So we're providing them through GitHub and our project website instead. Resolving and unpacking them is also not trivial -- e.g., have a look at the [custom logic used in the marytts-installer](https://github.com/marytts/marytts-installer/blob/master/build.gradle).

We've been developing a more elegant solution, but it involves significant upstream refactoring.

**Comment by candelrg** [comment]
OK, I understand. Thanks for the information.
