### ISSUE TITLE
Problem with cmu-rms-hsmm voice

### ISSUE THREAD

**Issue by vano468** [marytts/marytts#702]
Hello!
I use latest version of marytts and cmu-rms-hsmm voice and I have a problem with some simple words, ex: me, give, being. Instead of getting pronunciation, I receive a sound like bass-bit, but for complex words I get a very good pronunciation.

This problem can be reproduced on http://mary.dfki.de:59125 with `cmu-rms-hsmm en_US male hmm`.

How can I handle this problem?

**Comment by psibre** [comment]
It looks like this bug is triggered when the input is too short. You can work around it by adding more input, e.g., instead of "me", try "me, too", and if you really only want the "me", you can cut the output accordingly (based on the `REALISED_DURATIONS`).
