### ISSUE TITLE
Importing Bengali

### ISSUE THREAD

**Issue by imty1000** [marytts/marytts#705]
Dear Sir, I have been trying to import Bengali in marytts using corpus from http://www.iitm.ac.in/donlab/tts/index.php. how ever when ever i try using voiceimport.sh get several error. i followed https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial and using gradlew still getting a lot of missing errors such as missing allphone though allphone.txt is present.

Is there any step by step tutorial through which i can build the marytts for bengali?
It will be really helpful if anyone helps me.

**Comment by psibre** [comment]
For a new language, you need to obtain NLP components [as described here](../wiki/New-Language-Support) before you can build a voice. However, we now have an [incubating replacement for creating the lexicon resources](/marytts/gradle-marytts-lexicon-compiler-plugin). Having said that, you might take a look at the existing NLP resources for [Telugu](../tree/bf63d176abbc4f680556fe8dae0afaaa0a52d8c3/marytts-languages/marytts-lang-te) or [Hindi](/marytts/marytts-lang-hi), which may or may not help you bootstrap Bengali components.

Furthermore, there might well be one or more existing solutions created by other MaryTTS users in the past.

**Comment by imty1000** [comment]
Dear sir, thank you for reply. however, i have tried this process many times but failed to save files using transcription.sh where no mater how many words i convert it save only a few. last time i put around 12,000 words but all went in vain. Also i have my allphone.xml for Bengali. Than started working with voiceimport.sh. I know i am doing something wrong. Can anyone help me by showing the voice importing process using the voice from http://www.iitm.ac.in/donlab/tts/index.php as it has .wav and data.txt

**Comment by psibre** [comment]
As I said, there is no point trying to build a Bengali voice without Bengali NLP components.

I recommend that you focus on compiling a lexicon or building equivalent pronunciation prediction components, like for Telugu or Hindi. If you run into an error, please open specific issues that give details about the error, and how to reproduce it.
