### ISSUE TITLE
HMMVoiceCompiler fails

### ISSUE THREAD

**Issue by psmlbhor** [marytts/marytts#708]
I am trying to build my own voice. All the steps work perfectly fine except the final **HMMVoiceCompilerl**. I get the following output when I run it:
```
maven out> T E S T S
maven out>-------------------------------------------------------
maven out>Running marytts.voice.Neutral_voiceHsmm.LoadVoiceIT
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.783 sec <<< FAILURE! - in marytts.voice.Neutral_voiceHsmm.LoadVoiceIT
maven out>marytts.voice.Neutral_voiceHsmm.LoadVoiceIT  Time elapsed: 0.78 sec  <<< ERROR!
maven out>java.lang.Exception: Problem starting module Synthesis
maven out>	at marytts.voice.Neutral_voiceHsmm.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate voice 'neutral_voice-hsmm'
maven out>	at marytts.voice.Neutral_voiceHsmm.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate model 'duration' of type 'hmm' from 'null'
maven out>	at marytts.voice.Neutral_voiceHsmm.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>Caused by: java.lang.AssertionError
maven out>	at marytts.voice.Neutral_voiceHsmm.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>
maven err>Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
maven err>	at marytts.server.Mary.shutdown(Mary.java:371)
maven err>	at marytts.server.Mary$2.run(Mary.java:290)
maven out>
maven out>Results :
maven out>
maven out>Tests in error: 
maven out>  LoadVoiceIT.beforeClass:14 »  Problem starting module Synthesis
maven out>
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
maven out>
maven out>[INFO] 
maven out>[INFO] --- maven-failsafe-plugin:2.19.1:verify (verify) @ voice-neutral_voice-hsmm ---
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] BUILD FAILURE
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Total time: 8.920 s
maven out>[INFO] Finished at: 2017-03-04T13:30:01+05:30
maven out>[INFO] Final Memory: 31M/397M
maven out>[INFO] ------------------------------------------------------------------------
maven out>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (verify) on project voice-neutral_voice-hsmm: There are test failures.
maven out>[ERROR] 
maven out>[ERROR] Please refer to /home/pranjal/BE_PROJECT/FINAL_PROJECT_TRAIN/TRAINING/neutral_train/mary/voice-neutral_voice-hsmm/target/failsafe-reports for the individual test results.
maven out>[ERROR] -> [Help 1]
maven out>[ERROR] 
maven out>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
maven out>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
maven out>[ERROR] 
maven out>[ERROR] For more information about the errors and possible solutions, please read the following articles:
maven out>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
java.lang.Exception: The component HMMVoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:375)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:95)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```
It says the **Mary system is not running**. I have tried manually running the server, still it doesn't work. Before building my voice, I had build the voice of CMU (just for getting familiar with the entire process). CMU's voice builds without any error.
This same issue has been closed on 3 other threads. But the solution mentioned there doesn't work for me. What is the cause for this error and what is the solution?

**Comment by seblemaguer** [comment]
Something is wrong in your configuration file according to this part:

```
maven out>	at marytts.voice.Neutral_voiceHsmm.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate voice 'neutral_voice-hsmm'
maven out>	at marytts.voice.Neutral_voiceHsmm.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate model 'duration' of type 'hmm' from 'null'
```

check the duration model configuration in the voice config file

**Comment by psmlbhor** [comment]
This is my voice.config file

`#Auto-generated config file for voice neutral_voice-hsmm

name = neutral_voice-hsmm
locale = en-US


####################################################################
####################### Module settings  ###########################
####################################################################
# For keys ending in ".list", values will be appended across config files,
# so that .list keys can occur in several config files.
# For all other keys, values will be copied to the global config, so
# keys should be unique across config files.

hmm.voices.list = \
   neutral_voice-hsmm

# If this setting is not present, a default value of 0 is assumed.
voice.neutral_voice-hsmm.wants.to.be.default = 0

# Set your voice specifications
voice.neutral_voice-hsmm.gender = male
voice.neutral_voice-hsmm.locale = en-US
voice.neutral_voice-hsmm.domain = general
voice.neutral_voice-hsmm.samplingRate = 16000
voice.neutral_voice-hsmm.framePeriod = 80

# HMM Voice-specific parameters 
# parameters used during models training 
# MGC: stage=gamma=0 alpha=0.42 16KHz linear gain; alpha=0.55 48Khz log gain (default) 
# LSP: gamma>0  
#          LSP: gamma=1 alpha=0.0  linear gain/log gain 
#      Mel-LSP: gamma=1 alpha=0.42 log gain 
#      MGC-LSP: gamma=3 alpha=0.42 log gain 
voice.neutral_voice-hsmm.alpha = 0.42
voice.neutral_voice-hsmm.gamma = 0
#voice.neutral_voice-hsmm.logGain = 1
voice.neutral_voice-hsmm.logGain = true

# Parameter beta for postfiltering (parameter for tuning)
voice.neutral_voice-hsmm.beta = 0.1

# HMM Voice-specific files
# Information about trees
voice.neutral_voice-hsmm.Ftd = jar:/marytts/voice/Neutral_voiceHsmm/tree-dur.inf
voice.neutral_voice-hsmm.Ftf = jar:/marytts/voice/Neutral_voiceHsmm/tree-lf0.inf
voice.neutral_voice-hsmm.Ftm = jar:/marytts/voice/Neutral_voiceHsmm/tree-mgc.inf
voice.neutral_voice-hsmm.Fts = jar:/marytts/voice/Neutral_voiceHsmm/tree-str.inf

# Information about means and variances PDFs 
voice.neutral_voice-hsmm.Fmd = jar:/marytts/voice/Neutral_voiceHsmm/dur.pdf
voice.neutral_voice-hsmm.Fmf = jar:/marytts/voice/Neutral_voiceHsmm/lf0.pdf
voice.neutral_voice-hsmm.Fmm = jar:/marytts/voice/Neutral_voiceHsmm/mgc.pdf
voice.neutral_voice-hsmm.Fms = jar:/marytts/voice/Neutral_voiceHsmm/str.pdf

# Information about Global Mean and Variance PDFs
voice.neutral_voice-hsmm.useGV = true

# Variable for allowing context-dependent GV (without sil)
voice.neutral_voice-hsmm.useContextDependentGV = true

# GV method: gradient or derivative (default gradient)
voice.neutral_voice-hsmm.gvMethod = gradient

# Max number of GV iterations (parameters for tuning)
voice.neutral_voice-hsmm.maxMgcGvIter = 100
voice.neutral_voice-hsmm.maxLf0GvIter = 100
voice.neutral_voice-hsmm.maxStrGvIter = 100

# GV weights for each parameter: between 0.0-2.0
voice.neutral_voice-hsmm.gvWeightMgc = 1.0
voice.neutral_voice-hsmm.gvWeightLf0 = 1.0
voice.neutral_voice-hsmm.gvWeightStr = 1.0

# Mean and variance files for GV
voice.neutral_voice-hsmm.Fgvf = jar:/marytts/voice/Neutral_voiceHsmm/gv-lf0.pdf
voice.neutral_voice-hsmm.Fgvm = jar:/marytts/voice/Neutral_voiceHsmm/gv-mgc.pdf
voice.neutral_voice-hsmm.Fgvs = jar:/marytts/voice/Neutral_voiceHsmm/gv-str.pdf

# A context features file example for start-up testing.
voice.neutral_voice-hsmm.FeaFile = jar:/marytts/voice/Neutral_voiceHsmm/features_example.pfeats

# Tricky phones file in case there were problematic phones during training, empty otherwise.
voice.neutral_voice-hsmm.trickyPhonesFile = jar:/marytts/voice/Neutral_voiceHsmm/trickyPhones.txt

# Information about Mixed Excitation
voice.neutral_voice-hsmm.useMixExc = true

# Filters for mixed excitation 
# File format: one column with all the taps, where the number of taps per filter = numTaps/numFilters 
voice.neutral_voice-hsmm.Fif = jar:/marytts/voice/Neutral_voiceHsmm/mix_excitation_5filters_99taps_16Kz.txt
# Number of filters in bandpass bank
voice.neutral_voice-hsmm.in = 5

# Information about acousticModels (if true allows prosody modification specified in MARYXML input)
voice.neutral_voice-hsmm.useAcousticModels = true

# acoustic models to use (HMM models or carts from other voices can be specified)
#(uncoment to allow prosody modification specified in MARYXML input)
voice.neutral_voice-hsmm.acousticModels = duration F0

voice.neutral_voice-hsmm.duration.model = hmm
# voice.neutral_voice-hsmm.duration.data not used for hmm models
voice.neutral_voice-hsmm.duration.attribute = d

voice.neutral_voice-hsmm.F0.model = hmm
# voice.neutral_voice-hsmm.F0.data not used for hmm models
voice.neutral_voice-hsmm.F0.attribute = f0
`

I don't know exactly which setting you are talking about, but this seems to be the line
`voice.neutral_voice-hsmm.duration.model = hmm`
I checked it in the demo trained voice.config file and the setting is same.

**Comment by psibre** [comment]
There is a problem loading the resources. Please double-check that all of the resources listed in the config properties with `jar:*` values are really on the classpath.

**Comment by psmlbhor** [comment]
I checked them. All of the files listed in the config file are present in the path given. No file is missing

**Comment by seblemaguer** [comment]
can you share your jar ?

**Comment by psibre** [comment]
I would recommend debugging this in an IDE to figure out why the NPE happens.

**Comment by psmlbhor** [comment]
@seblemaguer By jar do you mean the trained voice .jar file?

**Comment by psmlbhor** [comment]
@psibre What do you by NPE?

**Comment by psibre** [comment]
@psmlbhor http://lmgtfy.com/?q=npe+java

**Comment by psmlbhor** [comment]
@psibre Ah! I am sorry. I will be trying to debug it in Eclipse then.
