### ISSUE TITLE
Bug - German Transcription

### ISSUE THREAD

**Issue by hoenickf** [marytts/marytts#709]
I discovered an issue with the transcription for DE.
'gneis' is transcirbed to "' s ? n g" which is wrong.

Result:
<t g2p_method="rules" ph="' s ? n g" pos="VVPP">gneis</t>

Explanation what a gneis is:
https://de.wikipedia.org/wiki/Gneis

**Comment by psibre** [comment]
Thanks for this report (and your other ones)!

This is an epic example of how the current syllabification implementation fails. =(

We'll get to this, but might not have time until next month.

**Comment by hoenickf** [comment]
Thanks for your response.
Just tell me when there is a way, I can support this project.
