### ISSUE TITLE
Properly package correct licenses for marytts, marytts-builder, and dependencies

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#71]
This can be mostly automated with various maven plugins.

**Comment by Munzey** [comment]
@psibre can we close this? Or should this be thrown in with the plan to have the en_GB module licensed separately and add a milestone?

**Comment by psibre** [comment]
I think we can move this to 6.x -- it's important to expose the licenses, but doing it with maven is probably a wasted effort in light of the pending shift to gradle.
