### ISSUE TITLE
Do not include log4j.properties in JARs

### ISSUE THREAD

**Issue by heruan** [marytts/marytts#711]
I noticed that every time I include MaryTTS as a dependency to my project, my logging setting screw up, so I've investigated and found out that `marytts-runtime-5.2.jar` contains a `log4j.properties` in `marytts.util` package and so does `jtok-core-1.9.3.jar`.

Including logging settings in JARs is a common mistake, since it eventually screw up someone's logs (see for example https://www.mkyong.com/maven/maven-exclude-log4j-properties-in-jar-file/).

**Comment by psibre** [comment]
Thanks for raising the issue. Just to clarify, when you say "screw up", are you talking about dependency conflicts, or unintended log level changes, or what?

We've been meaning to give the logging in MaryTTS a significant rewrite, but so far it's been low priority. In the meantime, we've been working around dependency conflicts, like in marytts/gradle-marytts-voicebuilding-plugin@52717ee43154cc307354a4911750957db0aaec17 -- i.e.

```diff
diff --git a/build.gradle b/build.gradle
index e8fea1d..b0d5b05 100644
--- a/build.gradle
+++ b/build.gradle
@@ -22,6 +22,7 @@ configurations.all {
     resolutionStrategy {
         dependencySubstitution {
             force 'org.codehaus.groovy:groovy-all:2.4.4'
+            substitute module('org.slf4j:slf4j-log4j12:1.6.1') with module('org.slf4j:log4j-over-slf4j:1.6.1')
         }
     }
 }
```

**Comment by heruan** [comment]
Thank you @psibre for the interest on this. When I say "screw up" I mean the logging settings of my environment (WildFly 10) are overridden by the `log4j.properties` found on the classpath. Since I need to use the container settings, I can't override them with another properties file, so for now I'm rebuilding the JARs without those files (but obviously I can't maintain this for long 😉 ).

**Comment by psibre** [comment]
Until we have a stable solution, you can try to work around the issue by filtering your dependencies via [Gradle](http://imperceptiblethoughts.com/shadow/#filtering_shadow_jar_contents) or [Maven](https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html) plugins to *exclude* the `marytts/util/log4j.properties` file.
