### ISSUE TITLE
upgrade logging framework

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#712]
The legacy logging framework (log4j v1.2.16) needs to be upgraded. It should be more flexible and avoid clashing with downstream projects (which could well be using different logging frameworks).
It's not unlikely that the best upgrade path would be to log4j v2.

This is expected to resolve related issues such as #255 and #711.

**Comment by heruan** [comment]
Any update on this?

**Comment by seblemaguer** [comment]
Hello,

the upgrade has been done for marytts 6.x (see branch https://github.com/marytts/marytts/tree/6.x) However, this 6.x doesn't integrate the backend yet. Do you have a specific need?

**Comment by heruan** [comment]
Thank you Sébastien for the update. I'm currently need the runtime embedded on my application, but if I include 5.2 the whole application logging properties gets reconfigured by some property files in it.

Do you have an ETA for 6.x embedded runtime?

**Comment by heruan** [comment]
Here I am again, a year later 🙂 I see there were a couple of pre-releases lately, the latest being [0.6.1-ALPHA2](https://github.com/marytts/marytts/releases/tag/v6.0.1-ALPHA2). Does this include the backend?

**Comment by psibre** [comment]
# master branch

For the moment, still unchanged:
```
$ ./gradlew dependencyInsight --configuration runtimeClasspath --dependency log4j

> Task :dependencyInsight
log4j:log4j:1.2.16
   variant "default+runtime" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-runtime
   ]

log4j:log4j:1.2.16
+--- project :marytts-common
|    +--- project :marytts-runtime
|    |    +--- runtimeClasspath
|    |    +--- project :marytts-languages:marytts-lang-de
|    |    |    \--- runtimeClasspath
|    |    +--- project :voice-cmu-slt-hsmm
|    |    |    \--- runtimeClasspath
|    |    +--- project :marytts-languages:marytts-lang-en
|    |    |    +--- runtimeClasspath
|    |    |    \--- project :voice-cmu-slt-hsmm (*)
|    |    +--- project :marytts-languages:marytts-lang-lb
|    |    |    \--- runtimeClasspath
|    |    +--- project :marytts-languages:marytts-lang-fr
|    |    |    +--- runtimeClasspath
|    |    |    \--- project :marytts-languages:marytts-lang-lb (*)
|    |    +--- project :marytts-languages:marytts-lang-it
|    |    |    \--- runtimeClasspath
|    |    +--- project :marytts-languages:marytts-lang-ru
|    |    |    \--- runtimeClasspath
|    |    +--- project :marytts-languages:marytts-lang-sv
|    |    |    \--- runtimeClasspath
|    |    +--- project :marytts-languages:marytts-lang-te
|    |    |    \--- runtimeClasspath
|    |    \--- project :marytts-languages:marytts-lang-tr
|    |         \--- runtimeClasspath
|    \--- project :marytts-signalproc
|         \--- project :marytts-runtime (*)
+--- de.dfki.lt.jtok:jtok-core:1.9.3
|    \--- project :marytts-runtime (*)
\--- org.slf4j:slf4j-log4j12:1.6.1
     \--- de.dfki.lt.jtok:jtok-core:1.9.3 (*)

org.slf4j:slf4j-log4j12:1.6.1
   variant "runtime" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-runtime
   ]

org.slf4j:slf4j-log4j12:1.6.1
\--- de.dfki.lt.jtok:jtok-core:1.9.3
     \--- project :marytts-runtime
          +--- runtimeClasspath
          +--- project :marytts-languages:marytts-lang-de
          |    \--- runtimeClasspath
          +--- project :voice-cmu-slt-hsmm
          |    \--- runtimeClasspath
          +--- project :marytts-languages:marytts-lang-en
          |    +--- runtimeClasspath
          |    \--- project :voice-cmu-slt-hsmm (*)
          +--- project :marytts-languages:marytts-lang-lb
          |    \--- runtimeClasspath
          +--- project :marytts-languages:marytts-lang-fr
          |    +--- runtimeClasspath
          |    \--- project :marytts-languages:marytts-lang-lb (*)
          +--- project :marytts-languages:marytts-lang-it
          |    \--- runtimeClasspath
          +--- project :marytts-languages:marytts-lang-ru
          |    \--- runtimeClasspath
          +--- project :marytts-languages:marytts-lang-sv
          |    \--- runtimeClasspath
          +--- project :marytts-languages:marytts-lang-te
          |    \--- runtimeClasspath
          \--- project :marytts-languages:marytts-lang-tr
               \--- runtimeClasspath

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

# 6.x branch

It's a little different for the incubating branch:
```
$ ./gradlew marytts-common:dependencyInsight --configuration runtimeClasspath --dependency log4j

> Task :marytts-common:dependencyInsight 
log4j:log4j:1.2.16
+--- de.dfki.lt.jtok:jtok-core:2.1.18
|    \--- runtimeClasspath
\--- org.slf4j:slf4j-log4j12:1.6.1
     \--- de.dfki.lt.jtok:jtok-core:2.1.18 (*)

org.apache.logging.log4j:log4j-api:2.9.1
\--- org.apache.logging.log4j:log4j-core:2.9.1
     +--- runtimeClasspath
     \--- project :marytts-utils
          \--- runtimeClasspath

org.apache.logging.log4j:log4j-core:2.9.1
+--- runtimeClasspath
\--- project :marytts-utils
     \--- runtimeClasspath

org.slf4j:slf4j-log4j12:1.6.1
\--- de.dfki.lt.jtok:jtok-core:2.1.18
     \--- runtimeClasspath

(*) - dependencies omitted (listed previously)


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

You can resolve this from OJO:
https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/de/dfki/mary/marytts-common/6.0.1-SNAPSHOT

**Comment by heruan** [comment]
Thank you, I'll try to use the SNAPSHOT from OJO. Are there also ALPHAs? So that I can stick with a specific tag!

**Comment by psibre** [comment]
Good point. Alpha release here:
https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/General/oss-release-local/de/dfki/mary/marytts-common/6.0.1-ALPHA2

**Comment by heruan** [comment]
Thank you @psibre, I was finally able to push the get the new JARs 🙂

How do you suggest to approach 6.x at alpha stage? I see there is no more `MaryInterface` in the classpath, which was my starting point to embed MaryTTS in another Java project.

Is there any stub documentation/examples for 6.x yet?

**Comment by psibre** [comment]
@seblemaguer will be able to answer that (but it might be a few days)

**Comment by seblemaguer** [comment]
@heruan I am currently finishing some urgent things. I come back to you when I have some time

**Comment by seblemaguer** [comment]
Hello,

before any explanation, a couple of warnings: the 6.x is in alpha stage => so there are some bugs and some things are subject to change (even though, the main part should not). Also I am currently working on integrating support for HTS engine and world to the system, that take some times and I have also other priorities which explain the delay?

Having said that, the way mary 6.X is approaching the embedding is a little bit different. From now on, it will be a mary thread "Server" in a another client thread as a "Client". 

The client send a query to the server which contains 2 main informations: the input and the configuration. The input is supposed to be any kind of object but only textual input has been tested. the configuration is a MaryConfiguration object. I suggest to use a JSON and load it using a JSONMaryConfigLoader object which is more permissive than the property one.

I will make a minimal example available and update the issue before the end of next week with it.

**Comment by heruan** [comment]
Thank you very much @seblemaguer! My environment is a Spring Boot 2.1 microservice which acts as SIP client and should use an embedded Mary server. So, an example on how to create an audio stream from text in 6.X would be greatly appreciated!

**Comment by seblemaguer** [comment]
I started to put the example here (it doesn't reach the audio part yet and it is not functional outside of my computer): https://github.com/seblemaguer/minimal_marytts_example

I still have to finish some things to reach the audio but at least you have logic (mainly in this file: https://github.com/seblemaguer/minimal_marytts_example/blob/master/buildSrc/src/main/java/marytts/Synthesize.java )

**Comment by heruan** [comment]
Thank you @seblemaguer, this is starting to shed some light 🙂 I look forward for the audio part and next Mary releases!
