### ISSUE TITLE
HMMVoiceDataPreparation don't find paths for program

### ISSUE THREAD

**Issue by MenshovSergey** [marytts/marytts#713]
I try add new voice using tutorial https://github.com/marytts/marytts/wiki/HMMVoiceCreation and i get
*Missing path for awk 
*Missing path for perl 
*Missing path for bc 
*Missing path for tclsh 
*Missing path for sox 
*Missing path for hts/htk 
*Missing path for hts_engine 
*Missing path for sptk 
*Missing path for ehmm
on step 4.1
Where he get paths for program? 
What are true path?

**Comment by psibre** [comment]
Most of these can be installed via your package manager of choice. Which linux distribution are you using?

**Comment by MenshovSergey** [comment]
14.04

**Comment by psibre** [comment]
So... Ubuntu apparently.
You'll need to install the missing packages `awk`, `perl`, `bc`, `tcl`, and `sox`.
You need to obtain the HTK sources, patch them with HTS, and install it from source, just like hts_engine, sptk, and ehmm. The ehmm sources are inside the MaryTTS sources, under `/lib/external/ehmm`.
Make sure you use the correct version of all of the above -- see the wiki for details.
