### ISSUE TITLE
Training LTS rules with transcription.sh fails

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#714]
Hi folks,

I tried to train LTS rules until I came across this error:

```
....
Training decision tree for: c
java.lang.IllegalArgumentException: Value not defined for given nominal attribute!
at weka.core.AbstractInstance.setValue(AbstractInstance.java:470)
```

I also checked for allophones that are not in my allophone file. Nothing wrong there.

Where can I start to debug which line in my lexicon causes this?

Thanks a lot!

**Comment by psibre** [comment]
Have a look at how we now do it in [marytts/marytts-lexicon-de](/marytts/marytts-lexicon-de). It's very experimental at this point, but the old code has not been maintained for years, and when we need to fix bugs, we'll do it in [marytts/gradle-marytts-lexicon-compiler-plugin](/marytts/gradle-marytts-lexicon-compiler-plugin).

**Comment by entenbein** [comment]
One entry consisted of two words... :man_facepalming: 

For anyone searching for this kind of error: check your dictionary for blanks on the _left side_.

**Comment by psibre** [comment]
@entenbein Could you give further details of what exactly triggered the error? It would help us to add tests to guard against input parsing errors such as this.

**Comment by entenbein** [comment]
Sure,

one entry in LTS training/input file/lexicon looked like that:

_two words | t w o w o r d s_

**Comment by psibre** [comment]
@entenbein Thanks, we'll see how to handle that more gracefully.
