### ISSUE TITLE
 Cannot instantiate object from 'marytts.language.lb.LuxembourgishPreprocess': marytts.language.lb.LuxembourgishPreprocess

### ISSUE THREAD

**Issue by Gonzalliz** [marytts/marytts#718]
I tried to run mary TTS in eclipse following the steps as in https://github.com/marytts/marytts/wiki/Eclipse_6.X
But when I try to run I get this error. What I'm missing here.
![image](https://cloud.githubusercontent.com/assets/10574113/24238052/ea131daa-0fce-11e7-9f96-f2c9bc85c160.png)

**Comment by psibre** [comment]
Are you trying to develop on MaryTTS 5.2 or 6.0-SNAPSHOT?

**Comment by Gonzalliz** [comment]
6.0-SNAPSHOT

**Comment by psibre** [comment]
I cannot reproduce this at my end. You can try applying the [Gradle Eclipse plugin](https://docs.gradle.org/current/userguide/eclipse_plugin.html) and then open the generated project in Eclipse.

I know that this error does not appear if I run MaryTTS from the command line, or inside IntelliJ IDEA. Personally, I've found no happiness in developing Gradle-based projects in Eclipse. You may be better off with a different IDE.

**Comment by Gonzalliz** [comment]
Yes I was able to the server using ./gradlew run. Then I can access using the ip.
But what I want is access the TTS methods using terminal commands. Can I do that?
For an example ( >tts <text input> <outputaudiofilename> ).
Is there any guide on that?

**Comment by seblemaguer** [comment]
that is a different problem to what you are suggesting in a first place. If you just want to use a command line, you can see the examples from https://github.com/marytts/marytts-txt2wav

**Comment by sandrock** [comment]
Hello. I am trying to run a fresh new install of MaryTTS 5.2 and I have a similar error when I run `marytts-server.bat`.

I cannot find a resolution while reading your comments. Can someone explain what is going on here? 

I am using OpenJDK 16.0.1.

```
Exception in thread main
Cannot instantiate object from '...LuxembourgishPreprocess': 
  No signature of method marytts.language.lb.LuxembourgishPreprocess.getClass() is applicable for argument types: () values: []
Possible solutions: metaClass(groovy.lang.Closure), getState(), [...]
  at marytts.util.MaryRuntimeUtils.instantiateObject(MaryRuntimeUtils.java:130)
Caused by: groovy.lang.MissingMethodException: No signature of method marytts...LuxembourgishPreprocess.getClass() is applicable for argument types: () values: []
  at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap()
  at ...
  at marytts...LuxembourgishPreprocess.<init>(LuxembourgishPreprocess.groovy:39)
```

**Comment by Quad-Plex** [comment]
I'm building a simple TTS Java Application on MaryTTS, and while trying to expand the available languages, I ran into the same issue.

build.gradle:
```
dependencies {
        implementation group: 'de.dfki.mary', name: 'voice-cmu-slt-hsmm', version: '5.2.1', {
        exclude group: 'com.twmacinta', module: 'fast-md5'
        exclude group: 'gov.nist.math', module: 'Jampack'
        }
        
        [...]
        
        implementation group: 'de.dfki.mary', name: 'marytts-lang-lb', version: '5.2.1', {
        exclude group: 'com.twmacinta', module: 'fast-md5'
        exclude group: 'gov.nist.math', module: 'Jampack'
        }
    }
```

The error I am seeing upon initializing my Application:

```
Caused by: marytts.exceptions.MaryConfigurationException: Cannot start MARY server
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate object from 'marytts.language.lb.LuxembourgishPreprocess': No signature of method: marytts.language.lb.LuxembourgishPreprocess.getClass() is applicable for argument types: () values: []
Caused by: groovy.lang.MissingMethodException: No signature of method: marytts.language.lb.LuxembourgishPreprocess.getClass() is applicable for argument types: () values: []
Execution failed for task ':Main.main()'.
```
