### ISSUE TITLE
Can we change voice quality (say from male to female)

### ISSUE THREAD

**Issue by MaheshVelankar** [marytts/marytts#719]
I am still new to TTS
I have read somewhere that HMM / HTS voices can be changed (like they can be averaged etc..)

Is it possible to change a voice from male to female ... or young to old?
(It seems such thing is possible in eSpeak software.)

If it is possible what are the steps involved?

Please let me know.
Thanks

**Comment by psibre** [comment]
> I have read somewhere that HMM / HTS voices can be changed (like they can be averaged etc..)
> 
> Is it possible to change a voice from male to female ... or young to old?

It's possible to use *voice adaptation* techniques to change perceived speaker gender or age, but that's not something you can do with MaryTTS.

> (It seems such thing is possible in eSpeak software.)

eSpeak uses *formant* synthesis. Which means the signal is always generated "from scratch", and if you know which knobs to fiddle with, you can make it sound like anything you like. The catch... is that you have to know which knobs to fiddle with.

**Comment by kaiserjp** [comment]
@MaheshVelankar  have you solved the voice transformation you asked for? I'm trying to do more or less the same with an Arabic voice and I have some problems to apply effects to achieve that.
