### ISSUE TITLE
Adding languages to an new LocalMaryInterface implementation 

### ISSUE THREAD

**Issue by kaiserjp** [marytts/marytts#721]
I'm trying to do an stand-alone application that be able to synthesize into several languages. I created a new one program from scratch importing by Gradle the voice-cmu-slt-hsmm. But, I don't know how I can import some other voices. (I'm just discovering Gradle...)
I tried to import the marytts-lang-XX project and their .jar through Gradle 'build.gradle', but I have had difficulties I can't solve with the default parameters of the project ":marytts-runtime".
I have been finding in the wiki, but I don't found any entry related with this issue.
If someone can help me in some way I will be grateful.

**Comment by psibre** [comment]
Please have a look at the **gradle** branch of our [sample application](/marytts/marytts-txt2wav).
Each voice dependency has a transitive dependency on the corresponding language component. If you just depend on voices from different languages, you can use them all.

**Comment by kaiserjp** [comment]
Hi, 
I'm working on the stand-alone package and I have not much clear the difference between the voice and the language component (or lang package). I means, in example, the marytts-language-de package is the language support for German voices (bits3-hsmm and bits1-hsmm). But the voices itself are inside the package? and how could I call them (incorporate or import) into the marytts-text2wave code? and finally, do you know some documentation, about voices, other than the original from the marytts-wiki?
Many thanks!!

**Comment by psibre** [comment]
Each component is packaged as a separate jar artifact, and you control what is loaded by adding/removing them to/from the classpath. For applications this would mean adding them as dependencies, taking extra care to properly merge the service loaders.
