### ISSUE TITLE
Question about incremental voice development

### ISSUE THREAD

**Issue by MaheshVelankar** [marytts/marytts#723]
(Please point me to any information if it is already available and excuse me for that.)

Suppose I have a speaker and I record say 10000 lines spoken by him, create text files.......etc etc.......and use mary TTS to successfully create a new voice in a new language.

After say 3-4 months I get hold of the same speaker and record say another 1000 lines .... then do I need to rerun all 11000 lines together to create the voice once again, or can I "incrementally" improve on my old voice by adding these new 1000 lines?

Or in other words, can I go on building the voice in steps of say 1000 lines .... by incrementally improving it?

Thanks in advance.

**Comment by psibre** [comment]
Currently, both the unit-selection and HSMM based voices create resources which need to be built from all of the available data at once. If you change the data, you need to rebuild from scratch.

We are planning to migrate more of the tasks over to first-class Gradle tasks for performance and efficiency (currently, many of the tasks merely wrap the legacy VoiceImportTools). Incidentally, this migration to Gradle will allow us to leverage Gradle's incremental build capabilities. But even this would only streamline the data processing parts of the voicebuilding process, and not the model training or timeline compilation, which needs to be performed with all data at once.

**Comment by MaheshVelankar** [comment]
Thanks psibre, for the detailed explanation.

So can you please tell me what is the "Absolute minimum" data size (number of lines ... or words or time duration) that I should look for in order to start the MaryTTS work and get self-confidence that I can run all the required pieces of work to completion without error. 

I am thinking of starting with such minimum as a pilot project, and once I get that experience I shall start looking for actual ... complete data.

Please let me know this.
Thanks in advance.

**Comment by psibre** [comment]
The "minimum" amount of data is determined by the application domain, and the synthesis technique (unit-selection or HMM). I would recommend you take a look at our various voice repositories to get a feeling for how the voicebuilding works.
