### ISSUE TITLE
Predicted parameters for synthesised speech

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#724]
Hi,

I wanted to know if there is a way to know the predicted parameters for the synthesised speech in MaryTTS?
For eg: for a particular sentence what are the POS tags assigned, what are the prosody labels assigned, the breaks and accents assigned etc, is there a log that can provide such details?

Jesin

**Comment by seblemaguer** [comment]
do you mean the ACOUSTPARAMS output type ?

**Comment by jesinj** [comment]
yes, the acoustic parameters of a single synthesised sentence
