### ISSUE TITLE
When creating JAR  it says Can not start MARY server. ???

### ISSUE THREAD

**Issue by muddy-28** [marytts/marytts#725]
**My Envoirnment**
Eclipse Neon 
JDK  1.8.0_25
JRE   1.8.0.121

when using **local  MARY interface** it works using eclipse, and when exporting into JAR using following settings
![image](https://cloud.githubusercontent.com/assets/7922958/24691559/9924314e-19ed-11e7-94c0-8ada69cfd31e.png)

its says

error phrase 
**Can not start MARY  server** 
Although JAR includes extracted voices and all dependencies folder here is error screenshort.
![image](https://cloud.githubusercontent.com/assets/7922958/24692088/b669bbea-19f0-11e7-9b89-0443afa70a66.png)

**Comment by psibre** [comment]
Looks like a service loader issue. See #690 and our [demo application](/marytts/marytts-txt2wav) for solutions.
