### ISSUE TITLE
Add new words to an already build language e.g en_US

### ISSUE THREAD

**Issue by TahreemSaleem** [marytts/marytts#726]
Hey! I was wondering is there any way to add new words and pronunciation via transcription tool or anything to English language ,en_US? 
Basically I want to build a Urdu language, with English script. Hence i want to add some Urdu words in already built English language in marytts.

**Comment by psibre** [comment]
You can try the experimental [Lexicon compiler](/marytts/gradle-marytts-lexicon-compiler-plugin).
Have a look at the various lexicon repositories under [marytts](/marytts) to see how it can be used.
