### ISSUE TITLE
NZE language and new voice

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#727]
Hi,

We have developed some voices in New Zealand English and made the NZE locale better. And also implemented the WebMAUS labeller (https://clarin.phonetik.uni-muenchen.de/BASWebServices/), such that it can be used for any language that has a MAUS service available. Can you advice on how it can be added to the existing marytts as a pull request?

**Comment by psibre** [comment]
Thanks for the offer -- a working WebMAUS REST component for MaryTTS could be very useful to many people! Unfortunately, I don't see your code for this, so we need to take a step back first.

I see that you have one proper fork (your "marytts-1" repo), and another marytts repository that has all history removed -- only a single commit. For various reasons, this is considered bad, and I would recommend that you delete it, and rename your actual fork to "marytts".

You can only create a pull request from the actual fork. You can synchronize your fork with the current upstream branches by pulling from marytts/marytts ("upstream") and pushing to your fork (the "origin").

Please peruse the copious documentation, such as the [GitHub Flow writeup](https://guides.github.com/introduction/flow/) if you need to familiarize yourself further with the requisite concepts.
