### ISSUE TITLE
Content missing in output

### ISSUE THREAD

**Issue by garwiz** [marytts/marytts#732]
Hi,

if I enter the following text, the "1" is missing in output. It doesn't happen If I remove the leading ")".

> ) missing 1 number with closing paranthesis before

Regards!

**Comment by psibre** [comment]
Looks like an issue with the text preprocess module... The tokeniser preserves the digit, but it does not get a `ph` attribute if the closing parenthesis is there, which triggers an empty sentence...

**PHONEMES**
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<t pos=".">
)
</t>
<t g2p_method="lexicon" ph="' m I - s I N" pos="VBG">
missing
</t>
<t pos="CD">
1
</t>
<t g2p_method="lexicon" ph="' n V m - b r=" pos="NN">
number
</t>
<t g2p_method="lexicon" ph="' w I D" pos="IN">
with
</t>
<t g2p_method="lexicon" ph="' k l @U - z I N" pos="NN">
closing
</t>
<t g2p_method="rules" ph="' p E - r { n - T @ - s I s" pos="NN">
paranthesis
</t>
<t g2p_method="lexicon" ph="b I - ' f O r" pos="IN">
before
</t>
</s>
</p>
</maryxml>
```

**Comment by psibre** [comment]
Apparently the previous `)` is interpreted as a *currency*, and the bug is that for an unknown currency, [the digit is not expanded](../blob/c15be51c0c4cd4f77d5c918db15be90994524006/marytts-languages/marytts-lang-en/src/main/java/marytts/language/en/Preprocess.java#L290-L292).
