### ISSUE TITLE
HMMVoiceMakeVoice stuck

### ISSUE THREAD

**Issue by DataWorm** [marytts/marytts#738]
Hello,
 
I just tried to create a ‚new‘ voice with the cmu arctic sound files. I almost succeeded with the whole processing pipeline but in HMMVoiceMakeVoice it seems stuck (no progress visible in logs for hours and even days) in the following task:
`Start making a monophone mmf at Mon  1 May 02:26:23 CEST 2017`

I also tried to ran that MakeVoice step manually with the command `perl scripts/Training.pl scripts/Config.pm`. The last lines I got are the following, afterwards nothing further happens:
// load variance flooring macro
FV: loading variance floor(s) from file /home/pi/voices/cmu_arctic2/hts/models/qst001/ver1/cmp/vFloors
loading vector varFloor1
loading vector varFloor2
loading vector varFloor3
loading vector varFloor4
loading vector varFloor5

[hts.txt](https://github.com/marytts/marytts/files/968632/hts.txt)

I prepared a raspberry pi 3 with raspbian as platform to build voices. I built and used marytts from github and tried with tag versions v5.2 and v5.2-beta3, rebuild everything with maven, tried to reinstall the external dependencies... 

Any idea why it seems to be stuck at that point?! From other logs posted it looked like this step should be done within a second but not hours and days (even if raspberry might be a bit slower). So far I have no idea how to continue to resolve this issue apart from retrying everything on another machine.

I also just took a look at the running tasks. When the process just reached the mentioned point there is still a process (HHEd) running and working on high cpu load. But I can't believe that this step takes days without giving any further feedback.

Thx in advance for any further suggestions!

**Comment by psibre** [comment]
I'm not sure why you would want to run heavy compute jobs on an Rpi. The HTS scripts used by the legacy MaryTTS voicebuilding tools are single-threaded, so you're looking at something that takes around a day on modern hardware, and running it on a 1.2 GHz CPU with limited RAM.

Having said that, I have no experience with voicebuilding on ARM -- it might work, or it might not.

**Comment by DataWorm** [comment]
The reason is simple: 
- I don't have to test/install too much stuff on my servers (never change a running system)
- I don't have to setup a new big computer and can quickly change sd-card when I don't need it
- since I don't have to compile voices very often, I can accept when voicebuilding takes a bit longer

However I retried it now on another system and it seems to work so either I somehow misconfigured something on my raspbian or it really doesn't work on that platform for some reason. But could be nice to also support such kind of platforms.

**Comment by psibre** [comment]
OK, glad to hear you solved the issue.

Regarding the runtime dependencies, that's why we prepared a [docker image for exactly this](/marytts/marytts-dockerfiles/tree/master/marytts-builder-hsmm). Then you can run the legacy HTS voicebuilding in a container, see [here](http://www.coli.uni-saarland.de/~steiner/teaching/2016/winter/voicebuilding/slides/index.html#/hts-voicebuilding-with-docker) for details.
