### ISSUE TITLE
New Snapshot release?

### ISSUE THREAD

**Issue by fhennig** [marytts/marytts#739]
Hey, 

when will there be a new 6.0-SNAPSHOT?

I rely on the fix which was merged in pull-request #677 and I want to know when I can expect it to be upstream.

**Comment by psibre** [comment]
Nothing prevents you from installing and using artifacts you build yourself.

If that doesn't work for you, you can resolve snapshots from OJO -- there's one for marytts-lang-de that was deployed a few days after your PR that should have the fix:

https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/de/dfki/mary/marytts-lang-de/6.0-SNAPSHOT/marytts-lang-de-6.0-20170220.100206-2.jar

**Comment by fhennig** [comment]
I do have a local working copy, it is just complicated to share with others on my team.

Thanks for that link! Though it looks like the change I need is not included.

I'll figure something out!

**Comment by psibre** [comment]
> Thanks for that link! Though it looks like the change I need is not included.

Sorry, fixed that:

https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/de/dfki/mary/marytts-lang-de/6.0-SNAPSHOT/marytts-lang-de-6.0-20170502.103418-3.jar

**Comment by fhennig** [comment]
Thanks!
