### ISSUE TITLE
Can't run marytts from eclipse neon 

### ISSUE THREAD

**Issue by Muhammad7Salah** [marytts/marytts#743]
Steps for installing marrytts:
Right click on marytts-builder -> run as -> run configurations
Maven Build -> new
Name it as marytts
workspace -> marytts
write in Goals install
check skip test box
then press ok
can find the log in this link  https://pastebin.com/7qibXgF9

Errors:
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :marytts-assembly-builder

Steps for solving this error :
Type this command in your command prompt window 
.\gradlew run

**Comment by psibre** [comment]
Is this about v6.0-SNAPSHOT or v5.2?

**Comment by Muhammad7Salah** [comment]
@psibre it is about v6.0-SNAPSHOT

**Comment by psibre** [comment]
Please use Gradle, not Maven. See the readme and #730.

**Comment by Muhammad7Salah** [comment]
@psibre ok thanks for yyour help
