### ISSUE TITLE
marytts en-gb cmu dictionary

### ISSUE THREAD

**Issue by Aani27** [marytts/marytts#745]
Hello everyone, 

I am new to marytts, thus came across an issue. I am following the following link for new language support.
https://github.com/marytts/marytts/wiki/New-Language-Support
in the transciption step to my knowledge i require two files: cmu dictionary and allophone. Allophone is built it so i found the file in /local/mary/marytts/marytts-languages/marytts-lang-en/lib/modules/en/gb/lexicon/allophones.en_GB. but somehow i am not able to find a CMU dictionary that follows those allophones. The language i am trying to built is en_GB

**Comment by psibre** [comment]
Please have a look at the [British English lexicon we built from OALD](https://github.com/marytts/marytts-lexicon-en_GB-oald).

**Comment by Aani27** [comment]
Thanku for your reply but i already have a built in allophone file with xml extension all i need is a dictionary/lexicon that follows those allophones OR
allophone and a lexicon that follows each other in en_GB

**Comment by psibre** [comment]
An "allophone file with xml extension" is not a lexicon, but a definition of the set of symbols mapped to speech sound classes and their phonetic features.
I repeat, please look at the existing `en_GB` lexicon we already provide to understand what you need.

**Comment by Aani27** [comment]
![image](https://cloud.githubusercontent.com/assets/28556606/25842852/e21879be-34be-11e7-98c5-78a5742c9030.png)
 thankyou for your patience and correction. Like in this image there is a .txt file for french that contain words and phenomes and an allophone file that as you corrected set of symbols mapped to speech. So i have this set of symbols but nothing to map it on. i downloaded few  cmu dictionaries but when i load them with the built in transcription tool in marytts transcription is red that is because to my understanding is mismatch between transcription and set of symbols. 
I will appreciate if you could help me with patience 

![image](https://cloud.githubusercontent.com/assets/28556606/25843539/1425f010-34c1-11e7-9feb-e6da863e67ea.png)

**Comment by psibre** [comment]
I'm afraid the Transcription Tool GUI has been unmaintained for years. Once again, please refer to the [marytts-lexicon-en_GB-oald](/marytts/marytts-lexicon-en_GB-oald) project to see how things currently work.
Specifically, you need to understand the concepts of phoneme or allophone set and the transcription format/notation in the lexicon.

You keep referring to "cmu dictionaries", but I'm not sure what you mean.
