### ISSUE TITLE
help me Alignment

### ISSUE THREAD

**Issue by baaslaawe** [marytts/marytts#749]
hello,

can help me   any open source that can help me to do Automated **Audio Segmentation Using Forced Alignment and  HTK** , because i got around 20 hours audiobook in my language   however for me it's not easy  to make by manually  transcript and audio so please help me .

thank you

**Comment by seblemaguer** [comment]
Hello,

what is the problem exactly as I don't manage to understand the blocking part

**Comment by baaslaawe** [comment]
thank you

my problem is if i want to build marytts is requirement enough data,  i got around 20 hours audiobook so for me it's not easy to do 20 hours make like this example =
( arctic_a0001 "AUTHOR OF THE DANGER TRAIL, PHILIP STEELS, ETC" )
( arctic_a0002 "Not at this particular case, Tom, apologized Whittemore." )


thank you
