### ISSUE TITLE
Error in transcribing words

### ISSUE THREAD

**Issue by Aani27** [marytts/marytts#751]
Hello Everyone, 

I have issue in transcription step. first 20 lines are empty because of which i am not able to train my data 
![image](https://cloud.githubusercontent.com/assets/28556606/26150705/0d3d585c-3b19-11e7-9913-d0e5198ef91f.png)

**Comment by psibre** [comment]
So remove the empty lines?

**Comment by Aani27** [comment]
Instead of loading it you have to Open and choose the file. In this way this issue wont appear
