### ISSUE TITLE
Can MaryTTS generate phonemes and duration from an audio file?

### ISSUE THREAD

**Issue by idoor88** [marytts/marytts#755]
Hi All, 
I know MaryTTS can generate phonemes and duration from Text, but is there a way for MaryTTS to generated phonemes and duration from an audio file? if not, any recommendations?
Thanks

**Comment by psibre** [comment]
MaryTTS does TTS: text-to-speech. You're asking about the opposite, speech-to-text, a.k.a. automatic speech recognition (ASR). If you search the web for that, you'll find an abundance of software, but MaryTTS does not belong in that category.
