### ISSUE TITLE
VoiceCreation on server without GUI

### ISSUE THREAD

**Issue by faaip** [marytts/marytts#758]
Hey all.

It's been a bit of a struggle, but I managed to compile marytts on an Ubuntu Server. I mainly want to do voice-creation, since I thought I could use mary-tts from command-line only. After running **voiceImport.sh** I get the following exception
`No X11 DISPLAY variable was set, but this program performed an operation which requires it`

, which could indicate that it needs a GUI to run. So here my question: is there any way to Marytts on a server and create voices using only command-line?

All the best,
Frederik

**Comment by seblemaguer** [comment]
Hello,

please have a look of how to build a voice using this 2 URL:
  - http://www.coli.uni-saarland.de/~steiner/teaching/2016/winter/voicebuilding/slides/index.html#/voicebuilding
  - https://github.com/marytts/voice-cmu-slt

**Comment by faaip** [comment]
Hey @seblemaguer .

Tried to make it work, but I'm stuck at the following step:
* Run the some location/bin/voiceimport.sh script from within your voicebuilding project’s build directory

this is at the Prepare for HTS Voicebuilding slide.. Can you elaborate?

Thanks

**Comment by psibre** [comment]
@faaip Building a legacy HMM voice in your particular context, that would indeed present an obstacle, as this part does try to pop up a GUI and would fail in a headless environment. It's a bit hacky, and when we have some time, we'll try to streamline this.

You can work around this like so:
1. In your **voicebuilding** directory, edit the file `build/database.config` and edit the property `db.marybase` to your **MaryTTS source** directory.
2. In your **voicebuilding** directory, create the file `build/mary/hmmFeatures.txt`. This file should have similar contents as the `build/mary/features.txt` file; in fact you could patch the latter to create the former (assuming `en_US` locale):
```diff
6,7d5
< halfphone_lr
< halfphone_unitname
9,11d6
< next_cplace
< next_ctype
< next_cvox
13,22d7
< next_next_cplace
< next_next_ctype
< next_next_cvox
< next_next_phone
< next_next_vc
< next_next_vfront
< next_next_vheight
< next_next_vlng
< next_next_vrnd
< next_phone
27,31d11
< next_vc
< next_vfront
< next_vheight
< next_vlng
< next_vrnd
35,43d14
< ph_cplace
< ph_ctype
< ph_cvox
< ph_vc
< ph_vfront
< ph_vheight
< ph_vlng
< ph_vrnd
< phone
52,54d22
< prev_cplace
< prev_ctype
< prev_cvox
56d23
< prev_phone
58,66d24
< prev_prev_cplace
< prev_prev_ctype
< prev_prev_cvox
< prev_prev_phone
< prev_prev_vc
< prev_prev_vfront
< prev_prev_vheight
< prev_prev_vlng
< prev_prev_vrnd
70,74d27
< prev_vc
< prev_vfront
< prev_vheight
< prev_vlng
< prev_vrnd
106c59,60
< words_to_next_punctuation
\ No newline at end of file
---
> words_to_next_punctuation
> 
```
