### ISSUE TITLE
Having a problem with wav files of 8000 Hz sampling rate 

### ISSUE THREAD

**Issue by DahliaFouad** [marytts/marytts#759]
Is     #marytts's training for language model working only with wav files of 16,000 Hz sampling rate? ,and if so why sampling rate field is editable !! 
Please I'm in deep need for an answer to my question as soon as possible.
thanks in advance .

**Comment by seblemaguer** [comment]
Hello,

marytts can only generate 16kHz signal for now. The framework was supposed to integrate different sampling rate but it has never been implemented AFAIK.
