### ISSUE TITLE
How are new voices to be built nowadays?

### ISSUE THREAD

**Issue by peteroupc** [marytts/marytts#762]
There seems to be no easy way now to get started building a voice compatible with MARY TTS.

In the [wiki documentation](https://github.com/marytts/marytts/wiki) (for example, in [HMMVoiceCreation](https://github.com/marytts/marytts/wiki/HMMVoiceCreation), the first step speaks of "download[ing] MARY TTS including Voice Import Tools"; however, the latest release of MARY TTS doesn't include Voice Import Tools or any other tool for creating a new voice.  In particular, the latest release doesn't include a `lib/external` directory for downloading and installing the required tools.

I also see [a voice building plugin](https://github.com/marytts/gradle-marytts-voicebuilding-plugin) which is supposed to replace Voice Import Tools.  However, I see no instructions on using that plugin, and the repository has no wiki.  In addition, building the project, copying the JARs created to the `lib` directory of MARY TTS, running the MARY TTS server, and loading the Web Client appears to have no effect.

Therefore, there seems to be no working and documented way to get started building new voices.  In particular, the questions I have include:

- How are the Voice Import Tools to be installed?
- How can the new voice building plugin be used with MARY TTS to create new voices?
- What or where are the updated instructions for installing and using the Voice Import Tools and/or the new voice building plugin to create new voices?

**Comment by psibre** [comment]
Sorry for the confusion... we've been slooooowly transitioning away from the legacy marytts-builder documented in the wiki.
What we use nowadays is the (undocumented) Gradle voicebuilding plugin, which is currently a mix of new build logic and an efficient wrapper around the v5.2 legacy tools. This works well for unit-selection voices, which all have their own repositories, e.g.,
- https://github.com/marytts/voice-cmu-slt
- https://github.com/marytts/voice-dfki-spike
- https://github.com/marytts/voice-dfki-pavoque-neutral
etc.

The point of the plugin is to inject all common voicebuilding logic into the respective voicebuilding project with minimal voice-specific configuration. Currently, the point of departure is to get your data into the `build/wav`, `build/text`, and `build/lab` directories in your voicebuilding project, then you can run the entire process from there using either the legacy VoiceImportTools or the Gradle-based build logic.

We're still improving this -- in particular, we're developing new libraries to remove the dependency on marytts-builder-5.2, and we'll document the entire *new* process once that all works.

If you want to build an HMM voice, my current advice would be to first build a unit-selection voice, and then have a look at an [experimental dockerized workflow](http://www.coli.uni-saarland.de/~steiner/teaching/2016/winter/voicebuilding/slides/index.html#/hts-voicebuilding-with-docker) we developed as an interim solution.

**Comment by psibre** [comment]
> however, the latest release of MARY TTS doesn't include Voice Import Tools or any other tool for creating a new voice. In particular, the latest release doesn't include a lib/external directory for downloading and installing the required tools.

Please note that the latest release is currently still [v5.2](../releases/tag/v5.2), whic *does* provide all the above. The `master` branch is not a release.

**Comment by peteroupc** [comment]
> Please note that the latest release is currently still v5.2, whic does provide all the above. The master branch is not a release.

That is what I meant when I said the "latest release": version 5.2, in particular, `marytts-5.2.zip`.

**Comment by psibre** [comment]
Right, even during the 5.x release era (now `5.x` branch), there was some inconsistency between the stuff under `lib` in the *source code* and the `lib` subdirectory of the MaryTTS distribution (packaged unter `target` and downloadable as a release asset).

In any case, have a look at how the voice-* projects work, and if you have any specific questions or problems, don't hesitate to open new issues as appropriate.
