### ISSUE TITLE
error in VoiceCompiler step

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#768]
I found following error in VoiceCompiler step.please help

root@jayantasPC:/local/mary/marytts2/target/marytts-builder-5.1.2/bin# ./voiceimport.sh 
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK Server VM (build 25.66-b01, mixed mode)

Opening GUI....... 
DurationCARTTrainer
Loading database layout:
DurationCARTTrainer
Reading config file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/database.config
DurationCARTTrainer
Loading basename list from file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/basenames.lst
Found 663 files in basename list
Loading features from file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/mary/features.txt
DurationCARTTrainer
INFO  VoiceCompiler: Creating directories
INFO  VoiceCompiler: Copying template files
INFO  VoiceCompiler: Copying voice files
INFO  VoiceCompiler: Compiling with Maven
maven err>Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
java.lang.Exception: The component VoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:336)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:91)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)

**Comment by psibre** [comment]
>  Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.

What does the console say?

**Comment by jayanta1122** [comment]
after setting environment variable for maven i got build failure: 

root@jayantasPC:/local/mary/marytts2/target/marytts-builder-5.1.2/bin# ./voiceimport.sh 
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK Server VM (build 25.66-b01, mixed mode)

Opening GUI....... 
DurationCARTTrainer
Loading database layout:
DurationCARTTrainer
Reading config file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/database.config
DurationCARTTrainer
Loading basename list from file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/basenames.lst
Found 663 files in basename list
Loading features from file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/mary/features.txt
INFO  VoiceCompiler: Creating directories
INFO  VoiceCompiler: Copying template files
INFO  VoiceCompiler: Copying voice files
INFO  VoiceCompiler: Compiling with Maven
maven out>[INFO] Scanning for projects...
maven out>[INFO]                                                                         
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Building voice-my_voice 5.1.2
maven out>[INFO] ------------------------------------------------------------------------
maven out>Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-failsafe-plugin/2.8/maven-failsafe-plugin-2.8.pom
maven out>
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] BUILD FAILURE
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Total time: 0.898 s
maven out>[INFO] Finished at: 2017-06-07T15:31:21+05:30
maven out>[INFO] Final Memory: 7M/82M
maven out>[INFO] ------------------------------------------------------------------------
maven out>[ERROR] Plugin org.apache.maven.plugins:maven-failsafe-plugin:2.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-failsafe-plugin:jar:2.8: Could not transfer artifact org.apache.maven.plugins:maven-failsafe-plugin:pom:2.8 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failure in name resolution: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
maven out>[ERROR] 
maven out>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
maven out>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
maven out>[ERROR] 
maven out>[ERROR] For more information about the errors and possible solutions, please read the following articles:
maven out>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
java.lang.Exception: The component VoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:336)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:91)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)

**Comment by psibre** [comment]
Looks to me like your Maven installation is broken, incomplete, or outdated.

**Comment by jayanta1122** [comment]
ok.thanks for replay

**Comment by psibre** [comment]
Cutting to the chase:

The legacy VoiceCompiler component has a clumsy hack that tries to run Maven inside a subprocess, in order to test and package the voice for distribution. This can fail for various reasons.
I recommend *not* using the VoiceImportTools GUI for this final step, because any errors are hidden deep in the execution stack.

You should be able to simply `cd /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/mary/` and run `mvn package`.

**Comment by psibre** [comment]
Note that you seem to be using the outdated v5.1.2 of MaryTTS.

**Comment by psibre** [comment]
Also, it's bad practice to build voices under the `target` directory of the MaryTTS source code. You should use a separate location for each voicebuilding project.

**Comment by jayanta1122** [comment]
@psibre Thanks for your valuable suggestions.I successfully compile the voice.There was some proxy issues in my network.

**Comment by psibre** [comment]
Thanks for the follow-up; glad you solved it!

**Comment by jayanta1122** [comment]
@psibre  I want to publish my voice and i am following https://github.com/marytts/marytts/wiki/Publishing-a-MARY-TTS-Voice. But my language is not shown in MaryTTS Installer.please help
