### ISSUE TITLE
hissing voice and silence

### ISSUE THREAD

**Issue by baaslaawe** [marytts/marytts#771]
hello 
please help me 
i got when i was complete a lot of **hissing voice and silence**
hissing sounds, Every word in the (S)
and also **voices sound horrible** 

**this is the text i was testing**
(Si uu u beerto dhulkii isaga laga soo qaaday, kolkaasuu ninkii eryay beer ceeden barigeedana wuxuu taagay)

**this is my VOICE EXAMPLES**
[Voice_Example.zip](https://github.com/marytts/marytts/files/1066856/Voice_Example.zip)

**allophones.so.xml**
[allophones.so.xml.zip](https://github.com/marytts/marytts/files/1066859/allophones.so.xml.zip)

**ALLOPHONES OUTBUT**

```
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="so">
<p>
<s>
<prosody pitch="+5%" range="+20%">
<phrase>
<t accent="L+H*" g2p_method="rules" ph="' s i" pos="content">
Si
<syllable accent="L+H*" ph="s i" stress="1">
<ph p="s"/>
<ph p="i"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="rules" ph="' u:" pos="content">
uu
<syllable accent="L+H*" ph="u:" stress="1">
<ph p="u:"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="u" pos="content">
u
<syllable ph="u">
<ph p="u"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="b e: r - t o" pos="content">
beerto
<syllable ph="b e: r">
<ph p="b"/>
<ph p="e:"/>
<ph p="r"/>
</syllable>
<syllable ph="t o">
<ph p="t"/>
<ph p="o"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="d@ u l - k i:" pos="content">
dhulkii
<syllable ph="d@ u l">
<ph p="d@"/>
<ph p="u"/>
<ph p="l"/>
</syllable>
<syllable ph="k i:">
<ph p="k"/>
<ph p="i:"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="i - s a - g a" pos="content">
isaga
<syllable ph="i">
<ph p="i"/>
</syllable>
<syllable ph="s a">
<ph p="s"/>
<ph p="a"/>
</syllable>
<syllable ph="g a">
<ph p="g"/>
<ph p="a"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="l a - g a" pos="content">
laga
<syllable ph="l a">
<ph p="l"/>
<ph p="a"/>
</syllable>
<syllable ph="g a">
<ph p="g"/>
<ph p="a"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="s o:" pos="content">
soo
<syllable ph="s o:">
<ph p="s"/>
<ph p="o:"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="q a: - d a j" pos="content">
qaaday
<syllable ph="q a:">
<ph p="q"/>
<ph p="a:"/>
</syllable>
<syllable ph="d a j">
<ph p="d"/>
<ph p="a"/>
<ph p="j"/>
</syllable>
</t>
<t pos="$PUNCT">
,
</t>
<boundary breakindex="4" tone="H-L%"/>
</phrase>
</prosody>
<prosody pitch="-5%" range="-20%">
<phrase>
<t accent="L+H*" g2p_method="rules" ph="' k o l - k a: - s u:" pos="content">
kolkaasuu
<syllable accent="L+H*" ph="k o l" stress="1">
<ph p="k"/>
<ph p="o"/>
<ph p="l"/>
</syllable>
<syllable ph="k a:">
<ph p="k"/>
<ph p="a:"/>
</syllable>
<syllable ph="s u:">
<ph p="s"/>
<ph p="u:"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="n i n - k i:" pos="content">
ninkii
<syllable ph="n i n">
<ph p="n"/>
<ph p="i"/>
<ph p="n"/>
</syllable>
<syllable ph="k i:">
<ph p="k"/>
<ph p="i:"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="e r - j a j" pos="content">
eryay
<syllable ph="e r">
<ph p="e"/>
<ph p="r"/>
</syllable>
<syllable ph="j a j">
<ph p="j"/>
<ph p="a"/>
<ph p="j"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="b e: r" pos="content">
beer
<syllable ph="b e: r">
<ph p="b"/>
<ph p="e:"/>
<ph p="r"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="rules" ph="' ?@ e: - d e n" pos="content">
ceeden
<syllable accent="L+H*" ph="?@ e:" stress="1">
<ph p="?@"/>
<ph p="e:"/>
</syllable>
<syllable ph="d e n">
<ph p="d"/>
<ph p="e"/>
<ph p="n"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="rules" ph="' b a - r i - g e: - d a - n a" pos="content">
barigeedana
<syllable accent="L+H*" ph="b a" stress="1">
<ph p="b"/>
<ph p="a"/>
</syllable>
<syllable ph="r i">
<ph p="r"/>
<ph p="i"/>
</syllable>
<syllable ph="g e:">
<ph p="g"/>
<ph p="e:"/>
</syllable>
<syllable ph="d a">
<ph p="d"/>
<ph p="a"/>
</syllable>
<syllable ph="n a">
<ph p="n"/>
<ph p="a"/>
</syllable>
</t>
<t accent="L+H*" g2p_method="userdict" ph="w u - X@ u:" pos="content">
wuxuu
<syllable ph="w u">
<ph p="w"/>
<ph p="u"/>
</syllable>
<syllable ph="X@ u:">
<ph p="X@"/>
<ph p="u:"/>
</syllable>
</t>
<t accent="!H*" g2p_method="userdict" ph="t a: - g a j" pos="content">
taagay
<syllable ph="t a:">
<ph p="t"/>
<ph p="a:"/>
</syllable>
<syllable ph="g a j">
<ph p="g"/>
<ph p="a"/>
<ph p="j"/>
</syllable>
</t>
<boundary breakindex="5" tone="L-L%"/>
</phrase>
</prosody>
</s>
</p>
</maryxml>
```

**Comment by psibre** [comment]
HMM-based synthesis can be quite tricky to get working. In this case, judging from the quality of the original audio you provided, I would assume that the feature extraction failed. There is a lot of compression noise (did you use MP3 at some point?) and limited spectral bandwidth, and the volume is very low. If you could get lossless recordings, you should definitely use those. Meanwhile, you could also try to normalize the audio.

In general, if you first build a unit-selection voice and it doesn't sound very natural, then you can expect additional problems when you try to train an HMM-based voice.

**Comment by baaslaawe** [comment]
thank you 
1. the audio before was  mp3 then i was convert to wav
2.  unit-selection voice natural , 

the problem was only HMM-based voice

**Comment by baaslaawe** [comment]
thank you @psibre 

please help me
**when i check  
[log.txt.tar.gz](https://github.com/marytts/marytts/files/1071973/log.txt.tar.gz)
i got a lot of  like this** 


=====================================================================
Start synthesizing waveforms (1mix) at Tue Jun 13 18:22:34 EAT 2017
=====================================================================
Synthesizing a speech waveform from gen_ax_7__30.mgc and gen_ax_7__30.lf0.../usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-integer' instead.
/usr/bin/sox WARN sox: Option `-2' is deprecated, use `-b 16' instead.
/usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-integer' instead.
/usr/bin/sox WARN sox: Option `-2' is deprecated, use `-b 16' instead.
x2x : warning: input data is over the range of type 'short'!

...............

===============================================================================
Start synthesizing waveforms using hts_engine at Mon Jun 12 01:03:06 EAT 2017
===============================================================================

Synthesizing a speech waveform from /home/awale/voice/data/somali/hts/data/labels/gen/gen_ax_10__31.lab using hts_engine.../usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-integer' instead.
/usr/bin/sox WARN sox: Option `-2' is deprecated, use `-b 16' instead.
/usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-integer' instead.
/usr/bin/sox WARN sox: Option `-2' is deprecated, use `-b 16' instead.

**Comment by psibre** [comment]
You need to make sure you have compatible versions of all required software installed correctly. Those warnings indicate that this is not the case.

**Comment by baaslaawe** [comment]
ok 
thank you

unit-selection voice is ok just problem  HMM-based voice
in my case what is the problem and how can i solve

**Comment by baaslaawe** [comment]
i was try to build cmu-clt-hsmm it's good voice idid't any problem 

when i do my language in  HMM-based voice i got bad voice

**Comment by baaslaawe** [comment]
please help

**Comment by baaslaawe** [comment]
stil i need your help @psibre

**Comment by psibre** [comment]
Like I said [a week ago](#issuecomment-307700369):
> you could also try to normalize the audio.

**Comment by baaslaawe** [comment]
thank you @psibre 

in your answer  i was confused

before if audio was mp3 how can i fixed  that  (feature extraction failed and compression noise) you said that 

i got audio book for mp3   i use to convert **sox** to wav 
 and also i was build new Voice and also was  try deferent voice 


(Degdeg bay u soo dareereen iyagoo dhan ka faraxsan oo is tusaya waxayan horay u cuni jirin in maanta ay cuni doonaan)
[Voice_Example2.zip](https://github.com/marytts/marytts/files/1084455/Voice_Example2.zip)


**more then 10 months from **September  10, 2016 until now** i did't get any result in my language , there is't  any resource and also there is no previous system**   

it maybe wrong my phonetic 

thank you for your sharing your knowledge

**Comment by nshmyrev** [comment]
Well, your original file is just 8khz, you should have build 8khz voice then or at least restrict frequencies in mcep. I also doubt you wrote the questions for hts properly.

It is more productive to share the whole voice folder, not just examples. You can upload to dropbox or google drive and give here a link.

**Comment by baaslaawe** [comment]
**1. Voice1** 
https://studentuumedu-my.sharepoint.com/personal/s228837_student_uum_edu_my/_layouts/15/guestaccess.aspx?folderid=159220a311797471da5fd06b046d5461b&authkey=ARL30Txszd1eZHYcquTblec&expiration=2017-07-09T10%3a44%3a45.000Z

**2. Voice2**
https://studentuumedu-my.sharepoint.com/personal/s228837_student_uum_edu_my/_layouts/15/guestaccess.aspx?folderid=1b1f80d81093d4b9e8ca2f7bc0282bac3&authkey=AeDWtQ0MZXRRzuNm-hS_AY0&expiration=2017-07-09T10%3a45%3a19.000Z

**Comment by nshmyrev** [comment]
@baaslaawe those are just source files. We need the voice database will all intermediate files (pitchmarks, mcep, trees, phone questions, etc). Otherwise we will have to recreate it ourselves and it takes a lot of time. It is better to upload a single large zip file which is easier to download.

**Comment by baaslaawe** [comment]
you mean HTS folder or mary

**Comment by nshmyrev** [comment]
Both

**Comment by baaslaawe** [comment]
thank you it's take time because my internet  slow

i will upload

**Comment by baaslaawe** [comment]
thank you @nshmyrev i was late 

1.  https://drive.google.com/drive/folders/0B0AS2DD8i5DcM0ZpSmlwYnVSVU0?usp=sharing

2.  https://drive.google.com/drive/folders/0B0AS2DD8i5DcMW1DcTh1czRTc0E?usp=sharing

**Comment by nshmyrev** [comment]
@baaslaawe is it intentional you built hts voice from just 5 files or did you delete some other files?

**Comment by baaslaawe** [comment]
no but i got like alot of like this 

Synthesizing a speech waveform from gen_ax_7__30.mgc and gen_ax_7__30.lf0.../usr/bin/sox WARN sox: Option -s' is deprecated, use-e signed-integer' instead.
/usr/bin/sox WARN sox: Option -2' is deprecated, use-b 16' instead.
/usr/bin/sox WARN sox: Option -s' is deprecated, use-e signed-integer' instead.
/usr/bin/sox WARN sox: Option -2' is deprecated, use-b 16' instead.
x2x : warning: input data is over the range of type 'short'!

**Comment by nshmyrev** [comment]
Ok, your files are too loud, the are normalized to volume 1.0, it is better to renormalize to volume 0.5.

Also I asked you to upload the zip file, you shared the file structure instead. Google does not allow to download that smoothly. Please share a zip file.

**Comment by nshmyrev** [comment]
You do not need two voices, single voice is enough.

**Comment by baaslaawe** [comment]
sorry for that i did't share for zip 

before i use this audio_converter_GUI.sh to convert , 


how can renormalize to volume 0.5

thakn you

**Comment by nshmyrev** [comment]
Something like 

      for f in *.wav; do sox $f $f.new.wav vol 0.5; mv $f.new.wav $f; done

**Comment by baaslaawe** [comment]
thank you bro @nshmyrev  

i will rebuild then i will share you any information 


thanks a lot

**Comment by baaslaawe** [comment]
thank you Mr @nshmyrev 

after renormalize mostly are good but i got little bit bad voice and also after sil or (.) i got  too loud volume then low volume .

**another** 
Processing directory /home/awale/voice/data/somali/hts/gen/qst001/ver1/1mix/1:
 Synthesizing a speech waveform from gen_SOM001-AB-S00190.mgc and gen_SOM001-AB-S00190.lf0.../usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-integer' instead.
/usr/bin/sox WARN sox: Option `-2' is deprecated, use `-b 16' instead.
/usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-integer' instead.
/usr/bin/sox WARN sox: Option `-2' is deprecated, use `-b 16' instead.
x2x : warning: input data is over the range of type 'short'!
x2x : warning: input data is over the range of type 'short'!
x2x : warning: input data is over the range of type 'short'!


===============================================================================
Start synthesizing waveforms using hts_engine at Thu Jun 22 03:59:54 EAT 2017
===============================================================================

Synthesizing a speech waveform from /home/awale/voice/data/somali/hts/data/labels/gen/gen_SOM001-AB-S00190.lab using hts_engine.../usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-integer' instead.
/usr/bin/sox WARN sox: Option `-2' is deprecated, use `-b 16' instead.
/usr/bin/sox WARN sox: Option `-s' is deprecated, use `-e signed-integer' instead.
/usr/bin/sox WARN sox: Option `-2' is deprecated, use `-b 16' instead.
done.

this text that i was test
(Si uu u beerto dhulkii isaga laga soo qaaday, kolkaasuu ninkii eryay beer ceeden barigeedana wuxuu taagay.

Degdeg bay u soo dareereen iyagoo dhan ka faraxsan oo is tusaya, waxayan horay u cuni jirin in maanta ay cuni doonaan)


Voice_Example3
https://drive.google.com/file/d/0B0AS2DD8i5DcY21EYUR3czB6amM/view?usp=sharing

log-2017.06.21-19/14/25.
https://drive.google.com/file/d/0B0AS2DD8i5DcVjR1WHczcm1MaXM/view?usp=sharing


any advice 

thnks

**Comment by nshmyrev** [comment]
> /usr/bin/sox WARN sox: Option -2' is deprecated, use-b 16' instead.

Install older sox version (0.12 probably)

**Comment by baaslaawe** [comment]
thank you Mr @nshmyrev  
it's work but just **VOICE(sound)  is bad** how can  voices sound horrible to good sound
example new voice :[sound horrible.zip](https://github.com/marytts/marytts/files/1099524/sound.horrible.zip)

also i got like this error

=====================================================================
Start synthesizing waveforms (1mix) at Sat Jun 24 04:24:46 EAT 2017
=====================================================================

Processing directory /home/awale/voice/data/somali/hts/gen/qst001/ver1/1mix/0:
 Synthesizing a speech waveform from gen_SOM001-AB-S00190.mgc and gen_SOM001-AB-S00190.lf0...x2x : warning: input data is over the range of type 'short'!
**x2x : warning: input data is over the range of type 'short'!
x2x : warning: input data is over the range of type 'short'!**
x2x : warning: input data is over the range of type 'short'!
x2x : warning: input data is over the range of type 'short'!
Processing directory /home/awale/voice/data/somali/hts/gen/qst001/ver1/1mix/1:
 Synthesizing a speech waveform from gen_SOM001-AB-S00190.mgc and gen_SOM001-AB-S00190.lf0...x2x : warning: input data is over the range of type 'short'!
x2x : warning: input data is over the range of type 'short'!
**x2x : warning: input data is over the range of type 'short'!**

**Comment by nshmyrev** [comment]
@baaslaawe does not sound horrible for me, just some glitches. Reduce the volume of the input sound one more time to avoid x2x errors, maybe 0.2 instead of 0.5. And rebuild all other files.

**Comment by baaslaawe** [comment]
thank you bro @nshmyrev,

next time i will try then i will rebuild


thank you a lot
