### ISSUE TITLE
PraatPitchMarker error

### ISSUE THREAD

**Issue by faaip** [marytts/marytts#775]
Hey all!

I'm on 5.x and I'm trying to build a USS voice, but I found into the following the PraatPitchMarker element. I'm testing with the cmu data and have set the db.wavDir to the correct folder. I tried editing the database.config file as described here: https://github.com/marytts/marytts/issues/540 . When I enter `praat --run` on line 35. After I edit the file, I get the following error

`Opening GUI....... 
Loading database layout:
Reading config file /home/mads/Desktop/cmu_test_light/database.config
Exception in thread "main" java.io.IOException: Error reading config file
    at marytts.tools.voiceimport.DatabaseLayout.readConfigFile(DatabaseLayout.java:396)
    at marytts.tools.voiceimport.DatabaseLayout.initialize(DatabaseLayout.java:229)
    at marytts.tools.voiceimport.DatabaseLayout.<init>(DatabaseLayout.java:169)
    at marytts.tools.voiceimport.DatabaseImportMain.main(DatabaseImportMain.java:413)
Caused by: java.io.IOException: Illegal line -- expecting two fields, got 1: 'AllophonesExtractor.styleDefinitionFile'
    at marytts.tools.voiceimport.DatabaseLayout.readConfigFile(DatabaseLayout.java:363)
    ... 3 more`

Does anyone know how this can be solved? Thanks!

**Comment by psibre** [comment]
> `Illegal line -- expecting two fields, got 1: 'AllophonesExtractor.styleDefinitionFile'`

My suspicion is that when you edited the `database.config` file, your editor trimmed trailing whitespace, corrupting the format of the file. You need to fix that.

**Comment by faaip** [comment]
Hey @psibre - first of all, thank you for your continuous help on these issues, it's a huge help! vim did indeed remove the trailing whitespace, so now Allophoneextractor is running. I ran into a new problem now and I hope it's ok that I ask for help in this thread.

I'm at step 7 in [UnitSelectionVoiceCreation-guide](https://github.com/marytts/marytts/wiki/UnitSelectionVoiceCreation) and trying to use the WaveTimelineMaker. When trying to run, I get `Processing [0] utterances`, which of course isn't right. I'm pretty sure I set db.wavDir is set correctly, since it worked in the other step. Do you (or anyone else) know to fix this?

**Comment by psibre** [comment]
If there is a `build/basenames.lst` file, then it is used *instead* of the files in the `wav/` directory. If that file is empty, you would have 0 utterances to process. Try removing that file and start over.

**Comment by faaip** [comment]
@psibre sorry for the late reply. Just tried your suggestion and it worked, thanks!
