### ISSUE TITLE
Request for minimal HMM based synthesis

### ISSUE THREAD

**Issue by ghost** [marytts/marytts#78]
Requesting for minimal HMM only speech synthesis (ideally with English/Russian) languages without any unnecessary dependencies. Only just one simple embeddable package without web-server/web-client and other packages.

Or can you give some advice to do it by yourself, I tryed to do that, but with no success. As I understand all core functionality is in marytts-runtime and all I need is in this package? Please, need help.

**Comment by Munzey** [comment]
We are slowly weaning mary off some of these dependencies: FreeTTS  will be gone in 5.2, and for 6.0 we plan to have all post signal-processing contained as an optional extra module. There is also (possibly after the time of this issue) now a `LocalMaryInterface` found in `marytts-runtime` which provides a simple unified interface for both the server and client.
