### ISSUE TITLE
Compiled voice doesn't show up in component-installer

### ISSUE THREAD

**Issue by faaip** [marytts/marytts#781]
Dear all.

Through trial and error and a lot of help from you guys, I've managed to create a voice using the CMS test package. I am now running into some final obsctacles and would love your help.

From what I understand: I first create a voice and then go to mary/my-voice/target/ and copy the .zip and .xml file. I then copy these into MARY-BASE/target/marytts-5.3-SNAPSHOT/download and then run the marytts-component-installer.

My problem is that the component installer only seems to show voices available on the website and not the one I just placed in the download folder. Am I overlooking something or doing something wrong?

My component.xml looks as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?><marytts-install xmlns="http://mary.dfki.de/installer">
  <voice gender="female" locale="en_US" name="test-voice" type="unit selection" version="5.3-SNAPSHOT">
    <description>Testing voice</description>
    <license href="http://mary.dfki.de/download/by-nd-3.0.html"/>
    <package filename="voice-my_voice-5.3-SNAPSHOT.zip" md5sum="ec1175d8073a4f01f6bb7c8829a5d5cf" size="105018503">
      <location folder="true" href="http://mary.dfki.de/download/5.3-SNAPSHOT/"/>
    </package>
    <files>lib/voice-my_voice-5.3-SNAPSHOT.jar</files>
    <depends language="en" version="5.3-SNAPSHOT"/>
  </voice>
</marytts-install>
```

Thank you so much,
Fred

**Comment by psibre** [comment]
First of all, you should have a `voice-my_voice-5.3-SNAPSHOT.zip` file, which you can just unzip into any MaryTTS installation. No need to "install" it.

But to address your question: was this XML descriptor generated automatically, or did you create it by hand? I ask because there are a few differences to what I would expect.

Are there any error messages when you run the `marytts-component-installer`?

**Comment by faaip** [comment]
Hey @psibre .

I tried doing a fresh compilation using the voiceImport tools and the .xml file now is as follows:
`<?xml version="1.0" encoding="UTF-8"?><marytts-install xmlns="http://mary.dfki.de/installer">
  <voice gender="female" locale="en-US" name="" type="marytts.unitselection.UnitSelectionVoice" version="5.3-SNAPSHOT">
    <description>A female English general voice</description>
    <license href="http://mary.dfki.de/download/by-nd-3.0.html"/>
    <package filename="voice-my_voice-5.3-SNAPSHOT.zip" md5sum="4567899e386e22123d964644972c3713" size="105018530">
      <location folder="true" href="http://mary.dfki.de/download/5.3-SNAPSHOT/"/>
    </package>
    <files>lib/voice-my_voice-5.3-SNAPSHOT.jar</files>
    <depends language="en" version="5.3-SNAPSHOT"/>
  </voice>
</marytts-install>
`

When reading the [guide](https://github.com/marytts/marytts/wiki/Publishing-a-MARY-TTS-Voice), I understand it as though I copy the .zip file and the .xml file into `MARY-BASE/target/marytts-5.3-SNAPSHOT/download` and the run the component-installer. The component-installer starts up fine and with no exceptions thrown, but my newly created doesn't show up in the list in the component installer. Am I missing something obvious? Thanks 👍

**Comment by faaip** [comment]
Got around this by not using the component-installer and just copy to the lib folder. Did the trick.
