### ISSUE TITLE
Error: Could not find or load main class marytts.tools.dbselection.WikipediaProcessor

### ISSUE THREAD

**Issue by neouyghur** [marytts/marytts#787]
I have encountered a problem when I am cleaning the wiki data. 

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Error: Could not find or load main class marytts.tools.dbselection.WikipediaProcessor

And my another question is that "can I use other text sources like a file includes texts except the wiki, if so how can I can do that?"

**Comment by psibre** [comment]
Could you please provide the exact command you ran?

**Comment by neouyghur** [comment]
the command I run:

wkdb_cleaning_up.sh wkdb.conf

**Comment by psibre** [comment]
From which directory are you running the script? Are you sure the jar files are in the `lib` subdirectory of that directory?

**Comment by neouyghur** [comment]
I am running the program the wikidata directory. in which directory these
jar files exist?

**Comment by psibre** [comment]
Please ensure that you have completed [the initial steps as documented](../wiki/New-Language-Support#0-set-up-your-environment).

**Comment by neouyghur** [comment]
This time I download the source code of 5.2 version and I use the ```mvn install``` command. It is built successfully. I run the code again, I still get same errors. 

 ```
sh ../marytts-5.2/marytts-assembly/assembly-builder/src/builder/bin/wkdb_cleaning_up.sh wkdb.conf                                             
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Error: Could not find or load main class marytts.tools.dbselection.WikipediaProcessor
```

**Comment by psibre** [comment]
Please pay attention to the wiki I linked to. You need to run the shell script from the correct target!
