### ISSUE TITLE
problem with german umlaute

### ISSUE THREAD

**Issue by juergmaier** [marytts/marytts#788]
Using "dfki-pavoque-neutral-hsmm" (voice-dfki-pavoque-neutral-hsmm-5.2.jar) as my botVoice I get a spoken "ä" for the text "ae". 
If my text has an "ae" in the sequence of letters, e.g. "waehrend", it is pronounced as "waehrend" and not as "während". 
Also the text "während" is pronounced the wrong way.
Can I somehow mark "ae" to be spoken as "ä" in my words?

**Comment by psibre** [comment]
I cannot hear the problem. Synthesizing "während" with voice-dfki-pavoque-neutral-hsmm:5.2 sounds find to me.
And the PHONEMES are correct as well:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t g2p_method="lexicon" ph="' v E: - R @ n t" pos="ADJD">
während
</t>
</s>
</p>
</maryxml>
```

**Comment by juergmaier** [comment]
Thanks for the quick answer and your confirmation that it works for you. This made me look out for encoding issues and indeed I used (in my python-script) simply a normal string:

mouth.speakBlocking("während")

Changing this to

mouth.speakBlocking(u"während") 

fixed the issue.
