### ISSUE TITLE
german "schere" not pronounced naturally

### ISSUE THREAD

**Issue by juergmaier** [marytts/marytts#789]
trying to make my robot play rockpaperscissor I am using "Schere Stein Papier" in german.
The word "Schere" (scissors) is pronounced with a rapid "e" by MaryTTS but should sound more like "Schehre" , with a long "e". I tried using "Schehre" but the "h" gets ignored.
How can I specify a more natural pronunciation for this word? (using voice-dfki-pavoque-neutral-hsmm-5.2.jar)

**Comment by fuzeller** [comment]
Are you able to build a voice from the source data, or are you only using the compiled voice (jar)?

**Comment by fuzeller** [comment]
You should be able to edit the user dictionary and change the phoneme. Under your target directory, /marytts-5.2-SNAPSHOT/user-dictionaries/, edit 'userdict-de.txt', by adding:
Schire | ' S i: - R @

Save the file and restart your server to try it.

**Comment by psibre** [comment]
Indeed, the word *Schere* is missing from the German dictionary source, and so the `PHONEMES` are predicted as:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t g2p_method="rules" ph="' S 6 - R @" pos="NN">
Schere
</t>
</s>
</p>
</maryxml>
```
Adding the missing word in [marytts-lexicon-lang-de](../../marytts-lexicon-de) fixes the issue:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t g2p_method="lexicon" ph="' S e: - R @" pos="NN">
Schere
</t>
</s>
</p>
</maryxml>
```

**Comment by psibre** [comment]
@juergmaier You can resolve an updated snapshot from [OJO](https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/de/dfki/mary/marytts-lexicon-de/0.2.0-SNAPSHOT). In the meantime, @fuzeller's suggestion is another good workaround.
