### ISSUE TITLE
portion of xml repeated in voice output, reproducable

### ISSUE THREAD

**Issue by logicaloctopus** [marytts/marytts#79]
When submitting a RAWMARYXML request to the engine there are certain conditions where it repeats a portion of the message.  Take this input for example...

&lt;?xml version="1.0" encoding="UTF-8" ?&gt;
&lt;maryxml version="0.4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://mary.dfki.de/2002/MaryXML" xml:lang="en-US"&gt;

&lt;prosody rate="-20%" contour="(0%,+5%) (70%,-0%) (100%,-10%)"&gt;This part gets repeated. Something to say.&lt;boundary duration="800"/&gt;&lt;/prosody&gt;

&lt;prosody range="+20%"&gt;another random sentence.&lt;boundary duration="1200"/&gt;&lt;/prosody&gt;

&lt;/maryxml&gt;

The portion "This part gets repeated."  Is contained in the output wave file a second time at the end of the utterance.  Changing the a to a capital in the last sentence "Another...' prevents it from happening.

Ive tried various utterances, and no matter what, if the final sentence begins with lower case, some portion of the preceding text is repeated at the end.  At least I've found a pattern and the work-around, but I don't believe this was the intended behaviour.

I am using marytts on:
Fedora release 14 (Laughlin)
with:
java version "1.7.0_06"
Java(TM) SE Runtime Environment (build 1.7.0_06-b24)
Java HotSpot(TM) 64-Bit Server VM (build 23.2-b09, mixed mode)
[

**Comment by Munzey** [comment]
fixed by #228
