### ISSUE TITLE
General questions regarding MaryTTS

### ISSUE THREAD

**Issue by topherseance** [marytts/marytts#793]
Hello,

I am a complete newbie in text-to-speech technologies and methods, so I apologize if I have some stupid questions.
(Is this Github Issue Tracker suitable for questions like this? Can I contact you via email?)

I want to add a new language: [Javanese language](https://en.wikipedia.org/wiki/Javanese_language)

However, I have several questions about MaryTTS:
1. Is it possible to add new language without having to create new voices? (i.e.: without recording voices from native speaker)
2. What is the difference between marytts projects named **marytts-lang-xx** and **marytts-lexicon-xx**, and how it is used together on the final program? (for example: [marytts-lang-pl](https://github.com/marytts/marytts-lang-pl) and [marytts-lexicon-pl](https://github.com/marytts/marytts-lexicon-pl))
3. About [Allophones XML file](https://github.com/marytts/marytts-lexicon-pl/blob/master/modules/pl/lexicon/allophones.pl.xml): What is **vheight, vfront, vrnd, ctype, cplace, cvox**?
4. About [this Polish lexicon file](https://github.com/marytts/marytts-lexicon-pl/blob/master/modules/pl/lexicon/pl.txt): Is this manually created or auto-generated?

Thanks before. =)

**Comment by seblemaguer** [comment]
Hello,

1.yes and no. if you want ot achieve TTS (so really reproducing speech) the language part is not going to be enough. if you just want to produce features therefore it is possible. The language is just dealing with the frontend part.
2. lang-xx is the package providing modules for the system  for the language xx (therefore postagger, phonemiser, ...). lexicon-xx is just providing the lexicon. Therefore, lang-xx depends on lexicon-xx
3. is vowel height? is vowel front? is vowel round? what is consonant type? what is consonnt place?
4. I personally don't know

According to your question I suggest that you read some lectures about TTS. You have a nice one here: http://www.speech.zone/courses/

**Comment by psibre** [comment]
> 4. About this Polish lexicon file: Is this manually created or auto-generated?

In that case, the file was generated using some other Polish G2P tool.
(If you look at [the history](../../marytts-lexicon-pl/commits/master/modules/pl/lexicon/pl.txt), you'll notice that this actually caused a lot of problems due to character encoding, etc.)

**Comment by topherseance** [comment]
Thanks!

I have some another questions:

Taken from [New Language Support](https://github.com/marytts/marytts/wiki/New-Language-Support) wiki page (which you said it is *legacy* in some other issue threads), Section "4. Minimal NLP components for the new language":

> Copy runtime files from the transcription tool:
>  marytts-lang-xy/src/main/resources/marytts/language/xy/lexicon/allophones.xy.xml
>  marytts-lang-xy/src/main/resources/marytts/language/xy/lexicon/xy.lts
>  marytts-lang-xy/src/main/resources/marytts/language/xy/lexicon/xy_lexicon.fst
>  marytts-lang-xy/src/main/resources/marytts/language/xy/tagger/xy_pos.fst

Can you give explanations on these files, what it does and how to make them?

1. xy.lts
2. xy_lexicon.fst
3. xy_pos.fst

I cloned the *marytts-master* project, I only find one .lts file, which is located on `/marytts-languages/marytts-lang-sv`. I don't find it on the other languages' folders, though, so I don't know which one to copy..

I am sorry for my lack of understanding... have been trying to make sense of how MaryTTS works.

--

Anyway, do you need any help creating Wiki pages and documentations?
Maybe I could help... Although I only have minimal knowledge on speech synthesis subject.
I thought it would be nice if there are some step-by-step tutorial for complete beginners.

**Comment by psibre** [comment]
The fst and lts files are *compiled* from the lexicon resources. The XML you'll have to create in a text editor or similar. This part of the tool chain is actually under active development (well... whenever I have time to work on it), and I plan to clarify this over the course of the coming month...

In the meantime, please have a look at the various lexicon repositories:
- https://github.com/marytts/marytts-lexicon-en_US-cmudict
- https://github.com/marytts/marytts-lexicon-de

etc.

These are built separately, and then they are *resolved as dependencies* by the corresponding marytts-lang-* projects.

**Comment by topherseance** [comment]
Okay thanks!
