### ISSUE TITLE
Question regarding transcriptions

### ISSUE THREAD

**Issue by faaip** [marytts/marytts#794]
Dear all.

This question might be quite basic, but I haven't been able to find the answer online. I'm building an  english USS voice and am basing it on the transcriptions from festvox (txt.done.data). Is it possible to add new sentences to this? So that we'd be able to build a voice from custom sentences?

Thank you

**Comment by psibre** [comment]
Of course you can use whatever prompts you want. Please have a look at [the wiki](../wiki/VoiceImportToolsTutorial).

**Comment by faaip** [comment]
Perfect! Thank you for the help, @psibre
