### ISSUE TITLE
Source for MaryTTS

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#797]
Hi,

This is a question to understand the actual speech synthesis procedure used in MaryTTS. What is the source signal that is used for MaryTTS? We know that in Festival it is an impulse train. Is it the same for MaryTTS? Are there any references where I can get this information?

**Comment by seblemaguer** [comment]
Hello,

just to be sure, you are talking about the unit selection or the HMM based synthesis ?

**Comment by jesinj** [comment]
Hi , 

I am talking about HMM synthesis.

**Comment by seblemaguer** [comment]
hello. the current version of marytts is using a java port of hts engine which is used in festival. Therefore it is also an impulse train.

**Comment by jesinj** [comment]
Thankyou for the clarification.
