### ISSUE TITLE
how to train

### ISSUE THREAD

**Issue by guliashvili** [marytts/marytts#804]
Hi, 
I'm adding support of the georgian language to marytts. I already finished following https://github.com/marytts/marytts/wiki/New-Language-Support tutorial.

Now I'm stuck on https://github.com/marytts/marytts/wiki/HMMVoiceCreation this tutorial.
For example, 

`
1- Run the AllophonesExtractor to create the prompt_allophones directory required in the next step. This component requires the MARY server.`

How should I do it? I checked AllophonesExtractor class and it's not even executable(has no main method)

**Comment by fuzeller** [comment]
@guliashvili Are you running the voiceimport process that provide a GUI?  e.g. (path)/marytts/target/marytts-builder-5.3-SNAPSHOT/bin$ ./voiceimport.sh (.bat for windows)?

**Comment by guliashvili** [comment]
@fuzeller 
I recorded my voice using redstart and then used audio_converter_GUI.sh. Can not I move to HMMVoice directly?

**Comment by psibre** [comment]
For a slightly updated workflow, have a look at (these slides)[http://www.coli.uni-saarland.de/~steiner/teaching/2016/winter/voicebuilding/slides/index.html#/voicebuilding-1].

**Comment by wotulong** [comment]
@guliashvili ,I think you have to run MaryTTS server to test you language module after you finish the tutorial "https://github.com/marytts/marytts/wiki/New-Language-Support".

**Comment by guliashvili** [comment]
@psibre 
WIll it work on 5.x branch? 
@wotulong 
on localhost:59125/locale I see new language added. Is there any other check for that?

**Comment by psibre** [comment]
@guliashvili The current versions of those Gradle plugins are designed to be compatible with 5.x -- in fact, they explicitly depend on v5.2.

**Comment by wotulong** [comment]
@guliashvili ,What you need to do before the step of "HMMVoiceCreation" is as follow side:
https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial

**Comment by wotulong** [comment]
I realize "UnitSelectionVoiceCreation" on 6.0, but it really take me a lot of time, and there are some bugs in the code that take much of my time.

**Comment by psibre** [comment]
@wotulong 
> I realize "UnitSelectionVoiceCreation" on 6.0

I'm not sure what you mean.

> there are some bugs in the code

which code?

If you have specific problems, please open a dedicated issue.
