### ISSUE TITLE
voiceimport MCEP Praat

### ISSUE THREAD

**Issue by guliashvili** [marytts/marytts#806]
I'm trying to replicate results of the https://github.com/marytts/marytts/wiki/VoiceImportToolsTutorial with ARCTIC data from CMU.

However both PraatPitchMaker ( I installed praat on ubuntu with sudo apt-get install praat) and MCEPMaker fail.
./check_install_external_programs.sh -check detects no problem.
I changed db.estDir to the correct location.
When I try this things server is started.

on MCEP I get following error 
```
Computing Mel cepstra for [1132] utterances.
---- Calculating the Mel-Cepstrum coefficents...
arctic_a0001
/home/a/marytts/lib/Festival/speech_tools/bin/sig2fv: input file not accessible "/home/a/gguli/voicetest/pm/arctic_a0001.pm"
Type -h for help on options.
java.lang.Exception: The component MCEPMaker produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException: Mel-Cepstrum  computation failed on file [arctic_a0001]!
Command line was: [/home/a/marytts/lib/Festival/speech_tools/bin/sig2fv -window_type hamming -factor 2.5 -otype est_binary -coefs melcep -melcep_order 12 -fbank_order 24 -shift 0.01 -preemph 0.97 -pm /home/a/gguli/voicetest/pm/arctic_a0001.pm -o /home/a/gguli/voicetest/mcep/arctic_a0001.mcep /home/a/gguli/voicetest/wav/arctic_a0001.wav].
	at marytts.util.io.General.launchProc(General.java:549)
	at marytts.tools.voiceimport.ESTCaller.make_mcep(ESTCaller.java:253)
	at marytts.tools.voiceimport.MCEPMaker.compute(MCEPMaker.java:263)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

```

When I run praatPitchMaker I get following
![pp](https://user-images.githubusercontent.com/4594711/30269383-b5ece008-96f9-11e7-9279-496c6033c82c.png)

**Comment by psibre** [comment]
For praat, see e.g. #540 for a workaround.
The MCEPs require the pitchmarks, so if Praat can't run, the error is to be expected.
