### ISSUE TITLE
HMMVoiceMakeVoice failed during "initialization & reestimation"

### ISSUE THREAD

**Issue by topherseance** [marytts/marytts#810]
I've created a new language package for Javanese, it seems to be working properly (checked using MaryTTS's HTTP APIs)

Now I am in the process of building the voices.  
I have recorded 365 .wav files. All Mono, converted to 16k sample rate, duration ranging from 3s to 11s.  
Here's the `soxi` output of one:

    soxi jv_01_0023.wav
    Input File     : 'jv_01_0023.wav'
    Channels       : 1
    Sample Rate    : 16000
    Precision      : 16-bit
    Duration       : 00:00:06.34 = 101477 samples ~ 475.673 CDDA sectors
    File Size      : 203k
    Bit Rate       : 256k
    Sample Encoding: 16-bit Signed Integer PCM

I built a test voice using only 50 wav files (001 - 050). It has been built successfully. All processes succeeded until the last step 14: run HMMVoiceCompiler.  
Installed it on my local MaryTTS server, tested generating audio file.  
Worked fine but the resulting voice is rather bad (no surprise because only using 50 wav files).

However, when I build it using all 365 wav files, it does not work.  
Failed on step 13: HMMVoiceMakeVoice, precisely on phase "initialization & reestimation".
Resulting this error: (attached the full error logs on the bottom)

    Step: Start initialization & reestimation at Rab Sep 27 16:33:23 WIB 2017
	java.lang.Exception: The component HMMVoiceMakeVoice produced the following exception: 
		at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
	Caused by: java.lang.RuntimeException:  computation failed on file [/home/topher/Documents/MyMaryProjects/27_Sept_2017/jv-tia-09/]!
	Command line was: [/usr/bin/perl /home/topher/Documents/MyMaryProjects/27_Sept_2017/jv-tia-09/hts/scripts/Training.pl /home/topher/Documents/MyMaryProjects/27_Sept_2017/jv-tia-09/hts/scripts/Config.pm].
		at marytts.tools.voiceimport.HMMVoiceMakeVoice.launchProcWithLogFile(HMMVoiceMakeVoice.java:189)
		at marytts.tools.voiceimport.HMMVoiceMakeVoice.compute(HMMVoiceMakeVoice.java:127)
		at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

I also chunked those 365 wav files into multiple projects, 50 wav files each. The first 50 is successful, but the other 50 are failed.

So in total, I have those many projects, only 2 of them succeeded, first 50 and last 65.  
All others failed at the same step, HMMVoiceMakeVoice, during "initialization & reestimation".  

jv-tia-03, wav 001 - 050 ---> SUCCESS
jv-tia-04, wav 001 - 365 ---> FAILED
jv-tia-05, wav 001 - 100 ---> FAILED
jv-tia-06, wav 051 - 100 ---> FAILED
jv-tia-07, wav 101 - 150 ---> FAILED
jv-tia-08, wav 151 - 200 ---> FAILED
jv-tia-09, wav 201 - 250 ---> FAILED
jv-tia-10, wav 251 - 300 ---> FAILED
jv-tia-11, wav 300 - 365 ---> SUCCESS

I was thinking that maybe my wav files are causing the error, but could not figure out what is the problem.  
Can you help me on this? What is the rules / requirement for an ideal wav files?

Full outputs & logs (Gist):
[1. Console Output](https://gist.github.com/topherseance/912688c5cbe52a2c471605283e43345d)
[2. HMMVoiceMakeVoice log](https://gist.github.com/topherseance/09bc1a261ed3c3a556c507f8f805693a)
The second log file, `log-2017.09.27-16:33:23 ` seems truncated at the end, I don't know why, all the other logs of each failed projects are the same like this.

Will post the full project if you need another information.

**Comment by psibre** [comment]
Could you try building a unit-selection voice first and see if that works? It's possible that there are problems with some utterances, including but not limited to recording issues, pitch tracking, labeling, etc.

**Comment by fuzeller** [comment]
I would start by carefully checking that set of text files against the audio, to ensure transcription is accurate. That's the most common cause for this error that I've seen, and is often a simple word omission or word order problem (typically just two words transposed by the speaker). If that isn't the case, @psibre 's list includes the other likely areas. Audio clipping would be a recording issue to check.

Segmenting the problem as you have is certainly a wise move.

**Comment by topherseance** [comment]
Thank you for the insights, will try them soon.

**Comment by topherseance** [comment]
Hello, finally fixed the problem.

In my case, it was because my language / lexicon file was not sufficient enough to cover all words on the voice recordings.  
In other words, there are word utterances in the recording files that does not have its corresponding word transcription (SAMPA notation) on the lexicon file.

I've improved the lexicon, recompiled the language package, then again built the voice and everything works fine now.

Thank you for your attention.
