### ISSUE TITLE
RmsLsfDistortionComputer does not ignore middle field in lab files?

### ISSUE THREAD

**Issue by insa-k** [marytts/marytts#811]
## Expected behavior
```
arctic_a0013 mean 0.5915107457557739 stddev 0.3194935142519355
arctic_a0020 mean 0.6367271407550598 stddev 0.37502664096732546
arctic_a0034 mean 0.5849500984464054 stddev 0.3441694655939251
arctic_a0038 mean 0.6084262880942136 stddev 0.3407963440081972
arctic_a0047 mean 0.6417401684974685 stddev 0.35578445577529694
Global mean 0.6116912793904914 stddev 0.3475775872861927 
```
## Actual behavior
```
arctic_a0013 mean 0.0 stddev 0.0
arctic_a0020 mean 0.0 stddev 0.0
arctic_a0034 mean 0.0 stddev 0.0
arctic_a0038 mean 0.0 stddev 0.0
arctic_a0047 mean 0.0 stddev 0.0
Global mean 0.0 stddev 0.0 
```

## Steps to reproduce the behavior
execute 
``` main 'marytts.signalproc.analysis.distance.RmsLsfDistortionComputer' ```
with reference lab-files that look like this:
```
separator ;
nfields 1
#
     0.38 -1 _
     0.47 -1 n
     0.57 -1 A 
....
```
and lab-files that are synthesized with MaryTTS. So they're definitely different.

(or use the task ```runCrossvalidation``` in this [plugin](https://github.com/insa-k/gradle-marytts-crossvalidation-plugin) )

This way the ```RmsLsfDistortionComputer``` doesn't calculate the differences properly and I get the output described in **actual behaviour**. 

When I replace all ```-1``` with ```26``` in the reference lab files, I get the desired output described in **expected behaviour**.

**Comment by seblemaguer** [comment]
can you try now ?

**Comment by insa-k** [comment]
sorry, for commenting back so late. Yes, thanks, with the new jtgt-version it works now. 
But should we keep this issue open until we exactly know what caused this in `RmsLsfDistortionComputer`?

**Comment by psibre** [comment]
@insa-k Thanks for the feedback. @seblemaguer and/or I will fix the new jtgt release on Bintray ASAP.

In the meantime, the part of the issue that is related to the lab file parsing in marytts-signalproc, I think it's too obscure, and that module is not really maintained anyway, so I don't think it's worth keeping this issue open.
