### ISSUE TITLE
StringIndexOutOfBoundsException in Java 9

### ISSUE THREAD

**Issue by heruan** [marytts/marytts#812]
Code in `marytts-runtime` to detect Java version fails since it supposes `java.version` to be in the form `X.y` e.g. `1.8` but since JDK 9 `java.version` is just `9`.

```java
public class EnvironmentChecks {

	/**
	 * Check central requirements in the runtime environment of the system.
	 * 
	 * @throws Error
	 *             if any requirement is violated.
	 */
	public static void check() {
		// Java version
		String javaVersion = System.getProperty("java.version");
		if (Float.parseFloat(javaVersion.substring(0, 3)) < 1.499) {
			throw new Error("Wrong java version: Required 1.5, found " + javaVersion);
		}
    // ...
}
```
throws
```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116) ~[na:na]
	at java.base/java.lang.String.substring(String.java:1885) ~[na:na]
	at marytts.server.EnvironmentChecks.check(EnvironmentChecks.java:46) ~[marytts-runtime-5.2.jar!/:na]
```

**Comment by seblemaguer** [comment]
Normally it is solved in master but we haven't published the artifacts yet. Can you try wit the master branch ?

**Comment by heruan** [comment]
Great to hear that! I had no chance to try master yet. Is the master branch based on 6.x? I'm really looking forward to try 6.x too.

**Comment by seblemaguer** [comment]
no not yet. The changes are too big in the 6.x version and it is not ready to be considered as stable. Therefore we prefer to wait before pushing it to master

**Comment by heruan** [comment]
The master branch seems based on 6.x though, at least `pom.xml` reports version `6.0-SNAPSHOT`. How can I run MaryTTS under JDK 9 in production, until 6.0 release?

**Comment by psibre** [comment]
@heruan This issue was fixed along with #783 and should have been closed at the time.

Incidentally, the master branch builds with Gradle, not Maven, like it says in the README. The `pom.xml` are obsolete and need to be deleted. =)

**Comment by heruan** [comment]
Thank you @psibre, I missed that! I confirm that building `master` with Gradle works, although it still reports version `6.0-SNAPSHOT` and that's made me guess `master` was based on 6.x.

BTW it runs on JDK 9 and that's great! Hope to see a release/backport of JDK 9 support to use it in production.

**Comment by psibre** [comment]
Development on master is already working toward 6.0... but as long as the 6.x branch hasn't been merged, it's still backward compatible. We may decide to release another 5.x version, but I can't promise it yet.
