### ISSUE TITLE
best practice for recording training data

### ISSUE THREAD

**Issue by guliashvili** [marytts/marytts#816]
Hi,

I'm going to record training data for my language. 
I have several questions before I start recording voice.
1) Is there any preferred microphone for recording voice?
2) As I know MaryTTS needs 16 bit 1 channel wav file. Is it better to record 24 bit voice with more channels and then to reduce it with sox, or is it better just to record 16 bit 1 channel voice.
3) I can not make MaryTTS selector(from wikipedia) make work. Maybe it's the bug for Georgian wikipedia, what options do I have other then that to choose the transcript?

**Comment by psibre** [comment]
> 1. Is there any preferred microphone for recording voice?

A close-talking mic and a quiet, non-reverberating environment.

> 2. As I know MaryTTS needs 16 bit 1 channel wav file. Is it better to record 24 bit voice with more channels and then to reduce it with sox, or is it better just to record 16 bit 1 channel voice.

For the recording, it's advisable to get the best quality that's practical. 24 bit, 48 kHz is perfect. You'll need to convert it for MaryTTS, but at some point in the future, you can rebuild a your voice when MaryTTS supports higher-quality voice data than it presently does.

> 3. I can not make MaryTTS selector(from wikipedia) make work. Maybe it's the bug for Georgian wikipedia, what options do I have other then that to choose the transcript?

You can build a lexicon from a text resource. Please have a look at the various lexicon project repositories under https://github.com/marytts to see how we currently do this.
