### ISSUE TITLE
Transcribe most frequent words - MARY Transcription Tool

### ISSUE THREAD

**Issue by AlisonPQ** [marytts/marytts#818]
Hi, I need help!
I am building a language in MaryTTS 5.2, but I have stopped at the part of "Transcription Tool", I have 1932 words with their respective phonetic transcription this fact leads me to ask you the following:

1. What steps do I have to follow to enable the "Train and predict" button?
2. Do I need audios for each word? (since I have not reached the audios part)
3. What is the minimum text of the language do I need? How much audio do I need?
![mary-transcription-tool](https://user-images.githubusercontent.com/7606783/31742334-3ade9d7c-b425-11e7-9426-17fd67dda160.png)

Any charitable soul?

**Comment by psibre** [comment]
Please have a look at the lexicon projects, e.g.,

- [marytts-lexicon-de](/marytts/marytts-lexicon-de)
- [marytts-lexicon-fr](/marytts/marytts-lexicon-fr)
- [marytts-lexicon-lb](/marytts/marytts-lexicon-lb)

etc.

If you create a new repository on GitHub with the same project layout as those, but with your own content, it should be possible to quickly build the lexicon needed for everything else.
