### ISSUE TITLE
Reading the .pdf files produced in voice model

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#819]
Hello,

Is there a way to read the .pdf files(like dur.pdf, lf0.pdf) produced as the voice model? And also are there any ways of editing them?

Any help is much appreciated.

**Comment by psibre** [comment]
Have you tried [Adobe Acrobat Reader](https://get.adobe.com/reader/)?

**Comment by psibre** [comment]
:rofl: 

But seriously, these are literally the files created by HTS. You can check there, or in [marytts.cart.io.HTSCARTReader#loadPdfs](../blob/4bcf8bdf7a9c5ab137e84480a6df1d3726259939/marytts-runtime/src/main/java/marytts/cart/io/HTSCARTReader.java#L324-L360).

**Comment by jesinj** [comment]
Hey Thanks,

I shall have a look.
