### ISSUE TITLE
Server Respect For $PORT

### ISSUE THREAD

**Issue by sorvis** [marytts/marytts#821]
It seems like the port number for the service is hard coded. I'm trying to push a docker image of MarryTTS to heroku, but its not binding to the right port so it doesn't work. 

Are there any work around I could use to cause it to use the correct port when it runs?

**Comment by seblemaguer** [comment]
I have a preliminary question: how do you start the server in docker?

**Comment by psibre** [comment]
> It seems like the port number for the service is hard coded.

Only the *default* port is hard-coded. If you want a different port, please set the `socket.port` property.

**Comment by sorvis** [comment]
@seblemaguer  I'm using this docker file here:
```

FROM debian:jessie

MAINTAINER giulio.paci@mivoq.it

RUN apt-get -y update \
    && apt-get -y install curl \
    && curl -s http://repository.mivoq.it/mivoq.gpg.key | apt-key add - \
    && echo "deb http://repository.mivoq.it/repositories/apt/debian experimental main" > /etc/apt/sources.list.d/mivoq.list \
    && apt-get -y update \
    && apt-get -y install `apt-cache search '^marytts-voice-' | sed -e 's/ .*//' | grep -v marytts-voice-en-cmu-slt-hsmm` \
    && apt-get -y clean

EXPOSE 59125

CMD ["/usr/bin/marytts-server","--","-Dlog4j.logger.marytts=INFO,stderr"]
```
https://github.com/fic2/dockerfiles/blob/master/fatts/Dockerfile

@psibre Can that be set through an environment variable or does that have to be a config file?

**Comment by psibre** [comment]
`socket.port` is a Java property, so you set it by adding `-Dsocket.port=12345` (or whatever port) to your `CMD`.

**Comment by sorvis** [comment]
@psibre Thank you that works when I changed the execute command like this:

`CMD ["/usr/bin/marytts-server","--","-Dlog4j.logger.marytts=INFO,stderr", "-Dsocket.port=83"]`

Now I'm thinking about writing a bash script that will read from the PORT environment variable and I think it will work!
