### ISSUE TITLE
confused while creating alphones.xml file

### ISSUE THREAD

**Issue by neouyghur** [marytts/marytts#825]
Hi, I am creating allphones for the Uyghur language, which is very similar to the Turkish language. So I am adapting the Turkish allphones.xml to Uyghur language, however, in Turkish version, I found some characters like @ is very different from the definition of official [samba](http://www.phon.ucl.ac.uk/home/sampa/) and [samba Turkish](http://www.phon.ucl.ac.uk/home/sampa/turkish.htm). Should not we follow the definition of the official samba document? Thanks.

**Comment by psibre** [comment]
If Uyghur doesn't have a schwa (SAMPA `@`), then just leave it out of your `allophones.ug.xml` file.

Regarding the question why the schwa symbol appears in the Turkish allophone definition, I suspect it might have to do with the fact that the canonical SAMPA symbol `1` might have clashed with the Arpabet-style primary stress symbol `1` that was used in some MaryTTS modules at that time.

**Comment by neouyghur** [comment]
@psibre actully my language includes all of the phones of Turkish and other external 3 phones. So I keep the @ as it is.  However, I am wondering  can I decide ph variables myself, which are totally different from the samba standard? Thanks.

**Comment by psibre** [comment]
The `ph` attributes in the allophone set definition XML should not be "totally different" from the SAMPA *notation*, which is just a (mostly) ASCII representation for IPA symbols. They are motivated by [**distinctive features**](https://en.wikipedia.org/wiki/Distinctive_feature) in phonology and ultimately determine various aspects of linguistic processing (such as syllabification) and features.
