### ISSUE TITLE
can we use multiple female/male voices for generating a new voice

### ISSUE THREAD

**Issue by neouyghur** [marytts/marytts#828]
hi, I own a speech dataset. Although it is a big dataset, it includes many speakers and each of them at most have 100 sentences. I think 100 sentences are not adequate for high-quality voice. So I am wondering can I use multiple female/male voices for generating voices?  Do you guys have this kind of experience? What is the result? Thanks.

**Comment by psibre** [comment]
You can certainly try and see what happens. For unit-selection, I expect a multi-speaker voice will be completely unintelligible, or -- at best -- extremely creepy-sounding.

It might be possible to create some sort of *eigenvoice* and use this for statistical parametric synthesis, but that's nothing you could do with MaryTTS at the moment.

**Comment by seblemaguer** [comment]
Like @psibre said it is not available with marytts. However, you should have a look on the "speaker adaptation" area. You can use marytts as a front-end and then merlin or hts as a backend
