### ISSUE TITLE
Error on HmmVoiceCompiler

### ISSUE THREAD

**Issue by actarus33** [marytts/marytts#829]
Hello,

For test purpose i have tried to compile the artic voice. All steps were fine until the last one HMMVoiceCompiler where i get that error. Anyone can help me?

INFO  HMMVoiceCompiler: Creating directories
INFO  HMMVoiceCompiler: Copying template files
INFO  HMMVoiceCompiler: Copying voice files
INFO  HMMVoiceCompiler: Compiling with Maven
maven out>[INFO] Scanning for projects...
maven out>[ERROR] [ERROR] Some problems were encountered while processing the POMs:
maven out>[FATAL] Non-resolvable parent POM for de.dfki.mary:voice-sarah-hsmm:[unknown-version]: Failure to find de.dfki.mary:marytts:pom:5.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 10
maven out> @ 
maven out>[ERROR] The build could not read 1 project -> [Help 1]
maven out>[ERROR]   
maven out>[ERROR]   The project de.dfki.mary:voice-sarah-hsmm:[unknown-version] (/home/me/Bureau/voicetest/mary/voice-sarah-hsmm/pom.xml) has 1 error
maven out>[ERROR]     Non-resolvable parent POM for de.dfki.mary:voice-sarah-hsmm:[unknown-version]: Failure to find de.dfki.mary:marytts:pom:5.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 10 -> [Help 2]
maven out>[ERROR] 
maven out>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
maven out>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
maven out>[ERROR] 
maven out>[ERROR] For more information about the errors and possible solutions, please read the following articles:
maven out>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
maven out>[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
java.lang.Exception: The component HMMVoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:375)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:95)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

**Comment by psibre** [comment]
If you want to use the legacy voice import tools, please ensure that you have run `mvn install` first.

**Comment by actarus33** [comment]
Thank you for your answer. It's now resolved.
I was using the latest source code of marytts (migrated to gradle) with the voice builder version 5.2,
so mvn install was not working. 
I can now build the voice without any problem

**Comment by ingosiegert** [comment]
I'm stuck at the same error, I'm using marytts-builder-5.2 and HMMVoiceCompiler failed, when I want to call mvn install (
I got the following error:
`[ERROR] Invalid packaging for parent POM de.dfki.mary:marytts:5.2, must be "pom" but is "jar" @ de.dfki.mary:marytts:5.2
`` (calling mvn install -e -X in the voice-directory)

**Comment by psibre** [comment]
@ingosiegert I'm afraid we've moved beyond Maven... but the HMMVoiceCompiler (outdated like the rest of the legacy voice import tools) has not adapted.

What you want to do is package the resources required to run the HMM voice into a jar file, by making sure you they are included in the `main` sourceSet. Please arrange them in a layout like our other HMM voice projects. E.g., for [voice-dfki-spike-hsmm](https://github.com/marytts/voice-dfki-spike-hsmm),
```
$ tree src
src
└── main
    └── resources
        └── marytts
            └── voice
                └── DfkiSpikeHsmm
                    ├── dur.pdf
                    ├── gv-lf0-littend.pdf
                    ├── gv-mgc-littend.pdf
                    ├── gv-str-littend.pdf
                    ├── lf0.pdf
                    ├── mgc.pdf
                    ├── mix_excitation_filters.txt
                    ├── spi001.pfeats
                    ├── str.pdf
                    ├── tree-dur.inf
                    ├── tree-lf0.inf
                    ├── tree-mgc.inf
                    ├── tree-str.inf
                    └── trickyPhones.txt
```
In your `build.gradle`, you can apply
```gradle
plugins {
    id 'de.dfki.mary.voicebuilding-base' version '5.2.2'
}
```
and then customize the `config`. Continuing the example, in voice-dfki-spike-hsmm, this looks like:
```gradle
afterEvaluate {
    generateVoiceConfig {
        config << [
                alpha               : 0.42,
                gamma               : 0,
                logGain             : false,
                beta                : 0.2,
                Ftd                 : 'jar:/marytts/voice/DfkiSpikeHsmm/tree-dur.inf',
                Ftf                 : 'jar:/marytts/voice/DfkiSpikeHsmm/tree-lf0.inf',
                Ftm                 : 'jar:/marytts/voice/DfkiSpikeHsmm/tree-mgc.inf',
                Fts                 : 'jar:/marytts/voice/DfkiSpikeHsmm/tree-str.inf',
                Fmd                 : 'jar:/marytts/voice/DfkiSpikeHsmm/dur.pdf',
                Fmf                 : 'jar:/marytts/voice/DfkiSpikeHsmm/lf0.pdf',
                Fmm                 : 'jar:/marytts/voice/DfkiSpikeHsmm/mgc.pdf',
                Fms                 : 'jar:/marytts/voice/DfkiSpikeHsmm/str.pdf',
                useGV               : true,
                maxMgcGvIter        : 100,
                maxLf0GvIter        : 100,
                Fgvf                : 'jar:/marytts/voice/DfkiSpikeHsmm/gv-lf0-littend.pdf',
                Fgvm                : 'jar:/marytts/voice/DfkiSpikeHsmm/gv-mgc-littend.pdf',
                Fgvs                : 'jar:/marytts/voice/DfkiSpikeHsmm/gv-str-littend.pdf',
                FeaFile             : 'jar:/marytts/voice/DfkiSpikeHsmm/spi001.pfeats',
                trickyPhonesFile    : 'jar:/marytts/voice/DfkiSpikeHsmm/trickyPhones.txt',
                useMixExc           : true,
                Fif                 : 'jar:/marytts/voice/DfkiSpikeHsmm/mix_excitation_filters.txt',
                in                  : 5,
                useAcousticModels   : true,
                acousticModels      : 'duration F0',
                'duration.model'    : 'hmm',
                'duration.attribute': 'd',
                'F0.model'          : 'hmm',
                'F0.attribute'      : 'f0'
        ]
    }
}
```
Note that this will hopefully be streamlined very soon, when we have time to update the voicebuilding plugins.

**Comment by ingosiegert** [comment]
Yes, I noticed.

I successfully switched to the gradle voice building and could build the example voices there.

So I did not test the above solution
