### ISSUE TITLE
maven central version

### ISSUE THREAD

**Issue by supertick** [marytts/marytts#830]
Hello !
Thank you for your great project.
I'm curious when the release schedule to Maven Central will be.  It seems we work with a 5.1.2 version, but Maven Central is 5.0.  I was hoping to adjust our pom to the latest available in a public repo.
Thanks.

**Comment by psibre** [comment]
MaryTTS is published to JCenter, never to Maven Central. Please see the [readme](..#using-marytts-in-your-own-java-projects).
