### ISSUE TITLE
Own voice synthesis recognition

### ISSUE THREAD

**Issue by Avinash01111992** [marytts/marytts#832]
The two basic requirements for building a voice are:
a. Wave files
b. Corresponding Transcription (in MARY or Festvox Format):

In the above two requirements what exactly the Wave files contains , 
**And what exactly we  need to be recorded in the Wave files for voice training   ??**
**What exactly Transcription ??**

**Comment by psibre** [comment]
You need a set of recorded utterances for the target domain, and the orthographic representation of those utterances. You will also need phonetically aligned labels, which can be obtained through forced alignment.
Please have a look at the documentation on the [wiki](../wiki/VoiceImportToolsTutorial), and search through the [voicebuilding issues](../issues?utf8=%E2%9C%93&q=label%3Avoicebuilding) to get a better understanding of the steps, and potential pitfalls, involved.

**Comment by Avinash01111992** [comment]
Clarify one thing recording of utterances is really impractical ? or we need to record possible utterances?

**Comment by psibre** [comment]
Clarify the question?

**Comment by Avinash01111992** [comment]
As you mentioned above we need Set of recorded utterances for the target domain

My question is set of Recorded utterances are more specific to the target domain or its generic ?

**Comment by seblemaguer** [comment]
You need to have utterances from the same speaker which are covering enough baseline elements (generally diphone). I you to read documentation about TTS. You have plenty material here: https://synsig.org/index.php/Education
