### ISSUE TITLE
Building German voice

### ISSUE THREAD

**Issue by Poehli** [marytts/marytts#833]
Hi,
I'm trying to train a new german voice from an audiobook I bought. However I get stuck at the HMMVoiceCompiler step, because not enough phones could be labeled automagically, meaning it results in an error indicating, that no label for four phones could be found. I use about an hour of audio-data, which I split in length of about 3-10 sec, manually with the help of audacity. I was not expecting to get perfect results with that amount of data, but a result nevertheless. I was wondering, if the automatic labeling gives poor results because I use a language different from English. If so, what would be the way to go? If not, what am I missing?

I followed this tutorial:
https://github.com/marytts/marytts/wiki/HMMVoiceCreation.

**Comment by seblemaguer** [comment]
Hello,

is it no label for four phones or no instances for four labels? If the second one, you have to get instances (at least one) for each phone of German. Else the model is not going to be able to predict anything for these

**Comment by Poehli** [comment]
I am not quiet sure, what that means, so I give you an example:
The compiler sais, that I was missing audio for the phone „Oi“. So I checked if the audio files contained it and they did, after a few sentences I heard it multiple times, not surprisingly, since its a pretty commen phone. But the automatic labeler didn’t seem to pick it up, that‘s why I was wondering if it‘s because I use German and not english.

**Comment by seblemaguer** [comment]
The important is not really the audio in this case but the alignment. If the alignment doesn't contain any "Oi" the system cannot learn it. I think the alignment describe in this wiki page is indeed for english. I would try to use webmaus or something else to get the alighnment properly for german and then train the voice based on that.
