### ISSUE TITLE
How to add silence to utterances?

### ISSUE THREAD

**Issue by kkufova** [marytts/marytts#840]
Hi,
I'm using the following code in my application:

> `MaryInterface maryTTS = new LocalMaryInterface();`
> `AudioInputStream audio = maryTTS.generateAudio("text");`
> `AudioPlayer player = new AudioPlayer(audio);`
> `player.start();`
> `player.join();`

As I noticed that Mary talks very fast, I would like to add silences before each spoken utterance. What is the easiest way to do so? I am not using any configuration XML file.

**Comment by fuzeller** [comment]
@kkufova There are a few of ways, though I don't know if they're the best:

1) Edit /marytts/marytts-runtime/src/main/java/marytts/modules/acoustic/BoundaryModel.java
				element.setAttribute(targetAttributeName, "400"); (change "400" to something else.

2) I have also edited the user dictionary to add a crude solution before. 
- Assign a lexicon "word" that's not likely to be used as an actual word, like "silenceone", or "sssss"
- Add to the appropriate user dictionary:
silenceone | _
silencetwo | _ _
silencefive | _ _ _ _ _|
...
You can use the tag in parentheses if that makes it easier to see them in text (they're stripped off):

"Hello. (silencetwo) Welcome to the world of speech synthesis."

It would mean adding the pause reference into your text, but this is easy with a replace.

3) Create and add a CART for pauses.

There are probably better ways!

Good luck!

**Comment by psibre** [comment]
@fuzeller Interesting hacks, if they work, then by all means!

@kkufova MaryTTS is designed to work with markup to control prosody. So the "proper" way to do it is to create a minimal XML document that contains a `boundary` element where you want the silence, like this:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<boundary duration="800" />
Some text.
</maryxml>
```
The `duration` attribute sets the length of the silence in milliseconds.

In your code, you would call the `generateAudio(Document doc)` method, making sure to `setInputType("RAWMARYXML")` first.

**Comment by kkufova** [comment]
@psibre, does it mean that for every text I want to read I need to create a separate XML file?

**Comment by psibre** [comment]
No, for every text you want to synthesize **with prosody control**, you need to create a separate [Document](https://docs.oracle.com/javase/8/docs/api/org/w3c/dom/Document.html).

**Comment by kkufova** [comment]
@psibre, I'm here:

```
MaryInterface maryTTS = new LocalMaryInterface();
maryTTS.setVoice("dfki-prudence");
maryTTS.setInputType("RAWMARYXML");

Document document = MaryXML.newDocument();

Element maryXML = document.getDocumentElement();
maryXML.setAttribute("xml:lang", "en-US");

// ---
Element boundary = MaryXML.appendChildElement(maryXML, MaryXML.BOUNDARY);
boundary.setAttribute("duration", "2000");
// ---

Element paragraph = MaryXML.appendChildElement(maryXML, MaryXML.PARAGRAPH);
Element sentence = MaryXML.appendChildElement(paragraph, MaryXML.SENTENCE);
Element token = MaryXML.appendChildElement(sentence, MaryXML.TOKEN);
token.setTextContent(text);

MaryData maryData = new MaryData(MaryDataType.PHONEMES, Locale.ENGLISH, false);
maryData.setDocument(document);

AudioInputStream audio = maryTTS.generateAudio(document);
AudioPlayer player = new AudioPlayer(audio);
player.start();
player.join();
```
However, setting the boundary like that apparently does not work. How to set it properly?

**Comment by psibre** [comment]
The document you create is well-structured, but that's also what's getting in the way of your goal here... If you have paragraph and sentence elements, you need to append the boundary at a lower level. On the other hand, if you append only the boundary and the text node directly, the MaryXML parser internally inserts the paragraph and sentence elements at the right level.

This works:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<boundary duration="800" />
Some text.
</maryxml>
```
This does *not* work:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<boundary duration="800" />
<p>
<s>
<t>
Some text.
</t>
</s>
</p>
</maryxml>
```
This does work:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<boundary duration="800" />
<t>
Some text.
</t>
</s>
</p>
</maryxml>
```

**Comment by psibre** [comment]
Incidentally, the locale for the prudence voice is `en-GB`, although `en-US` still works.

Note also [various utility methods in marytts.util.dom.MaryDomUtils](../blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-runtime/src/main/java/marytts/util/dom/MaryDomUtils.java#L90-L177).

**Comment by kkufova** [comment]
@psibre, I fixed both things and everything works great! Thanks! :-) 

And @fuzeller, thank you very much for your quick help! :-)

**Comment by psibre** [comment]
@kkufova Glad to hear it's working. Have fun!
