### ISSUE TITLE
How to change voices in Java applications?

### ISSUE THREAD

**Issue by kkufova** [marytts/marytts#841]
Hi,
I have the following dependency in my `pom.xml` file:

> `<dependency>`
> `<groupId>de.dfki.mary</groupId>`
> `<artifactId>voice-cmu-slt-hsmm</artifactId>`
> `<version>5.2</version>`
> `</dependency>`

I would like to change the default voice to `voice-dfki-poppy` (or any other). How to do it? Changing the artifact ID does not work:

> `Failure to find de.dfki.mary:voice-dfki-poppy:jar:5.2`

What is the easiest way to do so? I'm not using any XML configuration file.

**Comment by psibre** [comment]
First of all, you're facing a dependency resolution problem. The unit-selection voices are not available on JCenter due to their size. You can however download them from GitHub, or install them using one of several other methods.

There's another pitfall with unit-selection voices: you'll need to unpack the zip files somewhere and set the `mary.base` property so that MaryTTS can locate those assets on the filesystem at startup.

**Comment by kkufova** [comment]
@psibre, I have the .zip file downloaded. Where exactly should I set the `mary.base` property?

**Comment by psibre** [comment]
```
Caused by: marytts.exceptions.NoSuchPropertyException: Cannot read file `./lib/voices/dfki-prudence/halfphoneFeatures_ac.mry'. Check property `voice.dfki-prudence.featureFile' in configuration files
```
The leading `.` in that file path is the `mary.base` property, so set it to wherever you have unzipped the file.

**Comment by kkufova** [comment]
Thanks, running the application with `-Dmary.base=/path/to/the/voice` helped.

Thank you for your quick responses! :-)

**Comment by psibre** [comment]
Great!

If for some reason you don't want to unpack all of the unit selection voice assets under a single directory (`MARY_BASE`), you could technically also set all of the properties directly:
```
voice.dfki-prudence.featureFile=/some/random/directory/for/dfki/prudence/halfphoneFeatures_ac.mry
voice.dfki-poppy.featureFile=/another/completely/different/directory/for/dfki/poppy/halfphoneFeatures_ac.mry
```
etc. But that's extremely hacky...
