### ISSUE TITLE
MaryTTS: Voice distorted completely when increasing volume

### ISSUE THREAD

**Issue by igorland** [marytts/marytts#844]
I am trying to implement the following code in a stand-alone application:

    `
    public static void main(String[] args) throws MaryConfigurationException 
    {
        
        String textPretakeoffEnglish = "Here goes my text";
                
		// init mary
		LocalMaryInterface mary = null;
        AudioPlayer ap = null;
      
		try 
        {
			mary = new LocalMaryInterface();
            ap = new AudioPlayer();
                        
            mary.setVoice("dfki-prudence-hsmm"); 
            //mary.setAudioEffects("JetPilot");
                        
            mary.setAudioEffects("Volume(amount:9.0)");
        } catch (MaryConfigurationException e) {
			System.err.println("Could not initialize MaryTTS interface: " + e.getMessage());
			throw e;
		}

		// synthesize
		AudioInputStream audio = null;
		try 
        {
			audio = mary.generateAudio(textPretakeoffEnglish);
            ap.setAudio(audio);
            ap.start();  
		} catch (SynthesisException e) {
			System.err.println("Synthesis failed: " + e.getMessage());
			System.exit(1);
		}
	}
`

1) Without this line
     
`mary.setAudioEffects("Volume(amount:9.0)");`

the speech is fine but quite. Therefore, I want to increase the volume. 
However, with that line added, the voice gets completely distorted, and I get a bunch of 

`Warning: signal amplitude out of range: -80755`

errors. The choice of voices has no impact. It happens to every hsmm voice I tried.

Am I doing something wrong? How do I increase the volume without deteriorating the voice quality?

2) Also, is it possible to use a unit voice without server? I keep on getting this error:

`Could not initialize MaryTTS interface: Cannot start MARY server
Exception in thread "main" marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at testspeech.TestSpeech.main(TestSpeech.java:159)
Caused by: java.lang.Exception: Problem starting module Synthesis
	at marytts.server.Mary.startModules(Mary.java:151)
	at marytts.server.Mary.startup(Mary.java:297)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 1 more
Caused by: marytts.exceptions.MaryConfigurationException: Cannot build unit selection voice 'cmu-rms'
	at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:218)
	at marytts.unitselection.UnitSelectionSynthesizer.startup(UnitSelectionSynthesizer.java:94)
	at marytts.modules.Synthesis.startupSynthesizers(Synthesis.java:73)
	at marytts.modules.Synthesis.startup(Synthesis.java:65)
	at marytts.server.Mary.startModules(Mary.java:149)
	... 5 more
Caused by: marytts.exceptions.NoSuchPropertyException: Cannot read file `./lib/voices/cmu-rms/halfphoneFeatures_ac.mry'. Check property `voice.cmu-rms.featureFile' in configuration files
	at marytts.server.MaryProperties.needFilename(MaryProperties.java:389)
	at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:107)
	... 9 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:371)
	at marytts.server.Mary$2.run(Mary.java:290)`

3) Lastly, is it possible to increase the volume of the JetPilot effect somehow? It is so quite...

Thanks a lot!

**Comment by psibre** [comment]
Like the online help for the Volume effect says,
```
Volume Effect:
Scales the output volume by a fixed amount.
Parameter:
   <amount>   Definition : Amount of scaling (the output is simply multiplied by amount)
   Range      : [0.0,10.0]
Example:
amount:2.0;
```
If you multiply by a large value like 9, then most samples will be clipped. Use it responsibly. =)

Regarding the unit-selection voices, you need to set the `mary.base` property to the directory under which you unzipped the voice files.

Changing the "loudness" of a voice properly at runtime is actually a missing feature... You could normalize your recordings before you build the voice, or your might try applying dynamic range compression or similar after the output has been synthesized.

**Comment by igorland** [comment]
Thanks a lot for your reply.

1) Yes, it is much better with the volume set at 2.
3) Understood. I will play with the dynamic range.

Regarding item 2, I tried to search for an example of how to set the property to the file directory using a Java code but I could not find any. There is no method or field like `setProperty()` or `property` to change. Could you please advise?

Thank you so much for your support!

**Comment by psibre** [comment]
I believe you need to add the system property at startup. This has been asked and solved [several times in the past](https://github.com/marytts/marytts/issues?utf8=%E2%9C%93&q=mary.base+).

**Comment by igorland** [comment]
Thank you so much, psibre. One more question if I may. I need to pronounce speech multiple times. So, I declared MaryInterface as a class variable. Now, I need to declare 

AudioPlayer ap = new AudioPlayer();

as a local variable in every method. 

`
public void say1()
    {
        // Make final variable to use in lambda
        final String finalAnnouncement = textPretakeoffEnglish;
        
        // Delay this utterance by a random number between 30 and 50 seconds
        ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
        int delay = 5;
        
        // Create a task for one-shot execution using schedule()
        Runnable task = () -> 
        {
            try
            {
                AudioInputStream audio = marytts.generateAudio(finalAnnouncement);
                AudioPlayer ap = new AudioPlayer(); // HERE; IF AudioPlayer is made a class variable, it is not working more than once

                ap.setAudio(audio);
                ap.start();
            }
            catch (SynthesisException ex)
            {
                System.err.println("Error saying phrase.");
            }
            
            System.out.println("ANNOUNCEMENT TASK RUNNING");
        };
        
        executorService.schedule(task, delay, TimeUnit.SECONDS);
        executorService.shutdown();
        
    }
`

If I declare it as a class variable, it only works once and there is no speech the other times. I have no problem with that. My question is: once the method finishes, does AudioPlayer close all tasks so that no file descriptors are accumulating every time I create speech. How about the instance of AudioInputStream? Should I explicitly close the stream?

Thanks a lot!

**Comment by seblemaguer** [comment]
Hello, the problem is that the AudioPlayer class is subclassing the class Thread. A thread can't be restarted. As far as I see on the source code (see https://github.com/marytts/marytts/blob/master/marytts-signalproc/src/main/java/marytts/util/data/audio/AudioPlayer.java )  all the cleaning is done at the end of the method run

**Comment by igorland** [comment]
Great! Thank you so much!
