### ISSUE TITLE
How to install MaryTTS

### ISSUE THREAD

**Issue by victorlysak** [marytts/marytts#845]
Hi.
I am exploring ways to create a new voice using marytts.
Could someone, please, give me instructions, step-by-step, of how to install marytts on eclipse oxygen in Win 7 64?
I tried to follow the instructions here:
https://github.com/marytts/marytts/wiki/Eclipse_6.X
but it does not work.
I does not run a server.

thank you

**Comment by psibre** [comment]
First of all, are you planning to do *development* on/with MaryTTS? Or just **install** it to use it?

Because there's a lightweight [marytts-installer](https://github.com/marytts/marytts-installer) that should be really easy to use.

If you want to **develop** MaryTTS in Eclipse, it totally depends on whether you're working with the 5.x branch or the master branch. The former should be imported as a Maven project, while the master branch is built using Gradle.

> but it does not work.

Please explain what the problem is.

**Comment by victorlysak** [comment]
Thank you for the reply.
I am planning to create a new voice. with MaryTTS.

For this I installed ecliplse oxygen.
Than I installed all other staff as explained in the instructions that I followed but when I tryied to created new java application Mary, I could not select a marytts.server because it is not there.
![image](https://user-images.githubusercontent.com/35852534/35766487-a9a5385a-08d1-11e8-83a1-ffb3e3f4fe61.png)

**Comment by victorlysak** [comment]
this is what i have now
![image](https://user-images.githubusercontent.com/35852534/35766505-f66e5284-08d1-11e8-84fa-0c304fe602e4.png)

**Comment by psibre** [comment]
You don't need to install MaryTTS to build a voice -- you can use either the [Gradle voicebuilding plugin](https://github.com/marytts/gradle-marytts-voicebuilding-plugin) or the legacy VoiceImportTools as documented in the wiki.
The former is what we use to build our voices, just have a look at the various voice-* repositories under https://github.com/marytts. It's still incubating and not very well documented, but you can have a look at [these slides](http://www.coli.uni-saarland.de/~steiner/teaching/2016/winter/voicebuilding/slides/).

**However**, some of the third-party tools are tricky to get to work under Windows, so you should build your voice under Linux or Mac OSX.

None of the above requires Eclipse.

**Comment by victorlysak** [comment]
Thank you for the reply.

This means, if I don't have Windows, I cannot build my own voice?
Or.
How can I do this in Win 7 64?
If I take this  Gradle voicebuilding plugin , what do I plug it in? And how do I start at all?
thank you.

**Comment by victorlysak** [comment]
Now,
according to the guide, in step 2 I should run git clone .....
When I do, it says : git is not recognised as command.
what is git?
how do I get it into my machine?

thank you.

**Comment by psibre** [comment]
> This means, if I don't have Windows, I cannot build my own voice?
Or.
How can I do this in Win 7 64?

Like I said above, it's tricky. So if you don't know what you're doing, don't even try under Windows.

>  what is git?

**The thing for which this website is the hub!**
But seriously: http://lmgtfy.com/?q=git

**Comment by victorlysak** [comment]
Thank you.
I am downloading git......
so far, I have all the soft in the step 1.
I have also installed marytts 5.2 and it works, as I can run the server and then the client and I can install all voices.
I will report further.
thank you

**Comment by victorlysak** [comment]
So, I've installed the git and ran the following:
./gradlew legacyInit
./gradlew build

and the result is on the picture. 
the question is: can I go further or do I have to have a success on this build?
![image](https://user-images.githubusercontent.com/35852534/35772058-748df388-092f-11e8-8858-601d45f9663b.png)

**Comment by psibre** [comment]
> and the result is : both failed.

That's not really helpful. Please be specific if you expect assistance.

**Comment by victorlysak** [comment]
Well. I am trying to follow the instructions that are on the page you sent me the link.
That is:
1. Install software dependencies (as needed)
Praat
SoX
Edinburgh Speech Tools

I've downloaded and unpacked all these tools.
then, step
2. Clone voicebuilding project :
git clone https://github.com/marytts/voice-cmu-slt -b v5.2
cd voice-cmu-slt
... this is done

The next step says:
./gradlew legacyInit

this step failed. Here is picture why:
![image](https://user-images.githubusercontent.com/35852534/35772412-353ca150-0936-11e8-934d-51102f63b94a.png)

**Comment by psibre** [comment]
```
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
Please do.

**Comment by victorlysak** [comment]
Well, it says something :
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:197)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:327)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
        ... 2 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'sox'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
        ... 2 more
Caused by: java.io.IOException: Cannot run program "sox" (in directory "E:\Victor\ttstest\marytts\gradle-marytts-voicebuilding-plugin-master\voice-cmu-slt"): CreateProcess error=2, The system cannot find the file specified
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 5 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        ... 6 more

BUILD FAILED

Total time: 2.942 secs

Does this mean, that I have to put my sox into that directory and the whole folder ???
thank you.

**Comment by victorlysak** [comment]
OK. I have success on this now.
I have moved all the files from the sox folder to "voice-cmu-slt"
and then I also moved the Praat.exe to "voice-cmu-slt".
I think this had to be said in the instructions. :) 
I carry on........

**Comment by psibre** [comment]
The binaries are assumed to be on your `PATH` if the packages are installed. This is apparently not the case for your Windows.

**Comment by victorlysak** [comment]
No, it is not.
I start a project and I create a folder for it and then I pack everything into that folder.
Later, if I don't need it, simply remove that folder from my machine and it is clean.
That is the case.
....
so I have now build failed again
I'll try to sort it out and report.

thnak you.

**Comment by victorlysak** [comment]
it says:
        at marytts.util.io.General.launchProc(General.java:549)
        at marytts.tools.voiceimport.PraatPitchmarker.compute(PraatPitchmarker.java:294)
        at marytts.tools.voiceimport.DatabaseImportMain.main(DatabaseImportMain.java:428)
:legacyPraatPitchmarker FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':legacyPraatPitchmarker'.
> Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_161\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':legacyPraatPitchmarker'.

WHAT IS  ':legacyPraatPitchmarker' ?
thank you.

**Comment by psibre** [comment]
What version of Praat are you using?

**Comment by victorlysak** [comment]
I don't know :) , actually it's 6.0.36
but I found in debug this:
23:55:40.651 [ERROR] [org.gradle.BuildExceptionReporter]
23:55:40.651 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
23:55:40.651 [ERROR] [org.gradle.BuildExceptionReporter]
23:55:40.651 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
23:55:40.651 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':legacyPraatPitchmarker'.
23:55:40.652 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_161\bin\java.exe'' finished with non-zero exit value 1
23:55:40.652 [ERROR] [org.gradle.BuildExceptionReporter]
23:55:40.652 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
23:55:40.652 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.

does it mean that I should make a path to that praat?

**Comment by psibre** [comment]
What's the `PraatPitchmarker.command` in your `build/database.config`?

**Comment by victorlysak** [comment]
Yes. I found it here:
---

# Properties for module PraatPitchmarker:
PraatPitchmarker.command praat --run
PraatPitchmarker.maxPitch 500
PraatPitchmarker.minPitch 100
PraatPitchmarker.pmDir E:\Victor\ttstest\marytts\gradle-marytts-voicebuilding-plugin-master\voice-cmu-slt\build/pm/
PraatPitchmarker.waveDir E:\Victor\ttstest\marytts\gradle-marytts-voicebuilding-plugin-master\voice-cmu-slt\build/wav/
---

No. It is simply does not recognise praat.
On praat side I have only one Praat.exe file and nothing else. that's what I downloaded.
Shell I look for smth else?
Here:
00:07:05.464 [ERROR] [system.err] 'praat' is not recognized as an internal or external command,

maybe I try to copy praat to those folder in the config and run?

**Comment by psibre** [comment]
You could try upgrading the voicebuilding plugin to the newest version (v5.3.2), which may or may not solve the Praat issue.

But I *really* recommend you try to build a voice under Linux. All of these problems so far are due to Windows. I'm afraid I can't help you further with that.

**Comment by victorlysak** [comment]
I have created 3 more copies of praat.exe and put them in 
build/
build/pm/
build/wav/
and it now runs and outputs something like:
00:21:12.352 [QUIET] [system.out] arctic_b0246
00:21:12.692 [QUIET] [system.out] arctic_b0247
00:21:13.163 [QUIET] [system.out] arctic_b0248
00:21:13.425 [QUIET] [system.out] arctic_b0249
00:21:13.621 [QUIET] [system.out] arctic_b0250
00:21:13.902 [QUIET] [system.out] arctic_b0251
00:21:14.210 [QUIET] [system.out] arctic_b0252

looks all right

**Comment by victorlysak** [comment]
I have also down loaded festival. 
Do you know where does that go?

thank you.

**Comment by psibre** [comment]
At this point, I really believe you're wasting your time. Please take my advice and build under Linux.
