### ISSUE TITLE
transcription.sh

### ISSUE THREAD

**Issue by tarasfrompir** [marytts/marytts#846]
why can I process only 100,000 words.  I have 3 million words.

**Comment by psibre** [comment]
Could you please explain what you're doing, and what the unexpected thing is that presumably happens?

**Comment by tarasfrompir** [comment]
I have a dictionary with a transcription of 3000000 words. 
When importing this dictionary, an error occurs in the script.
So I can not fully download an existing dictionary for training and getting data from this dictionary.
So the question arises - how many words with transcription i can be used in the dictionary for his training?
Sorry for my English.

**Comment by psibre** [comment]
Thanks for the details.
I've never used the transcription with a lexicon that big -- the biggest one we have used is the Italian one, with just over 400k entries. But with the current state of the lexicon compiler, even a few hundred thousand entries should be more than enough.
So maybe just try with a smaller lexicon first?

**Comment by tarasfrompir** [comment]
I agree, but do I have all the possible words and their correct transcription, or is there no need for instruction in a large dictionary?

**Comment by psibre** [comment]
I don't believe in storing "all possible words".

The lexicon is designed to store a statistical model, which can provide the lexicon entries used for training, and predict the pronunciation of any word *not* in the lexicon. So if you train on a subset of your big dictionary and test on a different subset, the pronunciations in the test set should be more or less correct.
