### ISSUE TITLE
*** glibc detected *** java: double free or corruption (!prev): 0x09f013c0 ***

### ISSUE THREAD

**Issue by AGWeb09** [marytts/marytts#848]
I'm following the guide to install MaryTTS on a ubuntu 12.04 machine but when I reach this command

> sudo -u mary /local/mary/marytts/target/marytts-5.2/bin/marytts-server

I always receive this error message. Looking around for a solution but can't find anyone. Any advice?

> 
> java version "1.6.0_41"
> OpenJDK Runtime Environment (IcedTea6 1.13.13) (6b41-1.13.13-0ubuntu0.12.04.1)
> OpenJDK Server VM (build 23.41-b41, mixed mode)
> 
> *** glibc detected *** java: double free or corruption (!prev): 0x09f013c0 ***
> ======= Backtrace: =========
> /lib/i386-linux-gnu/libc.so.6(+0x74fd2)[0xb7632fd2]
> /usr/lib/jvm/java-6-openjdk-i386/jre/bin/../lib/i386/jli/libjli.so(JLI_MemFree+0x1d)[0xb776ef8d]
> java[0x804b805]
> java(JavaMain+0x42b)[0x804bd1b]
> /lib/i386-linux-gnu/libpthread.so.0(+0x6d4c)[0xb7779d4c]
> /lib/i386-linux-gnu/libc.so.6(clone+0x5e)[0xb76ace8e]
> ======= Memory map: ========
> 08048000-08051000 r-xp 00000000 08:01 2230903    /usr/lib/jvm/java-6-openjdk-i386/jre/bin/java
> 08051000-08052000 r--p 00008000 08:01 2230903    /usr/lib/jvm/java-6-openjdk-i386/jre/bin/java
> 08052000-08053000 rw-p 00009000 08:01 2230903    /usr/lib/jvm/java-6-openjdk-i386/jre/bin/java
> 09eff000-09f20000 rw-p 00000000 00:00 0          [heap]
> 675dd000-675de000 ---p 00000000 00:00 0
> 675de000-6765e000 rw-p 00000000 00:00 0          [stack:6981]
> 6765e000-67661000 ---p 00000000 00:00 0
> 67661000-676af000 rw-p 00000000 00:00 0          [stack:6980]
> 676af000-676b2000 ---p 00000000 00:00 0
> 676b2000-67730000 rw-p 00000000 00:00 0          [stack:6979]
> 67730000-67733000 ---p 00000000 00:00 0
> 67733000-677b1000 rw-p 00000000 00:00 0          [stack:6978]
> 677b1000-677b4000 ---p 00000000 00:00 0
> 677b4000-67802000 rw-p 00000000 00:00 0          [stack:6977]
> 67802000-67a02000 r--p 00000000 08:01 29891193   /usr/lib/locale/locale-archive
> 67a02000-67a05000 ---p 00000000 00:00 0
> 67a05000-67a53000 rw-p 00000000 00:00 0          [stack:6976]
> 67a53000-67a56000 ---p 00000000 00:00 0
> 67a56000-67aa4000 rw-p 00000000 00:00 0          [stack:6975]
> 67aa4000-67aa5000 ---p 00000000 00:00 0
> 67aa5000-67b25000 rw-p 00000000 00:00 0          [stack:6974]
> 67b25000-67cc0000 r--s 01a69000 08:01 2230912    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/rt.jar
> 67cc0000-6ac00000 rw-p 00000000 00:00 0
> 6ac00000-6ac21000 rw-p 00000000 00:00 0
> 6ac21000-6ad00000 ---p 00000000 00:00 0
> 6ad00000-6ad88000 rw-p 00000000 00:00 0
> 6ad88000-6ae00000 ---p 00000000 00:00 0
> 6ae00000-6ae21000 rw-p 00000000 00:00 0
> 6ae21000-6af00000 ---p 00000000 00:00 0
> 6af33000-6af67000 rw-p 00000000 00:00 0
> 6af67000-6af68000 ---p 00000000 00:00 0
> 6af68000-6afe8000 rw-p 00000000 00:00 0          [stack:6973]
> 6afe8000-6afe9000 ---p 00000000 00:00 0
> 6afe9000-6b071000 rw-p 00000000 00:00 0          [stack:6972]
> 6b071000-6b0a9000 rw-p 00000000 00:00 0
> 6b0a9000-6b0b7000 rw-p 00000000 00:00 0
> 6b0b7000-6b1ff000 rw-p 00000000 00:00 0
> 6b1ff000-6b207000 rw-p 00000000 00:00 0
> 6b207000-6b23f000 rw-p 00000000 00:00 0
> 6b23f000-6b24d000 rw-p 00000000 00:00 0
> 6b24d000-6b394000 rw-p 00000000 00:00 0
> 6b394000-6b39b000 rw-p 00000000 00:00 0
> 6b39b000-6b43f000 rw-p 00000000 00:00 0
> 6b43f000-6c440000 rw-p 00000000 00:00 0
> 6c440000-73440000 rw-p 00000000 00:00 0
> 73440000-74ef0000 rw-p 00000000 00:00 0
> 74ef0000-9def0000 rw-p 00000000 00:00 0
> 9def0000-9ec40000 rw-p 00000000 00:00 0
> 9ec40000-b3440000 rw-p 00000000 00:00 0
> b3440000-b3449000 rw-p 00000000 00:00 0
> b3449000-b3500000 rw-p 00000000 00:00 0
> b3500000-b3740000 rwxp 00000000 00:00 0
> b3740000-b65f3000 rw-p 00000000 00:00 0
> b65f3000-b6600000 ---p 00000000 00:00 0
> b6631000-b663b000 r-xp 00000000 08:01 25694351   /lib/i386-linux-gnu/libnss_files-2.15.so
> b663b000-b663c000 r--p 00009000 08:01 25694351   /lib/i386-linux-gnu/libnss_files-2.15.so
> b663c000-b663d000 rw-p 0000a000 08:01 25694351   /lib/i386-linux-gnu/libnss_files-2.15.so
> b663d000-b6647000 r-xp 00000000 08:01 25690230   /lib/i386-linux-gnu/libnss_nis-2.15.so
> b6647000-b6648000 r--p 00009000 08:01 25690230   /lib/i386-linux-gnu/libnss_nis-2.15.so
> b6648000-b6649000 rw-p 0000a000 08:01 25690230   /lib/i386-linux-gnu/libnss_nis-2.15.so
> b6649000-b665f000 r-xp 00000000 08:01 25690239   /lib/i386-linux-gnu/libnsl-2.15.so
> b665f000-b6660000 r--p 00015000 08:01 25690239   /lib/i386-linux-gnu/libnsl-2.15.so
> b6660000-b6661000 rw-p 00016000 08:01 25690239   /lib/i386-linux-gnu/libnsl-2.15.so
> b6661000-b6663000 rw-p 00000000 00:00 0
> b6663000-b666a000 r-xp 00000000 08:01 25694213   /lib/i386-linux-gnu/libnss_compat-2.15.so
> b666a000-b666b000 r--p 00006000 08:01 25694213   /lib/i386-linux-gnu/libnss_compat-2.15.so
> b666b000-b666c000 rw-p 00007000 08:01 25694213   /lib/i386-linux-gnu/libnss_compat-2.15.so
> b666c000-b6674000 r-xp 00000000 08:01 2230925    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libzip.so
> b6674000-b6675000 r--p 00007000 08:01 2230925    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libzip.so
> b6675000-b6676000 rw-p 00008000 08:01 2230925    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libzip.so
> b6676000-b667e000 rw-s 00000000 08:01 12582930   /tmp/hsperfdata_mary/6970
> b667e000-b66a6000 r-xp 00000000 08:01 2230954    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libjava.so
> b66a6000-b66a7000 r--p 00027000 08:01 2230954    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libjava.so
> b66a7000-b66a9000 rw-p 00028000 08:01 2230954    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libjava.so
> b66a9000-b66b0000 r-xp 00000000 08:01 25690232   /lib/i386-linux-gnu/librt-2.15.so
> b66b0000-b66b1000 r--p 00006000 08:01 25690232   /lib/i386-linux-gnu/librt-2.15.so
> b66b1000-b66b2000 rw-p 00007000 08:01 25690232   /lib/i386-linux-gnu/librt-2.15.so
> b66b2000-b66b5000 ---p 00000000 00:00 0
> b66b5000-b6703000 rw-p 00000000 00:00 0          [stack:6971]
> b6703000-b671f000 r-xp 00000000 08:01 25691041   /lib/i386-linux-gnu/libgcc_s.so.1
> b671f000-b6720000 r--p 0001b000 08:01 25691041   /lib/i386-linux-gnu/libgcc_s.so.1
> b6720000-b6721000 rw-p 0001c000 08:01 25691041   /lib/i386-linux-gnu/libgcc_s.so.1
> b6721000-b674b000 r-xp 00000000 08:01 25694352   /lib/i386-linux-gnu/libm-2.15.so
> b674b000-b674c000 r--p 00029000 08:01 25694352   /lib/i386-linux-gnu/libm-2.15.so
> b674c000-b674d000 rw-p 0002a000 08:01 25694352   /lib/i386-linux-gnu/libm-2.15.so
> b674d000-b6825000 r-xp 00000000 08:01 29889494   /usr/lib/i386-linux-gnu/libstdc++.so.6.0.16
> b6825000-b6826000 ---p 000d8000 08:01 29889494   /usr/lib/i386-linux-gnu/libstdc++.so.6.0.16
> b6826000-b682a000 r--p 000d8000 08:01 29889494   /usr/lib/i386-linux-gnu/libstdc++.so.6.0.16
> b682a000-b682b000 rw-p 000dc000 08:01 29889494   /usr/lib/i386-linux-gnu/libstdc++.so.6.0.16
> b682b000-b6832000 rw-p 00000000 00:00 0
> b6832000-b712f000 r-xp 00000000 08:01 2230943    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/server/libjvm.so
> b712f000-b7176000 r--p 008fc000 08:01 2230943    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/server/libjvm.so
> b7176000-b718a000 rw-p 00943000 08:01 2230943    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/server/libjvm.so
> b718a000-b75a8000 rw-p 00000000 00:00 0
> b75a8000-b75bc000 r-xp 00000000 08:01 25691131   /lib/i386-linux-gnu/libz.so.1.2.3.4
> b75bc000-b75bd000 r--p 00013000 08:01 25691131   /lib/i386-linux-gnu/libz.so.1.2.3.4
> b75bd000-b75be000 rw-p 00014000 08:01 25691131   /lib/i386-linux-gnu/libz.so.1.2.3.4
> b75be000-b7761000 r-xp 00000000 08:01 25690237   /lib/i386-linux-gnu/libc-2.15.so
> b7761000-b7763000 r--p 001a3000 08:01 25690237   /lib/i386-linux-gnu/libc-2.15.so
> b7763000-b7764000 rw-p 001a5000 08:01 25690237   /lib/i386-linux-gnu/libc-2.15.so
> b7764000-b7767000 rw-p 00000000 00:00 0
> b7767000-b776a000 r-xp 00000000 08:01 25690229   /lib/i386-linux-gnu/libdl-2.15.so
> b776a000-b776b000 r--p 00002000 08:01 25690229   /lib/i386-linux-gnu/libdl-2.15.so
> b776b000-b776c000 rw-p 00003000 08:01 25690229   /lib/i386-linux-gnu/libdl-2.15.so
> b776c000-b7770000 r-xp 00000000 08:01 2230934    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/jli/libjli.so
> b7770000-b7771000 r--p 00003000 08:01 2230934    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/jli/libjli.so
> b7771000-b7772000 rw-p 00004000 08:01 2230934    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/jli/libjli.so
> b7772000-b7773000 rw-p 00000000 00:00 0
> b7773000-b778a000 r-xp 00000000 08:01 25690240   /lib/i386-linux-gnu/libpthread-2.15.so
> b778a000-b778b000 r--p 00016000 08:01 25690240   /lib/i386-linux-gnu/libpthread-2.15.so
> b778b000-b778c000 rw-p 00017000 08:01 25690240   /lib/i386-linux-gnu/libpthread-2.15.so
> b778c000-b778f000 rw-p 00000000 00:00 0
> b778f000-b7790000 r--p 00859000 08:01 29891193   /usr/lib/locale/locale-archive
> b7790000-b7791000 rw-p 00000000 00:00 0
> b7791000-b7792000 r--p 00000000 00:00 0
> b7792000-b779e000 r-xp 00000000 08:01 2230931    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libverify.so
> b779e000-b779f000 r--p 0000b000 08:01 2230931    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libverify.so
> b779f000-b77a0000 rw-p 0000c000 08:01 2230931    /usr/lib/jvm/java-6-openjdk-i386/jre/lib/i386/libverify.so
> b77a0000-b77a2000 rw-p 00000000 00:00 0
> b77a2000-b77a3000 r-xp 00000000 00:00 0          [vdso]
> b77a3000-b77c3000 r-xp 00000000 08:01 25691179   /lib/i386-linux-gnu/ld-2.15.so
> b77c3000-b77c4000 r--p 0001f000 08:01 25691179   /lib/i386-linux-gnu/ld-2.15.so
> b77c4000-b77c5000 rw-p 00020000 08:01 25691179   /lib/i386-linux-gnu/ld-2.15.so
> bfeeb000-bfeec000 rwxp 00000000 00:00 0
> bff1e000-bff3f000 rw-p 00000000 00:00 0          [stack]
> /local/mary/marytts/target/marytts-5.2/bin/marytts-server: riga 11:  6970 Annullato               (core dump creato) java -showversion -Xms40m -Xmx1g -cp "$MARY_BASE/lib/*" -Dmary.base="$MARY_BASE" $* marytts.server.Mary

**Comment by psibre** [comment]
The last release version of MaryTTS that ran on Java 6 was 5.0 (2012). Incidentally, Ubuntu 12.4 is also EOL. I suggest you try with a supported Java version on a supported OS.
