### ISSUE TITLE
 Cannot start MARY serve

### ISSUE THREAD

**Issue by Nisreenelhassan** [marytts/marytts#849]
i tried to build marytts, this is my error 
i used marytts-5x
eclipse 9 and jdk8 
apache maven version 3.5.2 

Reactor Summary:
[INFO]
[INFO] MaryTTS ............................................ SUCCESS [ 14.084 s]
[INFO] marytts-common ..................................... SUCCESS [ 20.819 s]
[INFO] marytts-signalproc ................................. SUCCESS [ 18.392 s]
[INFO] marytts-runtime .................................... SUCCESS [ 46.451 s]
[INFO] marytts-lang-de .................................... SUCCESS [  5.452 s]
[INFO] marytts-lang-en .................................... FAILURE [  6.627 s]
[INFO] marytts-lang-te .................................... SKIPPED
[INFO] marytts-lang-tr .................................... SKIPPED
[INFO] marytts-lang-ru .................................... SKIPPED
[INFO] marytts-lang-it .................................... SKIPPED
[INFO] marytts-lang-fr .................................... SKIPPED
[INFO] marytts-lang-sv .................................... SKIPPED
[INFO] marytts-lang-lb .................................... SKIPPED
[INFO] marytts-languages .................................. SKIPPED
[INFO] voice-cmu-slt-hsmm ................................. SKIPPED
[INFO] marytts-client ..................................... SKIPPED
[INFO] marytts-builder .................................... SKIPPED
[INFO] marytts-redstart ................................... SKIPPED
[INFO] marytts-transcription .............................. SKIPPED
[INFO] marytts-assembly-builder ........................... SKIPPED
[INFO] marytts-assembly-runtime ........................... SKIPPED
[INFO] marytts-assembly ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:52 min
[INFO] Finished at: 2018-02-24T19:30:58+03:00
[INFO] Final Memory: 16M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project marytts-lang-en: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\HP\Desktop\marytts\marytts-languages\marytts-lang-en\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :marytts-lang-en

**Comment by seblemaguer** [comment]
Hello,

you should not use maven but gradle. The maven is there for website back compatibility but is going to disappear.

**Comment by Nisreenelhassan** [comment]
thank you so much it's worked now and build successful,now I will go to the second step to build for a new language :)
