### ISSUE TITLE
Data too long for column 'rev_comment'

### ISSUE THREAD

**Issue by sbalasis** [marytts/marytts#851]
Greetings,

I am trying to build a new language (greek) for mary but i seem to be stuck in the wikipedia markup cleaning text. My issue is that rev_comment column is small. From what i can understand is that i need to change rev_comment column creation from tinyblob to large. This is done in DBHandler.java inside package marytts.tools.dbselection.WikipediaProcessor. My issue is that i cannot compile the newly modified DBHandler.java file in order the changes to be applied. Can you please provide a detailed guide on how to do this?

Many thanks in advance,
stbal.

**Comment by sbalasis** [comment]
Also the output of my compilation of DBHandler.java

stbal@stbal-Lenovo-Z50-70:/local/mary/marytts/marytts-builder/src/main/java/marytts/tools/dbselection$ javac DBHandler.java
DBHandler.java:45: error: package marytts.util does not exist
import marytts.util.Pair;
                   ^
DBHandler.java:46: error: package marytts.util.io does not exist
import marytts.util.io.FileUtils;
                      ^
DBHandler.java:48: error: package org.mediawiki.importer does not exist
import org.mediawiki.importer.DumpWriter;
                             ^
DBHandler.java:49: error: package org.mediawiki.importer does not exist
import org.mediawiki.importer.SqlServerStream;
                             ^
DBHandler.java:50: error: package org.mediawiki.importer does not exist
import org.mediawiki.importer.SqlStream;
                             ^
DBHandler.java:51: error: package org.mediawiki.importer does not exist
import org.mediawiki.importer.SqlWriter;
                             ^
DBHandler.java:52: error: package org.mediawiki.importer does not exist
import org.mediawiki.importer.SqlWriter15;
                             ^
DBHandler.java:53: error: package org.mediawiki.importer does not exist
import org.mediawiki.importer.XmlDumpReader;
                             ^
DBHandler.java:1193: error: cannot find symbol
	public Pair<int[], byte[][]> getIdsAndFeatureVectors(String table, String condition) {
	       ^
  symbol:   class Pair
  location: class DBHandler
DBHandler.java:243: error: cannot find symbol
			SqlStream sqlStream = new SqlServerStream(wikiDB.cn);
			^
  symbol:   class SqlStream
  location: class DBHandler
DBHandler.java:243: error: cannot find symbol
			SqlStream sqlStream = new SqlServerStream(wikiDB.cn);
			                          ^
  symbol:   class SqlServerStream
  location: class DBHandler
DBHandler.java:244: error: cannot find symbol
			DumpWriter sqlWriter = new SqlWriter15(new SqlWriter.MySQLTraits(), sqlStream);
			^
  symbol:   class DumpWriter
  location: class DBHandler
DBHandler.java:244: error: cannot find symbol
			DumpWriter sqlWriter = new SqlWriter15(new SqlWriter.MySQLTraits(), sqlStream);
			                           ^
  symbol:   class SqlWriter15
  location: class DBHandler
DBHandler.java:244: error: package SqlWriter does not exist
			DumpWriter sqlWriter = new SqlWriter15(new SqlWriter.MySQLTraits(), sqlStream);
			                                                    ^
DBHandler.java:256: error: cannot find symbol
			XmlDumpReader xmlReader = new XmlDumpReader(filteredInput, sqlWriter);
			^
  symbol:   class XmlDumpReader
  location: class DBHandler
DBHandler.java:256: error: cannot find symbol
			XmlDumpReader xmlReader = new XmlDumpReader(filteredInput, sqlWriter);
			                              ^
  symbol:   class XmlDumpReader
  location: class DBHandler
DBHandler.java:1250: error: cannot find symbol
		return new Pair<int[], byte[][]>(idSet, features);
		           ^
  symbol:   class Pair
  location: class DBHandler
DBHandler.java:1907: error: cannot find symbol
			FileUtils.close(psFeaturesSet);
			^
  symbol:   variable FileUtils
  location: class DBHandler
18 errors

**Comment by psibre** [comment]
Sounds like classpath issues. Please be sure you're correctly following the instructions [in the wiki](../wiki/New-Language-Support).
Be aware that the marytts-builder code -- including the Wikipedia/new language DB stuff -- has been unmaintained for many years.

**Comment by sunilskar** [comment]
is this problem with wiki data at given line no. can we update this data file in the said xml file @ given line no. 
will this solution work for me

**Comment by sbalasis** [comment]
Greetings,

I was able to solve my problem by **downgrading both ubuntu linux version and jdk to openjdk1.7**

**Comment by ernest-p** [comment]
Getting this error on MacOS with Java 10

**Comment by psibre** [comment]
@ernest-p The [New Language Support](../wiki/New-Language-Support) is *really* outdated code and hasn't been properly maintained for many years. We have experimental code to replace parts of it [here](/marytts/gradle-marytts-lexicon-compiler-plugin), but YMMV.
If you need to work around this bug in the old code, and the blocker is your Java version, I recommend [SDKMAN!](https://sdkman.io/).
