### ISSUE TITLE
OpenMary TTS for Hindi, Null pointer Exception

### ISSUE THREAD

**Issue by arpitgoyal2008** [marytts/marytts#86]
Hi,

As discussed in issue#84, 

I am using openMary TTS 5.1 version
Operating System: Linux
Java version: 1.6.0

But a new problem has arrived, I am facing a issue when adding support for Hindi language in OpenMary.
I have completed successfully step 5 given in https://github.com/marytts/marytts/wiki/New-Language-Support (i.e. Run feature maker with the minimal NLP components) 

But now at step 6 (Database selection), when I run command
$ wkdb_database_selector.sh wkdb.conf 
I get following error:
Analysing feature vectors of 1034 sentences:
Exception in thread "main" java.lang.NullPointerException
	at marytts.tools.dbselection.CoverageDefinition.initialiseCoverage(CoverageDefinition.java:439)
	at marytts.tools.dbselection.DatabaseSelector.main2(DatabaseSelector.java:238)
	at marytts.tools.dbselection.DatabaseSelector.main(DatabaseSelector.java:113)

Kindly guide me through this

My wkdb.conf file is as follows:
WIKIDATAPATH=/home/arpit/Desktop/MARY/hindi
WIKILOCALE=hi
LOCALE=hi
MYSQLHOST=localhost
MYSQLUSER=root
MYSQLPASSWD=
MYSQLDB=wiki123
FEATUREMAKERRELIABILITY=strict
FEATUREMAKERFEATURESFORSELECTION="phone,next_phone,selection_prosody"
SELECTEDSENTENCESTABLENAME=test
SELECTEDSENTENCESTABLEDSCRIPTION="Testing table for selected sentences. Wikipedia locale: "
DATABASESELECTORSTOPCRITERION="numSentences 90 simpleDiphones simpleProsody"

@psibre : Kindly help me into this. I have been working to develop TTS for Hindi. But there are many problems I have to overcome. I have to discuss a lot of issues. Would you be able to give me a contact id so that I can mail you and discuss it with you. Its very urgent. My aim is first develop TTS for Hindi using OpenMary and then improve its performance. My email-id is arpitgoyal2008@gmail.com. I will be very grateful.

Regards,

**Comment by doaaobiedat** [comment]
i had the same problem 
```
Exception in thread "main" java.lang.NullPointerException
	at marytts.tools.dbselection.CoverageDefinition.initialiseCoverage(CoverageDefinition.java:439)
	at marytts.tools.dbselection.DatabaseSelector.main2(DatabaseSelector.java:238)
	at marytts.tools.dbselection.DatabaseSelector.main(DatabaseSelector.java:113)
```
Do I need to use version 4.1 instead of 5.1-SNAPSHOT or there another solution?

**Comment by Munzey** [comment]
the original issue seems to have been successfully addressed so closing
