### ISSUE TITLE
Does not work with Java 10

### ISSUE THREAD

**Issue by PapeThePope** [marytts/marytts#863]
MaryTTS ist not yet working with Java 10, can you look at that?

**Comment by sskorol** [comment]
Seems like it's related to version parsing. Faced with it couple of days ago as well.
I have several Java versions installed, so just switched to JDK 8 before using MaryTTS.

**Comment by sskorol** [comment]
@PapeThePope https://github.com/marytts/marytts/issues/783
so I guess we just need to build from sources or wait for official release

**Comment by saraheee** [comment]
Hi, it's working with Java 10.0.1 again, as the version number is longer. :)

**Comment by seblemaguer** [comment]
solved by #923
