### ISSUE TITLE
HMMVoiceMakeVoice ERROR [+7321] CreateInsts: Unknown label

### ISSUE THREAD

**Issue by doaaobiedat** [marytts/marytts#867]
Hi

i am building new HMM voice with marytts builder 

i run HMMVoiceMakeVoice 
by using this command
perl scripts/Training.pl scripts/Config.pm > logfile &

i have this error

***
ERROR [+7321]  CreateInsts: Unknown label w^a-ʔ+a=a||f3=0|f51=7|f22=0|f53=1|f33=2|f1=1|f4=0|f6=0|f14=L-L%|f8=0|f35=0|f30=2|f41=5|f26=0|f20=mid|f31=0|f36=1|f7=0|f47=3|f29=4|f15=7|f24=0|f46=1|f56=1|f18=0|f50=0|f49=0|f52=4|f27=1|f38=0|f19=0|f16=2|f28=0|f9=0|f39=0|f34=0|f13=onset|f17=0|f48=3|f2=1|f43=1|f23=0|f55=0|f57=0|f45=2|f40=2|f0=0|f5=!H*|f58=1|f37=1|f25=1|f21=L+H*|f42=1|f11=0|f10=0|f32=1|f44=1|f54=0|f12=0||
 FATAL ERROR - Terminating program /home/hiyassat/Trining_EqraFemale1Voice/marytts-5.1/lib/external/bin/HERest
Error in /home/hiyassat/Trining_EqraFemale1Voice/marytts-5.1/lib/external/bin/HERest    -A -B -C /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/configs/trn.cnf -D -T 1 -S /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/data/scp/train.scp -I /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/data/labels/full.mlf -m 1 -u tmvwdmv -w 5000 -t 1500 100 5000  -H /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/models/qst001/ver1/cmp/fullcontext.mmf -N /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/models/qst001/ver1/dur/fullcontext.mmf -M /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/models/qst001/ver1/cmp -R /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/models/qst001/ver1/dur -C /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/configs/nvf.cnf -s /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/stats/qst001/ver1/cmp.stats -w 0.0 /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/data/lists/full.list /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/abkaryat_Ali/hts/data/lists/full.list
***

solution: copy and paste into full.list file in hts/data/full.lists and rerun from embedded reestimation (fullcontext) step

but this error appears several times with different labels (more than 30 times ) 
i have a huge data so this solution is not efficient and take a lot of time for one step to be done.

is there another solution for this error?, or how could i know the labels and add them all before run this step

**Comment by seblemaguer** [comment]
Hello,

this phonetic label "ʔ" is not an ascii phonetic label so it couldn't be used by mary/hts. You need to have an ascii allophoneset
