### ISSUE TITLE
Voice name modification

### ISSUE THREAD

**Issue by pierocosi** [marytts/marytts#869]
Is there an easy guide (if this is possible) or some instructions 
to change the name of a VOICE of a JAR file without having to
recreate the VOICE JAR file itself ?
… in other words ... which are the files contained in the JAR file that I have to edit and modify (even BINARY files with HEX editor ???) 

e.g. let's consider the voice 
voice-cmu-clb-hsmm-5.2-SNAPSHOT.jar
which files in marytts and META-INF
 I have to edit in order to change the name cmu-clb in something else?
 
MANY THANKS
Piero

**Comment by psibre** [comment]
Hi @pierocosi, you would need to modify the voice name in the config file, taking care to update all property names to match the new voice name. For example, to rename [voice-cmu-bdl-hsmm](https://github.com/marytts/voice-cmu-bdl-hsmm), this is the required diff for the config:
```diff
1c1
< # Auto-generated config file for voice cmu-bdl-hsmm
---
> # Auto-generated config file for voice fnord-hsmm
3c3
< name = cmu-bdl-hsmm
---
> name = fnord-hsmm
6c6
< hmm.voices.list = cmu-bdl-hsmm
---
> hmm.voices.list = fnord-hsmm
8,40c8,40
< voice.cmu-bdl-hsmm.alpha = 0.42
< voice.cmu-bdl-hsmm.gamma = 0
< voice.cmu-bdl-hsmm.logGain = false
< voice.cmu-bdl-hsmm.beta = 0
< voice.cmu-bdl-hsmm.Ftd = jar:/marytts/voice/CmuBdlHsmm/tree-dur.inf
< voice.cmu-bdl-hsmm.Ftf = jar:/marytts/voice/CmuBdlHsmm/tree-lf0.inf
< voice.cmu-bdl-hsmm.Ftm = jar:/marytts/voice/CmuBdlHsmm/tree-mgc.inf
< voice.cmu-bdl-hsmm.Fts = jar:/marytts/voice/CmuBdlHsmm/tree-str.inf
< voice.cmu-bdl-hsmm.Fmd = jar:/marytts/voice/CmuBdlHsmm/dur.pdf
< voice.cmu-bdl-hsmm.Fmf = jar:/marytts/voice/CmuBdlHsmm/lf0.pdf
< voice.cmu-bdl-hsmm.Fmm = jar:/marytts/voice/CmuBdlHsmm/mgc.pdf
< voice.cmu-bdl-hsmm.Fms = jar:/marytts/voice/CmuBdlHsmm/str.pdf
< voice.cmu-bdl-hsmm.useGV = true
< voice.cmu-bdl-hsmm.maxMgcGvIter = 200
< voice.cmu-bdl-hsmm.maxLf0GvIter = 200
< voice.cmu-bdl-hsmm.Fgvf = jar:/marytts/voice/CmuBdlHsmm/gv-lf0-littend.pdf
< voice.cmu-bdl-hsmm.Fgvm = jar:/marytts/voice/CmuBdlHsmm/gv-mgc-littend.pdf
< voice.cmu-bdl-hsmm.Fgvs = jar:/marytts/voice/CmuBdlHsmm/gv-str-littend.pdf
< voice.cmu-bdl-hsmm.FeaFile = jar:/marytts/voice/CmuBdlHsmm/arctic_a0499.pfeats
< voice.cmu-bdl-hsmm.trickyPhonesFile = jar:/marytts/voice/CmuBdlHsmm/trickyPhones.txt
< voice.cmu-bdl-hsmm.useMixExc = true
< voice.cmu-bdl-hsmm.Fif = jar:/marytts/voice/CmuBdlHsmm/mix_excitation_filters.txt
< voice.cmu-bdl-hsmm.in = 5
< voice.cmu-bdl-hsmm.useAcousticModels = true
< voice.cmu-bdl-hsmm.acousticModels = duration F0
< voice.cmu-bdl-hsmm.duration.model = hmm
< voice.cmu-bdl-hsmm.duration.attribute = d
< voice.cmu-bdl-hsmm.F0.model = hmm
< voice.cmu-bdl-hsmm.F0.attribute = f0
< voice.cmu-bdl-hsmm.domain = general
< voice.cmu-bdl-hsmm.gender = male
< voice.cmu-bdl-hsmm.locale = en_US
< voice.cmu-bdl-hsmm.samplingRate = 16000
\ No newline at end of file
---
> voice.fnord-hsmm.alpha = 0.42
> voice.fnord-hsmm.gamma = 0
> voice.fnord-hsmm.logGain = false
> voice.fnord-hsmm.beta = 0
> voice.fnord-hsmm.Ftd = jar:/marytts/voice/CmuBdlHsmm/tree-dur.inf
> voice.fnord-hsmm.Ftf = jar:/marytts/voice/CmuBdlHsmm/tree-lf0.inf
> voice.fnord-hsmm.Ftm = jar:/marytts/voice/CmuBdlHsmm/tree-mgc.inf
> voice.fnord-hsmm.Fts = jar:/marytts/voice/CmuBdlHsmm/tree-str.inf
> voice.fnord-hsmm.Fmd = jar:/marytts/voice/CmuBdlHsmm/dur.pdf
> voice.fnord-hsmm.Fmf = jar:/marytts/voice/CmuBdlHsmm/lf0.pdf
> voice.fnord-hsmm.Fmm = jar:/marytts/voice/CmuBdlHsmm/mgc.pdf
> voice.fnord-hsmm.Fms = jar:/marytts/voice/CmuBdlHsmm/str.pdf
> voice.fnord-hsmm.useGV = true
> voice.fnord-hsmm.maxMgcGvIter = 200
> voice.fnord-hsmm.maxLf0GvIter = 200
> voice.fnord-hsmm.Fgvf = jar:/marytts/voice/CmuBdlHsmm/gv-lf0-littend.pdf
> voice.fnord-hsmm.Fgvm = jar:/marytts/voice/CmuBdlHsmm/gv-mgc-littend.pdf
> voice.fnord-hsmm.Fgvs = jar:/marytts/voice/CmuBdlHsmm/gv-str-littend.pdf
> voice.fnord-hsmm.FeaFile = jar:/marytts/voice/CmuBdlHsmm/arctic_a0499.pfeats
> voice.fnord-hsmm.trickyPhonesFile = jar:/marytts/voice/CmuBdlHsmm/trickyPhones.txt
> voice.fnord-hsmm.useMixExc = true
> voice.fnord-hsmm.Fif = jar:/marytts/voice/CmuBdlHsmm/mix_excitation_filters.txt
> voice.fnord-hsmm.in = 5
> voice.fnord-hsmm.useAcousticModels = true
> voice.fnord-hsmm.acousticModels = duration F0
> voice.fnord-hsmm.duration.model = hmm
> voice.fnord-hsmm.duration.attribute = d
> voice.fnord-hsmm.F0.model = hmm
> voice.fnord-hsmm.F0.attribute = f0
> voice.fnord-hsmm.domain = general
> voice.fnord-hsmm.gender = male
> voice.fnord-hsmm.locale = en_US
> voice.fnord-hsmm.samplingRate = 16000
\ No newline at end of file
```
It would be more elegant to also rename the name of the java package and resource namespace accordingly, but this will work.

Note that the above was accomplished simply by changing one string in the voice project's `build.gradle`:
```diff
diff --git a/build.gradle b/build.gradle
index f62aa82..b51179b 100644
--- a/build.gradle
+++ b/build.gradle
@@ -6,7 +6,7 @@ group 'de.dfki.mary'
 version '5.3-SNAPSHOT'
 
 voice {
-    name = 'cmu-bdl-hsmm'
+    name = 'fnord-hsmm'
     language = 'en'
     region = 'US'
     gender = 'male'
```

**Comment by pierocosi** [comment]
Many Thanks for your reply!

I tried to do it within Windows!

I used "IZArc" to unjar the VOICE jarr file
I did all the changes
and I used again IZArc to create the new jar file
Action: Add
Compression: Maximal
Method: Deflate
Encription: None

I put the file in the lib dir of the server but ... NO NEW VOICE APPEARS !!!!

**Comment by psibre** [comment]
Please paste the output of `zipinfo YOURJARFILE`.

**Comment by pierocosi** [comment]
Here It is

 

sysadmin@Shivling:~$ zipinfo voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT.jar 

Archive:  voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT.jar

Zip file size: 201783 bytes, number of entries: 22

-rw-a--     2.0 fat      539 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/Config.class

-rw-a--     2.0 fat     6256 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/dur.pdf

-rw-a--     2.0 fat    13811 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/features_example.pfeats

-rw-a--     2.0 fat       72 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/gv-lf0.pdf

-rw-a--     2.0 fat      416 t- stor 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/gv-mgc.pdf

-rw-a--     2.0 fat       96 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/gv-str.pdf

-rw-a--     2.0 fat     1433 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/hmmFeaturesMap.txt

-rw-a--     2.0 fat    38624 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/lf0.pdf

-rw-a--     2.0 fat   103832 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/mgc.pdf

-rw-a--     2.0 fat    10992 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/mix_excitation_5filters_99taps_16000Hz.txt

-rw-a--     2.0 fat    37112 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/str.pdf

-rw-a--     2.0 fat    19628 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/tree-dur.inf

-rw-a--     2.0 fat    94167 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/tree-lf0.inf

-rw-a--     2.0 fat    18230 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/tree-mgc.inf

-rw-a--     2.0 fat    37406 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/tree-str.inf

-rw-a--     2.0 fat       83 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/trickyPhones.txt

-rw-a--     2.0 fat     4907 t- defX 18-May-25 17:22 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/marytts/voice/MivoqSteveHsmm/voice.config

-rw-a--     2.0 fat      348 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/META-INF/MANIFEST.MF

-rw-a--     2.0 fat      127 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/META-INF/maven/de.dfki.mary/voice-mivoq-steve-hsmm/pom.properties

-rw-a--     2.0 fat     5629 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/META-INF/maven/de.dfki.mary/voice-mivoq-steve-hsmm/pom.xml

-rw-a--     2.0 fat      327 t- defX 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/META-INF/rev_info.properties

-rw-a--     2.0 fat       35 t- stor 17-Oct-03 09:59 voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/META-INF/services/marytts.config.MaryConfig

22 files, 394070 bytes uncompressed, 196501 bytes compressed:  50.1%

 

 

 

MANY THANKS

Piero

 

Da: psibre [mailto:notifications@github.com] 
Inviato: venerdì 25 maggio 2018 19:11
A: marytts/marytts <marytts@noreply.github.com>
Cc: pierocosi <piero.cosi@pd.istc.cnr.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [marytts/marytts] Voice name modification (#869)

 

Please paste the output of zipinfo YOURJARFILE.

**Comment by psibre** [comment]
I think what happened when you manually created the jar file is that a garbage path element was prepended to each entry inside the jar. You want to have it *without* the leading `voice-mivoq-steve-01-hsmm-5.2-SNAPSHOT/`.

**Comment by psibre** [comment]
The jar filenames are irrelevant. What matters are the voice names and the corresponding properties loaded from the configuration(s). **You cannot have two different voices with the same name.** But you *can* have different voices sharing the same resources if you want. If you merge the service loaders you can even package them in the same jar file.

**Comment by pierocosi** [comment]
I did not want to have two different voices with the same name but two different voices created with same name but with different set of files....  after having renamed them into two different voices.

Hope to be clear enough... sorry for my English!

**Comment by psibre** [comment]
Just to clarify, if you have one speech corpus called "pippo", you can of course use this same data to build one voice called "pippo-01", and then a second voice called "pippo-02". By convention, you would end up with two jar files, "voice-pippo-01.jar" (containing the property `name = "pippo-01"` in its config), and "voice-pippo-02.jar" (containing the property `name = "pippo-02"` in its config).

A MaryTTS server started with both jars on the classpath would then provide two distinct voices, "pippo-01" and "pippo-02", which presumably sound more or less the same, modulo some difference in their respective voicebuilding process (different label sets, model parameters, cost function coefficients, vocoder parameters, or whatever).

**Comment by pierocosi** [comment]
The problem is that I have two speech corpus (same voice: pippo) one with let's say 500 sentences and the second with 1000 sentences ... and I ... STUPID ... created 2 voices with the same name and I want now to rename them and use them both!

**Comment by pierocosi** [comment]
The problem is that I have two speech corpus (same voice: pippo) one with let's say 500 sentences and the second with 1000 sentences ... and I ... STUPID ... created 2 voices with the same name and I want now to rename them and use them both!

 

Da: psibre [mailto:notifications@github.com] 
Inviato: lunedì 28 maggio 2018 16:44
A: marytts/marytts <marytts@noreply.github.com>
Cc: pierocosi <piero.cosi@pd.istc.cnr.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [marytts/marytts] Voice name modification (#869)

 

Just to clarify, if you have one speech corpus called "pippo", you can of course use this same data to build one voice called "pippo-01", and then a second voice called "pippo-02". By convention, you would end up with two jar files, "voice-pippo-01.jar" (containing the property name = "pippo-01" in its config), and "voice-pippo-02.jar" (containing the property name = "pippo-02" in its config).

A MaryTTS server started with both jars on the classpath would then provide two distinct voices, "pippo-01" and "pippo-02", which presumably sound more or less the same, modulo some difference in their respective voicebuilding process (different label sets, model parameters, cost function coefficients, vocoder parameters, or whatever).

**Comment by psibre** [comment]
If you really want to build two different voices from the two different corpora, I recommend you maintain two different voicebuilding projects, configured with different voice names.

However, it sounds like you might want to "merge" the data and build a single voice that subsumes both corpora? In that case, just build one voice with all the data.

**Comment by pierocosi** [comment]
NO. SORRY!

 

In effect I BUILT two different voices from two different corpora (same speaker pippo)

and I GAVE THE VOICE THE SAME NAME pippo

 

And now I want to rename the two voices with the same name pippo in pippo-01 and pippo-02

without having to rebuild again the two voices with different names.

 

Da: psibre [mailto:notifications@github.com] 
Inviato: lunedì 28 maggio 2018 17:29
A: marytts/marytts <marytts@noreply.github.com>
Cc: pierocosi <piero.cosi@pd.istc.cnr.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [marytts/marytts] Voice name modification (#869)

 

If you really want to build two different voices from the two different corpora, I recommend you maintain two different voicebuilding projects, configured with different voice names.

However, it sounds like you might want to "merge" the data and build a single voice that subsumes both corpora? In that case, just build one voice with all the data.

**Comment by psibre** [comment]
Ah, I see.

Three options:
1. If you're using the Gradle-based voicebuilding plugin (I assume you're not, but I would recommend it), just change the `voice.name` property (see [above](#issuecomment-392089366)) and rerun `./gradlew build`.
2. With the legacy VoiceImportTools, just change the `db.voicename` in the `database.config`, and rerun the "Voice Compiler" component.
3. If all you have is the jar files, then unzip them, modify the config resources, and repackage them, just like you did for your "steve" voice.

**Comment by pierocosi** [comment]
MANY THANKS INDEED!!!!

 

Da: psibre [mailto:notifications@github.com] 
Inviato: lunedì 28 maggio 2018 19:04
A: marytts/marytts <marytts@noreply.github.com>
Cc: pierocosi <piero.cosi@pd.istc.cnr.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [marytts/marytts] Voice name modification (#869)

 

Ah, I see.

Three options:

1.	If you're using the Gradle-based voicebuilding plugin (I assume you're not, but I would recommend it), just change the voice.name property (see above <> ) and rerun ./gradlew build.
2.	With the legacy VoiceImportTools, just change the db.voicename in the database.config, and rerun the "Voice Compiler" component.
3.	If all you have is the jar files, then unzip them, modify the config resources, and repackage them, just like you did for your "steve" voice.

**Comment by psibre** [comment]
Glad it worked!
