### ISSUE TITLE
error at TranscriptionAligner step,.InvalidDataException

### ISSUE THREAD

**Issue by doaaobiedat** [marytts/marytts#870]
Hello

i am building a new arabic voice by voiceimport tool

i had this error #867 , as a suggestion to solve this error, i rebuild allophones.ar.xml by replace the allophone ʔ with A 
- run transcription.sh
- produce ar.lts ,ar_lexicon.fst ,ar_pos.fst, ar_pos.list 
put them and allophones.ar.xml  in lexicon, tagger folders in resources

- rerun voiceimport tool 
- Error in TranscriptionAligner 

```
traversing through 360 files
s-1
/media/hiyassat/Data/Training_EqraFemale1Voice/training_all/trial3/lab/s-1.lab
Orig   : _|o|a|b|q|a|r|i|j|t|u|_|A|l|sˤ|d|i|j|q|_
Correct: _|o|a|b|q|a|r|i|j|t|u|A|l|sˤ|d|i|j|q|_
Alignments:  _ # o # a # b # q # a # r # i # j # t # u # # A # l # sˤ # d # i # j # q # _ 
Boundary, align =  _ 
Ph = o, align =  o 
Ph = a, align =  a 
Ph = b, align =  b 
Ph = q, align =  q 
Ph = a, align =  a 
Ph = r, align =  r 
Ph = i, align =  i 
Ph = j, align =  j 
Ph = t, align =  t 
Ph = u, align =  u 
Ph = A, align =  A 
Ph = l, align =  l 
Ph = sˤ, align =  sˤ 
Ph = d, align =  d 
Ph = i, align =  i 
Ph = j, align =  j 
Ph = q, align =  q 
Boundary, align =  _ 
java.lang.Exception: The component TranscriptionAligner produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: marytts.exceptions.InvalidDataException: Label "A" not found in AllophoneSet for Locale ar
	at marytts.tools.analysis.MaryTranscriptionAligner.alignXmlTranscriptions(MaryTranscriptionAligner.java:95)
	at marytts.tools.voiceimport.TranscriptionAligner.alignTranscription(TranscriptionAligner.java:164)
	at marytts.tools.voiceimport.TranscriptionAligner.compute(TranscriptionAligner.java:133)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
```

* note that TranscriptionAligner step worked correctly before the changes i made in allophones.ar.xml

**Comment by psibre** [comment]
Which locale are you using in your voicebuilding project? Are you certain you have the required language component on your classpath? It looks like your modification to the AllophoneSet is not correctly reflected there.

**Comment by doaaobiedat** [comment]
>Which locale are you using in your voicebuilding project?

local ar

>Are you certain you have the required language component on your classpath?

mostly yes
 
i'd successfully built ar voice before, with the same steps and same data ,but the problem was that the error #867 appeared a lot. so, to avoid that error i want to change Allophnes that made it.

the changes i made just in allophones.ar.xml ,ar.txt, userdict-ar.txt
i can not determine where i did wrong!

**Comment by psibre** [comment]
If you're using the code at https://github.com/doaaobiedat/marytts-lang-ar/blob/master/lib/modules/ar/lexicon/allophones.ar.xml, then it's clear that your AllophoneSet does *not* contain the `A` entry. It does have an `a`, but case is significant!

**Comment by doaaobiedat** [comment]
>If you're using the code at https://github.com/doaaobiedat/marytts-lang-ar/blob/master/lib/modules/ar/lexicon/allophones.ar.xml

This code was before modifications..


I made changes on this allophones:
ʔ ----> A
ʃ ----> p 
ɣ ---> y
ʕ ---> o 

''''
<allophones name="sampa" xml:lang="ar"
		features="vlng vheight vfront vrnd ctype cplace cvox">
	<silence ph="_"/>

	<vowel ph="a:" vlng="l" vheight="3" vfront="2" vrnd="-"/>
	<vowel ph="a" vlng="s" vheight="3" vfront="2" vrnd="-"/>
	<vowel ph="u:" vlng="l" vheight="1" vfront="3" vrnd="+"/>
	<vowel ph="u" vlng="s" vheight="1" vfront="3" vrnd="+"/>
	<vowel ph="i:" vlng="l" vheight="1" vfront="1" vrnd="-"/>
	<vowel ph="i" vlng="s" vheight="1" vfront="1" vrnd="-"/>


	<consonant ph="A" ctype="s" cplace="g" cvox="+"/>
<consonant ph="b" ctype="s" cplace="l" cvox="+"/>
	<consonant ph="t" ctype="s" cplace="a" cvox="-"/>
	<consonant ph="θ" ctype="f" cplace="a" cvox="-"/>
	<consonant ph="ʒ" ctype="s" cplace="p" cvox="+"/>
	<consonant ph="ħ" ctype="f" cplace="g" cvox="-"/>
	<consonant ph="x" ctype="f" cplace="g" cvox="-"/>
	<consonant ph="d" ctype="s" cplace="a" cvox="+"/>
	<consonant ph="ð" ctype="f" cplace="a" cvox="+"/>
	<consonant ph="r" ctype="r" cplace="a" cvox="+"/>
	<consonant ph="z" ctype="f" cplace="a" cvox="+"/>
	<consonant ph="s" ctype="f" cplace="a" cvox="-"/>
	<consonant ph="p" ctype="f" cplace="p" cvox="-"/>
	<consonant ph="sˤ" ctype="f" cplace="a" cvox="-"/>
	<consonant ph="dˤ" ctype="f" cplace="a" cvox="+"/>
	<consonant ph="tˤ" ctype="s" cplace="a" cvox="+"/>
	<consonant ph="zˤ" ctype="f" cplace="a" cvox="+"/>
	<consonant ph="o" ctype="a" cplace="g" cvox="+"/>
	<consonant ph="y" ctype="a" cplace="g" cvox="+"/>
	<consonant ph="f" ctype="f" cplace="b" cvox="-"/>
	<consonant ph="q" ctype="s" cplace="v" cvox="+"/>
	<consonant ph="k" ctype="s" cplace="v" cvox="-"/>
	<consonant ph="l" ctype="l" cplace="a" cvox="+"/>
	<consonant ph="m" ctype="n" cplace="l" cvox="+"/>
	<consonant ph="n" ctype="n" cplace="a" cvox="+"/>
	<consonant ph="h" ctype="f" cplace="g" cvox="-"/>
	<consonant ph="w" ctype="r" cplace="l" cvox="+"/>
	<consonant ph="j" ctype="r" cplace="p" cvox="+"/>
</allophones>
 
'''

**Comment by doaaobiedat** [comment]
>If you load your modified language component in the MaryTTS server and predict the pronunciation for a word that previously had a pronunciation containing the ʔ allophone, can you confirm that it now has A instead?

yes


```
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="ar">
  <p>
 <s>
 <phrase>
 <t accent="L+H*" g2p_method="rules" ph="' o a b - q a - r i j - t u" pos="content">
 عَبقَرِيةُ
 <syllable accent="L+H*" ph="o a b" stress="1">
 <ph p="o"/>
 <ph p="a"/>
 <ph p="b"/>
 </syllable>
 <syllable ph="q a">
 <ph p="q"/>
 <ph p="a"/>
 </syllable>
 <syllable ph="r i j">
 <ph p="r"/>
 <ph p="i"/>
 <ph p="j"/>
 </syllable>
 <syllable ph="t u">
 <ph p="t"/>
 <ph p="u"/>
 </syllable>
 </t>
 <t accent="!H*" g2p_method="rules" ph="' A l sˤ d i j q" pos="content">
 الصدِّيق
 <syllable accent="!H*" ph="A l sˤ d i j q" stress="1">
 <ph p="A"/>
 <ph p="l"/>
 <ph p="sˤ"/>
 <ph p="d"/>
 <ph p="i"/>
 <ph p="j"/>
 <ph p="q"/>
 </syllable>
 </t>
 <boundary breakindex="5" tone="L-L%"/>
 </phrase>
 </s>
 </p>
 </maryxml> 
```

**Comment by psibre** [comment]
How are you running the TranscriptionAligner component? What's on the classpath?

**Comment by doaaobiedat** [comment]
Finally !!
It solved , but I don't recognize where was the problem, i did almost the same steps..every trial , suddenly TranscriptionAligner done successfully.

Thanks psibre

**Comment by psibre** [comment]
Glad to hear it!
