### ISSUE TITLE
Voice starting to break down and clogging after some time 

### ISSUE THREAD

**Issue by log69** [marytts/marytts#874]
Hi everyone, I'm testing your online demo at http://mary.dfki.de:59125/ and when pasting in a text longer than a couple of sentences (say, 6 ones) then clicking the SPEAK button creates the voice and it starts reading it just nicely with great accent and tones. Except after a few seconds (around 3 sec) it starts breaking down becoming very laggish and kind of clogging.

The same happens on several computers in localhost as well. Why is that? Some voice samples are very nice and just awesome until that couple of seconds when it becomes bad independent of the text.

Appreciate any help on the matter. Version is 5.2, system is Linux Ubuntu 18 x64. Java runtime is OpenJDK 10.0.1. Thx.

**Comment by log69** [comment]
I've removed some groovy package and it's fixed that. Works nice, thanks for this great project.

**Comment by psibre** [comment]
Indeed, the next release will ensure the transitive `groovy-all` dependency doesn't leak into the runtime classpath downstream.

**Comment by frnsys** [comment]
@log69 can you describe what you did? Running into a similar issue

**Comment by log69** [comment]
As I wrote above, removed the groovy packages. List them and uninstall them.
