### ISSUE TITLE
Java out-of-memory if too many languages are installed

### ISSUE THREAD

**Issue by fnunnari** [marytts/marytts#878]
The JVM goes out of memory while starting the server if too many languages are installed.

I installed all EN and US languages using the GUI (./gradlew runInstallerGui).
Server was working fine (./gradlew run).
Then I installed 3 french languages.
After running, the jvm stopped claiming that the Heap is out of memory.

According to the process viewer, the JVM is running with 1GB max virtual memory (-Xmx1024m).

How can I increase the max JVM allocation size?
Would the same setting be applied when running via "marytts-server"?

OS: Linux version 4.4.0-116-generic (Ubuntu 5.4.0-6ubuntu1~16.04.9)
java version "1.8.0_171"
MaryTTS commit 64155d4735192e9ee4b6b5a67f7028c2fc2362d8
Merge: 8ffb913 db89b65
Author: psibre <ingmar.steiner@dfki.de>
Date:   Mon May 8 15:03:56 2017 +0200

**Comment by fuzeller** [comment]
Hi @fnunnari,
You can edit you marytts-server file under your marytts/build/(marytts-5.something)/bin/ folder.

Change -Xmx1g to whatever's appropriate for your system (example below is -Xmx8g)

```#!/bin/bash
##########################################################################
# MARY TTS server
##########################################################################

# Set the Mary base installation directory in an environment variable:
BINDIR="`dirname "$0"`"
export MARY_BASE="`(cd "$BINDIR"/.. ; pwd)`"


java -showversion -Xms40m -Xmx8g -cp "$MARY_BASE/lib/*" -Dmary.base="$MARY_BASE" $* marytts.server.Mary```

**Comment by psibre** [comment]
@fnunnari I can't actually reproduce this... I installed a bunch of voices via `./gradlew runInstallerGui`, and then started the MaryTTS server using `./gradlew run`:
```
:run
MARY server 6.0-SNAPSHOT starting as an HTTP server... started in 7.565 s on port 59125
> Building 98% > :run
```
Here's the list of voices installed and loaded (from http://localhost:59125/voices):
```
upmc-pierre-hsmm fr male hmm
upmc-pierre fr male unitselection general
upmc-jessica-hsmm fr female hmm
upmc-jessica fr female unitselection general
enst-dennys-hsmm fr male hmm
enst-camille-hsmm fr female hmm
enst-camille fr female unitselection general
dfki-spike-hsmm en_GB male hmm
dfki-spike en_GB male unitselection general
dfki-prudence-hsmm en_GB female hmm
dfki-prudence en_GB female unitselection general
dfki-poppy-hsmm en_GB female hmm
dfki-poppy en_GB female unitselection general
dfki-pavoque-styles de male unitselection general
dfki-pavoque-neutral-hsmm de male hmm
dfki-pavoque-neutral de male unitselection general
dfki-obadiah-hsmm en_GB male hmm
dfki-obadiah en_GB male unitselection general
cmu-slt-hsmm en_US female hmm
bits3-hsmm de male hmm
bits1-hsmm de female hmm
```
No problems running this on OSX 10.11.6 with OpenJDK 1.8.

To quote Roy, "Have you tried turning it off and on again?"

**Comment by fnunnari** [comment]
I reproduced the crash on my my installation and copied the full output.

* Current voices:

enst-camille fr female unitselection general
dfki-spike-hsmm en_GB male hmm
dfki-spike en_GB male unitselection general
dfki-prudence-hsmm en_GB female hmm
dfki-prudence en_GB female unitselection general
dfki-poppy-hsmm en_GB female hmm
dfki-poppy en_GB female unitselection general
dfki-obadiah-hsmm en_GB male hmm
dfki-obadiah en_GB male unitselection general
cmu-slt-hsmm en_US female hmm
cmu-slt en_US female unitselection general
cmu-rms-hsmm en_US male hmm
cmu-rms en_US male unitselection general
cmu-bdl-hsmm en_US male hmm
cmu-bdl en_US male unitselection general

* Installed: upmc-pierre, upmc-jessica

:runInstallerGui
Fontconfig warning: ignoring UTF-8: not a valid region tag
upmc-jessica selected for installation
upmc-pierre selected for installation
Check license(s)
Lookup took 57 ms
Showing license http://mary.dfki.de/download/by-sa-3.0.html for 2 components
License accepted.
Starting installation
Now installing upmc-jessica...
Installing upmc-jessica-5.2 in /local/data/MaryTTS/marytts/build/install/marytts...
Extracting directory: lib/
Extracting directory: lib/voices/
Extracting directory: lib/voices/upmc-jessica/
Extracting file: lib/voices/upmc-jessica/halfphoneFeatures_ac.mry
Extracting file: lib/voices/upmc-jessica/halfphoneUnits.mry
Extracting file: lib/voices/upmc-jessica/joinCostFeatures.mry
Extracting file: lib/voices/upmc-jessica/timeline_basenames.mry
Extracting file: lib/voices/upmc-jessica/timeline_waveforms.mry
Extracting file: lib/voice-upmc-jessica-5.2.jar
...done
Now installing upmc-pierre...
Installing upmc-pierre-5.2 in /local/data/MaryTTS/marytts/build/install/marytts...
Extracting directory: lib/
Extracting directory: lib/voices/
Extracting directory: lib/voices/upmc-pierre/
Extracting file: lib/voices/upmc-pierre/halfphoneFeatures_ac.mry
Extracting file: lib/voices/upmc-pierre/halfphoneUnits.mry
Extracting file: lib/voices/upmc-pierre/joinCostFeatures.mry
Extracting file: lib/voices/upmc-pierre/timeline_basenames.mry
Extracting file: lib/voices/upmc-pierre/timeline_waveforms.mry
Extracting file: lib/voice-upmc-pierre-5.2.jar
...done
upmc-pierre selected for uninstall

BUILD SUCCESSFUL

Total time: 1 mins 3.329 secs


* Running

./gradlew run
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:marytts-common:compileJava UP-TO-DATE
:marytts-common:processResources UP-TO-DATE
:marytts-common:classes UP-TO-DATE
:marytts-common:jar UP-TO-DATE
:marytts-signalproc:compileJava UP-TO-DATE
:marytts-signalproc:processResources UP-TO-DATE
:marytts-signalproc:classes UP-TO-DATE
:marytts-signalproc:jar UP-TO-DATE
:marytts-runtime:compileJava UP-TO-DATE
:marytts-runtime:compileGroovy UP-TO-DATE
:marytts-runtime:processResources UP-TO-DATE
:marytts-runtime:classes UP-TO-DATE
:marytts-runtime:jar UP-TO-DATE
:marytts-languages:marytts-lang-en:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-en:processResources UP-TO-DATE
:marytts-languages:marytts-lang-en:classes UP-TO-DATE
:marytts-languages:marytts-lang-en:jar UP-TO-DATE
:voice-cmu-slt-hsmm:compileJava UP-TO-DATE
:voice-cmu-slt-hsmm:processResources UP-TO-DATE
:voice-cmu-slt-hsmm:classes UP-TO-DATE
:voice-cmu-slt-hsmm:jar UP-TO-DATE
:marytts-languages:marytts-lang-de:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-de:processResources UP-TO-DATE
:marytts-languages:marytts-lang-de:classes UP-TO-DATE
:marytts-languages:marytts-lang-de:jar UP-TO-DATE
:marytts-languages:marytts-lang-fr:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-fr:processResources UP-TO-DATE
:marytts-languages:marytts-lang-fr:classes UP-TO-DATE
:marytts-languages:marytts-lang-fr:jar UP-TO-DATE
:marytts-languages:marytts-lang-it:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-it:processResources UP-TO-DATE
:marytts-languages:marytts-lang-it:classes UP-TO-DATE
:marytts-languages:marytts-lang-it:jar UP-TO-DATE
:marytts-languages:marytts-lang-lb:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-lb:compileGroovy UP-TO-DATE
:marytts-languages:marytts-lang-lb:processResources UP-TO-DATE
:marytts-languages:marytts-lang-lb:classes UP-TO-DATE
:marytts-languages:marytts-lang-lb:jar UP-TO-DATE
:marytts-languages:marytts-lang-ru:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-ru:processResources UP-TO-DATE
:marytts-languages:marytts-lang-ru:classes UP-TO-DATE
:marytts-languages:marytts-lang-ru:jar UP-TO-DATE
:marytts-languages:marytts-lang-sv:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-sv:processResources UP-TO-DATE
:marytts-languages:marytts-lang-sv:classes UP-TO-DATE
:marytts-languages:marytts-lang-sv:jar UP-TO-DATE
:marytts-languages:marytts-lang-te:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-te:processResources UP-TO-DATE
:marytts-languages:marytts-lang-te:classes UP-TO-DATE
:marytts-languages:marytts-lang-te:jar UP-TO-DATE
:marytts-languages:marytts-lang-tr:compileJava UP-TO-DATE
:marytts-languages:marytts-lang-tr:processResources UP-TO-DATE
:marytts-languages:marytts-lang-tr:classes UP-TO-DATE
:marytts-languages:marytts-lang-tr:jar UP-TO-DATE
:startScripts UP-TO-DATE
:marytts-languages:marytts-lang-de:generateComponentXmlDescriptor UP-TO-DATE
:marytts-languages:marytts-lang-en:generateComponentXmlDescriptor UP-TO-DATE
:marytts-languages:marytts-lang-fr:generateComponentXmlDescriptor UP-TO-DATE
:marytts-languages:marytts-lang-it:generateComponentXmlDescriptor UP-TO-DATE
:marytts-languages:marytts-lang-lb:generateComponentXmlDescriptor UP-TO-DATE
:marytts-languages:marytts-lang-ru:generateComponentXmlDescriptor UP-TO-DATE
:marytts-languages:marytts-lang-sv:generateComponentXmlDescriptor UP-TO-DATE
:marytts-languages:marytts-lang-te:generateComponentXmlDescriptor UP-TO-DATE
:marytts-languages:marytts-lang-tr:generateComponentXmlDescriptor UP-TO-DATE
:installerGuiStartScripts UP-TO-DATE
:installDist UP-TO-DATE
:run
MARY server 6.0-SNAPSHOT starting as an HTTP server...Exception in thread "main" java.lang.Exception: Problem starting module OpenNLPPosTagger
        at marytts.server.Mary.startModules(Mary.java:151)
        at marytts.server.Mary.startup(Mary.java:297)
        at marytts.server.Mary.startup(Mary.java:204)
        at marytts.server.Mary.main(Mary.java:513)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.io.DataInputStream.readUTF(DataInputStream.java:661)
        at java.io.DataInputStream.readUTF(DataInputStream.java:564)
        at opennlp.model.BinaryFileDataReader.readUTF(BinaryFileDataReader.java:61)
        at opennlp.model.AbstractModelReader.readUTF(AbstractModelReader.java:82)
        at opennlp.model.AbstractModelReader.getPredicates(AbstractModelReader.java:119)
        at opennlp.maxent.io.GISModelReader.constructModel(GISModelReader.java:74)
        at opennlp.model.GenericModelReader.constructModel(GenericModelReader.java:59)
        at opennlp.model.AbstractModelReader.getModel(AbstractModelReader.java:87)
        at opennlp.tools.util.model.GenericModelSerializer.create(GenericModelSerializer.java:35)
        at opennlp.tools.util.model.GenericModelSerializer.create(GenericModelSerializer.java:31)
        at opennlp.tools.util.model.BaseModel.loadModel(BaseModel.java:231)
        at opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:181)
        at opennlp.tools.postag.POSModel.<init>(POSModel.java:82)
        at marytts.modules.OpenNLPPosTagger.startup(OpenNLPPosTagger.java:81)
        at marytts.server.Mary.startModules(Mary.java:149)
        ... 3 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
        at marytts.server.Mary.shutdown(Mary.java:371)
        at marytts.server.Mary$3.run(Mary.java:290)
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 48.63 secs

**Comment by fnunnari** [comment]
Followed the suggestion of fuzeller.
Increasing the max RAM to 2GB solves the problem.

**Comment by psibre** [comment]
Glad to hear you worked around it!
