### ISSUE TITLE
MGC, LF0 & Strength

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#879]
Hi all,

This question is related to the use of MGC, LF0 and strength to train the voice model (for HMM based voice) in marytts. Is there any reason why only these 3 features MGC, LF0 and strength have been used? Is it related to some constraints in the next stages of voice building? Or can we add any more features to this?

Any insights in this direction is much appreciated.

**Comment by seblemaguer** [comment]
Hello,

if you look at the HTSModel class you will see that these 3 kind of coefficients are hard coded. For now, I don't have anytime to see with this part so I think if you can just use these features for now that is the best :)
