### ISSUE TITLE
ambiguous server warning

### ISSUE THREAD

**Issue by fsteinhardt** [marytts/marytts#88]
I'm using Mary TTS server 5.0 and got this warning while trying out different voices and languages:

from server.log:

2012-12-07 16:34:49,461 [I/O dispatcher 4] WARN  marytts.IO Voice `dfki-spike-hsmm' does not match document locale `de' -- ignoring!

What is ignored? The voice setting or the locale setting?

**Comment by Munzey** [comment]
in the xml input did you have the local set to de? spike is an en voice so that would throw an error.
