### ISSUE TITLE
Deadlocked/Waiting orphan threads produced upon interrupt.

### ISSUE THREAD

**Issue by mkoslowski-metis** [marytts/marytts#880]
Hello,

I apologize if this issue has been tackled before, or if I am using MaryTTS in a ham-fisted way.

I am creating a program that will allow for a priority queue of classes that extend AudioPlayer to interrupt voice messages with lower priority and have lower priority voice messages wait for higher priority messages to finish.

I was able to accomplish this goal, but unfortunately upon the profiling of my program, I see that whenever the speech is interrupted, it produces waiting threads that accumulate and take up space.
Here is part of a stack trace from JConsole:

marytts.util.data.ProducingDoubleDataSource.putOneDataPoint(ProducingDoubleDataSource.java:78)
marytts.htsengine.HTSVocoder.htsMLSAVocoder(HTSVocoder.java:512)
marytts.htsengine.HTSVocoder$HTSVocoderDataProducer.run(HTSVocoder.java:1882).

I am not a threading expert by any means, but i think this is because the vocoder is waiting for data from its parent thread.

I have experimented with regular threading logic, using daemon threads, and using an ExecutorService.

Please let me know if you have any suggestions,

Thanks.

**Comment by seblemaguer** [comment]
Hello,

I think you are right. The problem is is that the HTS package is just complicated to maintain and we will plan to have more a redesign about. 

In between we can try to find a short "patchy" solution, but I have no idea what is better. Do you have a suggestion?

**Comment by mkoslowski-metis** [comment]
I'm not sure how difficult this could be, but what if the AudioPlayer, along with its child threads, could be put into the same ThreadGroup? That way I would just have to do ap.getThreadGroup.interrupt(); (if ap was the name of the audio player).
I tested if I could make a thread (let's call it AudioHandler) that starts an AudioPlayer. I instantiated the AudioHandler to be a part of a ThreadGroup, but upon termination of the ThreadGroup the AudioPlayer remained.

**Comment by mkoslowski-metis** [comment]
Hello, I actually fixed my issue. Your cancel() method actually works great. I thought it didn't work because when i wanted to delete unstarted threads, I would start and cancel the threads immediately, but the thread would still play. Now, when giving the main thread a 200 millisecond sleep buffer after starting, every audioplayer can be started and stopped without thread buildup. Thanks!

**Comment by seblemaguer** [comment]
great :) sorry, couldn't have a look earlier :)
