### ISSUE TITLE
Assemble and install MaryTTS

### ISSUE THREAD

**Issue by farhatriaz** [marytts/marytts#889]
### Assemble and install MaryTTS:
**Using Eclipse, in the Package Explorer, right-click on the marytts project (at the top), then select Run As > Maven install**
**I get following errors.**
[INFO] Scanning for projects...
[WARNING] The project de.dfki.mary:marytts:pom:6.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] MaryTTS                                                            [pom]
[INFO] marytts-common                                                     [jar]
[INFO] marytts-signalproc                                                 [jar]
[INFO] marytts-runtime                                                    [jar]
[INFO] marytts-lang-de                                                    [jar]
[INFO] marytts-lang-en                                                    [jar]
[INFO] marytts-lang-te                                                    [jar]
[INFO] marytts-lang-tr                                                    [jar]
[INFO] marytts-lang-ru                                                    [jar]
[INFO] marytts-lang-it                                                    [jar]
[INFO] marytts-lang-fr                                                    [jar]
[INFO] marytts-lang-sv                                                    [jar]
[INFO] marytts-lang-lb                                                    [jar]
[INFO] marytts-languages                                                  [pom]
[INFO] voice-cmu-slt-hsmm                                                 [jar]
[INFO] marytts-client                                                     [jar]
[INFO] marytts-builder                                                    [jar]
[INFO] marytts-redstart                                                   [jar]
[INFO] marytts-transcription                                              [jar]
[INFO] marytts-assembly-builder                                           [pom]
[INFO] marytts-assembly-runtime                                           [pom]
[INFO] marytts-assembly                                                   [pom]
[INFO] 
[INFO] ------------------------< de.dfki.mary:marytts >------------------------
[INFO] Building MaryTTS 6.0-SNAPSHOT                                     [1/22]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts ---
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: C:\Users\farhat maken\git\marytts
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MaryTTS 6.0-SNAPSHOT ............................... FAILURE [  1.670 s]
[INFO] marytts-common ..................................... SKIPPED
[INFO] marytts-signalproc ................................. SKIPPED
[INFO] marytts-runtime .................................... SKIPPED
[INFO] marytts-lang-de .................................... SKIPPED
[INFO] marytts-lang-en .................................... SKIPPED
[INFO] marytts-lang-te .................................... SKIPPED
[INFO] marytts-lang-tr .................................... SKIPPED
[INFO] marytts-lang-ru .................................... SKIPPED
[INFO] marytts-lang-it .................................... SKIPPED
[INFO] marytts-lang-fr .................................... SKIPPED
[INFO] marytts-lang-sv .................................... SKIPPED
[INFO] marytts-lang-lb .................................... SKIPPED
[INFO] marytts-languages .................................. SKIPPED
[INFO] voice-cmu-slt-hsmm ................................. SKIPPED
[INFO] marytts-client ..................................... SKIPPED
[INFO] marytts-builder .................................... SKIPPED
[INFO] marytts-redstart ................................... SKIPPED
[INFO] marytts-transcription .............................. SKIPPED
[INFO] marytts-assembly-builder ........................... SKIPPED
[INFO] marytts-assembly-runtime ........................... SKIPPED
[INFO] marytts-assembly 6.0-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.469 s
[INFO] Finished at: 2018-08-28T16:22:11+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project marytts: Cannot get the revision information from the scm repository : 
[ERROR] Exception while executing SCM command. Error while executing command. Error while executing process. Cannot run program "git" (in directory "C:\Users\farhat maken\git\marytts"): CreateProcess error=2, The system cannot find the file specified
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by psibre** [comment]
My first guess is that something (EGit? buildnumber-maven-plugin?) is choking on the fact that your project directory path contains a space. This is Generally A Bad Idea.

But more to the point, the master branch **must be built with Gradle, not Maven!** Please switch to the 5.x branch if you want Maven, or use Gradle.

**Comment by dao-tt** [comment]
I have same error
