### ISSUE TITLE
using custom text corpus not a wikipedia dump

### ISSUE THREAD

**Issue by rkizito** [marytts/marytts#890]
I've already got a text corpus ( in utf8 text) that i'd like to use in creating a new voice. Is there an easy way to use it with MaryTTS and bypass the wikipedia dump/mysql route? The language is agglutinating and has an almost direct grapheme to phoneme correspondence.

**Comment by nshmyrev** [comment]
Yes, you just dump the data files into proper structure and proceed with the next steps. You can check [Creating New Language and Voice Components for the Updated MaryTTS Text-to-Speech Synthesis Platform ](https://arxiv.org/pdf/1712.04787.pdf) for details.

**Comment by rkizito** [comment]
Thanks nshmyrev. But by proper structure do you mean xml or a particular directory. I'm new to this.

**Comment by seblemaguer** [comment]
the maryxml is a valid start for what you want to do
