### ISSUE TITLE
Voice Creation following your tutorial succeeds but the volume of the voice changes during TTS

### ISSUE THREAD

**Issue by diegomary** [marytts/marytts#891]
Dear sirs, and Dear @psibre 

I have used your tutorial for voice creation using the legacy voiceimport tool.
[https://github.com/marytts/marytts/wiki/HMMVoiceCreation](url)
I have worked on the 5.2 release and the following observations are related to such environment.

I have decided to try with the preexisting corpus of text and wav files cmu_us_clb_arctic-0.95-release
And I proceeded with HMM voice creation tutorial.

I have limited my test to only 430 utterances in order to probe multiple attempts in short time aware of the limitations given by a small corpus.

All the steps passed well but In order to pass the **HMMVoiceMakeVoice** step I had to modify the following lines in Training.pl because I am running a new release of **sox** on my **Ubuntu 18** that doesn't support anymore the **-s option**. It supports indeed the **-e option**.

[TrainingPl.zip](https://github.com/marytts/marytts/files/2430652/TrainingPl.zip)

After changing the Training.pl file I was able to pass the step **HMMvoiceCompiler** and had the voice ready to install on the server.
Here's the voice:
[pom.zip](https://github.com/marytts/marytts/files/2430674/pom.zip)
[voice-diegus-hsmm-5.2.zip](https://github.com/marytts/marytts/files/2430675/voice-diegus-hsmm-5.2.zip)
Here's an example of usage with change of volume (The rainbow passage)
[SavedWavwithVolumechange.zip](https://github.com/marytts/marytts/files/2430680/SavedWavwithVolumechange.zip)

The problem is that when played the voice has up and downs in volume. The quality is good and I am aware that increasing the corpus could become excellent but there is this problem of volume change. Certain statements of my text are high volume and others are low up to become almost inaudible although present as shown in the synthethized excerpt.

What is your thought on this? I am at a loss because Ithink not to have forgotten anything from your tutorial of your tutorial apart the Training.pl file.
The voice is attached and it would be extremely kind of yours to have some feedback on this blocking result.

The same problem of up and down in volume appers also when I use my recorded waveforms spoken by me or using other speakers even if I normalize then.

Thanks in avance and congratulations for your amazing work so far. I am a huge fan of your project and a lover of Speech synthesis. 

Here's my Humble attempt of a voice font fully written in C++
[https://github.com/diegomary/ttsmfcvoicefont](url)
Kindest regard

Diego

**Comment by diegomary** [comment]
Hello there is anybody available to take a look at my issue?
Thanks Diego

**Comment by nshmyrev** [comment]
Most likely you accidentally modified the audio files in the database so that data varied in volume significantly. You can probably review the data during training to see if it was the case.

The effect is amplified by global variance in voice config. You can turn it of with useGV = false, it will be much more stable. You can also tune gvWeightStr to smaller value.

With bigger dataset the problem will likely go away, you can try on full clb dataset.

**Comment by diegomary** [comment]
Hello @nshmyrev, 
Thanks for your kind advice.

I wanted to add for sake of detail that using the same corpus but producing a voice of kind Unit Selection as per your detailed tutorial at
[https://github.com/marytts/marytts/wiki/UnitSelectionVoiceCreation](url) The results are very good without this change of volume.

I attach an excerpt of the Rainbow passage uttered by the Unit Selection Voice version.
[RainbowPas.zip](https://github.com/marytts/marytts/files/2445412/RainbowPas.zip)

I much appreciated your hints. I will immediately follow your directions and let you know as soon as I have feedback.

With kindest regards
Diego

**Comment by diegomary** [comment]
hello @nshmyrev,
I confirm that your hints produced the expected result and I thank you again for your advice. I am closing this issue since it is now clear. 
Kind regards 
Diego
