### ISSUE TITLE
Marytts 5.3-SNAPSHOT Run as Maven Install Problem

### ISSUE THREAD

**Issue by farhatriaz** [marytts/marytts#892]
I Clone and import the marytts 5X.
I'm trying to run as mavel install but facing some errors.
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project marytts: Cannot get the revision information from the scm repository :
[ERROR] Exception while executing SCM command. Error while executing command. Error while executing process. Cannot run program "git" (in directory "/home/farhat/git/marytts"): error=2, No such file or directory
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by seblemaguer** [comment]
Hello, normally you should use gradle and not maven to install.

**Comment by farhatriaz** [comment]
> Hello, normally you should use gradle and not maven to install.
Sir, I followed the following link.
As mentioned steps using Maven.
https://github.com/marytts/marytts/wiki/Eclipse_5.X

**Comment by seblemaguer** [comment]
sorry the wiki is outdated, we didn't have time to update this part. Can you try with gradle and see if it works?

**Comment by farhatriaz** [comment]
> sorry the wiki is outdated, we didn't have time to update this part. Can you try with gradle and see if it works?

Thanks.
Sir, Is there any other link for guidelines?

**Comment by seblemaguer** [comment]
Depends, what do you want to do?

**Comment by farhatriaz** [comment]
> Depends, what do you want to do?

Sir, I want to develop Urdu(language) Text to speech system.

**Comment by farhatriaz** [comment]
> Depends, what do you want to do?

Sir, please help me. I want to develop Urdu text to speech system.

**Comment by OttkO** [comment]
I am combining a lot of projects most of them use maven.
You should provide support for it.
I am stuck on the same problem as above.

**Comment by racinmat** [comment]
Just guessing from the " Cannot run program "git" (in directory "/home/farhat/git/marytts"): error=2, No such file or directory" you do not have your git binary in your PATH env variable and thus it can not find it and use it.

**Comment by psibre** [comment]
Just to jump in and clear up some confusion:
- The 5.x branch *currently* builds with Maven, so that's correct.
- The master branch builds with Gradle, *even though* it's still cluttered with obsolete `pom.xml` files.
So which build tool to use depends on the branch. We plan to clean this up to make it unambiguous very soon.

**Comment by psibre** [comment]
I've tried to fake a build environment on my machine that has no working `git`, by mapping it to `null` in the buildnumber-maven-plugin configuration:
```xml
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<configuration>
					<providerImplementations>
						<git>null</git>
					</providerImplementations>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
This allows me to reproduce your error.

A solution to this issue is to add the `revisionOnScmFailure` property:
```xml
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<configuration>
					<revisionOnScmFailure>${project.version}</revisionOnScmFailure>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
You can add this yourself until I've pushed a fix.

**Comment by psibre** [comment]
@OttkO Incidentally, other projects that use Maven can still use MaryTTS as a dependency regardless of which build we use.
