### ISSUE TITLE
Can not build marytts

### ISSUE THREAD

**Issue by racinmat** [marytts/marytts#896]
I downloaded the marytts-installer-5.2.zip and tried to install it according to its README.md. 
When running `marytts install:cmu-slt` it fails with this output: 
```
:bits1:payload (Thread[Daemon worker,5,main]) started.
:bits1:payload
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
Resource missing. [HTTP GET: http://mary.dfki.de/repo/de/dfki/mary/marytts-lang-de/5.2/ivy-5.2.xml]
Resource missing. [HTTP HEAD: http://mary.dfki.de/repo/de/dfki/mary/marytts-lang-de/5.2/marytts-lang-de-5.2.jar]
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
I/O exception (java.net.SocketException) caught when processing request to {s}->https://jcenter.bintray.com:443: Connection reset
Retrying request to {s}->https://jcenter.bintray.com:443
Resource missing. [HTTP GET: http://mary.dfki.de/repo/de/dfki/mary/marytts-runtime/5.2/ivy-5.2.xml]
Resource missing. [HTTP HEAD: http://mary.dfki.de/repo/de/dfki/mary/marytts-runtime/5.2/marytts-runtime-5.2.jar]
:bits1:payload (Thread[Daemon worker,5,main]) completed. Took 0.837 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':bits1:marytts'.
> Could not resolve de.dfki.mary:marytts-lang-de:5.2.
  Required by:
      MaryTTS:bits1:5.2 > de.dfki.mary:voice-bits1:5.2
   > Could not resolve de.dfki.mary:marytts-lang-de:5.2.
      > Could not get resource 'https://jcenter.bintray.com/de/dfki/mary/marytts-lang-de/5.2/marytts-lang-de-5.2.pom'.
         > Could not GET 'https://jcenter.bintray.com/de/dfki/mary/marytts-lang-de/5.2/marytts-lang-de-5.2.pom'.
            > Connection reset
> Could not resolve de.dfki.mary:marytts-runtime:5.2.
  Required by:
      MaryTTS:bits1:5.2 > de.dfki.mary:voice-bits1:5.2
   > Could not resolve de.dfki.mary:marytts-runtime:5.2.
      > Could not get resource 'https://jcenter.bintray.com/de/dfki/mary/marytts-runtime/5.2/marytts-runtime-5.2.pom'.
         > Could not GET 'https://jcenter.bintray.com/de/dfki/mary/marytts-runtime/5.2/marytts-runtime-5.2.pom'.
            > Connection reset
```

I use Windows 10, java 1.7. I don't understand what happens, when I access this URL where the GET command fails, in the browser, it works perfectly and downloads me the pom file. 

I also tried to clone the repo from github and run gradle build here, same error.
Then I checkout version 5.x and performed maven install, with the same error. 
Please, do you have any idea why is this happening and how to bypass this error?

I tried to disable the windows firewall, but it did not help.
I also ran the command from the command line with administrator privileges, and still the same error.

**Comment by psibre** [comment]
Hi @racinmat, a few things:
1. The issue title makes has nothing to do with what you describe -- the MaryTTS installer is completely separate from the main marytts repository.
1. The marytts-installer has its [own issue tracker](../../marytts-installer/issues)
1. You say that you're trying to run `marytts install:cmu-slt`, but the output you pasted is for the command `marytts install:bits1`.
1. Both of those commands work for me without errors (even when I use the obsolete Java version 7).

I'll close this issue, but if you continue to have problems with the marytts-installer, you can open a new issue on *its* issue tracker.

**Comment by racinmat** [comment]
My bad, I didn't know installer has its own issue tracker. 
I didn't pass the whole stacktrace, only the part with error. And as I understand it, `install:bits1` is called during the `install:cmu-slt`.

**Comment by psibre** [comment]
> And as I understand it, install:bits1 is called during the install:cmu-slt.

That's incorrect. However, if you run *only* `install`, then Gradle assumes you want to run the `install` task *in each subproject* -- the first of which is `bits1`, so then `install:bits1` is executed first. (The subproject logic is a bit convoluted, and in the process of being rewritten.)
