### ISSUE TITLE
install en-US language again

### ISSUE THREAD

**Issue by rohitraghav** [marytts/marytts#898]
I mistakenly uninstall en-US language from marytts-component-installer.sh.
How to reinstall?

**Comment by psibre** [comment]
Interesting! Apparently the GUI *should* prevent this from happening...
![installergui](https://user-images.githubusercontent.com/1278639/48425684-9ad28080-e765-11e8-8dc1-fcdeabf6dded.png)
![progress](https://user-images.githubusercontent.com/1278639/48425708-a625ac00-e765-11e8-9c94-d99084bf8d08.png)
![message](https://user-images.githubusercontent.com/1278639/48425712-a9209c80-e765-11e8-81bb-b0117e13716a.png)
...returning to the same GUI state as before -- but on the console it shows that it's nevertheless deleting the component!
```
en-US selected for uninstall
Starting uninstall
Now uninstalling en-US...
Removing en-US-6.0-SNAPSHOT from /Users/ingmar/workspace/marytts/build/install/marytts...
Could not uninstall en-US
```
Indeed, after restarting the GUI, the en-US language is missing:
![installergui2](https://user-images.githubusercontent.com/1278639/48426124-6b704380-e766-11e8-8d38-8e19a2c1489e.png)

**Comment by psibre** [comment]
You can recover from this by running the GUI through Gradle, i.e., `./gradlew runInstallerGui`.

**Comment by rohitraghav** [comment]
I am using marytts-5.2 and i think this needs to compile with maven not gradle ??

**Comment by psibre** [comment]
Ah, OK. In that case, the assembly is built by (an old version of) Gradle run via a Maven plugin. You can regenerate the accidentally uninstalled en-US component descriptor by running the command:
```
mvn org.fortasoft:gradle-maven-plugin:invoke \
  -Dtasks=marytts-assembly:assembly-runtime:assemble \
  -pl marytts-assembly/assembly-runtime
```

**Comment by rohitraghav** [comment]
However, i tried using maven with `mvn install` command i was getting some errors on performing the tests.
Then i skipped the tests using `mvn install -DskipTests` resulting in successful building maven.
Running marytts-component-installer then show the en-US language. 
Let me also give a try to your latest comment.
