### ISSUE TITLE
EnglishConfig cannot be resolved to a type

### ISSUE THREAD

**Issue by kurodenjiro** [marytts/marytts#901]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.988 s
[INFO] Finished at: 2018-11-27T00:39:03+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
5.1:testCompile (default-testCompile) on project marytts-lang-en: Compilation fa
ilure: Compilation failure:
[ERROR] C:\Users\B150M\Desktop\mozile_vietnam\marytts\marytts-languages\marytts-
lang-en\src\test\java\marytts\language\en\EnglishConfigExtraTest.java:[56,-1]
[ERROR] 1. ERROR in C:\Users\B150M\Desktop\mozile_vietnam\marytts\marytts-langua
ges\marytts-lang-en\src\test\java\marytts\language\en\EnglishConfigExtraTest.jav
a (at line 56)
[ERROR]         LanguageConfig e = new EnglishConfig();
[ERROR]                                ^^^^^^^^^^^^^
[ERROR] EnglishConfig cannot be resolved to a type
[ERROR] ----------
[ERROR]
[ERROR] C:\Users\B150M\Desktop\mozile_vietnam\marytts\marytts-languages\marytts-
lang-en\src\test\java\marytts\language\en\EnglishConfigExtraTest.java:[62,-1]
[ERROR] 2. ERROR in C:\Users\B150M\Desktop\mozile_vietnam\marytts\marytts-langua
ges\marytts-lang-en\src\test\java\marytts\language\en\EnglishConfigExtraTest.jav
a (at line 62)
[ERROR]         LanguageConfig e = new EnglishConfig();
[ERROR]                                ^^^^^^^^^^^^^
[ERROR] EnglishConfig cannot be resolved to a type
[ERROR] ----------
[ERROR] 2 problems (2 errors)
[ERROR]
[ERROR] Found 2 errors and 0 warnings.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :marytts-lang-en

**Comment by psibre** [comment]
Looks like you're trying to build with Maven. Please use Gradle -- see [the README](https://github.com/marytts/marytts/#building-marytts).
