### ISSUE TITLE
Marytts HMM voice quality changes with text length

### ISSUE THREAD

**Issue by skmalviya** [marytts/marytts#904]
I want to get attention on HMMVoice based on indic Hindi TTS. I trained both USS and HMM marytts voice on a dataset more than 2000 wav files. USS voice is excellent, no doubt on that. 
But for HMM, energy in the voice is getting reduced with text length on each output.

I have attached the USS and HMM output wav files. Please look and help me where I am doing wrong with the HMM training.
[HMM voice](https://drive.google.com/file/d/172D-HxoaFyvy0BmnnfwTYecHbNrtQrvp/view?usp=sharing)
[USS voice](https://drive.google.com/file/d/1dqANHFa35-sYfVzeE3JzR0_FGKpFjQHn/view?usp=sharing)

Using MaryTTS_5.2

**Comment by psibre** [comment]
This is unfortunately a known issue with the Java port of the HTS Engine code... I've never been able to reliably isolate what causes it, but it seems to be more of an issue with some voices than others.

In MaryTTS 6.x, we're actually moving to a wrapper library for HTS. This is still work in progress, but we expect to have a working version published very soon.

**Comment by skmalviya** [comment]
Thanks for the info. I will track and put suggestions for MaryTTS 6.X,

**Comment by candelrg** [comment]
Hello.
Does it mean that you expect a 6.0 release soon? (any potential timeframe?)
Is it somehow linked with the other issue with french voices ( #602 )?

Thank you by advance for your answer, and thank you anyway for the great job already done.

**Comment by seblemaguer** [comment]
Hello, to release the new version

as I am the only one so far working on the 6.X and as it is not my primary work, I can't give any timeframe. To give you an idea, the archecture refactorisation has been done and the main wrappings are also done. Some wrapping remains to be done and the cleaning also.
