### ISSUE TITLE
cannot start MARY server

### ISSUE THREAD

**Issue by dao-tt** [marytts/marytts#906]
environment: Os windows 7,
Eclipse IDE for Java Developers
Version: Oxygen.3a Release (4.7.3a)
Java version "1.8.0_171"

I import marytts follow this 

(https://github.com/marytts/marytts/wiki/Eclipse_6.X)

I run "Mary" then I got error as in the pic 
![eclipse](https://user-images.githubusercontent.com/45379807/49856694-d67b6b80-fe33-11e8-8cb5-79d99a9c3c9f.jpg)

Please help me
---------------------------------------------------------------
MARY server ${project.version} starting as an HTTP server...Exception in thread "main" java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Unknown Source)
	at java.util.regex.Matcher.replaceAll(Unknown Source)
	at java.lang.String.replaceAll(Unknown Source)
	at marytts.server.Mary.configureLogging(Mary.java:342)
	at marytts.server.Mary.startup(Mary.java:229)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.server.Mary.main(Mary.java:510)

**Comment by psibre** [comment]
Eclipse is tricky to set up for Gradle projects -- personally, I much recommend IntelliJ IDEA, which works right out of the box.

**Comment by psibre** [comment]
P.S. I tried updating the instructions on setting up Eclipse for MaryTTS 6.x, but lost patience with Eclipse. You can see my preliminary updates in the eclipse-6.x branch on the Wiki.

**Comment by dao-tt** [comment]
@psibre Thank you I will try IntelliJ IDEA

**Comment by seblemaguer** [comment]
@dao-tt is it solved?
