### ISSUE TITLE
Conversion to OGG Vorbis format not supported on ubuntu 18.10

### ISSUE THREAD

**Issue by Carbonhell** [marytts/marytts#912]
I've been trying to output my sound in audio format, specifically Vorbis, but I get "Conversion to OGG Vorbis format not supported." whenever i attempt a http request from browser:
http://localhost:59125/process?INPUT_TEXT=Aaa&INPUT_TYPE=TEXT&LOCALE=en_US&VOICE=cmu-slt-hsmm&OUTPUT_TYPE=AUDIO&AUDIO=Vorbis
This is on a virtual machine made with Oracle Virtualbox, hosting Ubuntu 18.10, I also tried to install vorbislib but the result didn't change, am i missing a step or what?

**Comment by psibre** [comment]
May I ask where you read that MaryTTS supports Ogg Vorbis? Was that for v3.5 (from 2007)? I'm afraid that feature was removed in v4.0 (2009) -- see the [FAQ](http://mary.dfki.de/faq.html#technical).
This has been a frequently requested feature for a long time (even on the [old TRAC](https://mary.opendfki.de/trac/wiki/FrequentlyAskedQuestions#oggvorbis)!).

If you need support for compressed audio, I suggest you pipe the output of MaryTTS through SoX (which [supports Ogg encoding](http://sox.sourceforge.net/soxformat.html)) or similar.
