### ISSUE TITLE
build fails EnglishLanguageconfig

### ISSUE THREAD

**Issue by aminbaig** [marytts/marytts#914]
I am trying to build the server. When I run mvn install everything runs but then I get the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project marytts-lang-en: Compilation failure: Compilation failure:
[ERROR] E:\marytts\marytts-languages\marytts-lang-en\src\test\java\marytts\language\en\EnglishConfigExtraTest.java:[56,-1]
[ERROR] 1. ERROR in E:\marytts\marytts-languages\marytts-lang-en\src\test\java\marytts\language\en\EnglishConfigExtraTest.java (at line 56)
[ERROR] LanguageConfig e = new EnglishConfig();
```

Is this a bug???

**Comment by psibre** [comment]
You need to use Gradle, not Maven. Please see the README.

**Comment by aminbaig** [comment]
From the documentation:

MaryTTS v5.x builds with Maven 3.0.x. If it is not installed on your system, see http://maven.apache.org/download.html or install it using your favorite package manager.

**Comment by aminbaig** [comment]
I am using the documentation at this link:

[https://github.com/marytts/marytts/tree/5.x](https://github.com/marytts/marytts/tree/5.x)

**Comment by aminbaig** [comment]
It says in the documents to use maven for building marytts.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by psibre** [comment]
@aminbaig Sorry, you did not say you which branch you were building from, so I assumed it was master. People tend to get confused by the residual `pom.xml` files we still haven't removed... =)

You're right, the 5.x branch builds with Maven. However, I cannot reproduce your errors. Could you please attach your console output (don't paste it in a comment)?

**Comment by aminbaig** [comment]
PFA
[buildoutput.txt](https://github.com/marytts/marytts/files/2864469/buildoutput.txt)

**Comment by psibre** [comment]
Thanks for the fast reply.

However,
```
[INFO] Building MaryTTS 6.0-SNAPSHOT
```
you *do* seem to be building on the master branch.

**Comment by aminbaig** [comment]
Oh…which branch should I change to?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by psibre** [comment]
As you [quoted above](#issuecomment-463565165):
> MaryTTS v5.x builds with Maven 3.0.x.

So, checkout [the 5.x branch](https://github.com/marytts/marytts/tree/5.x).

**Comment by aminbaig** [comment]
I actually cloned the same one. From the drop down I selected 5.x before getting the cloning link.

Pretty sure I did not select the master branch but I will do it again.

**Comment by aminbaig** [comment]
Success! Thanks @psibre

**Comment by psibre** [comment]
Great!

The clone link in the GitHub UI doesn't actually do anything regarding the branch to checkout. You need to do that locally.

From `git help clone`:
> --branch <name>, -b <name>
> Instead of pointing the newly created HEAD to the branch pointed to by the cloned repository's HEAD, point
> to <name> branch instead. In a non-bare repository, this is the branch that will be checked out.  --branch
> can also take tags and detaches the HEAD at that commit in the resulting repository.
