### ISSUE TITLE
New language support issue - Maori

### ISSUE THREAD

**Issue by isabellashields** [marytts/marytts#916]
Hello, 

I'm having difficulty with adding a new language. I have followed the steps listed on the New Language Support page on the wiki, but cannot progress past running the tests. I am able to compile from the marytts-lang-ma directory that I've set up.

When running mvn test, I get the following error message:
![image](https://user-images.githubusercontent.com/20761616/54323986-87c2b500-4660-11e9-87b5-c82fc34a8a66.png)

Any ideas about why this might be occurring?

Thanks in advance!

**Comment by psibre** [comment]
Looks like there may be a problem with the dependencies. Could you please share your marytts-lang-ma code?

**Comment by psibre** [comment]
Incidentally, I believe the ISO 639-1 code for Maori is *mi*; I suggest following that convention.

**Comment by cadetandrey** [comment]
Please describe how add Russian or change to Russian?
$ cd marytts-lang-ru
$ mvn test
completed success
And how add language to master pom ?
marytts/pom.xml
marytts/marytts-assembly/assembly-runtime/pom.xml

Thank you
Andrey
