### ISSUE TITLE
really wrong pronounced words with lang=de

### ISSUE THREAD

**Issue by qwertologe** [marytts/marytts#918]
de / dfki-pavoque-neutral-hsmm

badest:
`grep 'uck[aeiout]' /usr/share/dict/ngerman`
... and try to hear the words.

not much better:
`grep '[qQ]u' ...`

and the last of the real problems:
`grep grenz ...`

This is not repairable with extension of de.txt since there are >3400 words in ngerman.
The problem is the pronunciation itself.

**Comment by seblemaguer** [comment]
Hello,

sorry, I don't understand your problem, is it the synthesis or is it the phonetisation step which is problematic?

**Comment by qwertologe** [comment]
e.g.

- "zucken" is pronounced as "zunken" - should: ts'U-k@n
- "quetschen" as "kwuen" - should: 'kvEt-S@n
- "Grenzwert" as "Grünzwert" - should: gREnts-ve:6t

Theses problems exist in most hits if you use the `grep` like described.

**Comment by psibre** [comment]
Could you please attach the MaryXML output of `REALISED_ACOUSTPARAMS`?

**Comment by qwertologe** [comment]
> Could you please attach the MaryXML output of `REALISED_ACOUSTPARAMS`?

How? I would provide the information.

**Comment by seblemaguer** [comment]
Hello,

you defined the output type as `REALISED_ACOUSTPARAMS` in the request. If you are using the webpage generated by the server, it is the combo box on the right. If you are using the script,  you have to find where you defined AUDIO as an output type and replaced with  `REALISED_ACOUSTPARAMS`
