### ISSUE TITLE
new language phone set  and transcription (Lao language)

### ISSUE THREAD

**Issue by dao-tt** [marytts/marytts#921]
Hi I need some help,

I created Lao language with Vientiane intonation so I name it lo_VT,
I use Transcription tool but I got the error that can not load phone set 
![Screen Shot 2019-04-23 at 15 15 06](https://user-images.githubusercontent.com/45379807/56558759-af4f5a80-65da-11e9-9ee0-c152d8e73d88.png)

my allophone is attacked here
[allophones.lo.txt](https://github.com/marytts/marytts/files/3106072/allophones.lo.txt)
*use .txt for uploading here

and some lao word i created
![Screen Shot 2019-04-23 at 15 20 59](https://user-images.githubusercontent.com/45379807/56559067-7499f200-65db-11e9-8c39-59daf0b30adc.png)

please give me an advice for solving the problem, do I miss something here for Transcription?

Thank you in advance for your help!!

**Comment by seblemaguer** [comment]
Hello,

can you copy the full exception stacktrace (not a picture but the actual text)?

**Comment by dao-tt** [comment]
@seblemaguer I will caption the screen and send here
