### ISSUE TITLE
Cannot run MaryTTS on OS X Mojave 10.14.5 (18F132)

### ISSUE THREAD

**Issue by kirkmarkarian** [marytts/marytts#922]
I'm not a programmer of any sort, but I used to be able to use MaryTTS on my various Macs in the past.  Now, I am no longer able to run the server, nor the other portions of the program.  Will there be an update for OS X?  Also, will the update ever exist as a standalone application, the typical type, with a pretty icon and able to be launched from the Applications folder?

**Comment by kirkmarkarian** [comment]
Just curious if anybody else has had this issue, and if it might get fixed?

**Comment by seblemaguer** [comment]
Hello,

so in order. What is the error?

I am not working on macos but on linux. However, I don't specifics pattern from linux but from unix. Therefore, the next versions should be compatible with macos. 

Why do you want to have it as an application to be launched using an icon?

**Comment by kirkmarkarian** [comment]
Sébastien,
Thanks for replying.

I download the Runtime Package from here:  https://github.com/marytts/marytts/releases/download/v5.2/marytts-5.2.zip

Then, like I always used to be able to do before, I unzip the package, then I double click on the marytts-server file in the bin folder of the downloaded file.  This used to open up the server, and I could begin to do other things like download voices with the marytts-component-installer or run the marytts-client and make it speak.

Now, when I double-click on the marytts-server, I just get this:

> Last login: Sat May 25 13:11:09 on ttys000

XXXXX:~ XXX$ /Users/XXX/Desktop/marytts-5.2/bin/marytts-server ; exit;
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Exception in thread "main" java.lang.UnsupportedClassVersionError: marytts/server/Mary : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
> 

So, no access to what I used to be able to do, because the server simply won’t start.  I am not a programmer, I do not know how to correct code to fix this issue.

As for the server/installer/client being packaged as a singular app that one can load into the dock?  Well, why not?  Why does one have to open three separate java files to do something they could do from one?  If I go to the web-page, and work online, I do not have to open 2 extra windows to do things like access voices or type a command.  For example, the Praat speech synthesizer is loaded into one application, and can be accessed from within.  I don’t like the voice(s) from Praat as much as I like the CMU voices that MaryTTS has access to.  MaryTTS is superior in sound, to my ears.  

I spend most of my day working with synthesized sound to create music, and have been studying it for 24 years.  I strive for better sound.  Why not have a better sounding TTS app like MaryTTS be more accessible to the lay-person?  It’s a fantastic app.  When I use voices for my music, I use MaryTTS.  It’s simply better.  It’s open-source and FREE, so I’m not going to get sued for using the voices that are able to be used in such a manner.  I can’t use OS X voices for this.

Also, I also volunteer my time at an aphasia clinic near where I live, and I have aphasia myself.  I’d LOVE to share a speech synthesizer like MaryTTS to people who are not very well-versed in computer usage, but are adept at using speech synthesizers.  MaryTTS is better.  I can actually share this with speech pathologists.

If there is a way to create a singular application, I would GLADLY design the icon for it, I am also a graphic designer, and have been for over 20 years.  I would be happy to provide a nice-looking icon for such a useful application.

**Comment by seblemaguer** [comment]
The problem seems to be the use of java 7. Try to install java 8 and it should work.

For the singular app, I see your point. I can't guarantee we will have time to do it (as we already way behind schedules for more core functionalities).

**Comment by kirkmarkarian** [comment]
Sébastien,
Thank you!  Works great now - 
Kirk

**Comment by seblemaguer** [comment]
ok :)
