### ISSUE TITLE
Reducing time taken for audio synthesis

### ISSUE THREAD

**Issue by ziafkhan** [marytts/marytts#928]
Hi,

I have a large dataset from which i am generating a unit selection voice (~24 hrs) and am looking for a way to reduce synthesis time.
Things i have tried : 
1. Editing marybase.config to start caching as described in #682 . But it requires an exact match to be effective and I am dealing with variable numbers and dates.
2. As far as I have understood, beam search is executed at runtime to find the best path. Is there a way to reduce beam size to gain computation time at the expense of quality? Or any other parameter I may be as yet unaware of? I tried editing the beamSize declaration present in UnitSelectionVoice.java but it made no difference in the server log.

Is there anything else I can do? I am currently using v5.2, might switching to 6.0 improve synthesis speed?

Here is the server log - 

> 2019-08-02 12:38:01,136 [I/O dispatcher 1] INFO  marytts.R 0 New request (input type "TEXT", output type "AUDIO", voice "rakshita_13_p", effect "", audio "WAVE")
> 2019-08-02 12:38:01,136 [I/O dispatcher 1] INFO  marytts.server Read: confirming your account number now  as 1 2 3 4 5 6 P Q R, Your current account balance is 56432, Your PIN will expire on 31st January 2020, Have a great day..
> .
> .
> .
> .
> .
> 2019-08-02 12:38:03,770 [I/O dispatcher 1] INFO  marytts.Synthesis Audio format conversion required for voice rakshita_13_p
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0 Request processed in 2636 ms.
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    TextToMaryXML took 0 ms
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    JTokeniser took 2 ms
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    Preprocess took 16 ms
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    OpenNLPPosTagger took 9 ms
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    JPhonemiser took 4 ms
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    Prosody took 8 ms
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    PronunciationModel took 1 ms
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    AcousticModeller took 135 ms
> 2019-08-02 12:38:03,772 [I/O dispatcher 1] INFO  marytts.R 0    Synthesis took 2461 ms

**Comment by psibre** [comment]
I don't think the unitselection implementation is designed to scale up to that amount of voice data. And it hasn't really changed since 5.2, so switching to the current master will not help you much.

Partial caching is only going to help if you split up your synthesis requests, which will conceivably introduce other problems, even if some recurring chunks are reused from the cache instead of being synthesized anew.

Playing around with the Viterbi search parameters is also only going to get you so far in terms of performance.

If you have practical needs to speed up the synthesis and reduce the memory/storage footprint, I would recommend simply pruning the data used for voicebuilding. The benefit of adding more data probably doesn't improve overall quality much after 3-4h of audio.

On the other hand, the unitselection implementation could use an overhaul. If you're eager to get more efficiency out of MaryTTS, there are other search implementations that have been shown to work better, but of course they would need to be implemented.

**Comment by ziafkhan** [comment]
> I don't think the unitselection implementation is designed to scale up to that amount of voice data. And it hasn't really changed since 5.2, so switching to the current master will not help you much.

Thank you. This'll save some time.

> Playing around with the Viterbi search parameters is also only going to get you so far in terms of performance.

Okay. But I was hoping for some improvement in processing time. It made absolutely no difference (I changed the beamSize from 100 to 50). I also edited the Viterbi.java to fix the beamSize to 50 but to no effect. Any idea why? 

> If you have practical needs to speed up the synthesis and reduce the memory/storage footprint, I would recommend simply pruning the data used for voicebuilding. The benefit of adding more data probably doesn't improve overall quality much after 3-4h of audio.

To be honest we heard perceptible improvements in quality of speech until 22 hrs of data. Regardless, do you have any tips you can share for pruning the database?

**Comment by seblemaguer** [comment]
> Okay. But I was hoping for some improvement in processing time. It made absolutely no difference (I changed the beamSize from 100 to 50). I also edited the Viterbi.java to fix the beamSize to 50 but to no effect. Any idea why?

based on the code of `java public List<SelectedUnit> selectUnits(List<Element> tokensAndBoundaries, marytts.modules.synthesis.Voice voice)`, you have a preprocess before reaching the viterbi. That may explain why you don't see any improvement in the performance. 

> To be honest we heard perceptible improvements in quality of speech until 22 hrs of data. Regardless, do you have any tips you can share for pruning the database?

I would suggest to apply corpus reduction algorithms to keep the balance between the different diphone of the database. The rest depends also on the db and the speaker specificities

**Comment by ziafkhan** [comment]
Okay. Thanks.
