### ISSUE TITLE
Dokumentation of the MARY HTTP interface

### ISSUE THREAD

**Issue by florianschiel** [marytts/marytts#93]
> Hi,
> 
> we are running a 'Mary TTS server 4.1.1 (impl. 20100909)'
> (output of 'version'). I found the build-in docu page
> 'MARY HTTP Interface: Documentation by example' but this is not
> sufficiant for the HTTP interface.
> More specifically I'm looking the exact definintion of
> 
> effect_(effectname)_selected
> effect_(effectname)_parameters
> 
> By fiddling around I found that the following works:
> 
> http://marytts.phonetik.uni-muenchen.de:59125/process?INPUT_TEXT=Hallo+Welt&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&AUDIO=WAVE_FILE&LOCALE=de&VOICE=bits1un
> itselautolabelhmm&effect_volume_selected=on&effect_volume_parameters=amount:1.5;
> 
> 
> But I couldn't get the other effects working, although they work in the
> web interface (except 'durScale').
> 
> Question: Where do I get a complete description of the HTTP interface?
> 
> Best regards,
> 
> Florian

**Comment by seblemaguer** [comment]
As we are redesigning the core and the interface too, this issue won't be  accurate for next marytts versionss
