### ISSUE TITLE
Add a new Language and converting to an android appication

### ISSUE THREAD

**Issue by toblinkz** [marytts/marytts#930]
I want to add my language on marytts and then I want to develop a android application using marytts engine so I can convert text to speech of my languages text in an android application

**Comment by seblemaguer** [comment]
Hello,

which language do you want to add?

For android, normally you should adapt mary to not use a server but to be a library.

**Comment by toblinkz** [comment]
I want to add Yoruba. It is a native language in Nigeria

**Comment by seblemaguer** [comment]
Hello,

ok so what you need to have to be able to build a new language is to have a tokenizer and a G2P module (at least). The key is to have a proper allophone set which needs to be defined in its xml file. I would suggest to look the en_GB one for example as a start: marytts-languages/marytts-lang-en/src/main/resources/marytts/language/en_GB/lexicon/allophones.en_GB.xml. Associated to this, you should have a lexicon (you can have a look at https://github.com/marytts/marytts-lexicon-en_GB-oald)
