### ISSUE TITLE
Repo Down

### ISSUE THREAD

**Issue by supertick** [marytts/marytts#931]
Hello,
Is the following repo still valid ?  It appears to be down.
Cheers, 
  - Greg

Downloading from marytts: http://mary.dfki.de/repo/org/eclipse/collections/eclipse-collections-api/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.collections:eclipse-collections-api/maven-metadata.xml from/to marytts (http://mary.dfki.de/repo): Connect to mary.dfki.de:80 [mary.dfki.de/134.96.190.208] failed: Connection timed out (Connection timed out)
Downloading from marytts: http://mary.dfki.de/repo/org/eclipse/collections/eclipse-collections/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.collections:eclipse-collections/maven-metadata.xml from/to marytts (http://mary.dfki.de/repo): Connect to mary.dfki.de:80 [mary.dfki.de/134.96.190.208] failed: Connection timed out (Connection timed out)
Downloading from marytts: http://mary.dfki.de/repo/org/eclipse/collections/eclipse-collections-forkjoin/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.collections:eclipse-collections-forkjoin/maven-metadata.xml from/to marytts (http://mary.dfki.de/repo): Connect to mary.dfki.de:80 [mary.dfki.de/134.96.190.208] failed: Connection timed out (Connection timed out)

**Comment by seblemaguer** [comment]
Hello,

I never came accross these repositories on my side.

@psibre does it ring a bell on your side?

**Comment by supertick** [comment]
It's the general web site http://mary.dfki.de/ and demo which all references appear to be pointing to.

**Comment by psibre** [comment]
The web server is running fine. But apparently DFKI has some network issues that are preventing connections to that server.

**Comment by psibre** [comment]
Update: DFKI has fixed the network issue. The domain and all of its resources should be reachable again.
