### ISSUE TITLE
voices created with 5.2 throws error in 6.0 marytts-server

### ISSUE THREAD

**Issue by yilmazay74** [marytts/marytts#937]
So far I was creating and running my voices with marytts 5.2. Recently, we decided to upgrade to Marytts 6.0.  However, when I add any of the previously created voices into the lib folder of the new marytts 6.0 server, it throws errors.
the error says that the required features and the found ones do not match. 
in other words one of the features is not found in the new server.
that not found feature is  : pos_in_syl
the error message says: 
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate model 'duration' of type 'cart' from 'jar:/marytts/voice/DfkiOt/dur.tree'
	at marytts.modules.synthesis.Voice.loadAcousticModels(Voice.java:338)
	at marytts.modules.synthesis.Voice.init(Voice.java:221)
	at marytts.modules.synthesis.Voice.<init>(Voice.java:182)
	... 8 more
Caused by: marytts.exceptions.MaryConfigurationException: Incompatible features between model and feature processor manager.
The model needs the following features:
phone accented accented_syls_from_phrase_end accented_syls_from_phrase_start breakindex edge next_accent next_cplace next_ctype next_cvox next_is_pause next_next_cplace next_next_ctype next_next_cvox next_next_phone next_next_vc next_next_vfront next_next_vheight next_next_vrnd next_phone next_punctuation next_stressed next_tobi_accent next_tobi_endtone next_vc next_vfront next_vheight next_vrnd nextnext_tobi_accent nextnext_tobi_endtone onsetcoda ph_cplace ph_ctype ph_cvox ph_vc ph_vfront ph_vheight ph_vrnd phrase_endtone phrase_numsyls phrase_numwords phrases_from_sentence_end phrases_from_sentence_start pos_in_syl position_type prev_accent prev_cplace prev_ctype prev_cvox prev_is_pause prev_phone prev_phrase_endtone prev_prev_cplace prev_prev_ctype prev_prev_cvox prev_prev_phone prev_prev_vc prev_prev_vfront prev_prev_vheight prev_prev_vrnd prev_punctuation prev_stressed prev_syl_break prev_vc prev_vfront prev_vheight prev_vrnd segs_from_syl_end segs_from_syl_start segs_from_word_end segs_from_word_start selection_prosody sentence_numphrases sentence_numwords sentence_punc stressed stressed_syls_from_phrase_end stressed_syls_from_phrase_start style syl_break syl_numsegs syls_from_phrase_end syls_from_phrase_start syls_from_prev_accent syls_from_prev_stressed syls_from_word_end syls_from_word_start syls_to_next_accent syls_to_next_stressed tobi_accent tobi_endtone word_numsegs word_numsyls words_from_phrase_end words_from_phrase_start words_from_prev_punctuation words_from_sentence_end words_from_sentence_start words_to_next_punctuation
The FeatureProcessorManager for locale tr (class marytts.features.FeatureProcessorManager) can produce the following features:
accented accented_syls_from_phrase_end accented_syls_from_phrase_start breakindex edge halfphone_lr halfphone_unitname next_accent next_cplace next_ctype next_cvox next_is_pause next_next_cplace next_next_ctype next_next_cvox next_next_phone next_next_vc next_next_vfront next_next_vheight next_next_vrnd next_phone next_punctuation next_stressed next_tobi_accent next_tobi_endtone next_vc next_vfront next_vheight next_vrnd nextnext_tobi_accent nextnext_tobi_endtone onsetcoda ph_cplace ph_ctype ph_cvox ph_vc ph_vfront ph_vheight ph_vrnd phone phrase_endtone phrase_numsyls phrase_numwords phrases_from_sentence_end phrases_from_sentence_start position_type prev_accent prev_cplace prev_ctype prev_cvox prev_is_pause prev_phone prev_phrase_endtone prev_prev_cplace prev_prev_ctype prev_prev_cvox prev_prev_phone prev_prev_vc prev_prev_vfront prev_prev_vheight prev_prev_vrnd prev_punctuation prev_stressed prev_syl_break prev_vc prev_vfront prev_vheight prev_vrnd segs_from_syl_end segs_from_syl_start segs_from_word_end segs_from_word_start selection_prosody sentence_numphrases sentence_numwords sentence_punc stressed stressed_syls_from_phrase_end stressed_syls_from_phrase_start style syl_break syl_numsegs syls_from_phrase_end syls_from_phrase_start syls_from_prev_accent syls_from_prev_stressed syls_from_word_end syls_from_word_start syls_to_next_accent syls_to_next_stressed tobi_accent tobi_endtone word_numsegs word_numsyls words_from_phrase_end words_from_phrase_start words_from_prev_punctuation words_from_sentence_end words_from_sentence_start words_to_next_punctuation unit_duration unit_logf0 unit_logf0delta
	at marytts.modules.acoustic.Model.setupFeatureComputer(Model.java:171)
	at marytts.modules.acoustic.Model.load(Model.java:150)
	at marytts.modules.acoustic.CARTModel.<init>(CARTModel.java:47)
	at marytts.modules.synthesis.Voice.loadAcousticModels(Voice.java:309)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Feature processor manager 'class marytts.features.FeatureProcessorManager' does not know the feature 'pos_in_syl'
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:203)
	at marytts.modules.acoustic.Model.setupFeatureComputer(Model.java:165)
	... 13 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:368)
	at marytts.server.Mary$3.run(Mary.java:287)

> Task :run FAILED

Could anyone please let me know if that behaviour is expected? I mean can't we use previous version's voices in the new marytts 6.0?
Is there any way to remove pos_in_syl  feature from the required features list to avoid this error?
Is there any tool to migrate previous voices to 6.0 to make them be usable in the new version?

Best Regards

**Comment by seblemaguer** [comment]
The 6.x is a complete rewrite of MaryTTS and won't be compatible with 5.2. I would suggest to stick to 5.2 for now.
