### ISSUE TITLE
Turkish voice created with marytts 5.2 sounds normal, the same voice gets corrupted when built with marytts6.0

### ISSUE THREAD

**Issue by yilmazay74** [marytts/marytts#938]
Hi,
I used to build voices  in Turkish language using marytts 5.2 builder. 
Recently we wanted to try marytts 6.0 hoping that we can achive far better performance.
However, on the contrary, it got worse. Even it is hardly understandable. 
I am attaching a sample voice synthesised by both 5.2 and 6.0. 
Voice created with Marytts  5.2:
https://drive.google.com/open?id=1pAxCKE-8eS8xGSDbb2iirXJ6u4cH9bvN
Voice created with Marytts 6.0:
https://drive.google.com/open?id=1hgbzyupaKQ5p0txRAL2vVmzl2tSBnTdL

The text to be syntehesized is : 
"Herkese merhabalar! Umarım herkes iyidir.
Herkese mükemmel bir hafta sonu tatili diliyorum."

Could you please let me know if I am missing something? I strictly followed all the steps on you Voice Building Tutorial page. In fact, as far as I see the voice building procedures are all the same for both 5.x and 6.0. 
Is there anything that I need to take into considiration whilce voice building with the new version 6.0?
Or is the new marytts 6.0 is not stable yet ?

Thanks for your support in advance.
Best Regards

**Comment by seblemaguer** [comment]
Hello,

marytts is not stable yet and well change massively the logic of marytts. The moment it will be ready, an announcement it will be made.

Meanwhile, I would suggest to stick to the master branch or marytts 5.2.1
