### ISSUE TITLE
Voice Building fails when total numbers of files exceeds a limit

### ISSUE THREAD

**Issue by yilmazay74** [marytts/marytts#942]
Hi,
I have been creating Unit Selection voice with Turkish Locale, and up to 2000 files (each with about 40 seconds long in average) I did not have major problems. However, when I want to further increase the number of files for building the new voice, It crashes in the HTK Labeler step.
At first I thought that could be a problem in the new data set , however, when I build a voice with those extra voice files, it can successfully build without problems.
Thus, I thought there might be a bug which causes the build process breaks at some point.
Unfortunately, when I google the error message on the web, there is no one-to-one same issue. 
The error message I am having is : 
Saving hmm's to dir /opt/tts/voices/ay-yyyy-vm11//htk//hmm/hmm1
Reestimation complete - average log prob per frame = -nan
     - total frames seen          = 0.000000e+00

In addition there are many warnings like:
 WARNING [-2331]  UpdateModels: @'[28] copied: only 0 egs
 in /usr/local/bin//HERest
 WARNING [-2331]  UpdateModels: dZ[29] copied: only 0 egs
 in /usr/local/bin//HERest
 WARNING [-2331]  UpdateModels: tS[30] copied: only 0 egs
 in /usr/local/bin//HERest

 Processing Data: test_text_126.mfcc; Label test_text_126.lab
Retrying Beta pass at 400.0
Retrying Beta pass at 550.0
Retrying Beta pass at 700.0
Retrying Beta pass at 850.0
Retrying Beta pass at 1000.0
 No path found in beta pass
 WARNING [-7324]  StepBack: File /opt/tts/voices/ay-yyyy-vm11//htk//feat/test_text_126.mfcc - bad data or over pruning
 in /usr/local/bin//HERest
If someone can help me with this error I would appreciate it so much.

Best Regards and Happy New Year to All.

**Comment by seblemaguer** [comment]
Hello,

it seems that the file "test_text_126.mfcc" is creating a problem. I suggest you check the label file see for the durations and so on.

**Comment by yilmazay74** [comment]
Hi Seblemaguer,
Thanks for your reply.
Actually I only copied one sample of the whole error page. Actually, in the logherestTraining.txt file there is a warning for all files, not only for test_text_126.mfcc.
In addition, if total number of files is below 2000, I can build the voice without problems, including that HTK Labeler stage. Hence, we have a TTS model built with 2000 files and it can synthesize texts. But the quality is not so good. That is why we wanted to increase the corpus size and then I tried with 3000 voice samples. And it gave the error that I described previously.

Regards

**Comment by seblemaguer** [comment]
ok. These errors happen generally when at least one file is problematic. You have too look which one(s) is cause this problem. You can start with the 2000 you were using and add the first 500 and if it is crashing dichotomically trying to inspect which files are causing problem
