### ISSUE TITLE
MaryTTs for android development

### ISSUE THREAD

**Issue by MohammadMaraqa** [marytts/marytts#943]
Hi everyone,  can anyone help me out with using MaryTTS platform with android studios I would really appreciate it and does anyone know if I can add my own voice on android development? Thank you!

**Comment by miclill** [comment]
I was trying to figure out the same thing. Unfortunately it seems that marrytts relies on javax.sound.sampled.AudioInputStream a lot which is not supported by Android. Maybe the marrytts developers can weigh in on how hard it would be to support something other than AudioInputStream?

**Comment by miclill** [comment]
Also see: #930 #659
