### ISSUE TITLE
EHMM Labeler baumWelch computation failed?

### ISSUE THREAD

**Issue by NadineTheBean** [marytts/marytts#944]
Hi all! :)

I am trying to create a new English voice as part of my senior project, but have encountered several issues getting things set up. 
At the moment, I am just trying to test VoiceImportTools on the arctic cmu wav files and txt.data.done file as described in this [tutorial](https://mary.opendfki.de/trac/wiki/VoiceImportToolsTutorial)
But I keep getting an error involving the baumWelch algorithm on the EHMM Labeler step.

I know I am using an outdated tutorial/version of marytts, but I've spent quite some time trying to get other versions working and so far v4.3.1 is the only one that has (almost) worked for me.

Also, I know someone has [posted about this error before](https://github.com/marytts/marytts/issues/178), but I think my error might have a different cause. It seems like they were able to fix it just by increasing the number of wav files to be at least 200, but I'm already working with 1132 wavs from arctic cmu.

================================================================
**I run into the following error:**
```
Preparing voice database for labelling using EHMM :
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Setting up EHMM directory ...
 ... done.
Getting Phone Sequence from Phone Features...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Dumping required files ....
( cd /voice/data/ehmm; perl /home/osboxes/Desktop/MARYTTS/lib/external//bin/phfromutt.pl /voice/data/ehmm/etc/ehmm.align /voice/data/ehmm/etc/ehmm.phoneList 5; perl /home/osboxes/Desktop/MARYTTS/lib/external//bin/getwavlist.pl /voice/data/ehmm/etc/ehmm.align /voice/data/ehmm/etc/ehmm.waveList; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Computing MFCCs ...
( cd /voice/data/ehmm; /home/osboxes/Desktop/MARYTTS/lib/external//bin/FeatureExtraction /voice/data/ehmm/etc/ehmm.featSettings /voice/data/ehmm/etc/ehmm.waveList >> log.txt; perl /home/osboxes/Desktop/MARYTTS/lib/external//bin/comp_dcep.pl /voice/data/ehmm/etc/ehmm.waveList /voice/data/ehmm/feat mfcc ft 0 0 >> log.txt ; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Scaling Feature Vectors ...
( cd /voice/data/ehmm; perl /home/osboxes/Desktop/MARYTTS/lib/external//bin/scale_feat.pl /voice/data/ehmm/etc/ehmm.waveList /voice/data/ehmm/feat /voice/data/ehmm/mod ft 4 >> log.txt; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Intializing EHMM Model ...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
EHMM baum-welch re-estimation ...
It may take more time (may be 1 or 2 days) depending on voice database ...
( cd /voice/data/ehmm; /home/osboxes/Desktop/MARYTTS/lib/external//bin/ehmm /voice/data/ehmm/etc/ehmm.phoneList.int /voice/data/ehmm/etc/ehmm.align.int 1 0 /voice/data/ehmm/feat ft /voice/data/ehmm/mod 0 0 0 >> log.txt; exit )

ERR> /bin/bash: line 1: /home/osboxes/Desktop/MARYTTS/lib/external//bin/ehmm: Is a directory
java.lang.Exception: The component EHMMLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
Caused by: marytts.exceptions.MaryConfigurationException: baumWelchEHMM computation failed.
Error: null
	at marytts.tools.voiceimport.EHMMLabeler.baumWelchEHMM(EHMMLabeler.java:517)
	at marytts.tools.voiceimport.EHMMLabeler.compute(EHMMLabeler.java:187)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:291)

```

================================================================

Any advice would be greatly appreciated; please let me know if I can provide any additional information that would help.

**Comment by seblemaguer** [comment]
The error is telling you that ```/home/osboxes/Desktop/MARYTTS/lib/external//bin/ehmm``` is a directory, not a binary file

**Comment by NadineTheBean** [comment]
> The error is telling you that `/home/osboxes/Desktop/MARYTTS/lib/external//bin/ehmm` is a directory, not a binary file

Thank you for the clarification! Unfortunately I am struggling to figure out what is wrong with my directory setup. Could you (or anyone) show me what the correct directory structure should be?

**Comment by seblemaguer** [comment]
can you paste the directory tree from the "/home/osboxes/Desktop/MARYTTS/lib/external//bin/".
