### ISSUE TITLE
Setup German language through Gradle in 

### ISSUE THREAD

**Issue by fabipfolix** [marytts/marytts#953]
I tried to set a really simple tts up through gradle, but i keep failing. The language should be german, but i don't get it to work.  I tried it like [in this tutorial](https://www.youtube.com/watch?v=OLKxBorVwk8&t=101s) and it's almost what i want except the language and it isn't built with gradle.

Can someone help me?

**Comment by seblemaguer** [comment]
Hello,

can you develop what do you mean by "through Gradle"? Do you have your own Gradle project? If so, could you explain how you set up the german package exactly ?

**Comment by fabipfolix** [comment]
I have a gradle project and want to implement the needed dependencies that i can use "dfki-pavoque de male unitselection general"-voice.

**Comment by seblemaguer** [comment]
Hello,

I think you could have a look at this: https://github.com/marytts/marytts-txt2wav/tree/gradle

If you want to use a Pavoque voice you need to add the following lines in the `build.gradle` in the `dependencies` bloc:

```gradle
    compile group: 'de.dfki.mary', name: 'marytts-lang-de', version: '5.2'
    compile group: 'de.dfki.mary', name: 'voice-dfki-pavoque-neutral-hsmm', version: '5.2'
```

You can then have a look of how to integrate mary in your code by look at the following class: https://github.com/marytts/marytts-txt2wav/blob/gradle/src/main/java/de/dfki/mary/Txt2Wav.java

For now, that is the HSMM voice, I let you try to see for the unit selection

**Comment by fabipfolix** [comment]
Thanks, it works now. I think this voice is fine enough.

**Comment by fabipfolix** [comment]
I created an uberjar of my project with this method:
`task uberJar(type: Jar) {
    manifest {
        attributes 'Main-Class': 'bot.Main'
    }

    archiveClassifier = 'uber'

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}
`
If i try to use the program, i get this error: `java.lang.IllegalArgumentException: No such voice: dfki-pavoque-neutral-hsmm`

How can I addthe voice to the jarfile? All other dependencies are working.

**Comment by seblemaguer** [comment]
Hello,

for the formatting, you have to use 3 backquotes instead of only one (see https://guides.github.com/features/mastering-markdown/ )

For your question: is the voice a compile or a runtime dependency?

**Comment by fabipfolix** [comment]
I'm not sure what's the difference. 
That's my build.gradle:
```
plugins {
    id 'java'
}

group 'de.fabipfolix'
version '1.1'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'

    implementation group: 'commons-cli', name: 'commons-cli', version: '1.3.1'

    implementation group: 'de.dfki.mary', name: 'voice-cmu-slt-hsmm', version: '5.2'
    implementation group: 'de.dfki.mary', name: 'marytts-lang-de', version: '5.2'
    implementation group: 'de.dfki.mary', name: 'voice-dfki-pavoque-neutral-hsmm', version: '5.2'

    implementation 'net.dv8tion:JDA:4.1.1_110'
    implementation 'com.jagrosh:jda-utilities:3.0.2'
    implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.34'
}
task uberJar(type: Jar) {
    manifest {
        attributes 'Main-Class': 'bot.Bot'
    }

    archiveClassifier = 'uber'

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}

compileJava.options.encoding = 'UTF-8'
```

**Comment by psibre** [comment]
My first guess is that the service loaders are not correctly merged in your uber jar.

Please verify this, and maybe have a look at how this problem is solved in the [`gradle` branch of our **marytts-txt2wav** project](https://github.com/marytts/marytts-txt2wav/blob/gradle/build.gradle#L31-L34).

**Comment by fabipfolix** [comment]
It works, if I use shadowJar.
Thanks :D
