### ISSUE TITLE
Server hang when xml:lang="en"

### ISSUE THREAD

**Issue by hgneng** [marytts/marytts#96]
Hello,

MARY version: 5.0
OS: Mac OS X 10.7.5
Java version: 1.7.0_06

Reproduce process:
1. start MARY http server and GUI client
2. In MARY GUI client: set input type of RAWMARYXML and output type of AUDIO
3. paste following xml in input area which is copied from http://mary.dfki.de/documentation/maryxml
4. click "Play" and server hang. Java process eat up the CPU.

```
<?xml version="1.0" encoding="UTF-8" ?>
<maryxml version="0.4"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://mary.dfki.de/2002/MaryXML"
xml:lang="en">
<prosody rate="+20%" pitch="+20%" range="-10%" volume="loud">
This is something you have to see!
</prosody>
</maryxml>
```

If I change xml:lang to `xml:lang="en-US"`, everything is fine.

Cameron

**Comment by Munzey** [comment]
locale issue has been fixed as part of #286 but is still to be merged. see my [dropFakeEnGB](https://github.com/Munzey/marytts/tree/dropFakeEnGB) branch.
