### ISSUE TITLE
prosody doesn't work correctly

### ISSUE THREAD

**Issue by hgneng** [marytts/marytts#97]
MARY version: 5.0
client: MARY GUI client
input type: RAWMARYXML
output type: AUDIO
OS: Mac OS X 10.7.5
Java version: 1.7.0_06

Reproduce process:
1. paste following code to input area and play. We will hear the first hello is spoken faster than normal and the second hello is spoken slower than normal. But we expect it is spoken in normal speed/rate.
2. delete both "hello". Text in <prosody> is spoken in normal speed not 20% faster.

```
<?xml version="1.0" encoding="UTF-8" ?>
<maryxml version="0.4"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://mary.dfki.de/2002/MaryXML"
xml:lang="en-US">
hello
<prosody rate="+20%" pitch="+20%" range="-10%" volume="loud">
This is something you have to see!
</prosody>
hello
</maryxml>
```

Cameron

**Comment by Munzey** [comment]
@psibre right again about the XML2Utt crap! This is resolved now that the FreeTTS dependencies are gone see #228
