### ISSUE TITLE
MaryTTS server down?

### ISSUE THREAD

**Issue by jesinj** [marytts/marytts#979]
Hi,

The MaryTTS server seems to be down as we are not able to access it. Is this a temporary problem that will be solved soon? Please update on whether the server will be available soon.

**Comment by psibre** [comment]
http://mary.dfki.de:59125/ is available again, through no action on our part.

As [mentioned in #660](https://github.com/marytts/marytts/issues/660#issuecomment-328059594), there is a cronjob that restarts the server nightly. If it crashes in between, please be patient.

Of course, you should not be relying on http://mary.dfki.de:59125/ in production. If you need a running MaryTTS web service, please run your own instance.
