### ISSUE TITLE
MaryGUIClient hangs on server error, blocks CPU at 100% load

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#98]
As reported by @hgneng in #96, the GUI client can enter a state in which an unexpected server response causes the "stop" button to not be reset, and a Thread to be spawned that consumes 100% CPU. Even when the "stop" button is clicked manually and reset to "play", the Thread does not terminate.

Also no error message is shown in the client.

**Comment by Munzey** [comment]
@psibre has this been addressed? 5.2 milestone if not?

**Comment by psibre** [comment]
I'd rather drop the client into purgatory -- we haven't used it in years, and the code is rather unmaintained.
