### ISSUE TITLE
Adding new language support - No known way of generating output error

### ISSUE THREAD

**Issue by muntasir2000** [marytts/marytts#981]
Hi, I am trying to add support for Bangla language. I have created all the necessary files allophones.xml, lexicon, POS etc. and built the language component. But when I am calling the /process endpoint like this - `/process?INPUT_TEXT=<text-here>&INPUT_TYPE=TEXT&OUTPUT_TYPE=PHONEMES&AUDIO=WAVE_FILE&LOCALE=bn`, I am getting this error - 
`java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
`
Calling `locale` endpoint lists my new locale succesfully. So I think I have done the integration right.

For other input types (ALLOPHONES, PARTSOFSPEECH, ACOUSTICPARAMS etc.) I'm encountering same error.

I have tried 3 ways -
1. Using MaryTTS v5.2, following the same way as other languages in the marytts-languages directory. Same issue.
2. Using the Gradle plugin, I first built the lexicon and then the language component (following (https://github.com/marytts/marytts-lang-pl)[this] repo). Then I copied the marytts-lexicon-bn.jar and marytts-lang-bn.jar to /target/marytts-5.2/lib directory and then started the v5.2 server. Same issue.
3. Using v6.0 (latest master branch), I followed the same way as other languages in marytts-languages directory. **Here I got success while calling /process endpoint with all input/output types. Not facing the issue.** But I can't use this language component built with v6.0 while building voice using the (https://github.com/marytts/gradle-marytts-voicebuilding-plugin)[gradle-marytts-voicebuilding-plugin], the `hasVoiceConfigs` test fails in the last stage of voice building. I think success with v6.0 proves that my lexicon, allphones.xml etc files are in correct format.

Also, if I use the language component built with marytts v5.2 with (https://github.com/marytts/gradle-marytts-voicebuilding-plugin)[gradle-marytts-voicebuilding-plugin], then voice building fails with `canProcessTextToSpeech`, `canProcessTokensToTargetfeatures` and `canProcessTokensToSpeech' tests. I suppose the language component is not working correctly because it can't process all input types (correct me if I'm wrong, I might open a separate issue after some more digging in).  

So, what might be causing the No known way of generating output issue?

**Comment by seblemaguer** [comment]
I think the language configuration file does not list the modules that the package proposes. Do you have a link to the repository?

**Comment by muntasir2000** [comment]
I have uploaded the source into Github for your checking. Here is the link - 
https://github.com/muntasir2000/marytts-lang-bn

**Comment by seblemaguer** [comment]
Your `bn.config` contains a typo:

```ini
modules.classes.list = \
        marytts.modules.JPhonemiser(bn.) 
        marytts.modules.MinimalisticPosTagger(bn, bn.) \
```

should be

```ini
modules.classes.list = \
        marytts.modules.JPhonemiser(bn.)  \
        marytts.modules.MinimalisticPosTagger(bn,bn.)
```

Furthermore, the resource pointed for POS tagger is not in the package. That will also lead to another fail.

**Comment by muntasir2000** [comment]
> Your `bn.config` contains a typo:
> 
> ```ini
> modules.classes.list = \
>         marytts.modules.JPhonemiser(bn.) 
>         marytts.modules.MinimalisticPosTagger(bn, bn.) \
> ```
> 
> should be
> 
> ```ini
> modules.classes.list = \
>         marytts.modules.JPhonemiser(bn.)  \
>         marytts.modules.MinimalisticPosTagger(bn,bn.)
> ```
> 
> Furthermore, the resource pointed for POS tagger is not in the package. That will also lead to another fail.

Thanks a lot. This fixed the issue.
