### ISSUE TITLE
Odd issue with Gradle script

### ISSUE THREAD

**Issue by wholder** [marytts/marytts#982]
I decided to investigate the various Gradle scripts in the project and got some unexpected errors. For example, when I run this script:

![Screen Shot 2020-05-09 at 10 45 47 PM](https://user-images.githubusercontent.com/1062514/81491857-ddd0bf80-9247-11ea-8068-3c0c0fe83733.png)

in macOS IntelliJ, I get this odd error:

```
/Users/wholder/IdeaProjects/marytts/marytts-runtime/src/main/java/marytts/signalproc/effects/BaseAudioEffect.java:30: error: unmappable character for encoding ASCII
// It??s main functionality is providing base functions for parsing parameter strings
     ^
```
To make sure this wasn't something my other experiment corrupted, I trashed my original project and fetched it again fresh from Githib.

Similarly, if I run this Gradle script:

![Screen Shot 2020-05-09 at 10 49 10 PM](https://user-images.githubusercontent.com/1062514/81491863-e3c6a080-9247-11ea-9e4e-b9d6ce816ba9.png)

I get this error:

```
/Users/wholder/IdeaProjects/marytts/marytts-common/src/main/java/marytts/util/MaryUtils.java:129: error: unmappable character for encoding ASCII
		final String letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ??????abcdefghijklmnopqrstuvwxyz????????";
		                                                  ^
```
I'm not sure what's going on, as the files both look fine in IntelliJ's editor. Any ideas on what I'm doing wrong?

Wayne

**Comment by seblemaguer** [comment]
It seems IntelliJ is not configured for Unicode. We assume all the files to be encoded in UTF-8.

**Comment by psibre** [comment]
@wholder I just responded to your identical comment over at https://github.com/marytts/marytts/issues/980#issuecomment-626277803
