### ISSUE TITLE
can't change language/voice from the web Interface

### ISSUE THREAD

**Issue by falisca** [marytts/marytts#993]
Hi, 
After building I assume that all languages are already loaded, all test passed.
After running in the web interface I see only en-us voice (default).
Is it normal?

Tried downloading (uninstalling first) some languages, with no luck.
There are other procedures?

I'm on Windows 10 latest with java 8.

**Comment by seblemaguer** [comment]
you only see the languages corresponding to the available voices in the web interface. 2 solutions: not using the web interface, installing voices to the language you want?

**Comment by falisca** [comment]
In the web interface I see only one voice, the default en-us.
It means that only the en-us voice exsist at all?
When I open the install Gui i see all languages as installed, as expected.
Trying to uninstall voices give me an error "unable to uninstall voice" but after clicking ok i can install it with no problem.
Actually doing this the result is the same.

**Comment by psibre** [comment]
You need to understand that the languages and voices are different components. When you build MaryTTS from source, you build all language components, and one voice (cmu-slt-hsmm). All other voices are installed from the Web via the Installer GUI.

See https://github.com/marytts/marytts#downloading-and-installing-voices
